%%%-------------------------------------------------------------------
%%% @doc Returns list of all countries
%%% @end
%%%-------------------------------------------------------------------
-module(iso_erlang_country_lists).

%% API
-export([
 get_alpha_2_country_list/0,
 get_alpha_3_country_list/0,
 get_country_name_list/0
]).

get_alpha_2_country_list() ->
    [<<"AF">>,
     <<"AX">>,
     <<"AL">>,
     <<"DZ">>,
     <<"AS">>,
     <<"AD">>,
     <<"AO">>,
     <<"AI">>,
     <<"AQ">>,
     <<"AG">>,
     <<"AR">>,
     <<"AM">>,
     <<"AW">>,
     <<"AU">>,
     <<"AT">>,
     <<"AZ">>,
     <<"BS">>,
     <<"BH">>,
     <<"BD">>,
     <<"BB">>,
     <<"BY">>,
     <<"BE">>,
     <<"BZ">>,
     <<"BJ">>,
     <<"BM">>,
     <<"BT">>,
     <<"BO">>,
     <<"BA">>,
     <<"BW">>,
     <<"BV">>,
     <<"BR">>,
     <<"VG">>,
     <<"IO">>,
     <<"BN">>,
     <<"BG">>,
     <<"BF">>,
     <<"BI">>,
     <<"KH">>,
     <<"CM">>,
     <<"CA">>,
     <<"CV">>,
     <<"KY">>,
     <<"CF">>,
     <<"TD">>,
     <<"CL">>,
     <<"CN">>,
     <<"HK">>,
     <<"MO">>,
     <<"CX">>,
     <<"CC">>,
     <<"CO">>,
     <<"KM">>,
     <<"CG">>,
     <<"CD">>,
     <<"CK">>,
     <<"CR">>,
     <<"CI">>,
     <<"HR">>,
     <<"CU">>,
     <<"CY">>,
     <<"CZ">>,
     <<"DK">>,
     <<"DJ">>,
     <<"DM">>,
     <<"DO">>,
     <<"EC">>,
     <<"EG">>,
     <<"SV">>,
     <<"GQ">>,
     <<"ER">>,
     <<"EE">>,
     <<"ET">>,
     <<"FK">>,
     <<"FO">>,
     <<"FJ">>,
     <<"FI">>,
     <<"FR">>,
     <<"GF">>,
     <<"PF">>,
     <<"TF">>,
     <<"GA">>,
     <<"GM">>,
     <<"GE">>,
     <<"DE">>,
     <<"GH">>,
     <<"GI">>,
     <<"GR">>,
     <<"GL">>,
     <<"GD">>,
     <<"GP">>,
     <<"GU">>,
     <<"GT">>,
     <<"GG">>,
     <<"GN">>,
     <<"GW">>,
     <<"GY">>,
     <<"HT">>,
     <<"HM">>,
     <<"VA">>,
     <<"HN">>,
     <<"HU">>,
     <<"IS">>,
     <<"IN">>,
     <<"ID">>,
     <<"IR">>,
     <<"IQ">>,
     <<"IE">>,
     <<"IM">>,
     <<"IL">>,
     <<"IT">>,
     <<"JM">>,
     <<"JP">>,
     <<"JE">>,
     <<"JO">>,
     <<"KZ">>,
     <<"KE">>,
     <<"KI">>,
     <<"KP">>,
     <<"KR">>,
     <<"KW">>,
     <<"KG">>,
     <<"LA">>,
     <<"LV">>,
     <<"LB">>,
     <<"LS">>,
     <<"LR">>,
     <<"LY">>,
     <<"LI">>,
     <<"LT">>,
     <<"LU">>,
     <<"MK">>,
     <<"MG">>,
     <<"MW">>,
     <<"MY">>,
     <<"MV">>,
     <<"ML">>,
     <<"MT">>,
     <<"MH">>,
     <<"MQ">>,
     <<"MR">>,
     <<"MU">>,
     <<"YT">>,
     <<"MX">>,
     <<"FM">>,
     <<"MD">>,
     <<"MC">>,
     <<"MN">>,
     <<"ME">>,
     <<"MS">>,
     <<"MA">>,
     <<"MZ">>,
     <<"MM">>,
     <<"NA">>,
     <<"NR">>,
     <<"NP">>,
     <<"NL">>,
     <<"AN">>,
     <<"NC">>,
     <<"NZ">>,
     <<"NI">>,
     <<"NE">>,
     <<"NG">>,
     <<"NU">>,
     <<"NF">>,
     <<"MP">>,
     <<"NO">>,
     <<"OM">>,
     <<"PK">>,
     <<"PW">>,
     <<"PS">>,
     <<"PA">>,
     <<"PG">>,
     <<"PY">>,
     <<"PE">>,
     <<"PH">>,
     <<"PN">>,
     <<"PL">>,
     <<"PT">>,
     <<"PR">>,
     <<"QA">>,
     <<"RE">>,
     <<"RO">>,
     <<"RU">>,
     <<"RW">>,
     <<"BL">>,
     <<"SH">>,
     <<"KN">>,
     <<"LC">>,
     <<"MF">>,
     <<"PM">>,
     <<"VC">>,
     <<"WS">>,
     <<"SM">>,
     <<"ST">>,
     <<"SA">>,
     <<"SN">>,
     <<"RS">>,
     <<"SC">>,
     <<"SL">>,
     <<"SG">>,
     <<"SK">>,
     <<"SI">>,
     <<"SB">>,
     <<"SO">>,
     <<"ZA">>,
     <<"GS">>,
     <<"SS">>,
     <<"ES">>,
     <<"LK">>,
     <<"SD">>,
     <<"SR">>,
     <<"SJ">>,
     <<"SZ">>,
     <<"SE">>,
     <<"CH">>,
     <<"SY">>,
     <<"TW">>,
     <<"TJ">>,
     <<"TZ">>,
     <<"TH">>,
     <<"TL">>,
     <<"TG">>,
     <<"TK">>,
     <<"TO">>,
     <<"TT">>,
     <<"TN">>,
     <<"TR">>,
     <<"TM">>,
     <<"TC">>,
     <<"TV">>,
     <<"UG">>,
     <<"UA">>,
     <<"AE">>,
     <<"GB">>,
     <<"US">>,
     <<"UM">>,
     <<"UY">>,
     <<"UZ">>,
     <<"VU">>,
     <<"VE">>,
     <<"VN">>,
     <<"VI">>,
     <<"WF">>,
     <<"EH">>,
     <<"YE">>,
     <<"ZM">>,
     <<"ZW">>].

get_alpha_3_country_list() ->
    [<<"AFG">>,
     <<"ALA">>,
     <<"ALB">>,
     <<"DZA">>,
     <<"ASM">>,
     <<"AND">>,
     <<"AGO">>,
     <<"AIA">>,
     <<"ATA">>,
     <<"ATG">>,
     <<"ARG">>,
     <<"ARM">>,
     <<"ABW">>,
     <<"AUS">>,
     <<"AUT">>,
     <<"AZE">>,
     <<"BHS">>,
     <<"BHR">>,
     <<"BGD">>,
     <<"BRB">>,
     <<"BLR">>,
     <<"BEL">>,
     <<"BLZ">>,
     <<"BEN">>,
     <<"BMU">>,
     <<"BTN">>,
     <<"BOL">>,
     <<"BIH">>,
     <<"BWA">>,
     <<"BVT">>,
     <<"BRA">>,
     <<"VGB">>,
     <<"IOT">>,
     <<"BRN">>,
     <<"BGR">>,
     <<"BFA">>,
     <<"BDI">>,
     <<"KHM">>,
     <<"CMR">>,
     <<"CAN">>,
     <<"CPV">>,
     <<"CYM">>,
     <<"CAF">>,
     <<"TCD">>,
     <<"CHL">>,
     <<"CHN">>,
     <<"HKG">>,
     <<"MAC">>,
     <<"CXR">>,
     <<"CCK">>,
     <<"COL">>,
     <<"COM">>,
     <<"COG">>,
     <<"COD">>,
     <<"COK">>,
     <<"CRI">>,
     <<"CIV">>,
     <<"HRV">>,
     <<"CUB">>,
     <<"CYP">>,
     <<"CZE">>,
     <<"DNK">>,
     <<"DJI">>,
     <<"DMA">>,
     <<"DOM">>,
     <<"ECU">>,
     <<"EGY">>,
     <<"SLV">>,
     <<"GNQ">>,
     <<"ERI">>,
     <<"EST">>,
     <<"ETH">>,
     <<"FLK">>,
     <<"FRO">>,
     <<"FJI">>,
     <<"FIN">>,
     <<"FRA">>,
     <<"GUF">>,
     <<"PYF">>,
     <<"ATF">>,
     <<"GAB">>,
     <<"GMB">>,
     <<"GEO">>,
     <<"DEU">>,
     <<"GHA">>,
     <<"GIB">>,
     <<"GRC">>,
     <<"GRL">>,
     <<"GRD">>,
     <<"GLP">>,
     <<"GUM">>,
     <<"GTM">>,
     <<"GGY">>,
     <<"GIN">>,
     <<"GNB">>,
     <<"GUY">>,
     <<"HTI">>,
     <<"HMD">>,
     <<"VAT">>,
     <<"HND">>,
     <<"HUN">>,
     <<"ISL">>,
     <<"IND">>,
     <<"IDN">>,
     <<"IRN">>,
     <<"IRQ">>,
     <<"IRL">>,
     <<"IMN">>,
     <<"ISR">>,
     <<"ITA">>,
     <<"JAM">>,
     <<"JPN">>,
     <<"JEY">>,
     <<"JOR">>,
     <<"KAZ">>,
     <<"KEN">>,
     <<"KIR">>,
     <<"PRK">>,
     <<"KOR">>,
     <<"KWT">>,
     <<"KGZ">>,
     <<"LAO">>,
     <<"LVA">>,
     <<"LBN">>,
     <<"LSO">>,
     <<"LBR">>,
     <<"LBY">>,
     <<"LIE">>,
     <<"LTU">>,
     <<"LUX">>,
     <<"MKD">>,
     <<"MDG">>,
     <<"MWI">>,
     <<"MYS">>,
     <<"MDV">>,
     <<"MLI">>,
     <<"MLT">>,
     <<"MHL">>,
     <<"MTQ">>,
     <<"MRT">>,
     <<"MUS">>,
     <<"MYT">>,
     <<"MEX">>,
     <<"FSM">>,
     <<"MDA">>,
     <<"MCO">>,
     <<"MNG">>,
     <<"MNE">>,
     <<"MSR">>,
     <<"MAR">>,
     <<"MOZ">>,
     <<"MMR">>,
     <<"NAM">>,
     <<"NRU">>,
     <<"NPL">>,
     <<"NLD">>,
     <<"ANT">>,
     <<"NCL">>,
     <<"NZL">>,
     <<"NIC">>,
     <<"NER">>,
     <<"NGA">>,
     <<"NIU">>,
     <<"NFK">>,
     <<"MNP">>,
     <<"NOR">>,
     <<"OMN">>,
     <<"PAK">>,
     <<"PLW">>,
     <<"PSE">>,
     <<"PAN">>,
     <<"PNG">>,
     <<"PRY">>,
     <<"PER">>,
     <<"PHL">>,
     <<"PCN">>,
     <<"POL">>,
     <<"PRT">>,
     <<"PRI">>,
     <<"QAT">>,
     <<"REU">>,
     <<"ROU">>,
     <<"RUS">>,
     <<"RWA">>,
     <<"BLM">>,
     <<"SHN">>,
     <<"KNA">>,
     <<"LCA">>,
     <<"MAF">>,
     <<"SPM">>,
     <<"VCT">>,
     <<"WSM">>,
     <<"SMR">>,
     <<"STP">>,
     <<"SAU">>,
     <<"SEN">>,
     <<"SRB">>,
     <<"SYC">>,
     <<"SLE">>,
     <<"SGP">>,
     <<"SVK">>,
     <<"SVN">>,
     <<"SLB">>,
     <<"SOM">>,
     <<"ZAF">>,
     <<"SGS">>,
     <<"SSD">>,
     <<"ESP">>,
     <<"LKA">>,
     <<"SDN">>,
     <<"SUR">>,
     <<"SJM">>,
     <<"SWZ">>,
     <<"SWE">>,
     <<"CHE">>,
     <<"SYR">>,
     <<"TWN">>,
     <<"TJK">>,
     <<"TZA">>,
     <<"THA">>,
     <<"TLS">>,
     <<"TGO">>,
     <<"TKL">>,
     <<"TON">>,
     <<"TTO">>,
     <<"TUN">>,
     <<"TUR">>,
     <<"TKM">>,
     <<"TCA">>,
     <<"TUV">>,
     <<"UGA">>,
     <<"UKR">>,
     <<"ARE">>,
     <<"GBR">>,
     <<"USA">>,
     <<"UMI">>,
     <<"URY">>,
     <<"UZB">>,
     <<"VUT">>,
     <<"VEN">>,
     <<"VNM">>,
     <<"VIR">>,
     <<"WLF">>,
     <<"ESH">>,
     <<"YEM">>,
     <<"ZMB">>,
     <<"ZWE">>].

get_country_name_list() ->
    [<<"Afghanistan"/utf8>>,
     <<"Aland Islands"/utf8>>,
     <<"Albania"/utf8>>,
     <<"Algeria"/utf8>>,
     <<"American Samoa"/utf8>>,
     <<"Andorra"/utf8>>,
     <<"Angola"/utf8>>,
     <<"Anguilla"/utf8>>,
     <<"Antarctica"/utf8>>,
     <<"Antigua and Barbuda"/utf8>>,
     <<"Argentina"/utf8>>,
     <<"Armenia"/utf8>>,
     <<"Aruba"/utf8>>,
     <<"Australia"/utf8>>,
     <<"Austria"/utf8>>,
     <<"Azerbaijan"/utf8>>,
     <<"Bahamas"/utf8>>,
     <<"Bahrain"/utf8>>,
     <<"Bangladesh"/utf8>>,
     <<"Barbados"/utf8>>,
     <<"Belarus"/utf8>>,
     <<"Belgium"/utf8>>,
     <<"Belize"/utf8>>,
     <<"Benin"/utf8>>,
     <<"Bermuda"/utf8>>,
     <<"Bhutan"/utf8>>,
     <<"Bolivia"/utf8>>,
     <<"Bosnia and Herzegovina"/utf8>>,
     <<"Botswana"/utf8>>,
     <<"Bouvet Island"/utf8>>,
     <<"Brazil"/utf8>>,
     <<"British Virgin Islands"/utf8>>,
     <<"British Indian Ocean Territory"/utf8>>,
     <<"Brunei Darussalam"/utf8>>,
     <<"Bulgaria"/utf8>>,
     <<"Burkina Faso"/utf8>>,
     <<"Burundi"/utf8>>,
     <<"Cambodia"/utf8>>,
     <<"Cameroon"/utf8>>,
     <<"Canada"/utf8>>,
     <<"Cape Verde"/utf8>>,
     <<"Cayman Islands"/utf8>>,
     <<"Central African Republic"/utf8>>,
     <<"Chad"/utf8>>,
     <<"Chile"/utf8>>,
     <<"China"/utf8>>,
     <<"Hong Kong, Special Administrative Region of China"/utf8>>,
     <<"Macao, Special Administrative Region of China"/utf8>>,
     <<"Christmas Island"/utf8>>,
     <<"Cocos (Keeling) Islands"/utf8>>,
     <<"Colombia"/utf8>>,
     <<"Comoros"/utf8>>,
     <<"Congo (Brazzaville)"/utf8>>,
     <<"Democratic Republic of the Congo"/utf8>>,
     <<"Cook Islands"/utf8>>,
     <<"Costa Rica"/utf8>>,
     <<"Côte d'Ivoire"/utf8>>,
     <<"Croatia"/utf8>>,
     <<"Cuba"/utf8>>,
     <<"Cyprus"/utf8>>,
     <<"Czech Republic"/utf8>>,
     <<"Denmark"/utf8>>,
     <<"Djibouti"/utf8>>,
     <<"Dominica"/utf8>>,
     <<"Dominican Republic"/utf8>>,
     <<"Ecuador"/utf8>>,
     <<"Egypt"/utf8>>,
     <<"El Salvador"/utf8>>,
     <<"Equatorial Guinea"/utf8>>,
     <<"Eritrea"/utf8>>,
     <<"Estonia"/utf8>>,
     <<"Ethiopia"/utf8>>,
     <<"Falkland Islands (Malvinas)"/utf8>>,
     <<"Faroe Islands"/utf8>>,
     <<"Fiji"/utf8>>,
     <<"Finland"/utf8>>,
     <<"France"/utf8>>,
     <<"French Guiana"/utf8>>,
     <<"French Polynesia"/utf8>>,
     <<"French Southern Territories"/utf8>>,
     <<"Gabon"/utf8>>,
     <<"Gambia"/utf8>>,
     <<"Georgia"/utf8>>,
     <<"Germany"/utf8>>,
     <<"Ghana"/utf8>>,
     <<"Gibraltar"/utf8>>,
     <<"Greece"/utf8>>,
     <<"Greenland"/utf8>>,
     <<"Grenada"/utf8>>,
     <<"Guadeloupe"/utf8>>,
     <<"Guam"/utf8>>,
     <<"Guatemala"/utf8>>,
     <<"Guernsey"/utf8>>,
     <<"Guinea"/utf8>>,
     <<"Guinea-Bissau"/utf8>>,
     <<"Guyana"/utf8>>,
     <<"Haiti"/utf8>>,
     <<"Heard Island and Mcdonald Islands"/utf8>>,
     <<"Holy See (Vatican City State)"/utf8>>,
     <<"Honduras"/utf8>>,
     <<"Hungary"/utf8>>,
     <<"Iceland"/utf8>>,
     <<"India"/utf8>>,
     <<"Indonesia"/utf8>>,
     <<"Iran"/utf8>>,
     <<"Iraq"/utf8>>,
     <<"Ireland"/utf8>>,
     <<"Isle of Man"/utf8>>,
     <<"Israel"/utf8>>,
     <<"Italy"/utf8>>,
     <<"Jamaica"/utf8>>,
     <<"Japan"/utf8>>,
     <<"Jersey"/utf8>>,
     <<"Jordan"/utf8>>,
     <<"Kazakhstan"/utf8>>,
     <<"Kenya"/utf8>>,
     <<"Kiribati"/utf8>>,
     <<"Democratic People's Republic of Korea"/utf8>>,
     <<"Republic of Korea"/utf8>>,
     <<"Kuwait"/utf8>>,
     <<"Kyrgyzstan"/utf8>>,
     <<"Lao PDR"/utf8>>,
     <<"Latvia"/utf8>>,
     <<"Lebanon"/utf8>>,
     <<"Lesotho"/utf8>>,
     <<"Liberia"/utf8>>,
     <<"Libya"/utf8>>,
     <<"Liechtenstein"/utf8>>,
     <<"Lithuania"/utf8>>,
     <<"Luxembourg"/utf8>>,
     <<"Republic of Macedonia"/utf8>>,
     <<"Madagascar"/utf8>>,
     <<"Malawi"/utf8>>,
     <<"Malaysia"/utf8>>,
     <<"Maldives"/utf8>>,
     <<"Mali"/utf8>>,
     <<"Malta"/utf8>>,
     <<"Marshall Islands"/utf8>>,
     <<"Martinique"/utf8>>,
     <<"Mauritania"/utf8>>,
     <<"Mauritius"/utf8>>,
     <<"Mayotte"/utf8>>,
     <<"Mexico"/utf8>>,
     <<"Federated States of Micronesia"/utf8>>,
     <<"Moldova"/utf8>>,
     <<"Monaco"/utf8>>,
     <<"Mongolia"/utf8>>,
     <<"Montenegro"/utf8>>,
     <<"Montserrat"/utf8>>,
     <<"Morocco"/utf8>>,
     <<"Mozambique"/utf8>>,
     <<"Myanmar"/utf8>>,
     <<"Namibia"/utf8>>,
     <<"Nauru"/utf8>>,
     <<"Nepal"/utf8>>,
     <<"Netherlands"/utf8>>,
     <<"Netherlands Antilles"/utf8>>,
     <<"New Caledonia"/utf8>>,
     <<"New Zealand"/utf8>>,
     <<"Nicaragua"/utf8>>,
     <<"Niger"/utf8>>,
     <<"Nigeria"/utf8>>,
     <<"Niue"/utf8>>,
     <<"Norfolk Island"/utf8>>,
     <<"Northern Mariana Islands"/utf8>>,
     <<"Norway"/utf8>>,
     <<"Oman"/utf8>>,
     <<"Pakistan"/utf8>>,
     <<"Palau"/utf8>>,
     <<"Palestine"/utf8>>,
     <<"Panama"/utf8>>,
     <<"Papua New Guinea"/utf8>>,
     <<"Paraguay"/utf8>>,
     <<"Peru"/utf8>>,
     <<"Philippines"/utf8>>,
     <<"Pitcairn"/utf8>>,
     <<"Poland"/utf8>>,
     <<"Portugal"/utf8>>,
     <<"Puerto Rico"/utf8>>,
     <<"Qatar"/utf8>>,
     <<"Réunion"/utf8>>,
     <<"Romania"/utf8>>,
     <<"Russian Federation"/utf8>>,
     <<"Rwanda"/utf8>>,
     <<"Saint-Barthélemy"/utf8>>,
     <<"Saint Helena"/utf8>>,
     <<"Saint Kitts and Nevis"/utf8>>,
     <<"Saint Lucia"/utf8>>,
     <<"Saint-Martin (French part)"/utf8>>,
     <<"Saint Pierre and Miquelon"/utf8>>,
     <<"Saint Vincent and Grenadines"/utf8>>,
     <<"Samoa"/utf8>>,
     <<"San Marino"/utf8>>,
     <<"Sao Tome and Principe"/utf8>>,
     <<"Saudi Arabia"/utf8>>,
     <<"Senegal"/utf8>>,
     <<"Serbia"/utf8>>,
     <<"Seychelles"/utf8>>,
     <<"Sierra Leone"/utf8>>,
     <<"Singapore"/utf8>>,
     <<"Slovakia"/utf8>>,
     <<"Slovenia"/utf8>>,
     <<"Solomon Islands"/utf8>>,
     <<"Somalia"/utf8>>,
     <<"South Africa"/utf8>>,
     <<"South Georgia and the South Sandwich Islands"/utf8>>,
     <<"South Sudan"/utf8>>,
     <<"Spain"/utf8>>,
     <<"Sri Lanka"/utf8>>,
     <<"Sudan"/utf8>>,
     <<"Suriname *"/utf8>>,
     <<"Svalbard and Jan Mayen Islands"/utf8>>,
     <<"Swaziland"/utf8>>,
     <<"Sweden"/utf8>>,
     <<"Switzerland"/utf8>>,
     <<"Syrian Arab Republic (Syria)"/utf8>>,
     <<"Taiwan, Republic of China"/utf8>>,
     <<"Tajikistan"/utf8>>,
     <<"Tanzania"/utf8>>,
     <<"Thailand"/utf8>>,
     <<"Timor-Leste"/utf8>>,
     <<"Togo"/utf8>>,
     <<"Tokelau"/utf8>>,
     <<"Tonga"/utf8>>,
     <<"Trinidad and Tobago"/utf8>>,
     <<"Tunisia"/utf8>>,
     <<"Turkey"/utf8>>,
     <<"Turkmenistan"/utf8>>,
     <<"Turks and Caicos Islands"/utf8>>,
     <<"Tuvalu"/utf8>>,
     <<"Uganda"/utf8>>,
     <<"Ukraine"/utf8>>,
     <<"United Arab Emirates"/utf8>>,
     <<"United Kingdom"/utf8>>,
     <<"United States of America"/utf8>>,
     <<"United States Minor Outlying Islands"/utf8>>,
     <<"Uruguay"/utf8>>,
     <<"Uzbekistan"/utf8>>,
     <<"Vanuatu"/utf8>>,
     <<"Venezuela (Bolivarian Republic of)"/utf8>>,
     <<"Viet Nam"/utf8>>,
     <<"US Virgin Islands"/utf8>>,
     <<"Wallis and Futuna Islands"/utf8>>,
     <<"Western Sahara"/utf8>>,
     <<"Yemen"/utf8>>,
     <<"Zambia"/utf8>>,
     <<"Zimbabwe"/utf8>>].
