%%%-------------------------------------------------------------------
%%% @doc Converts countries to and from alpha-2, alpha-3, numerical code
%%%      and country name.
%%% @end
%%%-------------------------------------------------------------------
-module(iso_erlang_country_converter).

%% API
-export([
    alpha_2_to_name_upper/1,
    alpha_3_to_name_upper/1,
    alpha_2_to_numerical_code_upper/1,
    alpha_3_to_numerical_code_upper/1,
    to_alpha_2_upper/1,
    to_alpha_3_upper/1,
    to_country_name_upper/1,
    country_to_numerical_code_upper/1
]).

%% @doc Converts two letter country codes (ISO alpha-2) and the three letter country codes (ISO alpha-3)
%%      to United Nations numerical code M49 for countries. This is case-sensitive (Expects uppercase).
%% @end
country_to_numerical_code_upper(Country) when bit_size(Country) =:= 16 -> alpha_2_to_numerical_code_upper(Country);
country_to_numerical_code_upper(Country) when bit_size(Country) =:= 24 -> alpha_3_to_numerical_code_upper(Country).

%% @doc Converts two letter country codes (ISO alpha-2) and the three letter country codes (ISO alpha-3)
%%      to Country names. This is case-sensitive (Expects uppercase).
%% @end
to_country_name_upper(Country) when bit_size(Country) =:= 16 -> alpha_2_to_name_upper(Country);
to_country_name_upper(Country) when bit_size(Country) =:= 24 -> alpha_3_to_name_upper(Country).

%% @doc Converts two letter country code (ISO alpha-2) to the equivalent three letter country code (ISO alpha-3)
%%      This is case-sensitive (Expects uppercase).
%% @end
to_alpha_3_upper(<<"AD">>) -> <<"AND">>;
to_alpha_3_upper(<<"AE">>) -> <<"ARE">>;
to_alpha_3_upper(<<"AF">>) -> <<"AFG">>;
to_alpha_3_upper(<<"AG">>) -> <<"ATG">>;
to_alpha_3_upper(<<"AI">>) -> <<"AIA">>;
to_alpha_3_upper(<<"AL">>) -> <<"ALB">>;
to_alpha_3_upper(<<"AM">>) -> <<"ARM">>;
to_alpha_3_upper(<<"AO">>) -> <<"AGO">>;
to_alpha_3_upper(<<"AQ">>) -> <<"ATA">>;
to_alpha_3_upper(<<"AR">>) -> <<"ARG">>;
to_alpha_3_upper(<<"AS">>) -> <<"ASM">>;
to_alpha_3_upper(<<"AT">>) -> <<"AUT">>;
to_alpha_3_upper(<<"AU">>) -> <<"AUS">>;
to_alpha_3_upper(<<"AW">>) -> <<"ABW">>;
to_alpha_3_upper(<<"AX">>) -> <<"ALA">>;
to_alpha_3_upper(<<"AZ">>) -> <<"AZE">>;
to_alpha_3_upper(<<"BA">>) -> <<"BIH">>;
to_alpha_3_upper(<<"BB">>) -> <<"BRB">>;
to_alpha_3_upper(<<"BD">>) -> <<"BGD">>;
to_alpha_3_upper(<<"BE">>) -> <<"BEL">>;
to_alpha_3_upper(<<"BF">>) -> <<"BFA">>;
to_alpha_3_upper(<<"BG">>) -> <<"BGR">>;
to_alpha_3_upper(<<"BH">>) -> <<"BHR">>;
to_alpha_3_upper(<<"BI">>) -> <<"BDI">>;
to_alpha_3_upper(<<"BJ">>) -> <<"BEN">>;
to_alpha_3_upper(<<"BL">>) -> <<"BLM">>;
to_alpha_3_upper(<<"BM">>) -> <<"BMU">>;
to_alpha_3_upper(<<"BN">>) -> <<"BRN">>;
to_alpha_3_upper(<<"BO">>) -> <<"BOL">>;
to_alpha_3_upper(<<"BQ">>) -> <<"BES">>;
to_alpha_3_upper(<<"BR">>) -> <<"BRA">>;
to_alpha_3_upper(<<"BS">>) -> <<"BHS">>;
to_alpha_3_upper(<<"BT">>) -> <<"BTN">>;
to_alpha_3_upper(<<"BV">>) -> <<"BVT">>;
to_alpha_3_upper(<<"BW">>) -> <<"BWA">>;
to_alpha_3_upper(<<"BY">>) -> <<"BLR">>;
to_alpha_3_upper(<<"BZ">>) -> <<"BLZ">>;
to_alpha_3_upper(<<"CA">>) -> <<"CAN">>;
to_alpha_3_upper(<<"CC">>) -> <<"CCK">>;
to_alpha_3_upper(<<"CD">>) -> <<"COD">>;
to_alpha_3_upper(<<"CF">>) -> <<"CAF">>;
to_alpha_3_upper(<<"CG">>) -> <<"COG">>;
to_alpha_3_upper(<<"CH">>) -> <<"CHE">>;
to_alpha_3_upper(<<"CI">>) -> <<"CIV">>;
to_alpha_3_upper(<<"CK">>) -> <<"COK">>;
to_alpha_3_upper(<<"CL">>) -> <<"CHL">>;
to_alpha_3_upper(<<"CM">>) -> <<"CMR">>;
to_alpha_3_upper(<<"CN">>) -> <<"CHN">>;
to_alpha_3_upper(<<"CO">>) -> <<"COL">>;
to_alpha_3_upper(<<"CR">>) -> <<"CRI">>;
to_alpha_3_upper(<<"CU">>) -> <<"CUB">>;
to_alpha_3_upper(<<"CV">>) -> <<"CPV">>;
to_alpha_3_upper(<<"CW">>) -> <<"CUW">>;
to_alpha_3_upper(<<"CX">>) -> <<"CXR">>;
to_alpha_3_upper(<<"CY">>) -> <<"CYP">>;
to_alpha_3_upper(<<"CZ">>) -> <<"CZE">>;
to_alpha_3_upper(<<"DE">>) -> <<"DEU">>;
to_alpha_3_upper(<<"DJ">>) -> <<"DJI">>;
to_alpha_3_upper(<<"DK">>) -> <<"DNK">>;
to_alpha_3_upper(<<"DM">>) -> <<"DMA">>;
to_alpha_3_upper(<<"DO">>) -> <<"DOM">>;
to_alpha_3_upper(<<"DZ">>) -> <<"DZA">>;
to_alpha_3_upper(<<"EC">>) -> <<"ECU">>;
to_alpha_3_upper(<<"EE">>) -> <<"EST">>;
to_alpha_3_upper(<<"EG">>) -> <<"EGY">>;
to_alpha_3_upper(<<"EH">>) -> <<"ESH">>;
to_alpha_3_upper(<<"ER">>) -> <<"ERI">>;
to_alpha_3_upper(<<"ES">>) -> <<"ESP">>;
to_alpha_3_upper(<<"ET">>) -> <<"ETH">>;
to_alpha_3_upper(<<"FI">>) -> <<"FIN">>;
to_alpha_3_upper(<<"FJ">>) -> <<"FJI">>;
to_alpha_3_upper(<<"FK">>) -> <<"FLK">>;
to_alpha_3_upper(<<"FM">>) -> <<"FSM">>;
to_alpha_3_upper(<<"FO">>) -> <<"FRO">>;
to_alpha_3_upper(<<"FR">>) -> <<"FRA">>;
to_alpha_3_upper(<<"GA">>) -> <<"GAB">>;
to_alpha_3_upper(<<"GB">>) -> <<"GBR">>;
to_alpha_3_upper(<<"GD">>) -> <<"GRD">>;
to_alpha_3_upper(<<"GE">>) -> <<"GEO">>;
to_alpha_3_upper(<<"GF">>) -> <<"GUF">>;
to_alpha_3_upper(<<"GG">>) -> <<"GGY">>;
to_alpha_3_upper(<<"GH">>) -> <<"GHA">>;
to_alpha_3_upper(<<"GI">>) -> <<"GIB">>;
to_alpha_3_upper(<<"GL">>) -> <<"GRL">>;
to_alpha_3_upper(<<"GM">>) -> <<"GMB">>;
to_alpha_3_upper(<<"GN">>) -> <<"GIN">>;
to_alpha_3_upper(<<"GP">>) -> <<"GLP">>;
to_alpha_3_upper(<<"GQ">>) -> <<"GNQ">>;
to_alpha_3_upper(<<"GR">>) -> <<"GRC">>;
to_alpha_3_upper(<<"GS">>) -> <<"SGS">>;
to_alpha_3_upper(<<"GT">>) -> <<"GTM">>;
to_alpha_3_upper(<<"GU">>) -> <<"GUM">>;
to_alpha_3_upper(<<"GW">>) -> <<"GNB">>;
to_alpha_3_upper(<<"GY">>) -> <<"GUY">>;
to_alpha_3_upper(<<"HK">>) -> <<"HKG">>;
to_alpha_3_upper(<<"HM">>) -> <<"HMD">>;
to_alpha_3_upper(<<"HN">>) -> <<"HND">>;
to_alpha_3_upper(<<"HR">>) -> <<"HRV">>;
to_alpha_3_upper(<<"HT">>) -> <<"HTI">>;
to_alpha_3_upper(<<"HU">>) -> <<"HUN">>;
to_alpha_3_upper(<<"ID">>) -> <<"IDN">>;
to_alpha_3_upper(<<"IE">>) -> <<"IRL">>;
to_alpha_3_upper(<<"IL">>) -> <<"ISR">>;
to_alpha_3_upper(<<"IM">>) -> <<"IMN">>;
to_alpha_3_upper(<<"IN">>) -> <<"IND">>;
to_alpha_3_upper(<<"IO">>) -> <<"IOT">>;
to_alpha_3_upper(<<"IQ">>) -> <<"IRQ">>;
to_alpha_3_upper(<<"IR">>) -> <<"IRN">>;
to_alpha_3_upper(<<"IS">>) -> <<"ISL">>;
to_alpha_3_upper(<<"IT">>) -> <<"ITA">>;
to_alpha_3_upper(<<"JE">>) -> <<"JEY">>;
to_alpha_3_upper(<<"JM">>) -> <<"JAM">>;
to_alpha_3_upper(<<"JO">>) -> <<"JOR">>;
to_alpha_3_upper(<<"JP">>) -> <<"JPN">>;
to_alpha_3_upper(<<"KE">>) -> <<"KEN">>;
to_alpha_3_upper(<<"KG">>) -> <<"KGZ">>;
to_alpha_3_upper(<<"KH">>) -> <<"KHM">>;
to_alpha_3_upper(<<"KI">>) -> <<"KIR">>;
to_alpha_3_upper(<<"KM">>) -> <<"COM">>;
to_alpha_3_upper(<<"KN">>) -> <<"KNA">>;
to_alpha_3_upper(<<"KP">>) -> <<"PRK">>;
to_alpha_3_upper(<<"KR">>) -> <<"KOR">>;
to_alpha_3_upper(<<"KW">>) -> <<"KWT">>;
to_alpha_3_upper(<<"KY">>) -> <<"CYM">>;
to_alpha_3_upper(<<"KZ">>) -> <<"KAZ">>;
to_alpha_3_upper(<<"LA">>) -> <<"LAO">>;
to_alpha_3_upper(<<"LB">>) -> <<"LBN">>;
to_alpha_3_upper(<<"LC">>) -> <<"LCA">>;
to_alpha_3_upper(<<"LI">>) -> <<"LIE">>;
to_alpha_3_upper(<<"LK">>) -> <<"LKA">>;
to_alpha_3_upper(<<"LR">>) -> <<"LBR">>;
to_alpha_3_upper(<<"LS">>) -> <<"LSO">>;
to_alpha_3_upper(<<"LT">>) -> <<"LTU">>;
to_alpha_3_upper(<<"LU">>) -> <<"LUX">>;
to_alpha_3_upper(<<"LV">>) -> <<"LVA">>;
to_alpha_3_upper(<<"LY">>) -> <<"LBY">>;
to_alpha_3_upper(<<"MA">>) -> <<"MAR">>;
to_alpha_3_upper(<<"MC">>) -> <<"MCO">>;
to_alpha_3_upper(<<"MD">>) -> <<"MDA">>;
to_alpha_3_upper(<<"ME">>) -> <<"MNE">>;
to_alpha_3_upper(<<"MF">>) -> <<"MAF">>;
to_alpha_3_upper(<<"MG">>) -> <<"MDG">>;
to_alpha_3_upper(<<"MH">>) -> <<"MHL">>;
to_alpha_3_upper(<<"MK">>) -> <<"MKD">>;
to_alpha_3_upper(<<"ML">>) -> <<"MLI">>;
to_alpha_3_upper(<<"MM">>) -> <<"MMR">>;
to_alpha_3_upper(<<"MN">>) -> <<"MNG">>;
to_alpha_3_upper(<<"MO">>) -> <<"MAC">>;
to_alpha_3_upper(<<"MP">>) -> <<"MNP">>;
to_alpha_3_upper(<<"MQ">>) -> <<"MTQ">>;
to_alpha_3_upper(<<"MR">>) -> <<"MRT">>;
to_alpha_3_upper(<<"MS">>) -> <<"MSR">>;
to_alpha_3_upper(<<"MT">>) -> <<"MLT">>;
to_alpha_3_upper(<<"MU">>) -> <<"MUS">>;
to_alpha_3_upper(<<"MV">>) -> <<"MDV">>;
to_alpha_3_upper(<<"MW">>) -> <<"MWI">>;
to_alpha_3_upper(<<"MX">>) -> <<"MEX">>;
to_alpha_3_upper(<<"MY">>) -> <<"MYS">>;
to_alpha_3_upper(<<"MZ">>) -> <<"MOZ">>;
to_alpha_3_upper(<<"NA">>) -> <<"NAM">>;
to_alpha_3_upper(<<"NC">>) -> <<"NCL">>;
to_alpha_3_upper(<<"NE">>) -> <<"NER">>;
to_alpha_3_upper(<<"NF">>) -> <<"NFK">>;
to_alpha_3_upper(<<"NG">>) -> <<"NGA">>;
to_alpha_3_upper(<<"NI">>) -> <<"NIC">>;
to_alpha_3_upper(<<"NL">>) -> <<"NLD">>;
to_alpha_3_upper(<<"NO">>) -> <<"NOR">>;
to_alpha_3_upper(<<"NP">>) -> <<"NPL">>;
to_alpha_3_upper(<<"NR">>) -> <<"NRU">>;
to_alpha_3_upper(<<"NU">>) -> <<"NIU">>;
to_alpha_3_upper(<<"NZ">>) -> <<"NZL">>;
to_alpha_3_upper(<<"OM">>) -> <<"OMN">>;
to_alpha_3_upper(<<"PA">>) -> <<"PAN">>;
to_alpha_3_upper(<<"PE">>) -> <<"PER">>;
to_alpha_3_upper(<<"PF">>) -> <<"PYF">>;
to_alpha_3_upper(<<"PG">>) -> <<"PNG">>;
to_alpha_3_upper(<<"PH">>) -> <<"PHL">>;
to_alpha_3_upper(<<"PK">>) -> <<"PAK">>;
to_alpha_3_upper(<<"PL">>) -> <<"POL">>;
to_alpha_3_upper(<<"PM">>) -> <<"SPM">>;
to_alpha_3_upper(<<"PN">>) -> <<"PCN">>;
to_alpha_3_upper(<<"PR">>) -> <<"PRI">>;
to_alpha_3_upper(<<"PS">>) -> <<"PSE">>;
to_alpha_3_upper(<<"PT">>) -> <<"PRT">>;
to_alpha_3_upper(<<"PW">>) -> <<"PLW">>;
to_alpha_3_upper(<<"PY">>) -> <<"PRY">>;
to_alpha_3_upper(<<"QA">>) -> <<"QAT">>;
to_alpha_3_upper(<<"RE">>) -> <<"REU">>;
to_alpha_3_upper(<<"RO">>) -> <<"ROU">>;
to_alpha_3_upper(<<"RS">>) -> <<"SRB">>;
to_alpha_3_upper(<<"RU">>) -> <<"RUS">>;
to_alpha_3_upper(<<"RW">>) -> <<"RWA">>;
to_alpha_3_upper(<<"SA">>) -> <<"SAU">>;
to_alpha_3_upper(<<"SB">>) -> <<"SLB">>;
to_alpha_3_upper(<<"SC">>) -> <<"SYC">>;
to_alpha_3_upper(<<"SD">>) -> <<"SDN">>;
to_alpha_3_upper(<<"SE">>) -> <<"SWE">>;
to_alpha_3_upper(<<"SG">>) -> <<"SGP">>;
to_alpha_3_upper(<<"SH">>) -> <<"SHN">>;
to_alpha_3_upper(<<"SI">>) -> <<"SVN">>;
to_alpha_3_upper(<<"SJ">>) -> <<"SJM">>;
to_alpha_3_upper(<<"SK">>) -> <<"SVK">>;
to_alpha_3_upper(<<"SL">>) -> <<"SLE">>;
to_alpha_3_upper(<<"SM">>) -> <<"SMR">>;
to_alpha_3_upper(<<"SN">>) -> <<"SEN">>;
to_alpha_3_upper(<<"SO">>) -> <<"SOM">>;
to_alpha_3_upper(<<"SR">>) -> <<"SUR">>;
to_alpha_3_upper(<<"SS">>) -> <<"SSD">>;
to_alpha_3_upper(<<"ST">>) -> <<"STP">>;
to_alpha_3_upper(<<"SV">>) -> <<"SLV">>;
to_alpha_3_upper(<<"SX">>) -> <<"SXM">>;
to_alpha_3_upper(<<"SY">>) -> <<"SYR">>;
to_alpha_3_upper(<<"SZ">>) -> <<"SWZ">>;
to_alpha_3_upper(<<"TC">>) -> <<"TCA">>;
to_alpha_3_upper(<<"TD">>) -> <<"TCD">>;
to_alpha_3_upper(<<"TF">>) -> <<"ATF">>;
to_alpha_3_upper(<<"TG">>) -> <<"TGO">>;
to_alpha_3_upper(<<"TH">>) -> <<"THA">>;
to_alpha_3_upper(<<"TJ">>) -> <<"TJK">>;
to_alpha_3_upper(<<"TK">>) -> <<"TKL">>;
to_alpha_3_upper(<<"TL">>) -> <<"TLS">>;
to_alpha_3_upper(<<"TM">>) -> <<"TKM">>;
to_alpha_3_upper(<<"TN">>) -> <<"TUN">>;
to_alpha_3_upper(<<"TO">>) -> <<"TON">>;
to_alpha_3_upper(<<"TR">>) -> <<"TUR">>;
to_alpha_3_upper(<<"TT">>) -> <<"TTO">>;
to_alpha_3_upper(<<"TV">>) -> <<"TUV">>;
to_alpha_3_upper(<<"TW">>) -> <<"TWN">>;
to_alpha_3_upper(<<"TZ">>) -> <<"TZA">>;
to_alpha_3_upper(<<"UA">>) -> <<"UKR">>;
to_alpha_3_upper(<<"UG">>) -> <<"UGA">>;
to_alpha_3_upper(<<"UM">>) -> <<"UMI">>;
to_alpha_3_upper(<<"US">>) -> <<"USA">>;
to_alpha_3_upper(<<"UY">>) -> <<"URY">>;
to_alpha_3_upper(<<"UZ">>) -> <<"UZB">>;
to_alpha_3_upper(<<"VA">>) -> <<"VAT">>;
to_alpha_3_upper(<<"VC">>) -> <<"VCT">>;
to_alpha_3_upper(<<"VE">>) -> <<"VEN">>;
to_alpha_3_upper(<<"VG">>) -> <<"VGB">>;
to_alpha_3_upper(<<"VI">>) -> <<"VIR">>;
to_alpha_3_upper(<<"VN">>) -> <<"VNM">>;
to_alpha_3_upper(<<"VU">>) -> <<"VUT">>;
to_alpha_3_upper(<<"WF">>) -> <<"WLF">>;
to_alpha_3_upper(<<"WS">>) -> <<"WSM">>;
to_alpha_3_upper(<<"YE">>) -> <<"YEM">>;
to_alpha_3_upper(<<"YT">>) -> <<"MYT">>;
to_alpha_3_upper(<<"ZA">>) -> <<"ZAF">>;
to_alpha_3_upper(<<"ZM">>) -> <<"ZMB">>;
to_alpha_3_upper(<<"ZW">>) -> <<"ZWE">>.

%% @doc Converts three letter country code (ISO alpha-3) to the equivalent two letter country code (ISO alpha-2).
%%      This is case-sensitive (Expects uppercase).
%% @end
to_alpha_2_upper(<<"ABW">>) -> <<"AW">>;
to_alpha_2_upper(<<"AFG">>) -> <<"AF">>;
to_alpha_2_upper(<<"AGO">>) -> <<"AO">>;
to_alpha_2_upper(<<"AIA">>) -> <<"AI">>;
to_alpha_2_upper(<<"ALA">>) -> <<"AX">>;
to_alpha_2_upper(<<"ALB">>) -> <<"AL">>;
to_alpha_2_upper(<<"AND">>) -> <<"AD">>;
to_alpha_2_upper(<<"ARE">>) -> <<"AE">>;
to_alpha_2_upper(<<"ARG">>) -> <<"AR">>;
to_alpha_2_upper(<<"ARM">>) -> <<"AM">>;
to_alpha_2_upper(<<"ASM">>) -> <<"AS">>;
to_alpha_2_upper(<<"ATA">>) -> <<"AQ">>;
to_alpha_2_upper(<<"ATF">>) -> <<"TF">>;
to_alpha_2_upper(<<"ATG">>) -> <<"AG">>;
to_alpha_2_upper(<<"AUS">>) -> <<"AU">>;
to_alpha_2_upper(<<"AUT">>) -> <<"AT">>;
to_alpha_2_upper(<<"AZE">>) -> <<"AZ">>;
to_alpha_2_upper(<<"BDI">>) -> <<"BI">>;
to_alpha_2_upper(<<"BEL">>) -> <<"BE">>;
to_alpha_2_upper(<<"BEN">>) -> <<"BJ">>;
to_alpha_2_upper(<<"BES">>) -> <<"BQ">>;
to_alpha_2_upper(<<"BFA">>) -> <<"BF">>;
to_alpha_2_upper(<<"BGD">>) -> <<"BD">>;
to_alpha_2_upper(<<"BGR">>) -> <<"BG">>;
to_alpha_2_upper(<<"BHR">>) -> <<"BH">>;
to_alpha_2_upper(<<"BHS">>) -> <<"BS">>;
to_alpha_2_upper(<<"BIH">>) -> <<"BA">>;
to_alpha_2_upper(<<"BLM">>) -> <<"BL">>;
to_alpha_2_upper(<<"BLR">>) -> <<"BY">>;
to_alpha_2_upper(<<"BLZ">>) -> <<"BZ">>;
to_alpha_2_upper(<<"BMU">>) -> <<"BM">>;
to_alpha_2_upper(<<"BOL">>) -> <<"BO">>;
to_alpha_2_upper(<<"BRA">>) -> <<"BR">>;
to_alpha_2_upper(<<"BRB">>) -> <<"BB">>;
to_alpha_2_upper(<<"BRN">>) -> <<"BN">>;
to_alpha_2_upper(<<"BTN">>) -> <<"BT">>;
to_alpha_2_upper(<<"BVT">>) -> <<"BV">>;
to_alpha_2_upper(<<"BWA">>) -> <<"BW">>;
to_alpha_2_upper(<<"CAF">>) -> <<"CF">>;
to_alpha_2_upper(<<"CAN">>) -> <<"CA">>;
to_alpha_2_upper(<<"CCK">>) -> <<"CC">>;
to_alpha_2_upper(<<"CHE">>) -> <<"CH">>;
to_alpha_2_upper(<<"CHL">>) -> <<"CL">>;
to_alpha_2_upper(<<"CHN">>) -> <<"CN">>;
to_alpha_2_upper(<<"CIV">>) -> <<"CI">>;
to_alpha_2_upper(<<"CMR">>) -> <<"CM">>;
to_alpha_2_upper(<<"COD">>) -> <<"CD">>;
to_alpha_2_upper(<<"COG">>) -> <<"CG">>;
to_alpha_2_upper(<<"COK">>) -> <<"CK">>;
to_alpha_2_upper(<<"COL">>) -> <<"CO">>;
to_alpha_2_upper(<<"COM">>) -> <<"KM">>;
to_alpha_2_upper(<<"CPV">>) -> <<"CV">>;
to_alpha_2_upper(<<"CRI">>) -> <<"CR">>;
to_alpha_2_upper(<<"CUB">>) -> <<"CU">>;
to_alpha_2_upper(<<"CUW">>) -> <<"CW">>;
to_alpha_2_upper(<<"CXR">>) -> <<"CX">>;
to_alpha_2_upper(<<"CYM">>) -> <<"KY">>;
to_alpha_2_upper(<<"CYP">>) -> <<"CY">>;
to_alpha_2_upper(<<"CZE">>) -> <<"CZ">>;
to_alpha_2_upper(<<"DEU">>) -> <<"DE">>;
to_alpha_2_upper(<<"DJI">>) -> <<"DJ">>;
to_alpha_2_upper(<<"DMA">>) -> <<"DM">>;
to_alpha_2_upper(<<"DNK">>) -> <<"DK">>;
to_alpha_2_upper(<<"DOM">>) -> <<"DO">>;
to_alpha_2_upper(<<"DZA">>) -> <<"DZ">>;
to_alpha_2_upper(<<"ECU">>) -> <<"EC">>;
to_alpha_2_upper(<<"EGY">>) -> <<"EG">>;
to_alpha_2_upper(<<"ERI">>) -> <<"ER">>;
to_alpha_2_upper(<<"ESH">>) -> <<"EH">>;
to_alpha_2_upper(<<"ESP">>) -> <<"ES">>;
to_alpha_2_upper(<<"EST">>) -> <<"EE">>;
to_alpha_2_upper(<<"ETH">>) -> <<"ET">>;
to_alpha_2_upper(<<"FIN">>) -> <<"FI">>;
to_alpha_2_upper(<<"FJI">>) -> <<"FJ">>;
to_alpha_2_upper(<<"FLK">>) -> <<"FK">>;
to_alpha_2_upper(<<"FRA">>) -> <<"FR">>;
to_alpha_2_upper(<<"FRO">>) -> <<"FO">>;
to_alpha_2_upper(<<"FSM">>) -> <<"FM">>;
to_alpha_2_upper(<<"GAB">>) -> <<"GA">>;
to_alpha_2_upper(<<"GBR">>) -> <<"GB">>;
to_alpha_2_upper(<<"GEO">>) -> <<"GE">>;
to_alpha_2_upper(<<"GGY">>) -> <<"GG">>;
to_alpha_2_upper(<<"GHA">>) -> <<"GH">>;
to_alpha_2_upper(<<"GIB">>) -> <<"GI">>;
to_alpha_2_upper(<<"GIN">>) -> <<"GN">>;
to_alpha_2_upper(<<"GLP">>) -> <<"GP">>;
to_alpha_2_upper(<<"GMB">>) -> <<"GM">>;
to_alpha_2_upper(<<"GNB">>) -> <<"GW">>;
to_alpha_2_upper(<<"GNQ">>) -> <<"GQ">>;
to_alpha_2_upper(<<"GRC">>) -> <<"GR">>;
to_alpha_2_upper(<<"GRD">>) -> <<"GD">>;
to_alpha_2_upper(<<"GRL">>) -> <<"GL">>;
to_alpha_2_upper(<<"GTM">>) -> <<"GT">>;
to_alpha_2_upper(<<"GUF">>) -> <<"GF">>;
to_alpha_2_upper(<<"GUM">>) -> <<"GU">>;
to_alpha_2_upper(<<"GUY">>) -> <<"GY">>;
to_alpha_2_upper(<<"HKG">>) -> <<"HK">>;
to_alpha_2_upper(<<"HMD">>) -> <<"HM">>;
to_alpha_2_upper(<<"HND">>) -> <<"HN">>;
to_alpha_2_upper(<<"HRV">>) -> <<"HR">>;
to_alpha_2_upper(<<"HTI">>) -> <<"HT">>;
to_alpha_2_upper(<<"HUN">>) -> <<"HU">>;
to_alpha_2_upper(<<"IDN">>) -> <<"ID">>;
to_alpha_2_upper(<<"IMN">>) -> <<"IM">>;
to_alpha_2_upper(<<"IND">>) -> <<"IN">>;
to_alpha_2_upper(<<"IOT">>) -> <<"IO">>;
to_alpha_2_upper(<<"IRL">>) -> <<"IE">>;
to_alpha_2_upper(<<"IRN">>) -> <<"IR">>;
to_alpha_2_upper(<<"IRQ">>) -> <<"IQ">>;
to_alpha_2_upper(<<"ISL">>) -> <<"IS">>;
to_alpha_2_upper(<<"ISR">>) -> <<"IL">>;
to_alpha_2_upper(<<"ITA">>) -> <<"IT">>;
to_alpha_2_upper(<<"JAM">>) -> <<"JM">>;
to_alpha_2_upper(<<"JEY">>) -> <<"JE">>;
to_alpha_2_upper(<<"JOR">>) -> <<"JO">>;
to_alpha_2_upper(<<"JPN">>) -> <<"JP">>;
to_alpha_2_upper(<<"KAZ">>) -> <<"KZ">>;
to_alpha_2_upper(<<"KEN">>) -> <<"KE">>;
to_alpha_2_upper(<<"KGZ">>) -> <<"KG">>;
to_alpha_2_upper(<<"KHM">>) -> <<"KH">>;
to_alpha_2_upper(<<"KIR">>) -> <<"KI">>;
to_alpha_2_upper(<<"KNA">>) -> <<"KN">>;
to_alpha_2_upper(<<"KOR">>) -> <<"KR">>;
to_alpha_2_upper(<<"KWT">>) -> <<"KW">>;
to_alpha_2_upper(<<"LAO">>) -> <<"LA">>;
to_alpha_2_upper(<<"LBN">>) -> <<"LB">>;
to_alpha_2_upper(<<"LBR">>) -> <<"LR">>;
to_alpha_2_upper(<<"LBY">>) -> <<"LY">>;
to_alpha_2_upper(<<"LCA">>) -> <<"LC">>;
to_alpha_2_upper(<<"LIE">>) -> <<"LI">>;
to_alpha_2_upper(<<"LKA">>) -> <<"LK">>;
to_alpha_2_upper(<<"LSO">>) -> <<"LS">>;
to_alpha_2_upper(<<"LTU">>) -> <<"LT">>;
to_alpha_2_upper(<<"LUX">>) -> <<"LU">>;
to_alpha_2_upper(<<"LVA">>) -> <<"LV">>;
to_alpha_2_upper(<<"MAC">>) -> <<"MO">>;
to_alpha_2_upper(<<"MAF">>) -> <<"MF">>;
to_alpha_2_upper(<<"MAR">>) -> <<"MA">>;
to_alpha_2_upper(<<"MCO">>) -> <<"MC">>;
to_alpha_2_upper(<<"MDA">>) -> <<"MD">>;
to_alpha_2_upper(<<"MDG">>) -> <<"MG">>;
to_alpha_2_upper(<<"MDV">>) -> <<"MV">>;
to_alpha_2_upper(<<"MEX">>) -> <<"MX">>;
to_alpha_2_upper(<<"MHL">>) -> <<"MH">>;
to_alpha_2_upper(<<"MKD">>) -> <<"MK">>;
to_alpha_2_upper(<<"MLI">>) -> <<"ML">>;
to_alpha_2_upper(<<"MLT">>) -> <<"MT">>;
to_alpha_2_upper(<<"MMR">>) -> <<"MM">>;
to_alpha_2_upper(<<"MNE">>) -> <<"ME">>;
to_alpha_2_upper(<<"MNG">>) -> <<"MN">>;
to_alpha_2_upper(<<"MNP">>) -> <<"MP">>;
to_alpha_2_upper(<<"MOZ">>) -> <<"MZ">>;
to_alpha_2_upper(<<"MRT">>) -> <<"MR">>;
to_alpha_2_upper(<<"MSR">>) -> <<"MS">>;
to_alpha_2_upper(<<"MTQ">>) -> <<"MQ">>;
to_alpha_2_upper(<<"MUS">>) -> <<"MU">>;
to_alpha_2_upper(<<"MWI">>) -> <<"MW">>;
to_alpha_2_upper(<<"MYS">>) -> <<"MY">>;
to_alpha_2_upper(<<"MYT">>) -> <<"YT">>;
to_alpha_2_upper(<<"NAM">>) -> <<"NA">>;
to_alpha_2_upper(<<"NCL">>) -> <<"NC">>;
to_alpha_2_upper(<<"NER">>) -> <<"NE">>;
to_alpha_2_upper(<<"NFK">>) -> <<"NF">>;
to_alpha_2_upper(<<"NGA">>) -> <<"NG">>;
to_alpha_2_upper(<<"NIC">>) -> <<"NI">>;
to_alpha_2_upper(<<"NIU">>) -> <<"NU">>;
to_alpha_2_upper(<<"NLD">>) -> <<"NL">>;
to_alpha_2_upper(<<"NOR">>) -> <<"NO">>;
to_alpha_2_upper(<<"NPL">>) -> <<"NP">>;
to_alpha_2_upper(<<"NRU">>) -> <<"NR">>;
to_alpha_2_upper(<<"NZL">>) -> <<"NZ">>;
to_alpha_2_upper(<<"OMN">>) -> <<"OM">>;
to_alpha_2_upper(<<"PAK">>) -> <<"PK">>;
to_alpha_2_upper(<<"PAN">>) -> <<"PA">>;
to_alpha_2_upper(<<"PCN">>) -> <<"PN">>;
to_alpha_2_upper(<<"PER">>) -> <<"PE">>;
to_alpha_2_upper(<<"PHL">>) -> <<"PH">>;
to_alpha_2_upper(<<"PLW">>) -> <<"PW">>;
to_alpha_2_upper(<<"PNG">>) -> <<"PG">>;
to_alpha_2_upper(<<"POL">>) -> <<"PL">>;
to_alpha_2_upper(<<"PRI">>) -> <<"PR">>;
to_alpha_2_upper(<<"PRK">>) -> <<"KP">>;
to_alpha_2_upper(<<"PRT">>) -> <<"PT">>;
to_alpha_2_upper(<<"PRY">>) -> <<"PY">>;
to_alpha_2_upper(<<"PSE">>) -> <<"PS">>;
to_alpha_2_upper(<<"PYF">>) -> <<"PF">>;
to_alpha_2_upper(<<"QAT">>) -> <<"QA">>;
to_alpha_2_upper(<<"REU">>) -> <<"RE">>;
to_alpha_2_upper(<<"ROU">>) -> <<"RO">>;
to_alpha_2_upper(<<"RUS">>) -> <<"RU">>;
to_alpha_2_upper(<<"RWA">>) -> <<"RW">>;
to_alpha_2_upper(<<"SAU">>) -> <<"SA">>;
to_alpha_2_upper(<<"SDN">>) -> <<"SD">>;
to_alpha_2_upper(<<"SEN">>) -> <<"SN">>;
to_alpha_2_upper(<<"SGP">>) -> <<"SG">>;
to_alpha_2_upper(<<"SGS">>) -> <<"GS">>;
to_alpha_2_upper(<<"SHN">>) -> <<"SH">>;
to_alpha_2_upper(<<"SJM">>) -> <<"SJ">>;
to_alpha_2_upper(<<"SLB">>) -> <<"SB">>;
to_alpha_2_upper(<<"SLE">>) -> <<"SL">>;
to_alpha_2_upper(<<"SLV">>) -> <<"SV">>;
to_alpha_2_upper(<<"SMR">>) -> <<"SM">>;
to_alpha_2_upper(<<"SOM">>) -> <<"SO">>;
to_alpha_2_upper(<<"SPM">>) -> <<"PM">>;
to_alpha_2_upper(<<"SRB">>) -> <<"RS">>;
to_alpha_2_upper(<<"SSD">>) -> <<"SS">>;
to_alpha_2_upper(<<"STP">>) -> <<"ST">>;
to_alpha_2_upper(<<"SUR">>) -> <<"SR">>;
to_alpha_2_upper(<<"SVK">>) -> <<"SK">>;
to_alpha_2_upper(<<"SVN">>) -> <<"SI">>;
to_alpha_2_upper(<<"SWE">>) -> <<"SE">>;
to_alpha_2_upper(<<"SWZ">>) -> <<"SZ">>;
to_alpha_2_upper(<<"SXM">>) -> <<"SX">>;
to_alpha_2_upper(<<"SYC">>) -> <<"SC">>;
to_alpha_2_upper(<<"SYR">>) -> <<"SY">>;
to_alpha_2_upper(<<"TCA">>) -> <<"TC">>;
to_alpha_2_upper(<<"TCD">>) -> <<"TD">>;
to_alpha_2_upper(<<"TGO">>) -> <<"TG">>;
to_alpha_2_upper(<<"THA">>) -> <<"TH">>;
to_alpha_2_upper(<<"TJK">>) -> <<"TJ">>;
to_alpha_2_upper(<<"TKL">>) -> <<"TK">>;
to_alpha_2_upper(<<"TKM">>) -> <<"TM">>;
to_alpha_2_upper(<<"TLS">>) -> <<"TL">>;
to_alpha_2_upper(<<"TON">>) -> <<"TO">>;
to_alpha_2_upper(<<"TTO">>) -> <<"TT">>;
to_alpha_2_upper(<<"TUN">>) -> <<"TN">>;
to_alpha_2_upper(<<"TUR">>) -> <<"TR">>;
to_alpha_2_upper(<<"TUV">>) -> <<"TV">>;
to_alpha_2_upper(<<"TWN">>) -> <<"TW">>;
to_alpha_2_upper(<<"TZA">>) -> <<"TZ">>;
to_alpha_2_upper(<<"UGA">>) -> <<"UG">>;
to_alpha_2_upper(<<"UKR">>) -> <<"UA">>;
to_alpha_2_upper(<<"UMI">>) -> <<"UM">>;
to_alpha_2_upper(<<"URY">>) -> <<"UY">>;
to_alpha_2_upper(<<"USA">>) -> <<"US">>;
to_alpha_2_upper(<<"UZB">>) -> <<"UZ">>;
to_alpha_2_upper(<<"VAT">>) -> <<"VA">>;
to_alpha_2_upper(<<"VCT">>) -> <<"VC">>;
to_alpha_2_upper(<<"VEN">>) -> <<"VE">>;
to_alpha_2_upper(<<"VGB">>) -> <<"VG">>;
to_alpha_2_upper(<<"VIR">>) -> <<"VI">>;
to_alpha_2_upper(<<"VNM">>) -> <<"VN">>;
to_alpha_2_upper(<<"VUT">>) -> <<"VU">>;
to_alpha_2_upper(<<"WLF">>) -> <<"WF">>;
to_alpha_2_upper(<<"WSM">>) -> <<"WS">>;
to_alpha_2_upper(<<"YEM">>) -> <<"YE">>;
to_alpha_2_upper(<<"ZAF">>) -> <<"ZA">>;
to_alpha_2_upper(<<"ZMB">>) -> <<"ZM">>;
to_alpha_2_upper(<<"ZWE">>) -> <<"ZW">>.

%% @doc Converts two letter country code (ISO alpha-2) to the equivalent country name.
%%      This is case-sensitive (Expects uppercase).
%% @end
alpha_2_to_name_upper(<<"AD">>) -> <<"Andorra"/utf8>>;
alpha_2_to_name_upper(<<"AE">>) -> <<"United Arab Emirates (the)"/utf8>>;
alpha_2_to_name_upper(<<"AF">>) -> <<"Afghanistan"/utf8>>;
alpha_2_to_name_upper(<<"AG">>) -> <<"Antigua and Barbuda"/utf8>>;
alpha_2_to_name_upper(<<"AI">>) -> <<"Anguilla"/utf8>>;
alpha_2_to_name_upper(<<"AL">>) -> <<"Albania"/utf8>>;
alpha_2_to_name_upper(<<"AM">>) -> <<"Armenia"/utf8>>;
alpha_2_to_name_upper(<<"AO">>) -> <<"Angola"/utf8>>;
alpha_2_to_name_upper(<<"AQ">>) -> <<"Antarctica"/utf8>>;
alpha_2_to_name_upper(<<"AR">>) -> <<"Argentina"/utf8>>;
alpha_2_to_name_upper(<<"AS">>) -> <<"American Samoa"/utf8>>;
alpha_2_to_name_upper(<<"AT">>) -> <<"Austria"/utf8>>;
alpha_2_to_name_upper(<<"AU">>) -> <<"Australia"/utf8>>;
alpha_2_to_name_upper(<<"AW">>) -> <<"Aruba"/utf8>>;
alpha_2_to_name_upper(<<"AX">>) -> <<"Aland Islands"/utf8>>;
alpha_2_to_name_upper(<<"AZ">>) -> <<"Azerbaijan"/utf8>>;
alpha_2_to_name_upper(<<"BA">>) -> <<"Bosnia and Herzegovina"/utf8>>;
alpha_2_to_name_upper(<<"BB">>) -> <<"Barbados"/utf8>>;
alpha_2_to_name_upper(<<"BD">>) -> <<"Bangladesh"/utf8>>;
alpha_2_to_name_upper(<<"BE">>) -> <<"Belgium"/utf8>>;
alpha_2_to_name_upper(<<"BF">>) -> <<"Burkina Faso"/utf8>>;
alpha_2_to_name_upper(<<"BG">>) -> <<"Bulgaria"/utf8>>;
alpha_2_to_name_upper(<<"BH">>) -> <<"Bahrain"/utf8>>;
alpha_2_to_name_upper(<<"BI">>) -> <<"Burundi"/utf8>>;
alpha_2_to_name_upper(<<"BJ">>) -> <<"Benin"/utf8>>;
alpha_2_to_name_upper(<<"BL">>) -> <<"Saint Barthélemy"/utf8>>;
alpha_2_to_name_upper(<<"BM">>) -> <<"Bermuda"/utf8>>;
alpha_2_to_name_upper(<<"BN">>) -> <<"Brunei Darussalam"/utf8>>;
alpha_2_to_name_upper(<<"BO">>) -> <<"Bolivia (Plurinational State of)"/utf8>>;
alpha_2_to_name_upper(<<"BQ">>) -> <<"Bonaire, Sint Eustatius and Saba"/utf8>>;
alpha_2_to_name_upper(<<"BR">>) -> <<"Brazil"/utf8>>;
alpha_2_to_name_upper(<<"BS">>) -> <<"Bahamas (the)"/utf8>>;
alpha_2_to_name_upper(<<"BT">>) -> <<"Bhutan"/utf8>>;
alpha_2_to_name_upper(<<"BV">>) -> <<"Bouvet Island"/utf8>>;
alpha_2_to_name_upper(<<"BW">>) -> <<"Botswana"/utf8>>;
alpha_2_to_name_upper(<<"BY">>) -> <<"Belarus"/utf8>>;
alpha_2_to_name_upper(<<"BZ">>) -> <<"Belize"/utf8>>;
alpha_2_to_name_upper(<<"CA">>) -> <<"Canada"/utf8>>;
alpha_2_to_name_upper(<<"CC">>) -> <<"Cocos (Keeling) Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"CD">>) -> <<"Congo (the Democratic Republic of the)"/utf8>>;
alpha_2_to_name_upper(<<"CF">>) -> <<"Central African Republic (the)"/utf8>>;
alpha_2_to_name_upper(<<"CG">>) -> <<"Congo (the)"/utf8>>;
alpha_2_to_name_upper(<<"CH">>) -> <<"Switzerland"/utf8>>;
alpha_2_to_name_upper(<<"CI">>) -> <<"Côte d'Ivoire"/utf8>>;
alpha_2_to_name_upper(<<"CK">>) -> <<"Cook Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"CL">>) -> <<"Chile"/utf8>>;
alpha_2_to_name_upper(<<"CM">>) -> <<"Cameroon"/utf8>>;
alpha_2_to_name_upper(<<"CN">>) -> <<"China"/utf8>>;
alpha_2_to_name_upper(<<"CO">>) -> <<"Colombia"/utf8>>;
alpha_2_to_name_upper(<<"CR">>) -> <<"Costa Rica"/utf8>>;
alpha_2_to_name_upper(<<"CU">>) -> <<"Cuba"/utf8>>;
alpha_2_to_name_upper(<<"CV">>) -> <<"Cabo Verde"/utf8>>;
alpha_2_to_name_upper(<<"CW">>) -> <<"Curaçao"/utf8>>;
alpha_2_to_name_upper(<<"CX">>) -> <<"Christmas Island"/utf8>>;
alpha_2_to_name_upper(<<"CY">>) -> <<"Cyprus"/utf8>>;
alpha_2_to_name_upper(<<"CZ">>) -> <<"Czechia"/utf8>>;
alpha_2_to_name_upper(<<"DE">>) -> <<"Germany"/utf8>>;
alpha_2_to_name_upper(<<"DJ">>) -> <<"Djibouti"/utf8>>;
alpha_2_to_name_upper(<<"DK">>) -> <<"Denmark"/utf8>>;
alpha_2_to_name_upper(<<"DM">>) -> <<"Dominica"/utf8>>;
alpha_2_to_name_upper(<<"DO">>) -> <<"Dominican Republic (the)"/utf8>>;
alpha_2_to_name_upper(<<"DZ">>) -> <<"Algeria"/utf8>>;
alpha_2_to_name_upper(<<"EC">>) -> <<"Ecuador"/utf8>>;
alpha_2_to_name_upper(<<"EE">>) -> <<"Estonia"/utf8>>;
alpha_2_to_name_upper(<<"EG">>) -> <<"Egypt"/utf8>>;
alpha_2_to_name_upper(<<"EH">>) -> <<"Western Sahara*"/utf8>>;
alpha_2_to_name_upper(<<"ER">>) -> <<"Eritrea"/utf8>>;
alpha_2_to_name_upper(<<"ES">>) -> <<"Spain"/utf8>>;
alpha_2_to_name_upper(<<"ET">>) -> <<"Ethiopia"/utf8>>;
alpha_2_to_name_upper(<<"FI">>) -> <<"Finland"/utf8>>;
alpha_2_to_name_upper(<<"FJ">>) -> <<"Fiji"/utf8>>;
alpha_2_to_name_upper(<<"FK">>) -> <<"Falkland Islands (the) [Malvinas]"/utf8>>;
alpha_2_to_name_upper(<<"FM">>) -> <<"Micronesia (Federated States of)"/utf8>>;
alpha_2_to_name_upper(<<"FO">>) -> <<"Faroe Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"FR">>) -> <<"France"/utf8>>;
alpha_2_to_name_upper(<<"GA">>) -> <<"Gabon"/utf8>>;
alpha_2_to_name_upper(<<"GB">>) -> <<"United Kingdom of Great Britain and Northern Ireland (the)"/utf8>>;
alpha_2_to_name_upper(<<"GD">>) -> <<"Grenada"/utf8>>;
alpha_2_to_name_upper(<<"GE">>) -> <<"Georgia"/utf8>>;
alpha_2_to_name_upper(<<"GF">>) -> <<"French Guiana"/utf8>>;
alpha_2_to_name_upper(<<"GG">>) -> <<"Guernsey"/utf8>>;
alpha_2_to_name_upper(<<"GH">>) -> <<"Ghana"/utf8>>;
alpha_2_to_name_upper(<<"GI">>) -> <<"Gibraltar"/utf8>>;
alpha_2_to_name_upper(<<"GL">>) -> <<"Greenland"/utf8>>;
alpha_2_to_name_upper(<<"GM">>) -> <<"Gambia (the)"/utf8>>;
alpha_2_to_name_upper(<<"GN">>) -> <<"Guinea"/utf8>>;
alpha_2_to_name_upper(<<"GP">>) -> <<"Guadeloupe"/utf8>>;
alpha_2_to_name_upper(<<"GQ">>) -> <<"Equatorial Guinea"/utf8>>;
alpha_2_to_name_upper(<<"GR">>) -> <<"Greece"/utf8>>;
alpha_2_to_name_upper(<<"GS">>) -> <<"South Georgia and the South Sandwich Islands"/utf8>>;
alpha_2_to_name_upper(<<"GT">>) -> <<"Guatemala"/utf8>>;
alpha_2_to_name_upper(<<"GU">>) -> <<"Guam"/utf8>>;
alpha_2_to_name_upper(<<"GW">>) -> <<"Guinea-Bissau"/utf8>>;
alpha_2_to_name_upper(<<"GY">>) -> <<"Guyana"/utf8>>;
alpha_2_to_name_upper(<<"HK">>) -> <<"Hong Kong"/utf8>>;
alpha_2_to_name_upper(<<"HM">>) -> <<"Heard Island and McDonald Islands"/utf8>>;
alpha_2_to_name_upper(<<"HN">>) -> <<"Honduras"/utf8>>;
alpha_2_to_name_upper(<<"HR">>) -> <<"Croatia"/utf8>>;
alpha_2_to_name_upper(<<"HT">>) -> <<"Haiti"/utf8>>;
alpha_2_to_name_upper(<<"HU">>) -> <<"Hungary"/utf8>>;
alpha_2_to_name_upper(<<"ID">>) -> <<"Indonesia"/utf8>>;
alpha_2_to_name_upper(<<"IE">>) -> <<"Ireland"/utf8>>;
alpha_2_to_name_upper(<<"IL">>) -> <<"Israel"/utf8>>;
alpha_2_to_name_upper(<<"IM">>) -> <<"Isle of Man"/utf8>>;
alpha_2_to_name_upper(<<"IN">>) -> <<"India"/utf8>>;
alpha_2_to_name_upper(<<"IO">>) -> <<"British Indian Ocean Territory (the)"/utf8>>;
alpha_2_to_name_upper(<<"IQ">>) -> <<"Iraq"/utf8>>;
alpha_2_to_name_upper(<<"IR">>) -> <<"Iran (Islamic Republic of)"/utf8>>;
alpha_2_to_name_upper(<<"IS">>) -> <<"Iceland"/utf8>>;
alpha_2_to_name_upper(<<"IT">>) -> <<"Italy"/utf8>>;
alpha_2_to_name_upper(<<"JE">>) -> <<"Jersey"/utf8>>;
alpha_2_to_name_upper(<<"JM">>) -> <<"Jamaica"/utf8>>;
alpha_2_to_name_upper(<<"JO">>) -> <<"Jordan"/utf8>>;
alpha_2_to_name_upper(<<"JP">>) -> <<"Japan"/utf8>>;
alpha_2_to_name_upper(<<"KE">>) -> <<"Kenya"/utf8>>;
alpha_2_to_name_upper(<<"KG">>) -> <<"Kyrgyzstan"/utf8>>;
alpha_2_to_name_upper(<<"KH">>) -> <<"Cambodia"/utf8>>;
alpha_2_to_name_upper(<<"KI">>) -> <<"Kiribati"/utf8>>;
alpha_2_to_name_upper(<<"KM">>) -> <<"Comoros (the)"/utf8>>;
alpha_2_to_name_upper(<<"KN">>) -> <<"Saint Kitts and Nevis"/utf8>>;
alpha_2_to_name_upper(<<"KP">>) -> <<"Korea (the Democratic People's Republic of)"/utf8>>;
alpha_2_to_name_upper(<<"KR">>) -> <<"Korea (the Republic of)"/utf8>>;
alpha_2_to_name_upper(<<"KW">>) -> <<"Kuwait"/utf8>>;
alpha_2_to_name_upper(<<"KY">>) -> <<"Cayman Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"KZ">>) -> <<"Kazakhstan"/utf8>>;
alpha_2_to_name_upper(<<"LA">>) -> <<"Lao People's Democratic Republic (the)"/utf8>>;
alpha_2_to_name_upper(<<"LB">>) -> <<"Lebanon"/utf8>>;
alpha_2_to_name_upper(<<"LC">>) -> <<"Saint Lucia"/utf8>>;
alpha_2_to_name_upper(<<"LI">>) -> <<"Liechtenstein"/utf8>>;
alpha_2_to_name_upper(<<"LK">>) -> <<"Sri Lanka"/utf8>>;
alpha_2_to_name_upper(<<"LR">>) -> <<"Liberia"/utf8>>;
alpha_2_to_name_upper(<<"LS">>) -> <<"Lesotho"/utf8>>;
alpha_2_to_name_upper(<<"LT">>) -> <<"Lithuania"/utf8>>;
alpha_2_to_name_upper(<<"LU">>) -> <<"Luxembourg"/utf8>>;
alpha_2_to_name_upper(<<"LV">>) -> <<"Latvia"/utf8>>;
alpha_2_to_name_upper(<<"LY">>) -> <<"Libya"/utf8>>;
alpha_2_to_name_upper(<<"MA">>) -> <<"Morocco"/utf8>>;
alpha_2_to_name_upper(<<"MC">>) -> <<"Monaco"/utf8>>;
alpha_2_to_name_upper(<<"MD">>) -> <<"Moldova (the Republic of)"/utf8>>;
alpha_2_to_name_upper(<<"ME">>) -> <<"Montenegro"/utf8>>;
alpha_2_to_name_upper(<<"MF">>) -> <<"Saint Martin (French part)"/utf8>>;
alpha_2_to_name_upper(<<"MG">>) -> <<"Madagascar"/utf8>>;
alpha_2_to_name_upper(<<"MH">>) -> <<"Marshall Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"MK">>) -> <<"Macedonia (the former Yugoslav Republic of)"/utf8>>;
alpha_2_to_name_upper(<<"ML">>) -> <<"Mali"/utf8>>;
alpha_2_to_name_upper(<<"MM">>) -> <<"Myanmar"/utf8>>;
alpha_2_to_name_upper(<<"MN">>) -> <<"Mongolia"/utf8>>;
alpha_2_to_name_upper(<<"MO">>) -> <<"Macao"/utf8>>;
alpha_2_to_name_upper(<<"MP">>) -> <<"Northern Mariana Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"MQ">>) -> <<"Martinique"/utf8>>;
alpha_2_to_name_upper(<<"MR">>) -> <<"Mauritania"/utf8>>;
alpha_2_to_name_upper(<<"MS">>) -> <<"Montserrat"/utf8>>;
alpha_2_to_name_upper(<<"MT">>) -> <<"Malta"/utf8>>;
alpha_2_to_name_upper(<<"MU">>) -> <<"Mauritius"/utf8>>;
alpha_2_to_name_upper(<<"MV">>) -> <<"Maldives"/utf8>>;
alpha_2_to_name_upper(<<"MW">>) -> <<"Malawi"/utf8>>;
alpha_2_to_name_upper(<<"MX">>) -> <<"Mexico"/utf8>>;
alpha_2_to_name_upper(<<"MY">>) -> <<"Malaysia"/utf8>>;
alpha_2_to_name_upper(<<"MZ">>) -> <<"Mozambique"/utf8>>;
alpha_2_to_name_upper(<<"NA">>) -> <<"Namibia"/utf8>>;
alpha_2_to_name_upper(<<"NC">>) -> <<"New Caledonia"/utf8>>;
alpha_2_to_name_upper(<<"NE">>) -> <<"Niger (the)"/utf8>>;
alpha_2_to_name_upper(<<"NF">>) -> <<"Norfolk Island"/utf8>>;
alpha_2_to_name_upper(<<"NG">>) -> <<"Nigeria"/utf8>>;
alpha_2_to_name_upper(<<"NI">>) -> <<"Nicaragua"/utf8>>;
alpha_2_to_name_upper(<<"NL">>) -> <<"Netherlands (the)"/utf8>>;
alpha_2_to_name_upper(<<"NO">>) -> <<"Norway"/utf8>>;
alpha_2_to_name_upper(<<"NP">>) -> <<"Nepal"/utf8>>;
alpha_2_to_name_upper(<<"NR">>) -> <<"Nauru"/utf8>>;
alpha_2_to_name_upper(<<"NU">>) -> <<"Niue"/utf8>>;
alpha_2_to_name_upper(<<"NZ">>) -> <<"New Zealand"/utf8>>;
alpha_2_to_name_upper(<<"OM">>) -> <<"Oman"/utf8>>;
alpha_2_to_name_upper(<<"PA">>) -> <<"Panama"/utf8>>;
alpha_2_to_name_upper(<<"PE">>) -> <<"Peru"/utf8>>;
alpha_2_to_name_upper(<<"PF">>) -> <<"French Polynesia"/utf8>>;
alpha_2_to_name_upper(<<"PG">>) -> <<"Papua New Guinea"/utf8>>;
alpha_2_to_name_upper(<<"PH">>) -> <<"Philippines (the)"/utf8>>;
alpha_2_to_name_upper(<<"PK">>) -> <<"Pakistan"/utf8>>;
alpha_2_to_name_upper(<<"PL">>) -> <<"Poland"/utf8>>;
alpha_2_to_name_upper(<<"PM">>) -> <<"Saint Pierre and Miquelon"/utf8>>;
alpha_2_to_name_upper(<<"PN">>) -> <<"Pitcairn"/utf8>>;
alpha_2_to_name_upper(<<"PR">>) -> <<"Puerto Rico"/utf8>>;
alpha_2_to_name_upper(<<"PS">>) -> <<"Palestine, State of"/utf8>>;
alpha_2_to_name_upper(<<"PT">>) -> <<"Portugal"/utf8>>;
alpha_2_to_name_upper(<<"PW">>) -> <<"Palau"/utf8>>;
alpha_2_to_name_upper(<<"PY">>) -> <<"Paraguay"/utf8>>;
alpha_2_to_name_upper(<<"QA">>) -> <<"Qatar"/utf8>>;
alpha_2_to_name_upper(<<"RE">>) -> <<"Réunion"/utf8>>;
alpha_2_to_name_upper(<<"RO">>) -> <<"Romania"/utf8>>;
alpha_2_to_name_upper(<<"RS">>) -> <<"Serbia"/utf8>>;
alpha_2_to_name_upper(<<"RU">>) -> <<"Russian Federation (the)"/utf8>>;
alpha_2_to_name_upper(<<"RW">>) -> <<"Rwanda"/utf8>>;
alpha_2_to_name_upper(<<"SA">>) -> <<"Saudi Arabia"/utf8>>;
alpha_2_to_name_upper(<<"SB">>) -> <<"Solomon Islands"/utf8>>;
alpha_2_to_name_upper(<<"SC">>) -> <<"Seychelles"/utf8>>;
alpha_2_to_name_upper(<<"SD">>) -> <<"Sudan (the)"/utf8>>;
alpha_2_to_name_upper(<<"SE">>) -> <<"Sweden"/utf8>>;
alpha_2_to_name_upper(<<"SG">>) -> <<"Singapore"/utf8>>;
alpha_2_to_name_upper(<<"SH">>) -> <<"Saint Helena, Ascension and Tristan da Cunha"/utf8>>;
alpha_2_to_name_upper(<<"SI">>) -> <<"Slovenia"/utf8>>;
alpha_2_to_name_upper(<<"SJ">>) -> <<"Svalbard and Jan Mayen"/utf8>>;
alpha_2_to_name_upper(<<"SK">>) -> <<"Slovakia"/utf8>>;
alpha_2_to_name_upper(<<"SL">>) -> <<"Sierra Leone"/utf8>>;
alpha_2_to_name_upper(<<"SM">>) -> <<"San Marino"/utf8>>;
alpha_2_to_name_upper(<<"SN">>) -> <<"Senegal"/utf8>>;
alpha_2_to_name_upper(<<"SO">>) -> <<"Somalia"/utf8>>;
alpha_2_to_name_upper(<<"SR">>) -> <<"Suriname"/utf8>>;
alpha_2_to_name_upper(<<"SS">>) -> <<"South Sudan"/utf8>>;
alpha_2_to_name_upper(<<"ST">>) -> <<"Sao Tome and Principe"/utf8>>;
alpha_2_to_name_upper(<<"SV">>) -> <<"El Salvador"/utf8>>;
alpha_2_to_name_upper(<<"SX">>) -> <<"Sint Maarten (Dutch part)"/utf8>>;
alpha_2_to_name_upper(<<"SY">>) -> <<"Syrian Arab Republic"/utf8>>;
alpha_2_to_name_upper(<<"SZ">>) -> <<"Swaziland"/utf8>>;
alpha_2_to_name_upper(<<"TC">>) -> <<"Turks and Caicos Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"TD">>) -> <<"Chad"/utf8>>;
alpha_2_to_name_upper(<<"TF">>) -> <<"French Southern Territories (the)"/utf8>>;
alpha_2_to_name_upper(<<"TG">>) -> <<"Togo"/utf8>>;
alpha_2_to_name_upper(<<"TH">>) -> <<"Thailand"/utf8>>;
alpha_2_to_name_upper(<<"TJ">>) -> <<"Tajikistan"/utf8>>;
alpha_2_to_name_upper(<<"TK">>) -> <<"Tokelau"/utf8>>;
alpha_2_to_name_upper(<<"TL">>) -> <<"Timor-Leste"/utf8>>;
alpha_2_to_name_upper(<<"TM">>) -> <<"Turkmenistan"/utf8>>;
alpha_2_to_name_upper(<<"TN">>) -> <<"Tunisia"/utf8>>;
alpha_2_to_name_upper(<<"TO">>) -> <<"Tonga"/utf8>>;
alpha_2_to_name_upper(<<"TR">>) -> <<"Turkey"/utf8>>;
alpha_2_to_name_upper(<<"TT">>) -> <<"Trinidad and Tobago"/utf8>>;
alpha_2_to_name_upper(<<"TV">>) -> <<"Tuvalu"/utf8>>;
alpha_2_to_name_upper(<<"TW">>) -> <<"Taiwan (Province of China)"/utf8>>;
alpha_2_to_name_upper(<<"TZ">>) -> <<"Tanzania, United Republic of"/utf8>>;
alpha_2_to_name_upper(<<"UA">>) -> <<"Ukraine"/utf8>>;
alpha_2_to_name_upper(<<"UG">>) -> <<"Uganda"/utf8>>;
alpha_2_to_name_upper(<<"UM">>) -> <<"United States Minor Outlying Islands (the)"/utf8>>;
alpha_2_to_name_upper(<<"US">>) -> <<"United States of America (the)"/utf8>>;
alpha_2_to_name_upper(<<"UY">>) -> <<"Uruguay"/utf8>>;
alpha_2_to_name_upper(<<"UZ">>) -> <<"Uzbekistan"/utf8>>;
alpha_2_to_name_upper(<<"VA">>) -> <<"Holy See (the)"/utf8>>;
alpha_2_to_name_upper(<<"VC">>) -> <<"Saint Vincent and the Grenadines"/utf8>>;
alpha_2_to_name_upper(<<"VE">>) -> <<"Venezuela (Bolivarian Republic of)"/utf8>>;
alpha_2_to_name_upper(<<"VG">>) -> <<"Virgin Islands (British)"/utf8>>;
alpha_2_to_name_upper(<<"VI">>) -> <<"Virgin Islands (U.S.)"/utf8>>;
alpha_2_to_name_upper(<<"VN">>) -> <<"Viet Nam"/utf8>>;
alpha_2_to_name_upper(<<"VU">>) -> <<"Vanuatu"/utf8>>;
alpha_2_to_name_upper(<<"WF">>) -> <<"Wallis and Futuna"/utf8>>;
alpha_2_to_name_upper(<<"WS">>) -> <<"Samoa"/utf8>>;
alpha_2_to_name_upper(<<"YE">>) -> <<"Yemen"/utf8>>;
alpha_2_to_name_upper(<<"YT">>) -> <<"Mayotte"/utf8>>;
alpha_2_to_name_upper(<<"ZA">>) -> <<"South Africa"/utf8>>;
alpha_2_to_name_upper(<<"ZM">>) -> <<"Zambia"/utf8>>;
alpha_2_to_name_upper(<<"ZW">>) -> <<"Zimbabwe"/utf8>>.

%% @doc Converts three letter country code (ISO alpha-3) to the equivalent country name.
%%      This is case-sensitive (Expects uppercase).
%% @end
alpha_3_to_name_upper(<<"ABW">>) -> <<"Aruba"/utf8>>;
alpha_3_to_name_upper(<<"AFG">>) -> <<"Afghanistan"/utf8>>;
alpha_3_to_name_upper(<<"AGO">>) -> <<"Angola"/utf8>>;
alpha_3_to_name_upper(<<"AIA">>) -> <<"Anguilla"/utf8>>;
alpha_3_to_name_upper(<<"ALA">>) -> <<"Aland Islands"/utf8>>;
alpha_3_to_name_upper(<<"ALB">>) -> <<"Albania"/utf8>>;
alpha_3_to_name_upper(<<"AND">>) -> <<"Andorra"/utf8>>;
alpha_3_to_name_upper(<<"ARE">>) -> <<"United Arab Emirates (the)"/utf8>>;
alpha_3_to_name_upper(<<"ARG">>) -> <<"Argentina"/utf8>>;
alpha_3_to_name_upper(<<"ARM">>) -> <<"Armenia"/utf8>>;
alpha_3_to_name_upper(<<"ASM">>) -> <<"American Samoa"/utf8>>;
alpha_3_to_name_upper(<<"ATA">>) -> <<"Antarctica"/utf8>>;
alpha_3_to_name_upper(<<"ATF">>) -> <<"French Southern Territories (the)"/utf8>>;
alpha_3_to_name_upper(<<"ATG">>) -> <<"Antigua and Barbuda"/utf8>>;
alpha_3_to_name_upper(<<"AUS">>) -> <<"Australia"/utf8>>;
alpha_3_to_name_upper(<<"AUT">>) -> <<"Austria"/utf8>>;
alpha_3_to_name_upper(<<"AZE">>) -> <<"Azerbaijan"/utf8>>;
alpha_3_to_name_upper(<<"BDI">>) -> <<"Burundi"/utf8>>;
alpha_3_to_name_upper(<<"BEL">>) -> <<"Belgium"/utf8>>;
alpha_3_to_name_upper(<<"BEN">>) -> <<"Benin"/utf8>>;
alpha_3_to_name_upper(<<"BES">>) -> <<"Bonaire, Sint Eustatius and Saba"/utf8>>;
alpha_3_to_name_upper(<<"BFA">>) -> <<"Burkina Faso"/utf8>>;
alpha_3_to_name_upper(<<"BGD">>) -> <<"Bangladesh"/utf8>>;
alpha_3_to_name_upper(<<"BGR">>) -> <<"Bulgaria"/utf8>>;
alpha_3_to_name_upper(<<"BHR">>) -> <<"Bahrain"/utf8>>;
alpha_3_to_name_upper(<<"BHS">>) -> <<"Bahamas (the)"/utf8>>;
alpha_3_to_name_upper(<<"BIH">>) -> <<"Bosnia and Herzegovina"/utf8>>;
alpha_3_to_name_upper(<<"BLM">>) -> <<"Saint Barthélemy"/utf8>>;
alpha_3_to_name_upper(<<"BLR">>) -> <<"Belarus"/utf8>>;
alpha_3_to_name_upper(<<"BLZ">>) -> <<"Belize"/utf8>>;
alpha_3_to_name_upper(<<"BMU">>) -> <<"Bermuda"/utf8>>;
alpha_3_to_name_upper(<<"BOL">>) -> <<"Bolivia (Plurinational State of)"/utf8>>;
alpha_3_to_name_upper(<<"BRA">>) -> <<"Brazil"/utf8>>;
alpha_3_to_name_upper(<<"BRB">>) -> <<"Barbados"/utf8>>;
alpha_3_to_name_upper(<<"BRN">>) -> <<"Brunei Darussalam"/utf8>>;
alpha_3_to_name_upper(<<"BTN">>) -> <<"Bhutan"/utf8>>;
alpha_3_to_name_upper(<<"BVT">>) -> <<"Bouvet Island"/utf8>>;
alpha_3_to_name_upper(<<"BWA">>) -> <<"Botswana"/utf8>>;
alpha_3_to_name_upper(<<"CAF">>) -> <<"Central African Republic (the)"/utf8>>;
alpha_3_to_name_upper(<<"CAN">>) -> <<"Canada"/utf8>>;
alpha_3_to_name_upper(<<"CCK">>) -> <<"Cocos (Keeling) Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"CHE">>) -> <<"Switzerland"/utf8>>;
alpha_3_to_name_upper(<<"CHL">>) -> <<"Chile"/utf8>>;
alpha_3_to_name_upper(<<"CHN">>) -> <<"China"/utf8>>;
alpha_3_to_name_upper(<<"CIV">>) -> <<"Côte d'Ivoire"/utf8>>;
alpha_3_to_name_upper(<<"CMR">>) -> <<"Cameroon"/utf8>>;
alpha_3_to_name_upper(<<"COD">>) -> <<"Congo (the Democratic Republic of the)"/utf8>>;
alpha_3_to_name_upper(<<"COG">>) -> <<"Congo (the)"/utf8>>;
alpha_3_to_name_upper(<<"COK">>) -> <<"Cook Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"COL">>) -> <<"Colombia"/utf8>>;
alpha_3_to_name_upper(<<"COM">>) -> <<"Comoros (the)"/utf8>>;
alpha_3_to_name_upper(<<"CPV">>) -> <<"Cabo Verde"/utf8>>;
alpha_3_to_name_upper(<<"CRI">>) -> <<"Costa Rica"/utf8>>;
alpha_3_to_name_upper(<<"CUB">>) -> <<"Cuba"/utf8>>;
alpha_3_to_name_upper(<<"CUW">>) -> <<"Curaçao"/utf8>>;
alpha_3_to_name_upper(<<"CXR">>) -> <<"Christmas Island"/utf8>>;
alpha_3_to_name_upper(<<"CYM">>) -> <<"Cayman Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"CYP">>) -> <<"Cyprus"/utf8>>;
alpha_3_to_name_upper(<<"CZE">>) -> <<"Czechia"/utf8>>;
alpha_3_to_name_upper(<<"DEU">>) -> <<"Germany"/utf8>>;
alpha_3_to_name_upper(<<"DJI">>) -> <<"Djibouti"/utf8>>;
alpha_3_to_name_upper(<<"DMA">>) -> <<"Dominica"/utf8>>;
alpha_3_to_name_upper(<<"DNK">>) -> <<"Denmark"/utf8>>;
alpha_3_to_name_upper(<<"DOM">>) -> <<"Dominican Republic (the)"/utf8>>;
alpha_3_to_name_upper(<<"DZA">>) -> <<"Algeria"/utf8>>;
alpha_3_to_name_upper(<<"ECU">>) -> <<"Ecuador"/utf8>>;
alpha_3_to_name_upper(<<"EGY">>) -> <<"Egypt"/utf8>>;
alpha_3_to_name_upper(<<"ERI">>) -> <<"Eritrea"/utf8>>;
alpha_3_to_name_upper(<<"ESH">>) -> <<"Western Sahara*"/utf8>>;
alpha_3_to_name_upper(<<"ESP">>) -> <<"Spain"/utf8>>;
alpha_3_to_name_upper(<<"EST">>) -> <<"Estonia"/utf8>>;
alpha_3_to_name_upper(<<"ETH">>) -> <<"Ethiopia"/utf8>>;
alpha_3_to_name_upper(<<"FIN">>) -> <<"Finland"/utf8>>;
alpha_3_to_name_upper(<<"FJI">>) -> <<"Fiji"/utf8>>;
alpha_3_to_name_upper(<<"FLK">>) -> <<"Falkland Islands (the) [Malvinas]"/utf8>>;
alpha_3_to_name_upper(<<"FRA">>) -> <<"France"/utf8>>;
alpha_3_to_name_upper(<<"FRO">>) -> <<"Faroe Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"FSM">>) -> <<"Micronesia (Federated States of)"/utf8>>;
alpha_3_to_name_upper(<<"GAB">>) -> <<"Gabon"/utf8>>;
alpha_3_to_name_upper(<<"GBR">>) -> <<"United Kingdom of Great Britain and Northern Ireland (the)"/utf8>>;
alpha_3_to_name_upper(<<"GEO">>) -> <<"Georgia"/utf8>>;
alpha_3_to_name_upper(<<"GGY">>) -> <<"Guernsey"/utf8>>;
alpha_3_to_name_upper(<<"GHA">>) -> <<"Ghana"/utf8>>;
alpha_3_to_name_upper(<<"GIB">>) -> <<"Gibraltar"/utf8>>;
alpha_3_to_name_upper(<<"GIN">>) -> <<"Guinea"/utf8>>;
alpha_3_to_name_upper(<<"GLP">>) -> <<"Guadeloupe"/utf8>>;
alpha_3_to_name_upper(<<"GMB">>) -> <<"Gambia (the)"/utf8>>;
alpha_3_to_name_upper(<<"GNB">>) -> <<"Guinea-Bissau"/utf8>>;
alpha_3_to_name_upper(<<"GNQ">>) -> <<"Equatorial Guinea"/utf8>>;
alpha_3_to_name_upper(<<"GRC">>) -> <<"Greece"/utf8>>;
alpha_3_to_name_upper(<<"GRD">>) -> <<"Grenada"/utf8>>;
alpha_3_to_name_upper(<<"GRL">>) -> <<"Greenland"/utf8>>;
alpha_3_to_name_upper(<<"GTM">>) -> <<"Guatemala"/utf8>>;
alpha_3_to_name_upper(<<"GUF">>) -> <<"French Guiana"/utf8>>;
alpha_3_to_name_upper(<<"GUM">>) -> <<"Guam"/utf8>>;
alpha_3_to_name_upper(<<"GUY">>) -> <<"Guyana"/utf8>>;
alpha_3_to_name_upper(<<"HKG">>) -> <<"Hong Kong"/utf8>>;
alpha_3_to_name_upper(<<"HMD">>) -> <<"Heard Island and McDonald Islands"/utf8>>;
alpha_3_to_name_upper(<<"HND">>) -> <<"Honduras"/utf8>>;
alpha_3_to_name_upper(<<"HRV">>) -> <<"Croatia"/utf8>>;
alpha_3_to_name_upper(<<"HTI">>) -> <<"Haiti"/utf8>>;
alpha_3_to_name_upper(<<"HUN">>) -> <<"Hungary"/utf8>>;
alpha_3_to_name_upper(<<"IDN">>) -> <<"Indonesia"/utf8>>;
alpha_3_to_name_upper(<<"IMN">>) -> <<"Isle of Man"/utf8>>;
alpha_3_to_name_upper(<<"IND">>) -> <<"India"/utf8>>;
alpha_3_to_name_upper(<<"IOT">>) -> <<"British Indian Ocean Territory (the)"/utf8>>;
alpha_3_to_name_upper(<<"IRL">>) -> <<"Ireland"/utf8>>;
alpha_3_to_name_upper(<<"IRN">>) -> <<"Iran (Islamic Republic of)"/utf8>>;
alpha_3_to_name_upper(<<"IRQ">>) -> <<"Iraq"/utf8>>;
alpha_3_to_name_upper(<<"ISL">>) -> <<"Iceland"/utf8>>;
alpha_3_to_name_upper(<<"ISR">>) -> <<"Israel"/utf8>>;
alpha_3_to_name_upper(<<"ITA">>) -> <<"Italy"/utf8>>;
alpha_3_to_name_upper(<<"JAM">>) -> <<"Jamaica"/utf8>>;
alpha_3_to_name_upper(<<"JEY">>) -> <<"Jersey"/utf8>>;
alpha_3_to_name_upper(<<"JOR">>) -> <<"Jordan"/utf8>>;
alpha_3_to_name_upper(<<"JPN">>) -> <<"Japan"/utf8>>;
alpha_3_to_name_upper(<<"KAZ">>) -> <<"Kazakhstan"/utf8>>;
alpha_3_to_name_upper(<<"KEN">>) -> <<"Kenya"/utf8>>;
alpha_3_to_name_upper(<<"KGZ">>) -> <<"Kyrgyzstan"/utf8>>;
alpha_3_to_name_upper(<<"KHM">>) -> <<"Cambodia"/utf8>>;
alpha_3_to_name_upper(<<"KIR">>) -> <<"Kiribati"/utf8>>;
alpha_3_to_name_upper(<<"KNA">>) -> <<"Saint Kitts and Nevis"/utf8>>;
alpha_3_to_name_upper(<<"KOR">>) -> <<"Korea (the Republic of)"/utf8>>;
alpha_3_to_name_upper(<<"KWT">>) -> <<"Kuwait"/utf8>>;
alpha_3_to_name_upper(<<"LAO">>) -> <<"Lao People's Democratic Republic (the)"/utf8>>;
alpha_3_to_name_upper(<<"LBN">>) -> <<"Lebanon"/utf8>>;
alpha_3_to_name_upper(<<"LBR">>) -> <<"Liberia"/utf8>>;
alpha_3_to_name_upper(<<"LBY">>) -> <<"Libya"/utf8>>;
alpha_3_to_name_upper(<<"LCA">>) -> <<"Saint Lucia"/utf8>>;
alpha_3_to_name_upper(<<"LIE">>) -> <<"Liechtenstein"/utf8>>;
alpha_3_to_name_upper(<<"LKA">>) -> <<"Sri Lanka"/utf8>>;
alpha_3_to_name_upper(<<"LSO">>) -> <<"Lesotho"/utf8>>;
alpha_3_to_name_upper(<<"LTU">>) -> <<"Lithuania"/utf8>>;
alpha_3_to_name_upper(<<"LUX">>) -> <<"Luxembourg"/utf8>>;
alpha_3_to_name_upper(<<"LVA">>) -> <<"Latvia"/utf8>>;
alpha_3_to_name_upper(<<"MAC">>) -> <<"Macao"/utf8>>;
alpha_3_to_name_upper(<<"MAF">>) -> <<"Saint Martin (French part)"/utf8>>;
alpha_3_to_name_upper(<<"MAR">>) -> <<"Morocco"/utf8>>;
alpha_3_to_name_upper(<<"MCO">>) -> <<"Monaco"/utf8>>;
alpha_3_to_name_upper(<<"MDA">>) -> <<"Moldova (the Republic of)"/utf8>>;
alpha_3_to_name_upper(<<"MDG">>) -> <<"Madagascar"/utf8>>;
alpha_3_to_name_upper(<<"MDV">>) -> <<"Maldives"/utf8>>;
alpha_3_to_name_upper(<<"MEX">>) -> <<"Mexico"/utf8>>;
alpha_3_to_name_upper(<<"MHL">>) -> <<"Marshall Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"MKD">>) -> <<"Macedonia (the former Yugoslav Republic of)"/utf8>>;
alpha_3_to_name_upper(<<"MLI">>) -> <<"Mali"/utf8>>;
alpha_3_to_name_upper(<<"MLT">>) -> <<"Malta"/utf8>>;
alpha_3_to_name_upper(<<"MMR">>) -> <<"Myanmar"/utf8>>;
alpha_3_to_name_upper(<<"MNE">>) -> <<"Montenegro"/utf8>>;
alpha_3_to_name_upper(<<"MNG">>) -> <<"Mongolia"/utf8>>;
alpha_3_to_name_upper(<<"MNP">>) -> <<"Northern Mariana Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"MOZ">>) -> <<"Mozambique"/utf8>>;
alpha_3_to_name_upper(<<"MRT">>) -> <<"Mauritania"/utf8>>;
alpha_3_to_name_upper(<<"MSR">>) -> <<"Montserrat"/utf8>>;
alpha_3_to_name_upper(<<"MTQ">>) -> <<"Martinique"/utf8>>;
alpha_3_to_name_upper(<<"MUS">>) -> <<"Mauritius"/utf8>>;
alpha_3_to_name_upper(<<"MWI">>) -> <<"Malawi"/utf8>>;
alpha_3_to_name_upper(<<"MYS">>) -> <<"Malaysia"/utf8>>;
alpha_3_to_name_upper(<<"MYT">>) -> <<"Mayotte"/utf8>>;
alpha_3_to_name_upper(<<"NAM">>) -> <<"Namibia"/utf8>>;
alpha_3_to_name_upper(<<"NCL">>) -> <<"New Caledonia"/utf8>>;
alpha_3_to_name_upper(<<"NER">>) -> <<"Niger (the)"/utf8>>;
alpha_3_to_name_upper(<<"NFK">>) -> <<"Norfolk Island"/utf8>>;
alpha_3_to_name_upper(<<"NGA">>) -> <<"Nigeria"/utf8>>;
alpha_3_to_name_upper(<<"NIC">>) -> <<"Nicaragua"/utf8>>;
alpha_3_to_name_upper(<<"NIU">>) -> <<"Niue"/utf8>>;
alpha_3_to_name_upper(<<"NLD">>) -> <<"Netherlands (the)"/utf8>>;
alpha_3_to_name_upper(<<"NOR">>) -> <<"Norway"/utf8>>;
alpha_3_to_name_upper(<<"NPL">>) -> <<"Nepal"/utf8>>;
alpha_3_to_name_upper(<<"NRU">>) -> <<"Nauru"/utf8>>;
alpha_3_to_name_upper(<<"NZL">>) -> <<"New Zealand"/utf8>>;
alpha_3_to_name_upper(<<"OMN">>) -> <<"Oman"/utf8>>;
alpha_3_to_name_upper(<<"PAK">>) -> <<"Pakistan"/utf8>>;
alpha_3_to_name_upper(<<"PAN">>) -> <<"Panama"/utf8>>;
alpha_3_to_name_upper(<<"PCN">>) -> <<"Pitcairn"/utf8>>;
alpha_3_to_name_upper(<<"PER">>) -> <<"Peru"/utf8>>;
alpha_3_to_name_upper(<<"PHL">>) -> <<"Philippines (the)"/utf8>>;
alpha_3_to_name_upper(<<"PLW">>) -> <<"Palau"/utf8>>;
alpha_3_to_name_upper(<<"PNG">>) -> <<"Papua New Guinea"/utf8>>;
alpha_3_to_name_upper(<<"POL">>) -> <<"Poland"/utf8>>;
alpha_3_to_name_upper(<<"PRI">>) -> <<"Puerto Rico"/utf8>>;
alpha_3_to_name_upper(<<"PRK">>) -> <<"Korea (the Democratic People's Republic of)"/utf8>>;
alpha_3_to_name_upper(<<"PRT">>) -> <<"Portugal"/utf8>>;
alpha_3_to_name_upper(<<"PRY">>) -> <<"Paraguay"/utf8>>;
alpha_3_to_name_upper(<<"PSE">>) -> <<"Palestine, State of"/utf8>>;
alpha_3_to_name_upper(<<"PYF">>) -> <<"French Polynesia"/utf8>>;
alpha_3_to_name_upper(<<"QAT">>) -> <<"Qatar"/utf8>>;
alpha_3_to_name_upper(<<"REU">>) -> <<"Réunion"/utf8>>;
alpha_3_to_name_upper(<<"ROU">>) -> <<"Romania"/utf8>>;
alpha_3_to_name_upper(<<"RUS">>) -> <<"Russian Federation (the)"/utf8>>;
alpha_3_to_name_upper(<<"RWA">>) -> <<"Rwanda"/utf8>>;
alpha_3_to_name_upper(<<"SAU">>) -> <<"Saudi Arabia"/utf8>>;
alpha_3_to_name_upper(<<"SDN">>) -> <<"Sudan (the)"/utf8>>;
alpha_3_to_name_upper(<<"SEN">>) -> <<"Senegal"/utf8>>;
alpha_3_to_name_upper(<<"SGP">>) -> <<"Singapore"/utf8>>;
alpha_3_to_name_upper(<<"SGS">>) -> <<"South Georgia and the South Sandwich Islands"/utf8>>;
alpha_3_to_name_upper(<<"SHN">>) -> <<"Saint Helena, Ascension and Tristan da Cunha"/utf8>>;
alpha_3_to_name_upper(<<"SJM">>) -> <<"Svalbard and Jan Mayen"/utf8>>;
alpha_3_to_name_upper(<<"SLB">>) -> <<"Solomon Islands"/utf8>>;
alpha_3_to_name_upper(<<"SLE">>) -> <<"Sierra Leone"/utf8>>;
alpha_3_to_name_upper(<<"SLV">>) -> <<"El Salvador"/utf8>>;
alpha_3_to_name_upper(<<"SMR">>) -> <<"San Marino"/utf8>>;
alpha_3_to_name_upper(<<"SOM">>) -> <<"Somalia"/utf8>>;
alpha_3_to_name_upper(<<"SPM">>) -> <<"Saint Pierre and Miquelon"/utf8>>;
alpha_3_to_name_upper(<<"SRB">>) -> <<"Serbia"/utf8>>;
alpha_3_to_name_upper(<<"SSD">>) -> <<"South Sudan"/utf8>>;
alpha_3_to_name_upper(<<"STP">>) -> <<"Sao Tome and Principe"/utf8>>;
alpha_3_to_name_upper(<<"SUR">>) -> <<"Suriname"/utf8>>;
alpha_3_to_name_upper(<<"SVK">>) -> <<"Slovakia"/utf8>>;
alpha_3_to_name_upper(<<"SVN">>) -> <<"Slovenia"/utf8>>;
alpha_3_to_name_upper(<<"SWE">>) -> <<"Sweden"/utf8>>;
alpha_3_to_name_upper(<<"SWZ">>) -> <<"Swaziland"/utf8>>;
alpha_3_to_name_upper(<<"SXM">>) -> <<"Sint Maarten (Dutch part)"/utf8>>;
alpha_3_to_name_upper(<<"SYC">>) -> <<"Seychelles"/utf8>>;
alpha_3_to_name_upper(<<"SYR">>) -> <<"Syrian Arab Republic"/utf8>>;
alpha_3_to_name_upper(<<"TCA">>) -> <<"Turks and Caicos Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"TCD">>) -> <<"Chad"/utf8>>;
alpha_3_to_name_upper(<<"TGO">>) -> <<"Togo"/utf8>>;
alpha_3_to_name_upper(<<"THA">>) -> <<"Thailand"/utf8>>;
alpha_3_to_name_upper(<<"TJK">>) -> <<"Tajikistan"/utf8>>;
alpha_3_to_name_upper(<<"TKL">>) -> <<"Tokelau"/utf8>>;
alpha_3_to_name_upper(<<"TKM">>) -> <<"Turkmenistan"/utf8>>;
alpha_3_to_name_upper(<<"TLS">>) -> <<"Timor-Leste"/utf8>>;
alpha_3_to_name_upper(<<"TON">>) -> <<"Tonga"/utf8>>;
alpha_3_to_name_upper(<<"TTO">>) -> <<"Trinidad and Tobago"/utf8>>;
alpha_3_to_name_upper(<<"TUN">>) -> <<"Tunisia"/utf8>>;
alpha_3_to_name_upper(<<"TUR">>) -> <<"Turkey"/utf8>>;
alpha_3_to_name_upper(<<"TUV">>) -> <<"Tuvalu"/utf8>>;
alpha_3_to_name_upper(<<"TWN">>) -> <<"Taiwan (Province of China)"/utf8>>;
alpha_3_to_name_upper(<<"TZA">>) -> <<"Tanzania, United Republic of"/utf8>>;
alpha_3_to_name_upper(<<"UGA">>) -> <<"Uganda"/utf8>>;
alpha_3_to_name_upper(<<"UKR">>) -> <<"Ukraine"/utf8>>;
alpha_3_to_name_upper(<<"UMI">>) -> <<"United States Minor Outlying Islands (the)"/utf8>>;
alpha_3_to_name_upper(<<"URY">>) -> <<"Uruguay"/utf8>>;
alpha_3_to_name_upper(<<"USA">>) -> <<"United States of America (the)"/utf8>>;
alpha_3_to_name_upper(<<"UZB">>) -> <<"Uzbekistan"/utf8>>;
alpha_3_to_name_upper(<<"VAT">>) -> <<"Holy See (the)"/utf8>>;
alpha_3_to_name_upper(<<"VCT">>) -> <<"Saint Vincent and the Grenadines"/utf8>>;
alpha_3_to_name_upper(<<"VEN">>) -> <<"Venezuela (Bolivarian Republic of)"/utf8>>;
alpha_3_to_name_upper(<<"VGB">>) -> <<"Virgin Islands (British)"/utf8>>;
alpha_3_to_name_upper(<<"VIR">>) -> <<"Virgin Islands (U.S.)"/utf8>>;
alpha_3_to_name_upper(<<"VNM">>) -> <<"Viet Nam"/utf8>>;
alpha_3_to_name_upper(<<"VUT">>) -> <<"Vanuatu"/utf8>>;
alpha_3_to_name_upper(<<"WLF">>) -> <<"Wallis and Futuna"/utf8>>;
alpha_3_to_name_upper(<<"WSM">>) -> <<"Samoa"/utf8>>;
alpha_3_to_name_upper(<<"YEM">>) -> <<"Yemen"/utf8>>;
alpha_3_to_name_upper(<<"ZAF">>) -> <<"South Africa"/utf8>>;
alpha_3_to_name_upper(<<"ZMB">>) -> <<"Zambia"/utf8>>;
alpha_3_to_name_upper(<<"ZWE">>) -> <<"Zimbabwe"/utf8>>.

%% @doc Converts three letter country code (ISO alpha-3) to the equivalent United Nations numerical code M49 for countries.
%%      This is case-sensitive (Expects uppercase).
%% @end
alpha_3_to_numerical_code_upper(<<"ABW">>) -> 533;
alpha_3_to_numerical_code_upper(<<"AFG">>) -> 4;
alpha_3_to_numerical_code_upper(<<"AGO">>) -> 24;
alpha_3_to_numerical_code_upper(<<"AIA">>) -> 660;
alpha_3_to_numerical_code_upper(<<"ALA">>) -> 248;
alpha_3_to_numerical_code_upper(<<"ALB">>) -> 8;
alpha_3_to_numerical_code_upper(<<"AND">>) -> 20;
alpha_3_to_numerical_code_upper(<<"ARE">>) -> 784;
alpha_3_to_numerical_code_upper(<<"ARG">>) -> 32;
alpha_3_to_numerical_code_upper(<<"ARM">>) -> 51;
alpha_3_to_numerical_code_upper(<<"ASM">>) -> 16;
alpha_3_to_numerical_code_upper(<<"ATA">>) -> 10;
alpha_3_to_numerical_code_upper(<<"ATF">>) -> 260;
alpha_3_to_numerical_code_upper(<<"ATG">>) -> 28;
alpha_3_to_numerical_code_upper(<<"AUS">>) -> 36;
alpha_3_to_numerical_code_upper(<<"AUT">>) -> 40;
alpha_3_to_numerical_code_upper(<<"AZE">>) -> 31;
alpha_3_to_numerical_code_upper(<<"BDI">>) -> 108;
alpha_3_to_numerical_code_upper(<<"BEL">>) -> 56;
alpha_3_to_numerical_code_upper(<<"BEN">>) -> 204;
alpha_3_to_numerical_code_upper(<<"BES">>) -> 535;
alpha_3_to_numerical_code_upper(<<"BFA">>) -> 854;
alpha_3_to_numerical_code_upper(<<"BGD">>) -> 50;
alpha_3_to_numerical_code_upper(<<"BGR">>) -> 100;
alpha_3_to_numerical_code_upper(<<"BHR">>) -> 48;
alpha_3_to_numerical_code_upper(<<"BHS">>) -> 44;
alpha_3_to_numerical_code_upper(<<"BIH">>) -> 70;
alpha_3_to_numerical_code_upper(<<"BLM">>) -> 652;
alpha_3_to_numerical_code_upper(<<"BLR">>) -> 112;
alpha_3_to_numerical_code_upper(<<"BLZ">>) -> 84;
alpha_3_to_numerical_code_upper(<<"BMU">>) -> 60;
alpha_3_to_numerical_code_upper(<<"BOL">>) -> 68;
alpha_3_to_numerical_code_upper(<<"BRA">>) -> 76;
alpha_3_to_numerical_code_upper(<<"BRB">>) -> 52;
alpha_3_to_numerical_code_upper(<<"BRN">>) -> 96;
alpha_3_to_numerical_code_upper(<<"BTN">>) -> 64;
alpha_3_to_numerical_code_upper(<<"BVT">>) -> 74;
alpha_3_to_numerical_code_upper(<<"BWA">>) -> 72;
alpha_3_to_numerical_code_upper(<<"CAF">>) -> 140;
alpha_3_to_numerical_code_upper(<<"CAN">>) -> 124;
alpha_3_to_numerical_code_upper(<<"CCK">>) -> 166;
alpha_3_to_numerical_code_upper(<<"CHE">>) -> 756;
alpha_3_to_numerical_code_upper(<<"CHL">>) -> 152;
alpha_3_to_numerical_code_upper(<<"CHN">>) -> 156;
alpha_3_to_numerical_code_upper(<<"CIV">>) -> 384;
alpha_3_to_numerical_code_upper(<<"CMR">>) -> 120;
alpha_3_to_numerical_code_upper(<<"COD">>) -> 180;
alpha_3_to_numerical_code_upper(<<"COG">>) -> 178;
alpha_3_to_numerical_code_upper(<<"COK">>) -> 184;
alpha_3_to_numerical_code_upper(<<"COL">>) -> 170;
alpha_3_to_numerical_code_upper(<<"COM">>) -> 174;
alpha_3_to_numerical_code_upper(<<"CPV">>) -> 132;
alpha_3_to_numerical_code_upper(<<"CRI">>) -> 188;
alpha_3_to_numerical_code_upper(<<"CUB">>) -> 192;
alpha_3_to_numerical_code_upper(<<"CUW">>) -> 531;
alpha_3_to_numerical_code_upper(<<"CXR">>) -> 162;
alpha_3_to_numerical_code_upper(<<"CYM">>) -> 136;
alpha_3_to_numerical_code_upper(<<"CYP">>) -> 196;
alpha_3_to_numerical_code_upper(<<"CZE">>) -> 203;
alpha_3_to_numerical_code_upper(<<"DEU">>) -> 276;
alpha_3_to_numerical_code_upper(<<"DJI">>) -> 262;
alpha_3_to_numerical_code_upper(<<"DMA">>) -> 212;
alpha_3_to_numerical_code_upper(<<"DNK">>) -> 208;
alpha_3_to_numerical_code_upper(<<"DOM">>) -> 214;
alpha_3_to_numerical_code_upper(<<"DZA">>) -> 12;
alpha_3_to_numerical_code_upper(<<"ECU">>) -> 218;
alpha_3_to_numerical_code_upper(<<"EGY">>) -> 818;
alpha_3_to_numerical_code_upper(<<"ERI">>) -> 232;
alpha_3_to_numerical_code_upper(<<"ESH">>) -> 732;
alpha_3_to_numerical_code_upper(<<"ESP">>) -> 724;
alpha_3_to_numerical_code_upper(<<"EST">>) -> 233;
alpha_3_to_numerical_code_upper(<<"ETH">>) -> 231;
alpha_3_to_numerical_code_upper(<<"FIN">>) -> 246;
alpha_3_to_numerical_code_upper(<<"FJI">>) -> 242;
alpha_3_to_numerical_code_upper(<<"FLK">>) -> 238;
alpha_3_to_numerical_code_upper(<<"FRA">>) -> 250;
alpha_3_to_numerical_code_upper(<<"FRO">>) -> 234;
alpha_3_to_numerical_code_upper(<<"FSM">>) -> 583;
alpha_3_to_numerical_code_upper(<<"GAB">>) -> 266;
alpha_3_to_numerical_code_upper(<<"GBR">>) -> 826;
alpha_3_to_numerical_code_upper(<<"GEO">>) -> 268;
alpha_3_to_numerical_code_upper(<<"GGY">>) -> 831;
alpha_3_to_numerical_code_upper(<<"GHA">>) -> 288;
alpha_3_to_numerical_code_upper(<<"GIB">>) -> 292;
alpha_3_to_numerical_code_upper(<<"GIN">>) -> 324;
alpha_3_to_numerical_code_upper(<<"GLP">>) -> 312;
alpha_3_to_numerical_code_upper(<<"GMB">>) -> 270;
alpha_3_to_numerical_code_upper(<<"GNB">>) -> 624;
alpha_3_to_numerical_code_upper(<<"GNQ">>) -> 226;
alpha_3_to_numerical_code_upper(<<"GRC">>) -> 300;
alpha_3_to_numerical_code_upper(<<"GRD">>) -> 308;
alpha_3_to_numerical_code_upper(<<"GRL">>) -> 304;
alpha_3_to_numerical_code_upper(<<"GTM">>) -> 320;
alpha_3_to_numerical_code_upper(<<"GUF">>) -> 254;
alpha_3_to_numerical_code_upper(<<"GUM">>) -> 316;
alpha_3_to_numerical_code_upper(<<"GUY">>) -> 328;
alpha_3_to_numerical_code_upper(<<"HKG">>) -> 344;
alpha_3_to_numerical_code_upper(<<"HMD">>) -> 334;
alpha_3_to_numerical_code_upper(<<"HND">>) -> 340;
alpha_3_to_numerical_code_upper(<<"HRV">>) -> 191;
alpha_3_to_numerical_code_upper(<<"HTI">>) -> 332;
alpha_3_to_numerical_code_upper(<<"HUN">>) -> 348;
alpha_3_to_numerical_code_upper(<<"IDN">>) -> 360;
alpha_3_to_numerical_code_upper(<<"IMN">>) -> 833;
alpha_3_to_numerical_code_upper(<<"IND">>) -> 356;
alpha_3_to_numerical_code_upper(<<"IOT">>) -> 86;
alpha_3_to_numerical_code_upper(<<"IRL">>) -> 372;
alpha_3_to_numerical_code_upper(<<"IRN">>) -> 364;
alpha_3_to_numerical_code_upper(<<"IRQ">>) -> 368;
alpha_3_to_numerical_code_upper(<<"ISL">>) -> 352;
alpha_3_to_numerical_code_upper(<<"ISR">>) -> 376;
alpha_3_to_numerical_code_upper(<<"ITA">>) -> 380;
alpha_3_to_numerical_code_upper(<<"JAM">>) -> 388;
alpha_3_to_numerical_code_upper(<<"JEY">>) -> 832;
alpha_3_to_numerical_code_upper(<<"JOR">>) -> 400;
alpha_3_to_numerical_code_upper(<<"JPN">>) -> 392;
alpha_3_to_numerical_code_upper(<<"KAZ">>) -> 398;
alpha_3_to_numerical_code_upper(<<"KEN">>) -> 404;
alpha_3_to_numerical_code_upper(<<"KGZ">>) -> 417;
alpha_3_to_numerical_code_upper(<<"KHM">>) -> 116;
alpha_3_to_numerical_code_upper(<<"KIR">>) -> 296;
alpha_3_to_numerical_code_upper(<<"KNA">>) -> 659;
alpha_3_to_numerical_code_upper(<<"KOR">>) -> 410;
alpha_3_to_numerical_code_upper(<<"KWT">>) -> 414;
alpha_3_to_numerical_code_upper(<<"LAO">>) -> 418;
alpha_3_to_numerical_code_upper(<<"LBN">>) -> 422;
alpha_3_to_numerical_code_upper(<<"LBR">>) -> 430;
alpha_3_to_numerical_code_upper(<<"LBY">>) -> 434;
alpha_3_to_numerical_code_upper(<<"LCA">>) -> 662;
alpha_3_to_numerical_code_upper(<<"LIE">>) -> 438;
alpha_3_to_numerical_code_upper(<<"LKA">>) -> 144;
alpha_3_to_numerical_code_upper(<<"LSO">>) -> 426;
alpha_3_to_numerical_code_upper(<<"LTU">>) -> 440;
alpha_3_to_numerical_code_upper(<<"LUX">>) -> 442;
alpha_3_to_numerical_code_upper(<<"LVA">>) -> 428;
alpha_3_to_numerical_code_upper(<<"MAC">>) -> 446;
alpha_3_to_numerical_code_upper(<<"MAF">>) -> 663;
alpha_3_to_numerical_code_upper(<<"MAR">>) -> 504;
alpha_3_to_numerical_code_upper(<<"MCO">>) -> 492;
alpha_3_to_numerical_code_upper(<<"MDA">>) -> 498;
alpha_3_to_numerical_code_upper(<<"MDG">>) -> 450;
alpha_3_to_numerical_code_upper(<<"MDV">>) -> 462;
alpha_3_to_numerical_code_upper(<<"MEX">>) -> 484;
alpha_3_to_numerical_code_upper(<<"MHL">>) -> 584;
alpha_3_to_numerical_code_upper(<<"MKD">>) -> 807;
alpha_3_to_numerical_code_upper(<<"MLI">>) -> 466;
alpha_3_to_numerical_code_upper(<<"MLT">>) -> 470;
alpha_3_to_numerical_code_upper(<<"MMR">>) -> 104;
alpha_3_to_numerical_code_upper(<<"MNE">>) -> 499;
alpha_3_to_numerical_code_upper(<<"MNG">>) -> 496;
alpha_3_to_numerical_code_upper(<<"MNP">>) -> 580;
alpha_3_to_numerical_code_upper(<<"MOZ">>) -> 508;
alpha_3_to_numerical_code_upper(<<"MRT">>) -> 478;
alpha_3_to_numerical_code_upper(<<"MSR">>) -> 500;
alpha_3_to_numerical_code_upper(<<"MTQ">>) -> 474;
alpha_3_to_numerical_code_upper(<<"MUS">>) -> 480;
alpha_3_to_numerical_code_upper(<<"MWI">>) -> 454;
alpha_3_to_numerical_code_upper(<<"MYS">>) -> 458;
alpha_3_to_numerical_code_upper(<<"MYT">>) -> 175;
alpha_3_to_numerical_code_upper(<<"NAM">>) -> 516;
alpha_3_to_numerical_code_upper(<<"NCL">>) -> 540;
alpha_3_to_numerical_code_upper(<<"NER">>) -> 562;
alpha_3_to_numerical_code_upper(<<"NFK">>) -> 574;
alpha_3_to_numerical_code_upper(<<"NGA">>) -> 566;
alpha_3_to_numerical_code_upper(<<"NIC">>) -> 558;
alpha_3_to_numerical_code_upper(<<"NIU">>) -> 570;
alpha_3_to_numerical_code_upper(<<"NLD">>) -> 528;
alpha_3_to_numerical_code_upper(<<"NOR">>) -> 578;
alpha_3_to_numerical_code_upper(<<"NPL">>) -> 524;
alpha_3_to_numerical_code_upper(<<"NRU">>) -> 520;
alpha_3_to_numerical_code_upper(<<"NZL">>) -> 554;
alpha_3_to_numerical_code_upper(<<"OMN">>) -> 512;
alpha_3_to_numerical_code_upper(<<"PAK">>) -> 586;
alpha_3_to_numerical_code_upper(<<"PAN">>) -> 591;
alpha_3_to_numerical_code_upper(<<"PCN">>) -> 612;
alpha_3_to_numerical_code_upper(<<"PER">>) -> 604;
alpha_3_to_numerical_code_upper(<<"PHL">>) -> 608;
alpha_3_to_numerical_code_upper(<<"PLW">>) -> 585;
alpha_3_to_numerical_code_upper(<<"PNG">>) -> 598;
alpha_3_to_numerical_code_upper(<<"POL">>) -> 616;
alpha_3_to_numerical_code_upper(<<"PRI">>) -> 630;
alpha_3_to_numerical_code_upper(<<"PRK">>) -> 408;
alpha_3_to_numerical_code_upper(<<"PRT">>) -> 620;
alpha_3_to_numerical_code_upper(<<"PRY">>) -> 600;
alpha_3_to_numerical_code_upper(<<"PSE">>) -> 275;
alpha_3_to_numerical_code_upper(<<"PYF">>) -> 258;
alpha_3_to_numerical_code_upper(<<"QAT">>) -> 634;
alpha_3_to_numerical_code_upper(<<"REU">>) -> 638;
alpha_3_to_numerical_code_upper(<<"ROU">>) -> 642;
alpha_3_to_numerical_code_upper(<<"RUS">>) -> 643;
alpha_3_to_numerical_code_upper(<<"RWA">>) -> 646;
alpha_3_to_numerical_code_upper(<<"SAU">>) -> 682;
alpha_3_to_numerical_code_upper(<<"SDN">>) -> 729;
alpha_3_to_numerical_code_upper(<<"SEN">>) -> 686;
alpha_3_to_numerical_code_upper(<<"SGP">>) -> 702;
alpha_3_to_numerical_code_upper(<<"SGS">>) -> 239;
alpha_3_to_numerical_code_upper(<<"SHN">>) -> 654;
alpha_3_to_numerical_code_upper(<<"SJM">>) -> 744;
alpha_3_to_numerical_code_upper(<<"SLB">>) -> 90;
alpha_3_to_numerical_code_upper(<<"SLE">>) -> 694;
alpha_3_to_numerical_code_upper(<<"SLV">>) -> 222;
alpha_3_to_numerical_code_upper(<<"SMR">>) -> 674;
alpha_3_to_numerical_code_upper(<<"SOM">>) -> 706;
alpha_3_to_numerical_code_upper(<<"SPM">>) -> 666;
alpha_3_to_numerical_code_upper(<<"SRB">>) -> 688;
alpha_3_to_numerical_code_upper(<<"SSD">>) -> 728;
alpha_3_to_numerical_code_upper(<<"STP">>) -> 678;
alpha_3_to_numerical_code_upper(<<"SUR">>) -> 740;
alpha_3_to_numerical_code_upper(<<"SVK">>) -> 703;
alpha_3_to_numerical_code_upper(<<"SVN">>) -> 705;
alpha_3_to_numerical_code_upper(<<"SWE">>) -> 752;
alpha_3_to_numerical_code_upper(<<"SWZ">>) -> 748;
alpha_3_to_numerical_code_upper(<<"SXM">>) -> 534;
alpha_3_to_numerical_code_upper(<<"SYC">>) -> 690;
alpha_3_to_numerical_code_upper(<<"SYR">>) -> 760;
alpha_3_to_numerical_code_upper(<<"TCA">>) -> 796;
alpha_3_to_numerical_code_upper(<<"TCD">>) -> 148;
alpha_3_to_numerical_code_upper(<<"TGO">>) -> 768;
alpha_3_to_numerical_code_upper(<<"THA">>) -> 764;
alpha_3_to_numerical_code_upper(<<"TJK">>) -> 762;
alpha_3_to_numerical_code_upper(<<"TKL">>) -> 772;
alpha_3_to_numerical_code_upper(<<"TKM">>) -> 795;
alpha_3_to_numerical_code_upper(<<"TLS">>) -> 626;
alpha_3_to_numerical_code_upper(<<"TON">>) -> 776;
alpha_3_to_numerical_code_upper(<<"TTO">>) -> 780;
alpha_3_to_numerical_code_upper(<<"TUN">>) -> 788;
alpha_3_to_numerical_code_upper(<<"TUR">>) -> 792;
alpha_3_to_numerical_code_upper(<<"TUV">>) -> 798;
alpha_3_to_numerical_code_upper(<<"TWN">>) -> 158;
alpha_3_to_numerical_code_upper(<<"TZA">>) -> 834;
alpha_3_to_numerical_code_upper(<<"UGA">>) -> 800;
alpha_3_to_numerical_code_upper(<<"UKR">>) -> 804;
alpha_3_to_numerical_code_upper(<<"UMI">>) -> 581;
alpha_3_to_numerical_code_upper(<<"URY">>) -> 858;
alpha_3_to_numerical_code_upper(<<"USA">>) -> 840;
alpha_3_to_numerical_code_upper(<<"UZB">>) -> 860;
alpha_3_to_numerical_code_upper(<<"VAT">>) -> 336;
alpha_3_to_numerical_code_upper(<<"VCT">>) -> 670;
alpha_3_to_numerical_code_upper(<<"VEN">>) -> 862;
alpha_3_to_numerical_code_upper(<<"VGB">>) -> 92;
alpha_3_to_numerical_code_upper(<<"VIR">>) -> 850;
alpha_3_to_numerical_code_upper(<<"VNM">>) -> 704;
alpha_3_to_numerical_code_upper(<<"VUT">>) -> 548;
alpha_3_to_numerical_code_upper(<<"WLF">>) -> 876;
alpha_3_to_numerical_code_upper(<<"WSM">>) -> 882;
alpha_3_to_numerical_code_upper(<<"YEM">>) -> 887;
alpha_3_to_numerical_code_upper(<<"ZAF">>) -> 710;
alpha_3_to_numerical_code_upper(<<"ZMB">>) -> 894;
alpha_3_to_numerical_code_upper(<<"ZWE">>) -> 716.

%% @doc Converts two letter country code (ISO alpha-2) to the equivalent United Nations numerical code M49 for countries.
%%      This is case-sensitive (Expects uppercase).
%% @end
alpha_2_to_numerical_code_upper(<<"AD">>) -> 20;
alpha_2_to_numerical_code_upper(<<"AE">>) -> 784;
alpha_2_to_numerical_code_upper(<<"AF">>) -> 4;
alpha_2_to_numerical_code_upper(<<"AG">>) -> 28;
alpha_2_to_numerical_code_upper(<<"AI">>) -> 660;
alpha_2_to_numerical_code_upper(<<"AL">>) -> 8;
alpha_2_to_numerical_code_upper(<<"AM">>) -> 51;
alpha_2_to_numerical_code_upper(<<"AO">>) -> 24;
alpha_2_to_numerical_code_upper(<<"AQ">>) -> 10;
alpha_2_to_numerical_code_upper(<<"AR">>) -> 32;
alpha_2_to_numerical_code_upper(<<"AS">>) -> 16;
alpha_2_to_numerical_code_upper(<<"AT">>) -> 40;
alpha_2_to_numerical_code_upper(<<"AU">>) -> 36;
alpha_2_to_numerical_code_upper(<<"AW">>) -> 533;
alpha_2_to_numerical_code_upper(<<"AX">>) -> 248;
alpha_2_to_numerical_code_upper(<<"AZ">>) -> 31;
alpha_2_to_numerical_code_upper(<<"BA">>) -> 70;
alpha_2_to_numerical_code_upper(<<"BB">>) -> 52;
alpha_2_to_numerical_code_upper(<<"BD">>) -> 50;
alpha_2_to_numerical_code_upper(<<"BE">>) -> 56;
alpha_2_to_numerical_code_upper(<<"BF">>) -> 854;
alpha_2_to_numerical_code_upper(<<"BG">>) -> 100;
alpha_2_to_numerical_code_upper(<<"BH">>) -> 48;
alpha_2_to_numerical_code_upper(<<"BI">>) -> 108;
alpha_2_to_numerical_code_upper(<<"BJ">>) -> 204;
alpha_2_to_numerical_code_upper(<<"BL">>) -> 652;
alpha_2_to_numerical_code_upper(<<"BM">>) -> 60;
alpha_2_to_numerical_code_upper(<<"BN">>) -> 96;
alpha_2_to_numerical_code_upper(<<"BO">>) -> 68;
alpha_2_to_numerical_code_upper(<<"BQ">>) -> 535;
alpha_2_to_numerical_code_upper(<<"BR">>) -> 76;
alpha_2_to_numerical_code_upper(<<"BS">>) -> 44;
alpha_2_to_numerical_code_upper(<<"BT">>) -> 64;
alpha_2_to_numerical_code_upper(<<"BV">>) -> 74;
alpha_2_to_numerical_code_upper(<<"BW">>) -> 72;
alpha_2_to_numerical_code_upper(<<"BY">>) -> 112;
alpha_2_to_numerical_code_upper(<<"BZ">>) -> 84;
alpha_2_to_numerical_code_upper(<<"CA">>) -> 124;
alpha_2_to_numerical_code_upper(<<"CC">>) -> 166;
alpha_2_to_numerical_code_upper(<<"CD">>) -> 180;
alpha_2_to_numerical_code_upper(<<"CF">>) -> 140;
alpha_2_to_numerical_code_upper(<<"CG">>) -> 178;
alpha_2_to_numerical_code_upper(<<"CH">>) -> 756;
alpha_2_to_numerical_code_upper(<<"CI">>) -> 384;
alpha_2_to_numerical_code_upper(<<"CK">>) -> 184;
alpha_2_to_numerical_code_upper(<<"CL">>) -> 152;
alpha_2_to_numerical_code_upper(<<"CM">>) -> 120;
alpha_2_to_numerical_code_upper(<<"CN">>) -> 156;
alpha_2_to_numerical_code_upper(<<"CO">>) -> 170;
alpha_2_to_numerical_code_upper(<<"CR">>) -> 188;
alpha_2_to_numerical_code_upper(<<"CU">>) -> 192;
alpha_2_to_numerical_code_upper(<<"CV">>) -> 132;
alpha_2_to_numerical_code_upper(<<"CW">>) -> 531;
alpha_2_to_numerical_code_upper(<<"CX">>) -> 162;
alpha_2_to_numerical_code_upper(<<"CY">>) -> 196;
alpha_2_to_numerical_code_upper(<<"CZ">>) -> 203;
alpha_2_to_numerical_code_upper(<<"DE">>) -> 276;
alpha_2_to_numerical_code_upper(<<"DJ">>) -> 262;
alpha_2_to_numerical_code_upper(<<"DK">>) -> 208;
alpha_2_to_numerical_code_upper(<<"DM">>) -> 212;
alpha_2_to_numerical_code_upper(<<"DO">>) -> 214;
alpha_2_to_numerical_code_upper(<<"DZ">>) -> 12;
alpha_2_to_numerical_code_upper(<<"EC">>) -> 218;
alpha_2_to_numerical_code_upper(<<"EE">>) -> 233;
alpha_2_to_numerical_code_upper(<<"EG">>) -> 818;
alpha_2_to_numerical_code_upper(<<"EH">>) -> 732;
alpha_2_to_numerical_code_upper(<<"ER">>) -> 232;
alpha_2_to_numerical_code_upper(<<"ES">>) -> 724;
alpha_2_to_numerical_code_upper(<<"ET">>) -> 231;
alpha_2_to_numerical_code_upper(<<"FI">>) -> 246;
alpha_2_to_numerical_code_upper(<<"FJ">>) -> 242;
alpha_2_to_numerical_code_upper(<<"FK">>) -> 238;
alpha_2_to_numerical_code_upper(<<"FM">>) -> 583;
alpha_2_to_numerical_code_upper(<<"FO">>) -> 234;
alpha_2_to_numerical_code_upper(<<"FR">>) -> 250;
alpha_2_to_numerical_code_upper(<<"GA">>) -> 266;
alpha_2_to_numerical_code_upper(<<"GB">>) -> 826;
alpha_2_to_numerical_code_upper(<<"GD">>) -> 308;
alpha_2_to_numerical_code_upper(<<"GE">>) -> 268;
alpha_2_to_numerical_code_upper(<<"GF">>) -> 254;
alpha_2_to_numerical_code_upper(<<"GG">>) -> 831;
alpha_2_to_numerical_code_upper(<<"GH">>) -> 288;
alpha_2_to_numerical_code_upper(<<"GI">>) -> 292;
alpha_2_to_numerical_code_upper(<<"GL">>) -> 304;
alpha_2_to_numerical_code_upper(<<"GM">>) -> 270;
alpha_2_to_numerical_code_upper(<<"GN">>) -> 324;
alpha_2_to_numerical_code_upper(<<"GP">>) -> 312;
alpha_2_to_numerical_code_upper(<<"GQ">>) -> 226;
alpha_2_to_numerical_code_upper(<<"GR">>) -> 300;
alpha_2_to_numerical_code_upper(<<"GS">>) -> 239;
alpha_2_to_numerical_code_upper(<<"GT">>) -> 320;
alpha_2_to_numerical_code_upper(<<"GU">>) -> 316;
alpha_2_to_numerical_code_upper(<<"GW">>) -> 624;
alpha_2_to_numerical_code_upper(<<"GY">>) -> 328;
alpha_2_to_numerical_code_upper(<<"HK">>) -> 344;
alpha_2_to_numerical_code_upper(<<"HM">>) -> 334;
alpha_2_to_numerical_code_upper(<<"HN">>) -> 340;
alpha_2_to_numerical_code_upper(<<"HR">>) -> 191;
alpha_2_to_numerical_code_upper(<<"HT">>) -> 332;
alpha_2_to_numerical_code_upper(<<"HU">>) -> 348;
alpha_2_to_numerical_code_upper(<<"ID">>) -> 360;
alpha_2_to_numerical_code_upper(<<"IE">>) -> 372;
alpha_2_to_numerical_code_upper(<<"IL">>) -> 376;
alpha_2_to_numerical_code_upper(<<"IM">>) -> 833;
alpha_2_to_numerical_code_upper(<<"IN">>) -> 356;
alpha_2_to_numerical_code_upper(<<"IO">>) -> 86;
alpha_2_to_numerical_code_upper(<<"IQ">>) -> 368;
alpha_2_to_numerical_code_upper(<<"IR">>) -> 364;
alpha_2_to_numerical_code_upper(<<"IS">>) -> 352;
alpha_2_to_numerical_code_upper(<<"IT">>) -> 380;
alpha_2_to_numerical_code_upper(<<"JE">>) -> 832;
alpha_2_to_numerical_code_upper(<<"JM">>) -> 388;
alpha_2_to_numerical_code_upper(<<"JO">>) -> 400;
alpha_2_to_numerical_code_upper(<<"JP">>) -> 392;
alpha_2_to_numerical_code_upper(<<"KE">>) -> 404;
alpha_2_to_numerical_code_upper(<<"KG">>) -> 417;
alpha_2_to_numerical_code_upper(<<"KH">>) -> 116;
alpha_2_to_numerical_code_upper(<<"KI">>) -> 296;
alpha_2_to_numerical_code_upper(<<"KM">>) -> 174;
alpha_2_to_numerical_code_upper(<<"KN">>) -> 659;
alpha_2_to_numerical_code_upper(<<"KP">>) -> 408;
alpha_2_to_numerical_code_upper(<<"KR">>) -> 410;
alpha_2_to_numerical_code_upper(<<"KW">>) -> 414;
alpha_2_to_numerical_code_upper(<<"KY">>) -> 136;
alpha_2_to_numerical_code_upper(<<"KZ">>) -> 398;
alpha_2_to_numerical_code_upper(<<"LA">>) -> 418;
alpha_2_to_numerical_code_upper(<<"LB">>) -> 422;
alpha_2_to_numerical_code_upper(<<"LC">>) -> 662;
alpha_2_to_numerical_code_upper(<<"LI">>) -> 438;
alpha_2_to_numerical_code_upper(<<"LK">>) -> 144;
alpha_2_to_numerical_code_upper(<<"LR">>) -> 430;
alpha_2_to_numerical_code_upper(<<"LS">>) -> 426;
alpha_2_to_numerical_code_upper(<<"LT">>) -> 440;
alpha_2_to_numerical_code_upper(<<"LU">>) -> 442;
alpha_2_to_numerical_code_upper(<<"LV">>) -> 428;
alpha_2_to_numerical_code_upper(<<"LY">>) -> 434;
alpha_2_to_numerical_code_upper(<<"MA">>) -> 504;
alpha_2_to_numerical_code_upper(<<"MC">>) -> 492;
alpha_2_to_numerical_code_upper(<<"MD">>) -> 498;
alpha_2_to_numerical_code_upper(<<"ME">>) -> 499;
alpha_2_to_numerical_code_upper(<<"MF">>) -> 663;
alpha_2_to_numerical_code_upper(<<"MG">>) -> 450;
alpha_2_to_numerical_code_upper(<<"MH">>) -> 584;
alpha_2_to_numerical_code_upper(<<"MK">>) -> 807;
alpha_2_to_numerical_code_upper(<<"ML">>) -> 466;
alpha_2_to_numerical_code_upper(<<"MM">>) -> 104;
alpha_2_to_numerical_code_upper(<<"MN">>) -> 496;
alpha_2_to_numerical_code_upper(<<"MO">>) -> 446;
alpha_2_to_numerical_code_upper(<<"MP">>) -> 580;
alpha_2_to_numerical_code_upper(<<"MQ">>) -> 474;
alpha_2_to_numerical_code_upper(<<"MR">>) -> 478;
alpha_2_to_numerical_code_upper(<<"MS">>) -> 500;
alpha_2_to_numerical_code_upper(<<"MT">>) -> 470;
alpha_2_to_numerical_code_upper(<<"MU">>) -> 480;
alpha_2_to_numerical_code_upper(<<"MV">>) -> 462;
alpha_2_to_numerical_code_upper(<<"MW">>) -> 454;
alpha_2_to_numerical_code_upper(<<"MX">>) -> 484;
alpha_2_to_numerical_code_upper(<<"MY">>) -> 458;
alpha_2_to_numerical_code_upper(<<"MZ">>) -> 508;
alpha_2_to_numerical_code_upper(<<"NA">>) -> 516;
alpha_2_to_numerical_code_upper(<<"NC">>) -> 540;
alpha_2_to_numerical_code_upper(<<"NE">>) -> 562;
alpha_2_to_numerical_code_upper(<<"NF">>) -> 574;
alpha_2_to_numerical_code_upper(<<"NG">>) -> 566;
alpha_2_to_numerical_code_upper(<<"NI">>) -> 558;
alpha_2_to_numerical_code_upper(<<"NL">>) -> 528;
alpha_2_to_numerical_code_upper(<<"NO">>) -> 578;
alpha_2_to_numerical_code_upper(<<"NP">>) -> 524;
alpha_2_to_numerical_code_upper(<<"NR">>) -> 520;
alpha_2_to_numerical_code_upper(<<"NU">>) -> 570;
alpha_2_to_numerical_code_upper(<<"NZ">>) -> 554;
alpha_2_to_numerical_code_upper(<<"OM">>) -> 512;
alpha_2_to_numerical_code_upper(<<"PA">>) -> 591;
alpha_2_to_numerical_code_upper(<<"PE">>) -> 604;
alpha_2_to_numerical_code_upper(<<"PF">>) -> 258;
alpha_2_to_numerical_code_upper(<<"PG">>) -> 598;
alpha_2_to_numerical_code_upper(<<"PH">>) -> 608;
alpha_2_to_numerical_code_upper(<<"PK">>) -> 586;
alpha_2_to_numerical_code_upper(<<"PL">>) -> 616;
alpha_2_to_numerical_code_upper(<<"PM">>) -> 666;
alpha_2_to_numerical_code_upper(<<"PN">>) -> 612;
alpha_2_to_numerical_code_upper(<<"PR">>) -> 630;
alpha_2_to_numerical_code_upper(<<"PS">>) -> 275;
alpha_2_to_numerical_code_upper(<<"PT">>) -> 620;
alpha_2_to_numerical_code_upper(<<"PW">>) -> 585;
alpha_2_to_numerical_code_upper(<<"PY">>) -> 600;
alpha_2_to_numerical_code_upper(<<"QA">>) -> 634;
alpha_2_to_numerical_code_upper(<<"RE">>) -> 638;
alpha_2_to_numerical_code_upper(<<"RO">>) -> 642;
alpha_2_to_numerical_code_upper(<<"RS">>) -> 688;
alpha_2_to_numerical_code_upper(<<"RU">>) -> 643;
alpha_2_to_numerical_code_upper(<<"RW">>) -> 646;
alpha_2_to_numerical_code_upper(<<"SA">>) -> 682;
alpha_2_to_numerical_code_upper(<<"SB">>) -> 90;
alpha_2_to_numerical_code_upper(<<"SC">>) -> 690;
alpha_2_to_numerical_code_upper(<<"SD">>) -> 729;
alpha_2_to_numerical_code_upper(<<"SE">>) -> 752;
alpha_2_to_numerical_code_upper(<<"SG">>) -> 702;
alpha_2_to_numerical_code_upper(<<"SH">>) -> 654;
alpha_2_to_numerical_code_upper(<<"SI">>) -> 705;
alpha_2_to_numerical_code_upper(<<"SJ">>) -> 744;
alpha_2_to_numerical_code_upper(<<"SK">>) -> 703;
alpha_2_to_numerical_code_upper(<<"SL">>) -> 694;
alpha_2_to_numerical_code_upper(<<"SM">>) -> 674;
alpha_2_to_numerical_code_upper(<<"SN">>) -> 686;
alpha_2_to_numerical_code_upper(<<"SO">>) -> 706;
alpha_2_to_numerical_code_upper(<<"SR">>) -> 740;
alpha_2_to_numerical_code_upper(<<"SS">>) -> 728;
alpha_2_to_numerical_code_upper(<<"ST">>) -> 678;
alpha_2_to_numerical_code_upper(<<"SV">>) -> 222;
alpha_2_to_numerical_code_upper(<<"SX">>) -> 534;
alpha_2_to_numerical_code_upper(<<"SY">>) -> 760;
alpha_2_to_numerical_code_upper(<<"SZ">>) -> 748;
alpha_2_to_numerical_code_upper(<<"TC">>) -> 796;
alpha_2_to_numerical_code_upper(<<"TD">>) -> 148;
alpha_2_to_numerical_code_upper(<<"TF">>) -> 260;
alpha_2_to_numerical_code_upper(<<"TG">>) -> 768;
alpha_2_to_numerical_code_upper(<<"TH">>) -> 764;
alpha_2_to_numerical_code_upper(<<"TJ">>) -> 762;
alpha_2_to_numerical_code_upper(<<"TK">>) -> 772;
alpha_2_to_numerical_code_upper(<<"TL">>) -> 626;
alpha_2_to_numerical_code_upper(<<"TM">>) -> 795;
alpha_2_to_numerical_code_upper(<<"TN">>) -> 788;
alpha_2_to_numerical_code_upper(<<"TO">>) -> 776;
alpha_2_to_numerical_code_upper(<<"TR">>) -> 792;
alpha_2_to_numerical_code_upper(<<"TT">>) -> 780;
alpha_2_to_numerical_code_upper(<<"TV">>) -> 798;
alpha_2_to_numerical_code_upper(<<"TW">>) -> 158;
alpha_2_to_numerical_code_upper(<<"TZ">>) -> 834;
alpha_2_to_numerical_code_upper(<<"UA">>) -> 804;
alpha_2_to_numerical_code_upper(<<"UG">>) -> 800;
alpha_2_to_numerical_code_upper(<<"UM">>) -> 581;
alpha_2_to_numerical_code_upper(<<"US">>) -> 840;
alpha_2_to_numerical_code_upper(<<"UY">>) -> 858;
alpha_2_to_numerical_code_upper(<<"UZ">>) -> 860;
alpha_2_to_numerical_code_upper(<<"VA">>) -> 336;
alpha_2_to_numerical_code_upper(<<"VC">>) -> 670;
alpha_2_to_numerical_code_upper(<<"VE">>) -> 862;
alpha_2_to_numerical_code_upper(<<"VG">>) -> 92;
alpha_2_to_numerical_code_upper(<<"VI">>) -> 850;
alpha_2_to_numerical_code_upper(<<"VN">>) -> 704;
alpha_2_to_numerical_code_upper(<<"VU">>) -> 548;
alpha_2_to_numerical_code_upper(<<"WF">>) -> 876;
alpha_2_to_numerical_code_upper(<<"WS">>) -> 882;
alpha_2_to_numerical_code_upper(<<"YE">>) -> 887;
alpha_2_to_numerical_code_upper(<<"YT">>) -> 175;
alpha_2_to_numerical_code_upper(<<"ZA">>) -> 710;
alpha_2_to_numerical_code_upper(<<"ZM">>) -> 894;
alpha_2_to_numerical_code_upper(<<"ZW">>) -> 716.




