-module(iso_erlang_country_parity_test).

-compile(export_all).

-include_lib("eunit/include/eunit.hrl").

country_parity_test() ->
    %% Data pulled from https://www.iso.org/obp/ui/#search/code/
    CountryList = [#{name => <<"Afghanistan"/utf8>>, alpha2 => <<"AF">>, alpha3 => <<"AFG">>, numerical_code => 4},
                   #{name => <<"Aland Islands"/utf8>>, alpha2 => <<"AX">>, alpha3 => <<"ALA">>, numerical_code => 248},
                   #{name => <<"Albania"/utf8>>, alpha2 => <<"AL">>, alpha3 => <<"ALB">>, numerical_code => 8},
                   #{name => <<"Algeria"/utf8>>, alpha2 => <<"DZ">>, alpha3 => <<"DZA">>, numerical_code => 12},
                   #{name => <<"American Samoa"/utf8>>, alpha2 => <<"AS">>, alpha3 => <<"ASM">>, numerical_code => 16},
                   #{name => <<"Andorra"/utf8>>, alpha2 => <<"AD">>, alpha3 => <<"AND">>, numerical_code => 20},
                   #{name => <<"Angola"/utf8>>, alpha2 => <<"AO">>, alpha3 => <<"AGO">>, numerical_code => 24},
                   #{name => <<"Anguilla"/utf8>>, alpha2 => <<"AI">>, alpha3 => <<"AIA">>, numerical_code => 660},
                   #{name => <<"Antarctica"/utf8>>, alpha2 => <<"AQ">>, alpha3 => <<"ATA">>, numerical_code => 10},
                   #{name => <<"Antigua and Barbuda"/utf8>>, alpha2 => <<"AG">>, alpha3 => <<"ATG">>, numerical_code => 28},
                   #{name => <<"Argentina"/utf8>>, alpha2 => <<"AR">>, alpha3 => <<"ARG">>, numerical_code => 32},
                   #{name => <<"Armenia"/utf8>>, alpha2 => <<"AM">>, alpha3 => <<"ARM">>, numerical_code => 51},
                   #{name => <<"Aruba"/utf8>>, alpha2 => <<"AW">>, alpha3 => <<"ABW">>, numerical_code => 533},
                   #{name => <<"Australia"/utf8>>, alpha2 => <<"AU">>, alpha3 => <<"AUS">>, numerical_code => 36},
                   #{name => <<"Austria"/utf8>>, alpha2 => <<"AT">>, alpha3 => <<"AUT">>, numerical_code => 40},
                   #{name => <<"Azerbaijan"/utf8>>, alpha2 => <<"AZ">>, alpha3 => <<"AZE">>, numerical_code => 31},
                   #{name => <<"Bahamas (the)"/utf8>>, alpha2 => <<"BS">>, alpha3 => <<"BHS">>, numerical_code => 44},
                   #{name => <<"Bahrain"/utf8>>, alpha2 => <<"BH">>, alpha3 => <<"BHR">>, numerical_code => 48},
                   #{name => <<"Bangladesh"/utf8>>, alpha2 => <<"BD">>, alpha3 => <<"BGD">>, numerical_code => 50},
                   #{name => <<"Barbados"/utf8>>, alpha2 => <<"BB">>, alpha3 => <<"BRB">>, numerical_code => 52},
                   #{name => <<"Belarus"/utf8>>, alpha2 => <<"BY">>, alpha3 => <<"BLR">>, numerical_code => 112},
                   #{name => <<"Belgium"/utf8>>, alpha2 => <<"BE">>, alpha3 => <<"BEL">>, numerical_code => 56},
                   #{name => <<"Belize"/utf8>>, alpha2 => <<"BZ">>, alpha3 => <<"BLZ">>, numerical_code => 84},
                   #{name => <<"Benin"/utf8>>, alpha2 => <<"BJ">>, alpha3 => <<"BEN">>, numerical_code => 204},
                   #{name => <<"Bermuda"/utf8>>, alpha2 => <<"BM">>, alpha3 => <<"BMU">>, numerical_code => 60},
                   #{name => <<"Bhutan"/utf8>>, alpha2 => <<"BT">>, alpha3 => <<"BTN">>, numerical_code => 64},
                   #{name => <<"Bolivia (Plurinational State of)"/utf8>>, alpha2 => <<"BO">>, alpha3 => <<"BOL">>, numerical_code => 68},
                   #{name => <<"Bonaire, Sint Eustatius and Saba"/utf8>>, alpha2 => <<"BQ">>, alpha3 => <<"BES">>, numerical_code => 535},
                   #{name => <<"Bosnia and Herzegovina"/utf8>>, alpha2 => <<"BA">>, alpha3 => <<"BIH">>, numerical_code => 70},
                   #{name => <<"Botswana"/utf8>>, alpha2 => <<"BW">>, alpha3 => <<"BWA">>, numerical_code => 72},
                   #{name => <<"Bouvet Island"/utf8>>, alpha2 => <<"BV">>, alpha3 => <<"BVT">>, numerical_code => 74},
                   #{name => <<"Brazil"/utf8>>, alpha2 => <<"BR">>, alpha3 => <<"BRA">>, numerical_code => 76},
                   #{name => <<"British Indian Ocean Territory (the)"/utf8>>, alpha2 => <<"IO">>, alpha3 => <<"IOT">>, numerical_code => 86},
                   #{name => <<"Brunei Darussalam"/utf8>>, alpha2 => <<"BN">>, alpha3 => <<"BRN">>, numerical_code => 96},
                   #{name => <<"Bulgaria"/utf8>>, alpha2 => <<"BG">>, alpha3 => <<"BGR">>, numerical_code => 100},
                   #{name => <<"Burkina Faso"/utf8>>, alpha2 => <<"BF">>, alpha3 => <<"BFA">>, numerical_code => 854},
                   #{name => <<"Burundi"/utf8>>, alpha2 => <<"BI">>, alpha3 => <<"BDI">>, numerical_code => 108},
                   #{name => <<"Cabo Verde"/utf8>>, alpha2 => <<"CV">>, alpha3 => <<"CPV">>, numerical_code => 132},
                   #{name => <<"Cambodia"/utf8>>, alpha2 => <<"KH">>, alpha3 => <<"KHM">>, numerical_code => 116},
                   #{name => <<"Cameroon"/utf8>>, alpha2 => <<"CM">>, alpha3 => <<"CMR">>, numerical_code => 120},
                   #{name => <<"Canada"/utf8>>, alpha2 => <<"CA">>, alpha3 => <<"CAN">>, numerical_code => 124},
                   #{name => <<"Cayman Islands (the)"/utf8>>, alpha2 => <<"KY">>, alpha3 => <<"CYM">>, numerical_code => 136},
                   #{name => <<"Central African Republic (the)"/utf8>>, alpha2 => <<"CF">>, alpha3 => <<"CAF">>, numerical_code => 140},
                   #{name => <<"Chad"/utf8>>, alpha2 => <<"TD">>, alpha3 => <<"TCD">>, numerical_code => 148},
                   #{name => <<"Chile"/utf8>>, alpha2 => <<"CL">>, alpha3 => <<"CHL">>, numerical_code => 152},
                   #{name => <<"China"/utf8>>, alpha2 => <<"CN">>, alpha3 => <<"CHN">>, numerical_code => 156},
                   #{name => <<"Christmas Island"/utf8>>, alpha2 => <<"CX">>, alpha3 => <<"CXR">>, numerical_code => 162},
                   #{name => <<"Cocos (Keeling) Islands (the)"/utf8>>, alpha2 => <<"CC">>, alpha3 => <<"CCK">>, numerical_code => 166},
                   #{name => <<"Colombia"/utf8>>, alpha2 => <<"CO">>, alpha3 => <<"COL">>, numerical_code => 170},
                   #{name => <<"Comoros (the)"/utf8>>, alpha2 => <<"KM">>, alpha3 => <<"COM">>, numerical_code => 174},
                   #{name => <<"Congo (the Democratic Republic of the)"/utf8>>, alpha2 => <<"CD">>, alpha3 => <<"COD">>, numerical_code => 180},
                   #{name => <<"Congo (the)"/utf8>>, alpha2 => <<"CG">>, alpha3 => <<"COG">>, numerical_code => 178},
                   #{name => <<"Cook Islands (the)"/utf8>>, alpha2 => <<"CK">>, alpha3 => <<"COK">>, numerical_code => 184},
                   #{name => <<"Costa Rica"/utf8>>, alpha2 => <<"CR">>, alpha3 => <<"CRI">>, numerical_code => 188},
                   #{name => <<"Croatia"/utf8>>, alpha2 => <<"HR">>, alpha3 => <<"HRV">>, numerical_code => 191},
                   #{name => <<"Cuba"/utf8>>, alpha2 => <<"CU">>, alpha3 => <<"CUB">>, numerical_code => 192},
                   #{name => <<"Curaçao"/utf8>>, alpha2 => <<"CW">>, alpha3 => <<"CUW">>, numerical_code => 531},
                   #{name => <<"Cyprus"/utf8>>, alpha2 => <<"CY">>, alpha3 => <<"CYP">>, numerical_code => 196},
                   #{name => <<"Czechia"/utf8>>, alpha2 => <<"CZ">>, alpha3 => <<"CZE">>, numerical_code => 203},
                   #{name => <<"Côte d'Ivoire"/utf8>>, alpha2 => <<"CI">>, alpha3 => <<"CIV">>, numerical_code => 384},
                   #{name => <<"Denmark"/utf8>>, alpha2 => <<"DK">>, alpha3 => <<"DNK">>, numerical_code => 208},
                   #{name => <<"Djibouti"/utf8>>, alpha2 => <<"DJ">>, alpha3 => <<"DJI">>, numerical_code => 262},
                   #{name => <<"Dominica"/utf8>>, alpha2 => <<"DM">>, alpha3 => <<"DMA">>, numerical_code => 212},
                   #{name => <<"Dominican Republic (the)"/utf8>>, alpha2 => <<"DO">>, alpha3 => <<"DOM">>, numerical_code => 214},
                   #{name => <<"Ecuador"/utf8>>, alpha2 => <<"EC">>, alpha3 => <<"ECU">>, numerical_code => 218},
                   #{name => <<"Egypt"/utf8>>, alpha2 => <<"EG">>, alpha3 => <<"EGY">>, numerical_code => 818},
                   #{name => <<"El Salvador"/utf8>>, alpha2 => <<"SV">>, alpha3 => <<"SLV">>, numerical_code => 222},
                   #{name => <<"Equatorial Guinea"/utf8>>, alpha2 => <<"GQ">>, alpha3 => <<"GNQ">>, numerical_code => 226},
                   #{name => <<"Eritrea"/utf8>>, alpha2 => <<"ER">>, alpha3 => <<"ERI">>, numerical_code => 232},
                   #{name => <<"Estonia"/utf8>>, alpha2 => <<"EE">>, alpha3 => <<"EST">>, numerical_code => 233},
                   #{name => <<"Ethiopia"/utf8>>, alpha2 => <<"ET">>, alpha3 => <<"ETH">>, numerical_code => 231},
                   #{name => <<"Falkland Islands (the) [Malvinas]"/utf8>>, alpha2 => <<"FK">>, alpha3 => <<"FLK">>, numerical_code => 238},
                   #{name => <<"Faroe Islands (the)"/utf8>>, alpha2 => <<"FO">>, alpha3 => <<"FRO">>, numerical_code => 234},
                   #{name => <<"Fiji"/utf8>>, alpha2 => <<"FJ">>, alpha3 => <<"FJI">>, numerical_code => 242},
                   #{name => <<"Finland"/utf8>>, alpha2 => <<"FI">>, alpha3 => <<"FIN">>, numerical_code => 246},
                   #{name => <<"France"/utf8>>, alpha2 => <<"FR">>, alpha3 => <<"FRA">>, numerical_code => 250},
                   #{name => <<"French Guiana"/utf8>>, alpha2 => <<"GF">>, alpha3 => <<"GUF">>, numerical_code => 254},
                   #{name => <<"French Polynesia"/utf8>>, alpha2 => <<"PF">>, alpha3 => <<"PYF">>, numerical_code => 258},
                   #{name => <<"French Southern Territories (the)"/utf8>>, alpha2 => <<"TF">>, alpha3 => <<"ATF">>, numerical_code => 260},
                   #{name => <<"Gabon"/utf8>>, alpha2 => <<"GA">>, alpha3 => <<"GAB">>, numerical_code => 266},
                   #{name => <<"Gambia (the)"/utf8>>, alpha2 => <<"GM">>, alpha3 => <<"GMB">>, numerical_code => 270},
                   #{name => <<"Georgia"/utf8>>, alpha2 => <<"GE">>, alpha3 => <<"GEO">>, numerical_code => 268},
                   #{name => <<"Germany"/utf8>>, alpha2 => <<"DE">>, alpha3 => <<"DEU">>, numerical_code => 276},
                   #{name => <<"Ghana"/utf8>>, alpha2 => <<"GH">>, alpha3 => <<"GHA">>, numerical_code => 288},
                   #{name => <<"Gibraltar"/utf8>>, alpha2 => <<"GI">>, alpha3 => <<"GIB">>, numerical_code => 292},
                   #{name => <<"Greece"/utf8>>, alpha2 => <<"GR">>, alpha3 => <<"GRC">>, numerical_code => 300},
                   #{name => <<"Greenland"/utf8>>, alpha2 => <<"GL">>, alpha3 => <<"GRL">>, numerical_code => 304},
                   #{name => <<"Grenada"/utf8>>, alpha2 => <<"GD">>, alpha3 => <<"GRD">>, numerical_code => 308},
                   #{name => <<"Guadeloupe"/utf8>>, alpha2 => <<"GP">>, alpha3 => <<"GLP">>, numerical_code => 312},
                   #{name => <<"Guam"/utf8>>, alpha2 => <<"GU">>, alpha3 => <<"GUM">>, numerical_code => 316},
                   #{name => <<"Guatemala"/utf8>>, alpha2 => <<"GT">>, alpha3 => <<"GTM">>, numerical_code => 320},
                   #{name => <<"Guernsey"/utf8>>, alpha2 => <<"GG">>, alpha3 => <<"GGY">>, numerical_code => 831},
                   #{name => <<"Guinea"/utf8>>, alpha2 => <<"GN">>, alpha3 => <<"GIN">>, numerical_code => 324},
                   #{name => <<"Guinea-Bissau"/utf8>>, alpha2 => <<"GW">>, alpha3 => <<"GNB">>, numerical_code => 624},
                   #{name => <<"Guyana"/utf8>>, alpha2 => <<"GY">>, alpha3 => <<"GUY">>, numerical_code => 328},
                   #{name => <<"Haiti"/utf8>>, alpha2 => <<"HT">>, alpha3 => <<"HTI">>, numerical_code => 332},
                   #{name => <<"Heard Island and McDonald Islands"/utf8>>, alpha2 => <<"HM">>, alpha3 => <<"HMD">>, numerical_code => 334},
                   #{name => <<"Holy See (the)"/utf8>>, alpha2 => <<"VA">>, alpha3 => <<"VAT">>, numerical_code => 336},
                   #{name => <<"Honduras"/utf8>>, alpha2 => <<"HN">>, alpha3 => <<"HND">>, numerical_code => 340},
                   #{name => <<"Hong Kong"/utf8>>, alpha2 => <<"HK">>, alpha3 => <<"HKG">>, numerical_code => 344},
                   #{name => <<"Hungary"/utf8>>, alpha2 => <<"HU">>, alpha3 => <<"HUN">>, numerical_code => 348},
                   #{name => <<"Iceland"/utf8>>, alpha2 => <<"IS">>, alpha3 => <<"ISL">>, numerical_code => 352},
                   #{name => <<"India"/utf8>>, alpha2 => <<"IN">>, alpha3 => <<"IND">>, numerical_code => 356},
                   #{name => <<"Indonesia"/utf8>>, alpha2 => <<"ID">>, alpha3 => <<"IDN">>, numerical_code => 360},
                   #{name => <<"Iran (Islamic Republic of)"/utf8>>, alpha2 => <<"IR">>, alpha3 => <<"IRN">>, numerical_code => 364},
                   #{name => <<"Iraq"/utf8>>, alpha2 => <<"IQ">>, alpha3 => <<"IRQ">>, numerical_code => 368},
                   #{name => <<"Ireland"/utf8>>, alpha2 => <<"IE">>, alpha3 => <<"IRL">>, numerical_code => 372},
                   #{name => <<"Isle of Man"/utf8>>, alpha2 => <<"IM">>, alpha3 => <<"IMN">>, numerical_code => 833},
                   #{name => <<"Israel"/utf8>>, alpha2 => <<"IL">>, alpha3 => <<"ISR">>, numerical_code => 376},
                   #{name => <<"Italy"/utf8>>, alpha2 => <<"IT">>, alpha3 => <<"ITA">>, numerical_code => 380},
                   #{name => <<"Jamaica"/utf8>>, alpha2 => <<"JM">>, alpha3 => <<"JAM">>, numerical_code => 388},
                   #{name => <<"Japan"/utf8>>, alpha2 => <<"JP">>, alpha3 => <<"JPN">>, numerical_code => 392},
                   #{name => <<"Jersey"/utf8>>, alpha2 => <<"JE">>, alpha3 => <<"JEY">>, numerical_code => 832},
                   #{name => <<"Jordan"/utf8>>, alpha2 => <<"JO">>, alpha3 => <<"JOR">>, numerical_code => 400},
                   #{name => <<"Kazakhstan"/utf8>>, alpha2 => <<"KZ">>, alpha3 => <<"KAZ">>, numerical_code => 398},
                   #{name => <<"Kenya"/utf8>>, alpha2 => <<"KE">>, alpha3 => <<"KEN">>, numerical_code => 404},
                   #{name => <<"Kiribati"/utf8>>, alpha2 => <<"KI">>, alpha3 => <<"KIR">>, numerical_code => 296},
                   #{name => <<"Korea (the Democratic People's Republic of)"/utf8>>, alpha2 => <<"KP">>, alpha3 => <<"PRK">>, numerical_code => 408},
                   #{name => <<"Korea (the Republic of)"/utf8>>, alpha2 => <<"KR">>, alpha3 => <<"KOR">>, numerical_code => 410},
                   #{name => <<"Kuwait"/utf8>>, alpha2 => <<"KW">>, alpha3 => <<"KWT">>, numerical_code => 414},
                   #{name => <<"Kyrgyzstan"/utf8>>, alpha2 => <<"KG">>, alpha3 => <<"KGZ">>, numerical_code => 417},
                   #{name => <<"Lao People's Democratic Republic (the)"/utf8>>, alpha2 => <<"LA">>, alpha3 => <<"LAO">>, numerical_code => 418},
                   #{name => <<"Latvia"/utf8>>, alpha2 => <<"LV">>, alpha3 => <<"LVA">>, numerical_code => 428},
                   #{name => <<"Lebanon"/utf8>>, alpha2 => <<"LB">>, alpha3 => <<"LBN">>, numerical_code => 422},
                   #{name => <<"Lesotho"/utf8>>, alpha2 => <<"LS">>, alpha3 => <<"LSO">>, numerical_code => 426},
                   #{name => <<"Liberia"/utf8>>, alpha2 => <<"LR">>, alpha3 => <<"LBR">>, numerical_code => 430},
                   #{name => <<"Libya"/utf8>>, alpha2 => <<"LY">>, alpha3 => <<"LBY">>, numerical_code => 434},
                   #{name => <<"Liechtenstein"/utf8>>, alpha2 => <<"LI">>, alpha3 => <<"LIE">>, numerical_code => 438},
                   #{name => <<"Lithuania"/utf8>>, alpha2 => <<"LT">>, alpha3 => <<"LTU">>, numerical_code => 440},
                   #{name => <<"Luxembourg"/utf8>>, alpha2 => <<"LU">>, alpha3 => <<"LUX">>, numerical_code => 442},
                   #{name => <<"Macao"/utf8>>, alpha2 => <<"MO">>, alpha3 => <<"MAC">>, numerical_code => 446},
                   #{name => <<"Macedonia (the former Yugoslav Republic of)"/utf8>>, alpha2 => <<"MK">>, alpha3 => <<"MKD">>, numerical_code => 807},
                   #{name => <<"Madagascar"/utf8>>, alpha2 => <<"MG">>, alpha3 => <<"MDG">>, numerical_code => 450},
                   #{name => <<"Malawi"/utf8>>, alpha2 => <<"MW">>, alpha3 => <<"MWI">>, numerical_code => 454},
                   #{name => <<"Malaysia"/utf8>>, alpha2 => <<"MY">>, alpha3 => <<"MYS">>, numerical_code => 458},
                   #{name => <<"Maldives"/utf8>>, alpha2 => <<"MV">>, alpha3 => <<"MDV">>, numerical_code => 462},
                   #{name => <<"Mali"/utf8>>, alpha2 => <<"ML">>, alpha3 => <<"MLI">>, numerical_code => 466},
                   #{name => <<"Malta"/utf8>>, alpha2 => <<"MT">>, alpha3 => <<"MLT">>, numerical_code => 470},
                   #{name => <<"Marshall Islands (the)"/utf8>>, alpha2 => <<"MH">>, alpha3 => <<"MHL">>, numerical_code => 584},
                   #{name => <<"Martinique"/utf8>>, alpha2 => <<"MQ">>, alpha3 => <<"MTQ">>, numerical_code => 474},
                   #{name => <<"Mauritania"/utf8>>, alpha2 => <<"MR">>, alpha3 => <<"MRT">>, numerical_code => 478},
                   #{name => <<"Mauritius"/utf8>>, alpha2 => <<"MU">>, alpha3 => <<"MUS">>, numerical_code => 480},
                   #{name => <<"Mayotte"/utf8>>, alpha2 => <<"YT">>, alpha3 => <<"MYT">>, numerical_code => 175},
                   #{name => <<"Mexico"/utf8>>, alpha2 => <<"MX">>, alpha3 => <<"MEX">>, numerical_code => 484},
                   #{name => <<"Micronesia (Federated States of)"/utf8>>, alpha2 => <<"FM">>, alpha3 => <<"FSM">>, numerical_code => 583},
                   #{name => <<"Moldova (the Republic of)"/utf8>>, alpha2 => <<"MD">>, alpha3 => <<"MDA">>, numerical_code => 498},
                   #{name => <<"Monaco"/utf8>>, alpha2 => <<"MC">>, alpha3 => <<"MCO">>, numerical_code => 492},
                   #{name => <<"Mongolia"/utf8>>, alpha2 => <<"MN">>, alpha3 => <<"MNG">>, numerical_code => 496},
                   #{name => <<"Montenegro"/utf8>>, alpha2 => <<"ME">>, alpha3 => <<"MNE">>, numerical_code => 499},
                   #{name => <<"Montserrat"/utf8>>, alpha2 => <<"MS">>, alpha3 => <<"MSR">>, numerical_code => 500},
                   #{name => <<"Morocco"/utf8>>, alpha2 => <<"MA">>, alpha3 => <<"MAR">>, numerical_code => 504},
                   #{name => <<"Mozambique"/utf8>>, alpha2 => <<"MZ">>, alpha3 => <<"MOZ">>, numerical_code => 508},
                   #{name => <<"Myanmar"/utf8>>, alpha2 => <<"MM">>, alpha3 => <<"MMR">>, numerical_code => 104},
                   #{name => <<"Namibia"/utf8>>, alpha2 => <<"NA">>, alpha3 => <<"NAM">>, numerical_code => 516},
                   #{name => <<"Nauru"/utf8>>, alpha2 => <<"NR">>, alpha3 => <<"NRU">>, numerical_code => 520},
                   #{name => <<"Nepal"/utf8>>, alpha2 => <<"NP">>, alpha3 => <<"NPL">>, numerical_code => 524},
                   #{name => <<"Netherlands (the)"/utf8>>, alpha2 => <<"NL">>, alpha3 => <<"NLD">>, numerical_code => 528},
                   #{name => <<"New Caledonia"/utf8>>, alpha2 => <<"NC">>, alpha3 => <<"NCL">>, numerical_code => 540},
                   #{name => <<"New Zealand"/utf8>>, alpha2 => <<"NZ">>, alpha3 => <<"NZL">>, numerical_code => 554},
                   #{name => <<"Nicaragua"/utf8>>, alpha2 => <<"NI">>, alpha3 => <<"NIC">>, numerical_code => 558},
                   #{name => <<"Niger (the)"/utf8>>, alpha2 => <<"NE">>, alpha3 => <<"NER">>, numerical_code => 562},
                   #{name => <<"Nigeria"/utf8>>, alpha2 => <<"NG">>, alpha3 => <<"NGA">>, numerical_code => 566},
                   #{name => <<"Niue"/utf8>>, alpha2 => <<"NU">>, alpha3 => <<"NIU">>, numerical_code => 570},
                   #{name => <<"Norfolk Island"/utf8>>, alpha2 => <<"NF">>, alpha3 => <<"NFK">>, numerical_code => 574},
                   #{name => <<"Northern Mariana Islands (the)"/utf8>>, alpha2 => <<"MP">>, alpha3 => <<"MNP">>, numerical_code => 580},
                   #{name => <<"Norway"/utf8>>, alpha2 => <<"NO">>, alpha3 => <<"NOR">>, numerical_code => 578},
                   #{name => <<"Oman"/utf8>>, alpha2 => <<"OM">>, alpha3 => <<"OMN">>, numerical_code => 512},
                   #{name => <<"Pakistan"/utf8>>, alpha2 => <<"PK">>, alpha3 => <<"PAK">>, numerical_code => 586},
                   #{name => <<"Palau"/utf8>>, alpha2 => <<"PW">>, alpha3 => <<"PLW">>, numerical_code => 585},
                   #{name => <<"Palestine, State of"/utf8>>, alpha2 => <<"PS">>, alpha3 => <<"PSE">>, numerical_code => 275},
                   #{name => <<"Panama"/utf8>>, alpha2 => <<"PA">>, alpha3 => <<"PAN">>, numerical_code => 591},
                   #{name => <<"Papua New Guinea"/utf8>>, alpha2 => <<"PG">>, alpha3 => <<"PNG">>, numerical_code => 598},
                   #{name => <<"Paraguay"/utf8>>, alpha2 => <<"PY">>, alpha3 => <<"PRY">>, numerical_code => 600},
                   #{name => <<"Peru"/utf8>>, alpha2 => <<"PE">>, alpha3 => <<"PER">>, numerical_code => 604},
                   #{name => <<"Philippines (the)"/utf8>>, alpha2 => <<"PH">>, alpha3 => <<"PHL">>, numerical_code => 608},
                   #{name => <<"Pitcairn"/utf8>>, alpha2 => <<"PN">>, alpha3 => <<"PCN">>, numerical_code => 612},
                   #{name => <<"Poland"/utf8>>, alpha2 => <<"PL">>, alpha3 => <<"POL">>, numerical_code => 616},
                   #{name => <<"Portugal"/utf8>>, alpha2 => <<"PT">>, alpha3 => <<"PRT">>, numerical_code => 620},
                   #{name => <<"Puerto Rico"/utf8>>, alpha2 => <<"PR">>, alpha3 => <<"PRI">>, numerical_code => 630},
                   #{name => <<"Qatar"/utf8>>, alpha2 => <<"QA">>, alpha3 => <<"QAT">>, numerical_code => 634},
                   #{name => <<"Romania"/utf8>>, alpha2 => <<"RO">>, alpha3 => <<"ROU">>, numerical_code => 642},
                   #{name => <<"Russian Federation (the)"/utf8>>, alpha2 => <<"RU">>, alpha3 => <<"RUS">>, numerical_code => 643},
                   #{name => <<"Rwanda"/utf8>>, alpha2 => <<"RW">>, alpha3 => <<"RWA">>, numerical_code => 646},
                   #{name => <<"Réunion"/utf8>>, alpha2 => <<"RE">>, alpha3 => <<"REU">>, numerical_code => 638},
                   #{name => <<"Saint Barthélemy"/utf8>>, alpha2 => <<"BL">>, alpha3 => <<"BLM">>, numerical_code => 652},
                   #{name => <<"Saint Helena, Ascension and Tristan da Cunha"/utf8>>, alpha2 => <<"SH">>, alpha3 => <<"SHN">>, numerical_code => 654},
                   #{name => <<"Saint Kitts and Nevis"/utf8>>, alpha2 => <<"KN">>, alpha3 => <<"KNA">>, numerical_code => 659},
                   #{name => <<"Saint Lucia"/utf8>>, alpha2 => <<"LC">>, alpha3 => <<"LCA">>, numerical_code => 662},
                   #{name => <<"Saint Martin (French part)"/utf8>>, alpha2 => <<"MF">>, alpha3 => <<"MAF">>, numerical_code => 663},
                   #{name => <<"Saint Pierre and Miquelon"/utf8>>, alpha2 => <<"PM">>, alpha3 => <<"SPM">>, numerical_code => 666},
                   #{name => <<"Saint Vincent and the Grenadines"/utf8>>, alpha2 => <<"VC">>, alpha3 => <<"VCT">>, numerical_code => 670},
                   #{name => <<"Samoa"/utf8>>, alpha2 => <<"WS">>, alpha3 => <<"WSM">>, numerical_code => 882},
                   #{name => <<"San Marino"/utf8>>, alpha2 => <<"SM">>, alpha3 => <<"SMR">>, numerical_code => 674},
                   #{name => <<"Sao Tome and Principe"/utf8>>, alpha2 => <<"ST">>, alpha3 => <<"STP">>, numerical_code => 678},
                   #{name => <<"Saudi Arabia"/utf8>>, alpha2 => <<"SA">>, alpha3 => <<"SAU">>, numerical_code => 682},
                   #{name => <<"Senegal"/utf8>>, alpha2 => <<"SN">>, alpha3 => <<"SEN">>, numerical_code => 686},
                   #{name => <<"Serbia"/utf8>>, alpha2 => <<"RS">>, alpha3 => <<"SRB">>, numerical_code => 688},
                   #{name => <<"Seychelles"/utf8>>, alpha2 => <<"SC">>, alpha3 => <<"SYC">>, numerical_code => 690},
                   #{name => <<"Sierra Leone"/utf8>>, alpha2 => <<"SL">>, alpha3 => <<"SLE">>, numerical_code => 694},
                   #{name => <<"Singapore"/utf8>>, alpha2 => <<"SG">>, alpha3 => <<"SGP">>, numerical_code => 702},
                   #{name => <<"Sint Maarten (Dutch part)"/utf8>>, alpha2 => <<"SX">>, alpha3 => <<"SXM">>, numerical_code => 534},
                   #{name => <<"Slovakia"/utf8>>, alpha2 => <<"SK">>, alpha3 => <<"SVK">>, numerical_code => 703},
                   #{name => <<"Slovenia"/utf8>>, alpha2 => <<"SI">>, alpha3 => <<"SVN">>, numerical_code => 705},
                   #{name => <<"Solomon Islands"/utf8>>, alpha2 => <<"SB">>, alpha3 => <<"SLB">>, numerical_code => 90},
                   #{name => <<"Somalia"/utf8>>, alpha2 => <<"SO">>, alpha3 => <<"SOM">>, numerical_code => 706},
                   #{name => <<"South Africa"/utf8>>, alpha2 => <<"ZA">>, alpha3 => <<"ZAF">>, numerical_code => 710},
                   #{name => <<"South Georgia and the South Sandwich Islands"/utf8>>, alpha2 => <<"GS">>, alpha3 => <<"SGS">>, numerical_code => 239},
                   #{name => <<"South Sudan"/utf8>>, alpha2 => <<"SS">>, alpha3 => <<"SSD">>, numerical_code => 728},
                   #{name => <<"Spain"/utf8>>, alpha2 => <<"ES">>, alpha3 => <<"ESP">>, numerical_code => 724},
                   #{name => <<"Sri Lanka"/utf8>>, alpha2 => <<"LK">>, alpha3 => <<"LKA">>, numerical_code => 144},
                   #{name => <<"Sudan (the)"/utf8>>, alpha2 => <<"SD">>, alpha3 => <<"SDN">>, numerical_code => 729},
                   #{name => <<"Suriname"/utf8>>, alpha2 => <<"SR">>, alpha3 => <<"SUR">>, numerical_code => 740},
                   #{name => <<"Svalbard and Jan Mayen"/utf8>>, alpha2 => <<"SJ">>, alpha3 => <<"SJM">>, numerical_code => 744},
                   #{name => <<"Swaziland"/utf8>>, alpha2 => <<"SZ">>, alpha3 => <<"SWZ">>, numerical_code => 748},
                   #{name => <<"Sweden"/utf8>>, alpha2 => <<"SE">>, alpha3 => <<"SWE">>, numerical_code => 752},
                   #{name => <<"Switzerland"/utf8>>, alpha2 => <<"CH">>, alpha3 => <<"CHE">>, numerical_code => 756},
                   #{name => <<"Syrian Arab Republic"/utf8>>, alpha2 => <<"SY">>, alpha3 => <<"SYR">>, numerical_code => 760},
                   #{name => <<"Taiwan (Province of China)"/utf8>>, alpha2 => <<"TW">>, alpha3 => <<"TWN">>, numerical_code => 158},
                   #{name => <<"Tajikistan"/utf8>>, alpha2 => <<"TJ">>, alpha3 => <<"TJK">>, numerical_code => 762},
                   #{name => <<"Tanzania, United Republic of"/utf8>>, alpha2 => <<"TZ">>, alpha3 => <<"TZA">>, numerical_code => 834},
                   #{name => <<"Thailand"/utf8>>, alpha2 => <<"TH">>, alpha3 => <<"THA">>, numerical_code => 764},
                   #{name => <<"Timor-Leste"/utf8>>, alpha2 => <<"TL">>, alpha3 => <<"TLS">>, numerical_code => 626},
                   #{name => <<"Togo"/utf8>>, alpha2 => <<"TG">>, alpha3 => <<"TGO">>, numerical_code => 768},
                   #{name => <<"Tokelau"/utf8>>, alpha2 => <<"TK">>, alpha3 => <<"TKL">>, numerical_code => 772},
                   #{name => <<"Tonga"/utf8>>, alpha2 => <<"TO">>, alpha3 => <<"TON">>, numerical_code => 776},
                   #{name => <<"Trinidad and Tobago"/utf8>>, alpha2 => <<"TT">>, alpha3 => <<"TTO">>, numerical_code => 780},
                   #{name => <<"Tunisia"/utf8>>, alpha2 => <<"TN">>, alpha3 => <<"TUN">>, numerical_code => 788},
                   #{name => <<"Turkey"/utf8>>, alpha2 => <<"TR">>, alpha3 => <<"TUR">>, numerical_code => 792},
                   #{name => <<"Turkmenistan"/utf8>>, alpha2 => <<"TM">>, alpha3 => <<"TKM">>, numerical_code => 795},
                   #{name => <<"Turks and Caicos Islands (the)"/utf8>>, alpha2 => <<"TC">>, alpha3 => <<"TCA">>, numerical_code => 796},
                   #{name => <<"Tuvalu"/utf8>>, alpha2 => <<"TV">>, alpha3 => <<"TUV">>, numerical_code => 798},
                   #{name => <<"Uganda"/utf8>>, alpha2 => <<"UG">>, alpha3 => <<"UGA">>, numerical_code => 800},
                   #{name => <<"Ukraine"/utf8>>, alpha2 => <<"UA">>, alpha3 => <<"UKR">>, numerical_code => 804},
                   #{name => <<"United Arab Emirates (the)"/utf8>>, alpha2 => <<"AE">>, alpha3 => <<"ARE">>, numerical_code => 784},
                   #{name => <<"United Kingdom of Great Britain and Northern Ireland (the)"/utf8>>, alpha2 => <<"GB">>, alpha3 => <<"GBR">>, numerical_code => 826},
                   #{name => <<"United States Minor Outlying Islands (the)"/utf8>>, alpha2 => <<"UM">>, alpha3 => <<"UMI">>, numerical_code => 581},
                   #{name => <<"United States of America (the)"/utf8>>, alpha2 => <<"US">>, alpha3 => <<"USA">>, numerical_code => 840},
                   #{name => <<"Uruguay"/utf8>>, alpha2 => <<"UY">>, alpha3 => <<"URY">>, numerical_code => 858},
                   #{name => <<"Uzbekistan"/utf8>>, alpha2 => <<"UZ">>, alpha3 => <<"UZB">>, numerical_code => 860},
                   #{name => <<"Vanuatu"/utf8>>, alpha2 => <<"VU">>, alpha3 => <<"VUT">>, numerical_code => 548},
                   #{name => <<"Venezuela (Bolivarian Republic of)"/utf8>>, alpha2 => <<"VE">>, alpha3 => <<"VEN">>, numerical_code => 862},
                   #{name => <<"Viet Nam"/utf8>>, alpha2 => <<"VN">>, alpha3 => <<"VNM">>, numerical_code => 704},
                   #{name => <<"Virgin Islands (British)"/utf8>>, alpha2 => <<"VG">>, alpha3 => <<"VGB">>, numerical_code => 92},
                   #{name => <<"Virgin Islands (U.S.)"/utf8>>, alpha2 => <<"VI">>, alpha3 => <<"VIR">>, numerical_code => 850},
                   #{name => <<"Wallis and Futuna"/utf8>>, alpha2 => <<"WF">>, alpha3 => <<"WLF">>, numerical_code => 876},
                   #{name => <<"Western Sahara*"/utf8>>, alpha2 => <<"EH">>, alpha3 => <<"ESH">>, numerical_code => 732},
                   #{name => <<"Yemen"/utf8>>, alpha2 => <<"YE">>, alpha3 => <<"YEM">>, numerical_code => 887},
                   #{name => <<"Zambia"/utf8>>, alpha2 => <<"ZM">>, alpha3 => <<"ZMB">>, numerical_code => 894},
                   #{name => <<"Zimbabwe"/utf8>>, alpha2 => <<"ZW">>, alpha3 => <<"ZWE">>, numerical_code => 716}],

    validate_countries(CountryList),

    %% Validate get_alpha_2_country_list
    CountryAlpha2List = lists:map(fun(#{alpha2 := Alpha2}) -> Alpha2 end, CountryList),
    ?assertEqual(length(CountryAlpha2List), length(iso_erlang:get_alpha_2_country_list())),
    ?assertEqual([], CountryAlpha2List -- iso_erlang:get_alpha_2_country_list()),
    ?assertEqual([], iso_erlang:get_alpha_2_country_list() -- CountryAlpha2List),

    %% Validate get_alpha_3_country_list
    CountryAlpha3List = lists:map(fun(#{alpha3 := Alpha3}) -> Alpha3 end, CountryList),
    ?assertEqual(length(CountryAlpha3List), length(iso_erlang:get_alpha_3_country_list())),
    ?assertEqual([], CountryAlpha3List -- iso_erlang:get_alpha_3_country_list()),
    ?assertEqual([], iso_erlang:get_alpha_3_country_list() -- CountryAlpha3List),

    %% Validate get_country_name_list
    CountryNameList = lists:map(fun(#{name := Name}) -> Name end, CountryList),
    ?assertEqual(length(CountryNameList), length(iso_erlang:get_country_name_list())),
    ?assertEqual([], CountryNameList -- iso_erlang:get_country_name_list()),
    ?assertEqual([], iso_erlang:get_country_name_list() -- CountryNameList),

    %% country count get_country_count
    ?assertEqual(iso_erlang:get_country_count(), length(CountryNameList)).

validate_countries([]) ->
    ok;
validate_countries([#{name := Name, alpha2 := Alpha2, alpha3 := Alpha3, numerical_code := NumericalCode} | Tail]) ->
    %% Validate conversion from alpha2 and alpha3 to country name
    ?assertEqual(Name, iso_erlang:to_country_name(Alpha2)),
    ?assertEqual(Name, iso_erlang:country_alpha_2_to_name(Alpha2)),
    ?assertEqual(Name, iso_erlang:to_country_name(Alpha3)),
    ?assertEqual(Name, iso_erlang:country_alpha_3_to_name(Alpha3)),
    %% Validate conversion from alpha3 to alpha2
    ?assertEqual(Alpha2, iso_erlang:to_country_alpha_2(Alpha3)),
    %% Validate conversion from alpha2 to alpha3
    ?assertEqual(Alpha3, iso_erlang:to_country_alpha_3(Alpha2)),
    %% Validate conversion from alpha2 and alpha3 to country code
    ?assertEqual(NumericalCode, iso_erlang:country_to_numerical_code(Alpha2)),
    ?assertEqual(NumericalCode, iso_erlang:country_alpha_2_to_numerical_code(Alpha2)),
    ?assertEqual(NumericalCode, iso_erlang:country_to_numerical_code(Alpha3)),
    ?assertEqual(NumericalCode, iso_erlang:country_alpha_3_to_numerical_code(Alpha3)),
    %% Validate is country checks
    ?assertEqual(true, iso_erlang:is_country(Alpha2)),
    ?assertEqual(true, iso_erlang:is_country(Alpha3)),
    ?assertEqual(true, iso_erlang:is_country_alpha_3(Alpha3)),
    ?assertEqual(true, iso_erlang:is_country_alpha_2(Alpha2)),

    validate_countries(Tail).

