-module(countries_erlang).

%% API
-export([
    alpha_2_to_name/1,
    alpha_3_to_name/1,
    is_alpha_2/1,
    is_alpha_3/1,
    is_country/1,
    to_alpha_2/1,
    to_alpha_3/1,
    to_country_name/1
]).

to_country_name(Country) when bit_size(Country) =:= 2 -> alpha_2_to_name(Country);
to_country_name(Country) when bit_size(Country) =:= 3 -> alpha_3_to_name(Country).

is_country(Country) when bit_size(Country) =:= 2 -> is_alpha_2(Country);
is_country(Country) when bit_size(Country) =:= 3 -> is_alpha_3(Country);
is_country(_Other) -> false.

is_alpha_3(<<"AFG">>) -> true;
is_alpha_3(<<"ALA">>) -> true;
is_alpha_3(<<"ALB">>) -> true;
is_alpha_3(<<"DZA">>) -> true;
is_alpha_3(<<"ASM">>) -> true;
is_alpha_3(<<"AND">>) -> true;
is_alpha_3(<<"AGO">>) -> true;
is_alpha_3(<<"AIA">>) -> true;
is_alpha_3(<<"ATA">>) -> true;
is_alpha_3(<<"ATG">>) -> true;
is_alpha_3(<<"ARG">>) -> true;
is_alpha_3(<<"ARM">>) -> true;
is_alpha_3(<<"ABW">>) -> true;
is_alpha_3(<<"AUS">>) -> true;
is_alpha_3(<<"AUT">>) -> true;
is_alpha_3(<<"AZE">>) -> true;
is_alpha_3(<<"BHS">>) -> true;
is_alpha_3(<<"BHR">>) -> true;
is_alpha_3(<<"BGD">>) -> true;
is_alpha_3(<<"BRB">>) -> true;
is_alpha_3(<<"BLR">>) -> true;
is_alpha_3(<<"BEL">>) -> true;
is_alpha_3(<<"BLZ">>) -> true;
is_alpha_3(<<"BEN">>) -> true;
is_alpha_3(<<"BMU">>) -> true;
is_alpha_3(<<"BTN">>) -> true;
is_alpha_3(<<"BOL">>) -> true;
is_alpha_3(<<"BIH">>) -> true;
is_alpha_3(<<"BWA">>) -> true;
is_alpha_3(<<"BVT">>) -> true;
is_alpha_3(<<"BRA">>) -> true;
is_alpha_3(<<"VGB">>) -> true;
is_alpha_3(<<"IOT">>) -> true;
is_alpha_3(<<"BRN">>) -> true;
is_alpha_3(<<"BGR">>) -> true;
is_alpha_3(<<"BFA">>) -> true;
is_alpha_3(<<"BDI">>) -> true;
is_alpha_3(<<"KHM">>) -> true;
is_alpha_3(<<"CMR">>) -> true;
is_alpha_3(<<"CAN">>) -> true;
is_alpha_3(<<"CPV">>) -> true;
is_alpha_3(<<"CYM">>) -> true;
is_alpha_3(<<"CAF">>) -> true;
is_alpha_3(<<"TCD">>) -> true;
is_alpha_3(<<"CHL">>) -> true;
is_alpha_3(<<"CHN">>) -> true;
is_alpha_3(<<"HKG">>) -> true;
is_alpha_3(<<"MAC">>) -> true;
is_alpha_3(<<"CXR">>) -> true;
is_alpha_3(<<"CCK">>) -> true;
is_alpha_3(<<"COL">>) -> true;
is_alpha_3(<<"COM">>) -> true;
is_alpha_3(<<"COG">>) -> true;
is_alpha_3(<<"COD">>) -> true;
is_alpha_3(<<"COK">>) -> true;
is_alpha_3(<<"CRI">>) -> true;
is_alpha_3(<<"CIV">>) -> true;
is_alpha_3(<<"HRV">>) -> true;
is_alpha_3(<<"CUB">>) -> true;
is_alpha_3(<<"CYP">>) -> true;
is_alpha_3(<<"CZE">>) -> true;
is_alpha_3(<<"DNK">>) -> true;
is_alpha_3(<<"DJI">>) -> true;
is_alpha_3(<<"DMA">>) -> true;
is_alpha_3(<<"DOM">>) -> true;
is_alpha_3(<<"ECU">>) -> true;
is_alpha_3(<<"EGY">>) -> true;
is_alpha_3(<<"SLV">>) -> true;
is_alpha_3(<<"GNQ">>) -> true;
is_alpha_3(<<"ERI">>) -> true;
is_alpha_3(<<"EST">>) -> true;
is_alpha_3(<<"ETH">>) -> true;
is_alpha_3(<<"FLK">>) -> true;
is_alpha_3(<<"FRO">>) -> true;
is_alpha_3(<<"FJI">>) -> true;
is_alpha_3(<<"FIN">>) -> true;
is_alpha_3(<<"FRA">>) -> true;
is_alpha_3(<<"GUF">>) -> true;
is_alpha_3(<<"PYF">>) -> true;
is_alpha_3(<<"ATF">>) -> true;
is_alpha_3(<<"GAB">>) -> true;
is_alpha_3(<<"GMB">>) -> true;
is_alpha_3(<<"GEO">>) -> true;
is_alpha_3(<<"DEU">>) -> true;
is_alpha_3(<<"GHA">>) -> true;
is_alpha_3(<<"GIB">>) -> true;
is_alpha_3(<<"GRC">>) -> true;
is_alpha_3(<<"GRL">>) -> true;
is_alpha_3(<<"GRD">>) -> true;
is_alpha_3(<<"GLP">>) -> true;
is_alpha_3(<<"GUM">>) -> true;
is_alpha_3(<<"GTM">>) -> true;
is_alpha_3(<<"GGY">>) -> true;
is_alpha_3(<<"GIN">>) -> true;
is_alpha_3(<<"GNB">>) -> true;
is_alpha_3(<<"GUY">>) -> true;
is_alpha_3(<<"HTI">>) -> true;
is_alpha_3(<<"HMD">>) -> true;
is_alpha_3(<<"VAT">>) -> true;
is_alpha_3(<<"HND">>) -> true;
is_alpha_3(<<"HUN">>) -> true;
is_alpha_3(<<"ISL">>) -> true;
is_alpha_3(<<"IND">>) -> true;
is_alpha_3(<<"IDN">>) -> true;
is_alpha_3(<<"IRN">>) -> true;
is_alpha_3(<<"IRQ">>) -> true;
is_alpha_3(<<"IRL">>) -> true;
is_alpha_3(<<"IMN">>) -> true;
is_alpha_3(<<"ISR">>) -> true;
is_alpha_3(<<"ITA">>) -> true;
is_alpha_3(<<"JAM">>) -> true;
is_alpha_3(<<"JPN">>) -> true;
is_alpha_3(<<"JEY">>) -> true;
is_alpha_3(<<"JOR">>) -> true;
is_alpha_3(<<"KAZ">>) -> true;
is_alpha_3(<<"KEN">>) -> true;
is_alpha_3(<<"KIR">>) -> true;
is_alpha_3(<<"PRK">>) -> true;
is_alpha_3(<<"KOR">>) -> true;
is_alpha_3(<<"KWT">>) -> true;
is_alpha_3(<<"KGZ">>) -> true;
is_alpha_3(<<"LAO">>) -> true;
is_alpha_3(<<"LVA">>) -> true;
is_alpha_3(<<"LBN">>) -> true;
is_alpha_3(<<"LSO">>) -> true;
is_alpha_3(<<"LBR">>) -> true;
is_alpha_3(<<"LBY">>) -> true;
is_alpha_3(<<"LIE">>) -> true;
is_alpha_3(<<"LTU">>) -> true;
is_alpha_3(<<"LUX">>) -> true;
is_alpha_3(<<"MKD">>) -> true;
is_alpha_3(<<"MDG">>) -> true;
is_alpha_3(<<"MWI">>) -> true;
is_alpha_3(<<"MYS">>) -> true;
is_alpha_3(<<"MDV">>) -> true;
is_alpha_3(<<"MLI">>) -> true;
is_alpha_3(<<"MLT">>) -> true;
is_alpha_3(<<"MHL">>) -> true;
is_alpha_3(<<"MTQ">>) -> true;
is_alpha_3(<<"MRT">>) -> true;
is_alpha_3(<<"MUS">>) -> true;
is_alpha_3(<<"MYT">>) -> true;
is_alpha_3(<<"MEX">>) -> true;
is_alpha_3(<<"FSM">>) -> true;
is_alpha_3(<<"MDA">>) -> true;
is_alpha_3(<<"MCO">>) -> true;
is_alpha_3(<<"MNG">>) -> true;
is_alpha_3(<<"MNE">>) -> true;
is_alpha_3(<<"MSR">>) -> true;
is_alpha_3(<<"MAR">>) -> true;
is_alpha_3(<<"MOZ">>) -> true;
is_alpha_3(<<"MMR">>) -> true;
is_alpha_3(<<"NAM">>) -> true;
is_alpha_3(<<"NRU">>) -> true;
is_alpha_3(<<"NPL">>) -> true;
is_alpha_3(<<"NLD">>) -> true;
is_alpha_3(<<"ANT">>) -> true;
is_alpha_3(<<"NCL">>) -> true;
is_alpha_3(<<"NZL">>) -> true;
is_alpha_3(<<"NIC">>) -> true;
is_alpha_3(<<"NER">>) -> true;
is_alpha_3(<<"NGA">>) -> true;
is_alpha_3(<<"NIU">>) -> true;
is_alpha_3(<<"NFK">>) -> true;
is_alpha_3(<<"MNP">>) -> true;
is_alpha_3(<<"NOR">>) -> true;
is_alpha_3(<<"OMN">>) -> true;
is_alpha_3(<<"PAK">>) -> true;
is_alpha_3(<<"PLW">>) -> true;
is_alpha_3(<<"PSE">>) -> true;
is_alpha_3(<<"PAN">>) -> true;
is_alpha_3(<<"PNG">>) -> true;
is_alpha_3(<<"PRY">>) -> true;
is_alpha_3(<<"PER">>) -> true;
is_alpha_3(<<"PHL">>) -> true;
is_alpha_3(<<"PCN">>) -> true;
is_alpha_3(<<"POL">>) -> true;
is_alpha_3(<<"PRT">>) -> true;
is_alpha_3(<<"PRI">>) -> true;
is_alpha_3(<<"QAT">>) -> true;
is_alpha_3(<<"REU">>) -> true;
is_alpha_3(<<"ROU">>) -> true;
is_alpha_3(<<"RUS">>) -> true;
is_alpha_3(<<"RWA">>) -> true;
is_alpha_3(<<"BLM">>) -> true;
is_alpha_3(<<"SHN">>) -> true;
is_alpha_3(<<"KNA">>) -> true;
is_alpha_3(<<"LCA">>) -> true;
is_alpha_3(<<"MAF">>) -> true;
is_alpha_3(<<"SPM">>) -> true;
is_alpha_3(<<"VCT">>) -> true;
is_alpha_3(<<"WSM">>) -> true;
is_alpha_3(<<"SMR">>) -> true;
is_alpha_3(<<"STP">>) -> true;
is_alpha_3(<<"SAU">>) -> true;
is_alpha_3(<<"SEN">>) -> true;
is_alpha_3(<<"SRB">>) -> true;
is_alpha_3(<<"SYC">>) -> true;
is_alpha_3(<<"SLE">>) -> true;
is_alpha_3(<<"SGP">>) -> true;
is_alpha_3(<<"SVK">>) -> true;
is_alpha_3(<<"SVN">>) -> true;
is_alpha_3(<<"SLB">>) -> true;
is_alpha_3(<<"SOM">>) -> true;
is_alpha_3(<<"ZAF">>) -> true;
is_alpha_3(<<"SGS">>) -> true;
is_alpha_3(<<"SSD">>) -> true;
is_alpha_3(<<"ESP">>) -> true;
is_alpha_3(<<"LKA">>) -> true;
is_alpha_3(<<"SDN">>) -> true;
is_alpha_3(<<"SUR">>) -> true;
is_alpha_3(<<"SJM">>) -> true;
is_alpha_3(<<"SWZ">>) -> true;
is_alpha_3(<<"SWE">>) -> true;
is_alpha_3(<<"CHE">>) -> true;
is_alpha_3(<<"SYR">>) -> true;
is_alpha_3(<<"TWN">>) -> true;
is_alpha_3(<<"TJK">>) -> true;
is_alpha_3(<<"TZA">>) -> true;
is_alpha_3(<<"THA">>) -> true;
is_alpha_3(<<"TLS">>) -> true;
is_alpha_3(<<"TGO">>) -> true;
is_alpha_3(<<"TKL">>) -> true;
is_alpha_3(<<"TON">>) -> true;
is_alpha_3(<<"TTO">>) -> true;
is_alpha_3(<<"TUN">>) -> true;
is_alpha_3(<<"TUR">>) -> true;
is_alpha_3(<<"TKM">>) -> true;
is_alpha_3(<<"TCA">>) -> true;
is_alpha_3(<<"TUV">>) -> true;
is_alpha_3(<<"UGA">>) -> true;
is_alpha_3(<<"UKR">>) -> true;
is_alpha_3(<<"ARE">>) -> true;
is_alpha_3(<<"GBR">>) -> true;
is_alpha_3(<<"USA">>) -> true;
is_alpha_3(<<"UMI">>) -> true;
is_alpha_3(<<"URY">>) -> true;
is_alpha_3(<<"UZB">>) -> true;
is_alpha_3(<<"VUT">>) -> true;
is_alpha_3(<<"VEN">>) -> true;
is_alpha_3(<<"VNM">>) -> true;
is_alpha_3(<<"VIR">>) -> true;
is_alpha_3(<<"WLF">>) -> true;
is_alpha_3(<<"ESH">>) -> true;
is_alpha_3(<<"YEM">>) -> true;
is_alpha_3(<<"ZMB">>) -> true;
is_alpha_3(<<"ZWE">>) -> true;
is_alpha_3(_Other) -> false.

is_alpha_2(<<"AF">>) -> true;
is_alpha_2(<<"AX">>) -> true;
is_alpha_2(<<"AL">>) -> true;
is_alpha_2(<<"DZ">>) -> true;
is_alpha_2(<<"AS">>) -> true;
is_alpha_2(<<"AD">>) -> true;
is_alpha_2(<<"AO">>) -> true;
is_alpha_2(<<"AI">>) -> true;
is_alpha_2(<<"AQ">>) -> true;
is_alpha_2(<<"AG">>) -> true;
is_alpha_2(<<"AR">>) -> true;
is_alpha_2(<<"AM">>) -> true;
is_alpha_2(<<"AW">>) -> true;
is_alpha_2(<<"AU">>) -> true;
is_alpha_2(<<"AT">>) -> true;
is_alpha_2(<<"AZ">>) -> true;
is_alpha_2(<<"BS">>) -> true;
is_alpha_2(<<"BH">>) -> true;
is_alpha_2(<<"BD">>) -> true;
is_alpha_2(<<"BB">>) -> true;
is_alpha_2(<<"BY">>) -> true;
is_alpha_2(<<"BE">>) -> true;
is_alpha_2(<<"BZ">>) -> true;
is_alpha_2(<<"BJ">>) -> true;
is_alpha_2(<<"BM">>) -> true;
is_alpha_2(<<"BT">>) -> true;
is_alpha_2(<<"BO">>) -> true;
is_alpha_2(<<"BA">>) -> true;
is_alpha_2(<<"BW">>) -> true;
is_alpha_2(<<"BV">>) -> true;
is_alpha_2(<<"BR">>) -> true;
is_alpha_2(<<"VG">>) -> true;
is_alpha_2(<<"IO">>) -> true;
is_alpha_2(<<"BN">>) -> true;
is_alpha_2(<<"BG">>) -> true;
is_alpha_2(<<"BF">>) -> true;
is_alpha_2(<<"BI">>) -> true;
is_alpha_2(<<"KH">>) -> true;
is_alpha_2(<<"CM">>) -> true;
is_alpha_2(<<"CA">>) -> true;
is_alpha_2(<<"CV">>) -> true;
is_alpha_2(<<"KY">>) -> true;
is_alpha_2(<<"CF">>) -> true;
is_alpha_2(<<"TD">>) -> true;
is_alpha_2(<<"CL">>) -> true;
is_alpha_2(<<"CN">>) -> true;
is_alpha_2(<<"HK">>) -> true;
is_alpha_2(<<"MO">>) -> true;
is_alpha_2(<<"CX">>) -> true;
is_alpha_2(<<"CC">>) -> true;
is_alpha_2(<<"CO">>) -> true;
is_alpha_2(<<"KM">>) -> true;
is_alpha_2(<<"CG">>) -> true;
is_alpha_2(<<"CD">>) -> true;
is_alpha_2(<<"CK">>) -> true;
is_alpha_2(<<"CR">>) -> true;
is_alpha_2(<<"CI">>) -> true;
is_alpha_2(<<"HR">>) -> true;
is_alpha_2(<<"CU">>) -> true;
is_alpha_2(<<"CY">>) -> true;
is_alpha_2(<<"CZ">>) -> true;
is_alpha_2(<<"DK">>) -> true;
is_alpha_2(<<"DJ">>) -> true;
is_alpha_2(<<"DM">>) -> true;
is_alpha_2(<<"DO">>) -> true;
is_alpha_2(<<"EC">>) -> true;
is_alpha_2(<<"EG">>) -> true;
is_alpha_2(<<"SV">>) -> true;
is_alpha_2(<<"GQ">>) -> true;
is_alpha_2(<<"ER">>) -> true;
is_alpha_2(<<"EE">>) -> true;
is_alpha_2(<<"ET">>) -> true;
is_alpha_2(<<"FK">>) -> true;
is_alpha_2(<<"FO">>) -> true;
is_alpha_2(<<"FJ">>) -> true;
is_alpha_2(<<"FI">>) -> true;
is_alpha_2(<<"FR">>) -> true;
is_alpha_2(<<"GF">>) -> true;
is_alpha_2(<<"PF">>) -> true;
is_alpha_2(<<"TF">>) -> true;
is_alpha_2(<<"GA">>) -> true;
is_alpha_2(<<"GM">>) -> true;
is_alpha_2(<<"GE">>) -> true;
is_alpha_2(<<"DE">>) -> true;
is_alpha_2(<<"GH">>) -> true;
is_alpha_2(<<"GI">>) -> true;
is_alpha_2(<<"GR">>) -> true;
is_alpha_2(<<"GL">>) -> true;
is_alpha_2(<<"GD">>) -> true;
is_alpha_2(<<"GP">>) -> true;
is_alpha_2(<<"GU">>) -> true;
is_alpha_2(<<"GT">>) -> true;
is_alpha_2(<<"GG">>) -> true;
is_alpha_2(<<"GN">>) -> true;
is_alpha_2(<<"GW">>) -> true;
is_alpha_2(<<"GY">>) -> true;
is_alpha_2(<<"HT">>) -> true;
is_alpha_2(<<"HM">>) -> true;
is_alpha_2(<<"VA">>) -> true;
is_alpha_2(<<"HN">>) -> true;
is_alpha_2(<<"HU">>) -> true;
is_alpha_2(<<"IS">>) -> true;
is_alpha_2(<<"IN">>) -> true;
is_alpha_2(<<"ID">>) -> true;
is_alpha_2(<<"IR">>) -> true;
is_alpha_2(<<"IQ">>) -> true;
is_alpha_2(<<"IE">>) -> true;
is_alpha_2(<<"IM">>) -> true;
is_alpha_2(<<"IL">>) -> true;
is_alpha_2(<<"IT">>) -> true;
is_alpha_2(<<"JM">>) -> true;
is_alpha_2(<<"JP">>) -> true;
is_alpha_2(<<"JE">>) -> true;
is_alpha_2(<<"JO">>) -> true;
is_alpha_2(<<"KZ">>) -> true;
is_alpha_2(<<"KE">>) -> true;
is_alpha_2(<<"KI">>) -> true;
is_alpha_2(<<"KP">>) -> true;
is_alpha_2(<<"KR">>) -> true;
is_alpha_2(<<"KW">>) -> true;
is_alpha_2(<<"KG">>) -> true;
is_alpha_2(<<"LA">>) -> true;
is_alpha_2(<<"LV">>) -> true;
is_alpha_2(<<"LB">>) -> true;
is_alpha_2(<<"LS">>) -> true;
is_alpha_2(<<"LR">>) -> true;
is_alpha_2(<<"LY">>) -> true;
is_alpha_2(<<"LI">>) -> true;
is_alpha_2(<<"LT">>) -> true;
is_alpha_2(<<"LU">>) -> true;
is_alpha_2(<<"MK">>) -> true;
is_alpha_2(<<"MG">>) -> true;
is_alpha_2(<<"MW">>) -> true;
is_alpha_2(<<"MY">>) -> true;
is_alpha_2(<<"MV">>) -> true;
is_alpha_2(<<"ML">>) -> true;
is_alpha_2(<<"MT">>) -> true;
is_alpha_2(<<"MH">>) -> true;
is_alpha_2(<<"MQ">>) -> true;
is_alpha_2(<<"MR">>) -> true;
is_alpha_2(<<"MU">>) -> true;
is_alpha_2(<<"YT">>) -> true;
is_alpha_2(<<"MX">>) -> true;
is_alpha_2(<<"FM">>) -> true;
is_alpha_2(<<"MD">>) -> true;
is_alpha_2(<<"MC">>) -> true;
is_alpha_2(<<"MN">>) -> true;
is_alpha_2(<<"ME">>) -> true;
is_alpha_2(<<"MS">>) -> true;
is_alpha_2(<<"MA">>) -> true;
is_alpha_2(<<"MZ">>) -> true;
is_alpha_2(<<"MM">>) -> true;
is_alpha_2(<<"NA">>) -> true;
is_alpha_2(<<"NR">>) -> true;
is_alpha_2(<<"NP">>) -> true;
is_alpha_2(<<"NL">>) -> true;
is_alpha_2(<<"AN">>) -> true;
is_alpha_2(<<"NC">>) -> true;
is_alpha_2(<<"NZ">>) -> true;
is_alpha_2(<<"NI">>) -> true;
is_alpha_2(<<"NE">>) -> true;
is_alpha_2(<<"NG">>) -> true;
is_alpha_2(<<"NU">>) -> true;
is_alpha_2(<<"NF">>) -> true;
is_alpha_2(<<"MP">>) -> true;
is_alpha_2(<<"NO">>) -> true;
is_alpha_2(<<"OM">>) -> true;
is_alpha_2(<<"PK">>) -> true;
is_alpha_2(<<"PW">>) -> true;
is_alpha_2(<<"PS">>) -> true;
is_alpha_2(<<"PA">>) -> true;
is_alpha_2(<<"PG">>) -> true;
is_alpha_2(<<"PY">>) -> true;
is_alpha_2(<<"PE">>) -> true;
is_alpha_2(<<"PH">>) -> true;
is_alpha_2(<<"PN">>) -> true;
is_alpha_2(<<"PL">>) -> true;
is_alpha_2(<<"PT">>) -> true;
is_alpha_2(<<"PR">>) -> true;
is_alpha_2(<<"QA">>) -> true;
is_alpha_2(<<"RE">>) -> true;
is_alpha_2(<<"RO">>) -> true;
is_alpha_2(<<"RU">>) -> true;
is_alpha_2(<<"RW">>) -> true;
is_alpha_2(<<"BL">>) -> true;
is_alpha_2(<<"SH">>) -> true;
is_alpha_2(<<"KN">>) -> true;
is_alpha_2(<<"LC">>) -> true;
is_alpha_2(<<"MF">>) -> true;
is_alpha_2(<<"PM">>) -> true;
is_alpha_2(<<"VC">>) -> true;
is_alpha_2(<<"WS">>) -> true;
is_alpha_2(<<"SM">>) -> true;
is_alpha_2(<<"ST">>) -> true;
is_alpha_2(<<"SA">>) -> true;
is_alpha_2(<<"SN">>) -> true;
is_alpha_2(<<"RS">>) -> true;
is_alpha_2(<<"SC">>) -> true;
is_alpha_2(<<"SL">>) -> true;
is_alpha_2(<<"SG">>) -> true;
is_alpha_2(<<"SK">>) -> true;
is_alpha_2(<<"SI">>) -> true;
is_alpha_2(<<"SB">>) -> true;
is_alpha_2(<<"SO">>) -> true;
is_alpha_2(<<"ZA">>) -> true;
is_alpha_2(<<"GS">>) -> true;
is_alpha_2(<<"SS">>) -> true;
is_alpha_2(<<"ES">>) -> true;
is_alpha_2(<<"LK">>) -> true;
is_alpha_2(<<"SD">>) -> true;
is_alpha_2(<<"SR">>) -> true;
is_alpha_2(<<"SJ">>) -> true;
is_alpha_2(<<"SZ">>) -> true;
is_alpha_2(<<"SE">>) -> true;
is_alpha_2(<<"CH">>) -> true;
is_alpha_2(<<"SY">>) -> true;
is_alpha_2(<<"TW">>) -> true;
is_alpha_2(<<"TJ">>) -> true;
is_alpha_2(<<"TZ">>) -> true;
is_alpha_2(<<"TH">>) -> true;
is_alpha_2(<<"TL">>) -> true;
is_alpha_2(<<"TG">>) -> true;
is_alpha_2(<<"TK">>) -> true;
is_alpha_2(<<"TO">>) -> true;
is_alpha_2(<<"TT">>) -> true;
is_alpha_2(<<"TN">>) -> true;
is_alpha_2(<<"TR">>) -> true;
is_alpha_2(<<"TM">>) -> true;
is_alpha_2(<<"TC">>) -> true;
is_alpha_2(<<"TV">>) -> true;
is_alpha_2(<<"UG">>) -> true;
is_alpha_2(<<"UA">>) -> true;
is_alpha_2(<<"AE">>) -> true;
is_alpha_2(<<"GB">>) -> true;
is_alpha_2(<<"US">>) -> true;
is_alpha_2(<<"UM">>) -> true;
is_alpha_2(<<"UY">>) -> true;
is_alpha_2(<<"UZ">>) -> true;
is_alpha_2(<<"VU">>) -> true;
is_alpha_2(<<"VE">>) -> true;
is_alpha_2(<<"VN">>) -> true;
is_alpha_2(<<"VI">>) -> true;
is_alpha_2(<<"WF">>) -> true;
is_alpha_2(<<"EH">>) -> true;
is_alpha_2(<<"YE">>) -> true;
is_alpha_2(<<"ZM">>) -> true;
is_alpha_2(<<"ZW">>) -> true;
is_alpha_2(_Other) -> false.

to_alpha_3(<<"AF">>) -> <<"AFG">>;
to_alpha_3(<<"AX">>) -> <<"ALA">>;
to_alpha_3(<<"AL">>) -> <<"ALB">>;
to_alpha_3(<<"DZ">>) -> <<"DZA">>;
to_alpha_3(<<"AS">>) -> <<"ASM">>;
to_alpha_3(<<"AD">>) -> <<"AND">>;
to_alpha_3(<<"AO">>) -> <<"AGO">>;
to_alpha_3(<<"AI">>) -> <<"AIA">>;
to_alpha_3(<<"AQ">>) -> <<"ATA">>;
to_alpha_3(<<"AG">>) -> <<"ATG">>;
to_alpha_3(<<"AR">>) -> <<"ARG">>;
to_alpha_3(<<"AM">>) -> <<"ARM">>;
to_alpha_3(<<"AW">>) -> <<"ABW">>;
to_alpha_3(<<"AU">>) -> <<"AUS">>;
to_alpha_3(<<"AT">>) -> <<"AUT">>;
to_alpha_3(<<"AZ">>) -> <<"AZE">>;
to_alpha_3(<<"BS">>) -> <<"BHS">>;
to_alpha_3(<<"BH">>) -> <<"BHR">>;
to_alpha_3(<<"BD">>) -> <<"BGD">>;
to_alpha_3(<<"BB">>) -> <<"BRB">>;
to_alpha_3(<<"BY">>) -> <<"BLR">>;
to_alpha_3(<<"BE">>) -> <<"BEL">>;
to_alpha_3(<<"BZ">>) -> <<"BLZ">>;
to_alpha_3(<<"BJ">>) -> <<"BEN">>;
to_alpha_3(<<"BM">>) -> <<"BMU">>;
to_alpha_3(<<"BT">>) -> <<"BTN">>;
to_alpha_3(<<"BO">>) -> <<"BOL">>;
to_alpha_3(<<"BA">>) -> <<"BIH">>;
to_alpha_3(<<"BW">>) -> <<"BWA">>;
to_alpha_3(<<"BV">>) -> <<"BVT">>;
to_alpha_3(<<"BR">>) -> <<"BRA">>;
to_alpha_3(<<"VG">>) -> <<"VGB">>;
to_alpha_3(<<"IO">>) -> <<"IOT">>;
to_alpha_3(<<"BN">>) -> <<"BRN">>;
to_alpha_3(<<"BG">>) -> <<"BGR">>;
to_alpha_3(<<"BF">>) -> <<"BFA">>;
to_alpha_3(<<"BI">>) -> <<"BDI">>;
to_alpha_3(<<"KH">>) -> <<"KHM">>;
to_alpha_3(<<"CM">>) -> <<"CMR">>;
to_alpha_3(<<"CA">>) -> <<"CAN">>;
to_alpha_3(<<"CV">>) -> <<"CPV">>;
to_alpha_3(<<"KY">>) -> <<"CYM">>;
to_alpha_3(<<"CF">>) -> <<"CAF">>;
to_alpha_3(<<"TD">>) -> <<"TCD">>;
to_alpha_3(<<"CL">>) -> <<"CHL">>;
to_alpha_3(<<"CN">>) -> <<"CHN">>;
to_alpha_3(<<"HK">>) -> <<"HKG">>;
to_alpha_3(<<"MO">>) -> <<"MAC">>;
to_alpha_3(<<"CX">>) -> <<"CXR">>;
to_alpha_3(<<"CC">>) -> <<"CCK">>;
to_alpha_3(<<"CO">>) -> <<"COL">>;
to_alpha_3(<<"KM">>) -> <<"COM">>;
to_alpha_3(<<"CG">>) -> <<"COG">>;
to_alpha_3(<<"CD">>) -> <<"COD">>;
to_alpha_3(<<"CK">>) -> <<"COK">>;
to_alpha_3(<<"CR">>) -> <<"CRI">>;
to_alpha_3(<<"CI">>) -> <<"CIV">>;
to_alpha_3(<<"HR">>) -> <<"HRV">>;
to_alpha_3(<<"CU">>) -> <<"CUB">>;
to_alpha_3(<<"CY">>) -> <<"CYP">>;
to_alpha_3(<<"CZ">>) -> <<"CZE">>;
to_alpha_3(<<"DK">>) -> <<"DNK">>;
to_alpha_3(<<"DJ">>) -> <<"DJI">>;
to_alpha_3(<<"DM">>) -> <<"DMA">>;
to_alpha_3(<<"DO">>) -> <<"DOM">>;
to_alpha_3(<<"EC">>) -> <<"ECU">>;
to_alpha_3(<<"EG">>) -> <<"EGY">>;
to_alpha_3(<<"SV">>) -> <<"SLV">>;
to_alpha_3(<<"GQ">>) -> <<"GNQ">>;
to_alpha_3(<<"ER">>) -> <<"ERI">>;
to_alpha_3(<<"EE">>) -> <<"EST">>;
to_alpha_3(<<"ET">>) -> <<"ETH">>;
to_alpha_3(<<"FK">>) -> <<"FLK">>;
to_alpha_3(<<"FO">>) -> <<"FRO">>;
to_alpha_3(<<"FJ">>) -> <<"FJI">>;
to_alpha_3(<<"FI">>) -> <<"FIN">>;
to_alpha_3(<<"FR">>) -> <<"FRA">>;
to_alpha_3(<<"GF">>) -> <<"GUF">>;
to_alpha_3(<<"PF">>) -> <<"PYF">>;
to_alpha_3(<<"TF">>) -> <<"ATF">>;
to_alpha_3(<<"GA">>) -> <<"GAB">>;
to_alpha_3(<<"GM">>) -> <<"GMB">>;
to_alpha_3(<<"GE">>) -> <<"GEO">>;
to_alpha_3(<<"DE">>) -> <<"DEU">>;
to_alpha_3(<<"GH">>) -> <<"GHA">>;
to_alpha_3(<<"GI">>) -> <<"GIB">>;
to_alpha_3(<<"GR">>) -> <<"GRC">>;
to_alpha_3(<<"GL">>) -> <<"GRL">>;
to_alpha_3(<<"GD">>) -> <<"GRD">>;
to_alpha_3(<<"GP">>) -> <<"GLP">>;
to_alpha_3(<<"GU">>) -> <<"GUM">>;
to_alpha_3(<<"GT">>) -> <<"GTM">>;
to_alpha_3(<<"GG">>) -> <<"GGY">>;
to_alpha_3(<<"GN">>) -> <<"GIN">>;
to_alpha_3(<<"GW">>) -> <<"GNB">>;
to_alpha_3(<<"GY">>) -> <<"GUY">>;
to_alpha_3(<<"HT">>) -> <<"HTI">>;
to_alpha_3(<<"HM">>) -> <<"HMD">>;
to_alpha_3(<<"VA">>) -> <<"VAT">>;
to_alpha_3(<<"HN">>) -> <<"HND">>;
to_alpha_3(<<"HU">>) -> <<"HUN">>;
to_alpha_3(<<"IS">>) -> <<"ISL">>;
to_alpha_3(<<"IN">>) -> <<"IND">>;
to_alpha_3(<<"ID">>) -> <<"IDN">>;
to_alpha_3(<<"IR">>) -> <<"IRN">>;
to_alpha_3(<<"IQ">>) -> <<"IRQ">>;
to_alpha_3(<<"IE">>) -> <<"IRL">>;
to_alpha_3(<<"IM">>) -> <<"IMN">>;
to_alpha_3(<<"IL">>) -> <<"ISR">>;
to_alpha_3(<<"IT">>) -> <<"ITA">>;
to_alpha_3(<<"JM">>) -> <<"JAM">>;
to_alpha_3(<<"JP">>) -> <<"JPN">>;
to_alpha_3(<<"JE">>) -> <<"JEY">>;
to_alpha_3(<<"JO">>) -> <<"JOR">>;
to_alpha_3(<<"KZ">>) -> <<"KAZ">>;
to_alpha_3(<<"KE">>) -> <<"KEN">>;
to_alpha_3(<<"KI">>) -> <<"KIR">>;
to_alpha_3(<<"KP">>) -> <<"PRK">>;
to_alpha_3(<<"KR">>) -> <<"KOR">>;
to_alpha_3(<<"KW">>) -> <<"KWT">>;
to_alpha_3(<<"KG">>) -> <<"KGZ">>;
to_alpha_3(<<"LA">>) -> <<"LAO">>;
to_alpha_3(<<"LV">>) -> <<"LVA">>;
to_alpha_3(<<"LB">>) -> <<"LBN">>;
to_alpha_3(<<"LS">>) -> <<"LSO">>;
to_alpha_3(<<"LR">>) -> <<"LBR">>;
to_alpha_3(<<"LY">>) -> <<"LBY">>;
to_alpha_3(<<"LI">>) -> <<"LIE">>;
to_alpha_3(<<"LT">>) -> <<"LTU">>;
to_alpha_3(<<"LU">>) -> <<"LUX">>;
to_alpha_3(<<"MK">>) -> <<"MKD">>;
to_alpha_3(<<"MG">>) -> <<"MDG">>;
to_alpha_3(<<"MW">>) -> <<"MWI">>;
to_alpha_3(<<"MY">>) -> <<"MYS">>;
to_alpha_3(<<"MV">>) -> <<"MDV">>;
to_alpha_3(<<"ML">>) -> <<"MLI">>;
to_alpha_3(<<"MT">>) -> <<"MLT">>;
to_alpha_3(<<"MH">>) -> <<"MHL">>;
to_alpha_3(<<"MQ">>) -> <<"MTQ">>;
to_alpha_3(<<"MR">>) -> <<"MRT">>;
to_alpha_3(<<"MU">>) -> <<"MUS">>;
to_alpha_3(<<"YT">>) -> <<"MYT">>;
to_alpha_3(<<"MX">>) -> <<"MEX">>;
to_alpha_3(<<"FM">>) -> <<"FSM">>;
to_alpha_3(<<"MD">>) -> <<"MDA">>;
to_alpha_3(<<"MC">>) -> <<"MCO">>;
to_alpha_3(<<"MN">>) -> <<"MNG">>;
to_alpha_3(<<"ME">>) -> <<"MNE">>;
to_alpha_3(<<"MS">>) -> <<"MSR">>;
to_alpha_3(<<"MA">>) -> <<"MAR">>;
to_alpha_3(<<"MZ">>) -> <<"MOZ">>;
to_alpha_3(<<"MM">>) -> <<"MMR">>;
to_alpha_3(<<"NA">>) -> <<"NAM">>;
to_alpha_3(<<"NR">>) -> <<"NRU">>;
to_alpha_3(<<"NP">>) -> <<"NPL">>;
to_alpha_3(<<"NL">>) -> <<"NLD">>;
to_alpha_3(<<"AN">>) -> <<"ANT">>;
to_alpha_3(<<"NC">>) -> <<"NCL">>;
to_alpha_3(<<"NZ">>) -> <<"NZL">>;
to_alpha_3(<<"NI">>) -> <<"NIC">>;
to_alpha_3(<<"NE">>) -> <<"NER">>;
to_alpha_3(<<"NG">>) -> <<"NGA">>;
to_alpha_3(<<"NU">>) -> <<"NIU">>;
to_alpha_3(<<"NF">>) -> <<"NFK">>;
to_alpha_3(<<"MP">>) -> <<"MNP">>;
to_alpha_3(<<"NO">>) -> <<"NOR">>;
to_alpha_3(<<"OM">>) -> <<"OMN">>;
to_alpha_3(<<"PK">>) -> <<"PAK">>;
to_alpha_3(<<"PW">>) -> <<"PLW">>;
to_alpha_3(<<"PS">>) -> <<"PSE">>;
to_alpha_3(<<"PA">>) -> <<"PAN">>;
to_alpha_3(<<"PG">>) -> <<"PNG">>;
to_alpha_3(<<"PY">>) -> <<"PRY">>;
to_alpha_3(<<"PE">>) -> <<"PER">>;
to_alpha_3(<<"PH">>) -> <<"PHL">>;
to_alpha_3(<<"PN">>) -> <<"PCN">>;
to_alpha_3(<<"PL">>) -> <<"POL">>;
to_alpha_3(<<"PT">>) -> <<"PRT">>;
to_alpha_3(<<"PR">>) -> <<"PRI">>;
to_alpha_3(<<"QA">>) -> <<"QAT">>;
to_alpha_3(<<"RE">>) -> <<"REU">>;
to_alpha_3(<<"RO">>) -> <<"ROU">>;
to_alpha_3(<<"RU">>) -> <<"RUS">>;
to_alpha_3(<<"RW">>) -> <<"RWA">>;
to_alpha_3(<<"BL">>) -> <<"BLM">>;
to_alpha_3(<<"SH">>) -> <<"SHN">>;
to_alpha_3(<<"KN">>) -> <<"KNA">>;
to_alpha_3(<<"LC">>) -> <<"LCA">>;
to_alpha_3(<<"MF">>) -> <<"MAF">>;
to_alpha_3(<<"PM">>) -> <<"SPM">>;
to_alpha_3(<<"VC">>) -> <<"VCT">>;
to_alpha_3(<<"WS">>) -> <<"WSM">>;
to_alpha_3(<<"SM">>) -> <<"SMR">>;
to_alpha_3(<<"ST">>) -> <<"STP">>;
to_alpha_3(<<"SA">>) -> <<"SAU">>;
to_alpha_3(<<"SN">>) -> <<"SEN">>;
to_alpha_3(<<"RS">>) -> <<"SRB">>;
to_alpha_3(<<"SC">>) -> <<"SYC">>;
to_alpha_3(<<"SL">>) -> <<"SLE">>;
to_alpha_3(<<"SG">>) -> <<"SGP">>;
to_alpha_3(<<"SK">>) -> <<"SVK">>;
to_alpha_3(<<"SI">>) -> <<"SVN">>;
to_alpha_3(<<"SB">>) -> <<"SLB">>;
to_alpha_3(<<"SO">>) -> <<"SOM">>;
to_alpha_3(<<"ZA">>) -> <<"ZAF">>;
to_alpha_3(<<"GS">>) -> <<"SGS">>;
to_alpha_3(<<"SS">>) -> <<"SSD">>;
to_alpha_3(<<"ES">>) -> <<"ESP">>;
to_alpha_3(<<"LK">>) -> <<"LKA">>;
to_alpha_3(<<"SD">>) -> <<"SDN">>;
to_alpha_3(<<"SR">>) -> <<"SUR">>;
to_alpha_3(<<"SJ">>) -> <<"SJM">>;
to_alpha_3(<<"SZ">>) -> <<"SWZ">>;
to_alpha_3(<<"SE">>) -> <<"SWE">>;
to_alpha_3(<<"CH">>) -> <<"CHE">>;
to_alpha_3(<<"SY">>) -> <<"SYR">>;
to_alpha_3(<<"TW">>) -> <<"TWN">>;
to_alpha_3(<<"TJ">>) -> <<"TJK">>;
to_alpha_3(<<"TZ">>) -> <<"TZA">>;
to_alpha_3(<<"TH">>) -> <<"THA">>;
to_alpha_3(<<"TL">>) -> <<"TLS">>;
to_alpha_3(<<"TG">>) -> <<"TGO">>;
to_alpha_3(<<"TK">>) -> <<"TKL">>;
to_alpha_3(<<"TO">>) -> <<"TON">>;
to_alpha_3(<<"TT">>) -> <<"TTO">>;
to_alpha_3(<<"TN">>) -> <<"TUN">>;
to_alpha_3(<<"TR">>) -> <<"TUR">>;
to_alpha_3(<<"TM">>) -> <<"TKM">>;
to_alpha_3(<<"TC">>) -> <<"TCA">>;
to_alpha_3(<<"TV">>) -> <<"TUV">>;
to_alpha_3(<<"UG">>) -> <<"UGA">>;
to_alpha_3(<<"UA">>) -> <<"UKR">>;
to_alpha_3(<<"AE">>) -> <<"ARE">>;
to_alpha_3(<<"GB">>) -> <<"GBR">>;
to_alpha_3(<<"US">>) -> <<"USA">>;
to_alpha_3(<<"UM">>) -> <<"UMI">>;
to_alpha_3(<<"UY">>) -> <<"URY">>;
to_alpha_3(<<"UZ">>) -> <<"UZB">>;
to_alpha_3(<<"VU">>) -> <<"VUT">>;
to_alpha_3(<<"VE">>) -> <<"VEN">>;
to_alpha_3(<<"VN">>) -> <<"VNM">>;
to_alpha_3(<<"VI">>) -> <<"VIR">>;
to_alpha_3(<<"WF">>) -> <<"WLF">>;
to_alpha_3(<<"EH">>) -> <<"ESH">>;
to_alpha_3(<<"YE">>) -> <<"YEM">>;
to_alpha_3(<<"ZM">>) -> <<"ZMB">>;
to_alpha_3(<<"ZW">>) -> <<"ZWE">>.

to_alpha_2(<<"AFG">>) -> <<"AF">>;
to_alpha_2(<<"ALA">>) -> <<"AX">>;
to_alpha_2(<<"ALB">>) -> <<"AL">>;
to_alpha_2(<<"DZA">>) -> <<"DZ">>;
to_alpha_2(<<"ASM">>) -> <<"AS">>;
to_alpha_2(<<"AND">>) -> <<"AD">>;
to_alpha_2(<<"AGO">>) -> <<"AO">>;
to_alpha_2(<<"AIA">>) -> <<"AI">>;
to_alpha_2(<<"ATA">>) -> <<"AQ">>;
to_alpha_2(<<"ATG">>) -> <<"AG">>;
to_alpha_2(<<"ARG">>) -> <<"AR">>;
to_alpha_2(<<"ARM">>) -> <<"AM">>;
to_alpha_2(<<"ABW">>) -> <<"AW">>;
to_alpha_2(<<"AUS">>) -> <<"AU">>;
to_alpha_2(<<"AUT">>) -> <<"AT">>;
to_alpha_2(<<"AZE">>) -> <<"AZ">>;
to_alpha_2(<<"BHS">>) -> <<"BS">>;
to_alpha_2(<<"BHR">>) -> <<"BH">>;
to_alpha_2(<<"BGD">>) -> <<"BD">>;
to_alpha_2(<<"BRB">>) -> <<"BB">>;
to_alpha_2(<<"BLR">>) -> <<"BY">>;
to_alpha_2(<<"BEL">>) -> <<"BE">>;
to_alpha_2(<<"BLZ">>) -> <<"BZ">>;
to_alpha_2(<<"BEN">>) -> <<"BJ">>;
to_alpha_2(<<"BMU">>) -> <<"BM">>;
to_alpha_2(<<"BTN">>) -> <<"BT">>;
to_alpha_2(<<"BOL">>) -> <<"BO">>;
to_alpha_2(<<"BIH">>) -> <<"BA">>;
to_alpha_2(<<"BWA">>) -> <<"BW">>;
to_alpha_2(<<"BVT">>) -> <<"BV">>;
to_alpha_2(<<"BRA">>) -> <<"BR">>;
to_alpha_2(<<"VGB">>) -> <<"VG">>;
to_alpha_2(<<"IOT">>) -> <<"IO">>;
to_alpha_2(<<"BRN">>) -> <<"BN">>;
to_alpha_2(<<"BGR">>) -> <<"BG">>;
to_alpha_2(<<"BFA">>) -> <<"BF">>;
to_alpha_2(<<"BDI">>) -> <<"BI">>;
to_alpha_2(<<"KHM">>) -> <<"KH">>;
to_alpha_2(<<"CMR">>) -> <<"CM">>;
to_alpha_2(<<"CAN">>) -> <<"CA">>;
to_alpha_2(<<"CPV">>) -> <<"CV">>;
to_alpha_2(<<"CYM">>) -> <<"KY">>;
to_alpha_2(<<"CAF">>) -> <<"CF">>;
to_alpha_2(<<"TCD">>) -> <<"TD">>;
to_alpha_2(<<"CHL">>) -> <<"CL">>;
to_alpha_2(<<"CHN">>) -> <<"CN">>;
to_alpha_2(<<"HKG">>) -> <<"HK">>;
to_alpha_2(<<"MAC">>) -> <<"MO">>;
to_alpha_2(<<"CXR">>) -> <<"CX">>;
to_alpha_2(<<"CCK">>) -> <<"CC">>;
to_alpha_2(<<"COL">>) -> <<"CO">>;
to_alpha_2(<<"COM">>) -> <<"KM">>;
to_alpha_2(<<"COG">>) -> <<"CG">>;
to_alpha_2(<<"COD">>) -> <<"CD">>;
to_alpha_2(<<"COK">>) -> <<"CK">>;
to_alpha_2(<<"CRI">>) -> <<"CR">>;
to_alpha_2(<<"CIV">>) -> <<"CI">>;
to_alpha_2(<<"HRV">>) -> <<"HR">>;
to_alpha_2(<<"CUB">>) -> <<"CU">>;
to_alpha_2(<<"CYP">>) -> <<"CY">>;
to_alpha_2(<<"CZE">>) -> <<"CZ">>;
to_alpha_2(<<"DNK">>) -> <<"DK">>;
to_alpha_2(<<"DJI">>) -> <<"DJ">>;
to_alpha_2(<<"DMA">>) -> <<"DM">>;
to_alpha_2(<<"DOM">>) -> <<"DO">>;
to_alpha_2(<<"ECU">>) -> <<"EC">>;
to_alpha_2(<<"EGY">>) -> <<"EG">>;
to_alpha_2(<<"SLV">>) -> <<"SV">>;
to_alpha_2(<<"GNQ">>) -> <<"GQ">>;
to_alpha_2(<<"ERI">>) -> <<"ER">>;
to_alpha_2(<<"EST">>) -> <<"EE">>;
to_alpha_2(<<"ETH">>) -> <<"ET">>;
to_alpha_2(<<"FLK">>) -> <<"FK">>;
to_alpha_2(<<"FRO">>) -> <<"FO">>;
to_alpha_2(<<"FJI">>) -> <<"FJ">>;
to_alpha_2(<<"FIN">>) -> <<"FI">>;
to_alpha_2(<<"FRA">>) -> <<"FR">>;
to_alpha_2(<<"GUF">>) -> <<"GF">>;
to_alpha_2(<<"PYF">>) -> <<"PF">>;
to_alpha_2(<<"ATF">>) -> <<"TF">>;
to_alpha_2(<<"GAB">>) -> <<"GA">>;
to_alpha_2(<<"GMB">>) -> <<"GM">>;
to_alpha_2(<<"GEO">>) -> <<"GE">>;
to_alpha_2(<<"DEU">>) -> <<"DE">>;
to_alpha_2(<<"GHA">>) -> <<"GH">>;
to_alpha_2(<<"GIB">>) -> <<"GI">>;
to_alpha_2(<<"GRC">>) -> <<"GR">>;
to_alpha_2(<<"GRL">>) -> <<"GL">>;
to_alpha_2(<<"GRD">>) -> <<"GD">>;
to_alpha_2(<<"GLP">>) -> <<"GP">>;
to_alpha_2(<<"GUM">>) -> <<"GU">>;
to_alpha_2(<<"GTM">>) -> <<"GT">>;
to_alpha_2(<<"GGY">>) -> <<"GG">>;
to_alpha_2(<<"GIN">>) -> <<"GN">>;
to_alpha_2(<<"GNB">>) -> <<"GW">>;
to_alpha_2(<<"GUY">>) -> <<"GY">>;
to_alpha_2(<<"HTI">>) -> <<"HT">>;
to_alpha_2(<<"HMD">>) -> <<"HM">>;
to_alpha_2(<<"VAT">>) -> <<"VA">>;
to_alpha_2(<<"HND">>) -> <<"HN">>;
to_alpha_2(<<"HUN">>) -> <<"HU">>;
to_alpha_2(<<"ISL">>) -> <<"IS">>;
to_alpha_2(<<"IND">>) -> <<"IN">>;
to_alpha_2(<<"IDN">>) -> <<"ID">>;
to_alpha_2(<<"IRN">>) -> <<"IR">>;
to_alpha_2(<<"IRQ">>) -> <<"IQ">>;
to_alpha_2(<<"IRL">>) -> <<"IE">>;
to_alpha_2(<<"IMN">>) -> <<"IM">>;
to_alpha_2(<<"ISR">>) -> <<"IL">>;
to_alpha_2(<<"ITA">>) -> <<"IT">>;
to_alpha_2(<<"JAM">>) -> <<"JM">>;
to_alpha_2(<<"JPN">>) -> <<"JP">>;
to_alpha_2(<<"JEY">>) -> <<"JE">>;
to_alpha_2(<<"JOR">>) -> <<"JO">>;
to_alpha_2(<<"KAZ">>) -> <<"KZ">>;
to_alpha_2(<<"KEN">>) -> <<"KE">>;
to_alpha_2(<<"KIR">>) -> <<"KI">>;
to_alpha_2(<<"PRK">>) -> <<"KP">>;
to_alpha_2(<<"KOR">>) -> <<"KR">>;
to_alpha_2(<<"KWT">>) -> <<"KW">>;
to_alpha_2(<<"KGZ">>) -> <<"KG">>;
to_alpha_2(<<"LAO">>) -> <<"LA">>;
to_alpha_2(<<"LVA">>) -> <<"LV">>;
to_alpha_2(<<"LBN">>) -> <<"LB">>;
to_alpha_2(<<"LSO">>) -> <<"LS">>;
to_alpha_2(<<"LBR">>) -> <<"LR">>;
to_alpha_2(<<"LBY">>) -> <<"LY">>;
to_alpha_2(<<"LIE">>) -> <<"LI">>;
to_alpha_2(<<"LTU">>) -> <<"LT">>;
to_alpha_2(<<"LUX">>) -> <<"LU">>;
to_alpha_2(<<"MKD">>) -> <<"MK">>;
to_alpha_2(<<"MDG">>) -> <<"MG">>;
to_alpha_2(<<"MWI">>) -> <<"MW">>;
to_alpha_2(<<"MYS">>) -> <<"MY">>;
to_alpha_2(<<"MDV">>) -> <<"MV">>;
to_alpha_2(<<"MLI">>) -> <<"ML">>;
to_alpha_2(<<"MLT">>) -> <<"MT">>;
to_alpha_2(<<"MHL">>) -> <<"MH">>;
to_alpha_2(<<"MTQ">>) -> <<"MQ">>;
to_alpha_2(<<"MRT">>) -> <<"MR">>;
to_alpha_2(<<"MUS">>) -> <<"MU">>;
to_alpha_2(<<"MYT">>) -> <<"YT">>;
to_alpha_2(<<"MEX">>) -> <<"MX">>;
to_alpha_2(<<"FSM">>) -> <<"FM">>;
to_alpha_2(<<"MDA">>) -> <<"MD">>;
to_alpha_2(<<"MCO">>) -> <<"MC">>;
to_alpha_2(<<"MNG">>) -> <<"MN">>;
to_alpha_2(<<"MNE">>) -> <<"ME">>;
to_alpha_2(<<"MSR">>) -> <<"MS">>;
to_alpha_2(<<"MAR">>) -> <<"MA">>;
to_alpha_2(<<"MOZ">>) -> <<"MZ">>;
to_alpha_2(<<"MMR">>) -> <<"MM">>;
to_alpha_2(<<"NAM">>) -> <<"NA">>;
to_alpha_2(<<"NRU">>) -> <<"NR">>;
to_alpha_2(<<"NPL">>) -> <<"NP">>;
to_alpha_2(<<"NLD">>) -> <<"NL">>;
to_alpha_2(<<"ANT">>) -> <<"AN">>;
to_alpha_2(<<"NCL">>) -> <<"NC">>;
to_alpha_2(<<"NZL">>) -> <<"NZ">>;
to_alpha_2(<<"NIC">>) -> <<"NI">>;
to_alpha_2(<<"NER">>) -> <<"NE">>;
to_alpha_2(<<"NGA">>) -> <<"NG">>;
to_alpha_2(<<"NIU">>) -> <<"NU">>;
to_alpha_2(<<"NFK">>) -> <<"NF">>;
to_alpha_2(<<"MNP">>) -> <<"MP">>;
to_alpha_2(<<"NOR">>) -> <<"NO">>;
to_alpha_2(<<"OMN">>) -> <<"OM">>;
to_alpha_2(<<"PAK">>) -> <<"PK">>;
to_alpha_2(<<"PLW">>) -> <<"PW">>;
to_alpha_2(<<"PSE">>) -> <<"PS">>;
to_alpha_2(<<"PAN">>) -> <<"PA">>;
to_alpha_2(<<"PNG">>) -> <<"PG">>;
to_alpha_2(<<"PRY">>) -> <<"PY">>;
to_alpha_2(<<"PER">>) -> <<"PE">>;
to_alpha_2(<<"PHL">>) -> <<"PH">>;
to_alpha_2(<<"PCN">>) -> <<"PN">>;
to_alpha_2(<<"POL">>) -> <<"PL">>;
to_alpha_2(<<"PRT">>) -> <<"PT">>;
to_alpha_2(<<"PRI">>) -> <<"PR">>;
to_alpha_2(<<"QAT">>) -> <<"QA">>;
to_alpha_2(<<"REU">>) -> <<"RE">>;
to_alpha_2(<<"ROU">>) -> <<"RO">>;
to_alpha_2(<<"RUS">>) -> <<"RU">>;
to_alpha_2(<<"RWA">>) -> <<"RW">>;
to_alpha_2(<<"BLM">>) -> <<"BL">>;
to_alpha_2(<<"SHN">>) -> <<"SH">>;
to_alpha_2(<<"KNA">>) -> <<"KN">>;
to_alpha_2(<<"LCA">>) -> <<"LC">>;
to_alpha_2(<<"MAF">>) -> <<"MF">>;
to_alpha_2(<<"SPM">>) -> <<"PM">>;
to_alpha_2(<<"VCT">>) -> <<"VC">>;
to_alpha_2(<<"WSM">>) -> <<"WS">>;
to_alpha_2(<<"SMR">>) -> <<"SM">>;
to_alpha_2(<<"STP">>) -> <<"ST">>;
to_alpha_2(<<"SAU">>) -> <<"SA">>;
to_alpha_2(<<"SEN">>) -> <<"SN">>;
to_alpha_2(<<"SRB">>) -> <<"RS">>;
to_alpha_2(<<"SYC">>) -> <<"SC">>;
to_alpha_2(<<"SLE">>) -> <<"SL">>;
to_alpha_2(<<"SGP">>) -> <<"SG">>;
to_alpha_2(<<"SVK">>) -> <<"SK">>;
to_alpha_2(<<"SVN">>) -> <<"SI">>;
to_alpha_2(<<"SLB">>) -> <<"SB">>;
to_alpha_2(<<"SOM">>) -> <<"SO">>;
to_alpha_2(<<"ZAF">>) -> <<"ZA">>;
to_alpha_2(<<"SGS">>) -> <<"GS">>;
to_alpha_2(<<"SSD">>) -> <<"SS">>;
to_alpha_2(<<"ESP">>) -> <<"ES">>;
to_alpha_2(<<"LKA">>) -> <<"LK">>;
to_alpha_2(<<"SDN">>) -> <<"SD">>;
to_alpha_2(<<"SUR">>) -> <<"SR">>;
to_alpha_2(<<"SJM">>) -> <<"SJ">>;
to_alpha_2(<<"SWZ">>) -> <<"SZ">>;
to_alpha_2(<<"SWE">>) -> <<"SE">>;
to_alpha_2(<<"CHE">>) -> <<"CH">>;
to_alpha_2(<<"SYR">>) -> <<"SY">>;
to_alpha_2(<<"TWN">>) -> <<"TW">>;
to_alpha_2(<<"TJK">>) -> <<"TJ">>;
to_alpha_2(<<"TZA">>) -> <<"TZ">>;
to_alpha_2(<<"THA">>) -> <<"TH">>;
to_alpha_2(<<"TLS">>) -> <<"TL">>;
to_alpha_2(<<"TGO">>) -> <<"TG">>;
to_alpha_2(<<"TKL">>) -> <<"TK">>;
to_alpha_2(<<"TON">>) -> <<"TO">>;
to_alpha_2(<<"TTO">>) -> <<"TT">>;
to_alpha_2(<<"TUN">>) -> <<"TN">>;
to_alpha_2(<<"TUR">>) -> <<"TR">>;
to_alpha_2(<<"TKM">>) -> <<"TM">>;
to_alpha_2(<<"TCA">>) -> <<"TC">>;
to_alpha_2(<<"TUV">>) -> <<"TV">>;
to_alpha_2(<<"UGA">>) -> <<"UG">>;
to_alpha_2(<<"UKR">>) -> <<"UA">>;
to_alpha_2(<<"ARE">>) -> <<"AE">>;
to_alpha_2(<<"GBR">>) -> <<"GB">>;
to_alpha_2(<<"USA">>) -> <<"US">>;
to_alpha_2(<<"UMI">>) -> <<"UM">>;
to_alpha_2(<<"URY">>) -> <<"UY">>;
to_alpha_2(<<"UZB">>) -> <<"UZ">>;
to_alpha_2(<<"VUT">>) -> <<"VU">>;
to_alpha_2(<<"VEN">>) -> <<"VE">>;
to_alpha_2(<<"VNM">>) -> <<"VN">>;
to_alpha_2(<<"VIR">>) -> <<"VI">>;
to_alpha_2(<<"WLF">>) -> <<"WF">>;
to_alpha_2(<<"ESH">>) -> <<"EH">>;
to_alpha_2(<<"YEM">>) -> <<"YE">>;
to_alpha_2(<<"ZMB">>) -> <<"ZM">>;
to_alpha_2(<<"ZWE">>) -> <<"ZW">>.

alpha_2_to_name(<<"AF">>) -> <<"Afghanistan">>;
alpha_2_to_name(<<"AX">>) -> <<"Aland Islands">>;
alpha_2_to_name(<<"AL">>) -> <<"Albania">>;
alpha_2_to_name(<<"DZ">>) -> <<"Algeria">>;
alpha_2_to_name(<<"AS">>) -> <<"American Samoa">>;
alpha_2_to_name(<<"AD">>) -> <<"Andorra">>;
alpha_2_to_name(<<"AO">>) -> <<"Angola">>;
alpha_2_to_name(<<"AI">>) -> <<"Anguilla">>;
alpha_2_to_name(<<"AQ">>) -> <<"Antarctica">>;
alpha_2_to_name(<<"AG">>) -> <<"Antigua and Barbuda">>;
alpha_2_to_name(<<"AR">>) -> <<"Argentina">>;
alpha_2_to_name(<<"AM">>) -> <<"Armenia">>;
alpha_2_to_name(<<"AW">>) -> <<"Aruba">>;
alpha_2_to_name(<<"AU">>) -> <<"Australia">>;
alpha_2_to_name(<<"AT">>) -> <<"Austria">>;
alpha_2_to_name(<<"AZ">>) -> <<"Azerbaijan">>;
alpha_2_to_name(<<"BS">>) -> <<"Bahamas">>;
alpha_2_to_name(<<"BH">>) -> <<"Bahrain">>;
alpha_2_to_name(<<"BD">>) -> <<"Bangladesh">>;
alpha_2_to_name(<<"BB">>) -> <<"Barbados">>;
alpha_2_to_name(<<"BY">>) -> <<"Belarus">>;
alpha_2_to_name(<<"BE">>) -> <<"Belgium">>;
alpha_2_to_name(<<"BZ">>) -> <<"Belize">>;
alpha_2_to_name(<<"BJ">>) -> <<"Benin">>;
alpha_2_to_name(<<"BM">>) -> <<"Bermuda">>;
alpha_2_to_name(<<"BT">>) -> <<"Bhutan">>;
alpha_2_to_name(<<"BO">>) -> <<"Bolivia">>;
alpha_2_to_name(<<"BA">>) -> <<"Bosnia and Herzegovina">>;
alpha_2_to_name(<<"BW">>) -> <<"Botswana">>;
alpha_2_to_name(<<"BV">>) -> <<"Bouvet Island">>;
alpha_2_to_name(<<"BR">>) -> <<"Brazil">>;
alpha_2_to_name(<<"VG">>) -> <<"British Virgin Islands">>;
alpha_2_to_name(<<"IO">>) -> <<"British Indian Ocean Territory">>;
alpha_2_to_name(<<"BN">>) -> <<"Brunei Darussalam">>;
alpha_2_to_name(<<"BG">>) -> <<"Bulgaria">>;
alpha_2_to_name(<<"BF">>) -> <<"Burkina Faso">>;
alpha_2_to_name(<<"BI">>) -> <<"Burundi">>;
alpha_2_to_name(<<"KH">>) -> <<"Cambodia">>;
alpha_2_to_name(<<"CM">>) -> <<"Cameroon">>;
alpha_2_to_name(<<"CA">>) -> <<"Canada">>;
alpha_2_to_name(<<"CV">>) -> <<"Cape Verde">>;
alpha_2_to_name(<<"KY">>) -> <<"Cayman Islands">>;
alpha_2_to_name(<<"CF">>) -> <<"Central African Republic">>;
alpha_2_to_name(<<"TD">>) -> <<"Chad">>;
alpha_2_to_name(<<"CL">>) -> <<"Chile">>;
alpha_2_to_name(<<"CN">>) -> <<"China">>;
alpha_2_to_name(<<"HK">>) -> <<"Hong Kong, Special Administrative Region of China">>;
alpha_2_to_name(<<"MO">>) -> <<"Macao, Special Administrative Region of China">>;
alpha_2_to_name(<<"CX">>) -> <<"Christmas Island">>;
alpha_2_to_name(<<"CC">>) -> <<"Cocos (Keeling) Islands">>;
alpha_2_to_name(<<"CO">>) -> <<"Colombia">>;
alpha_2_to_name(<<"KM">>) -> <<"Comoros">>;
alpha_2_to_name(<<"CG">>) -> <<"Congo (Brazzaville)">>;
alpha_2_to_name(<<"CD">>) -> <<"Democratic Republic of the Congo">>;
alpha_2_to_name(<<"CK">>) -> <<"Cook Islands">>;
alpha_2_to_name(<<"CR">>) -> <<"Costa Rica">>;
alpha_2_to_name(<<"CI">>) -> <<"Côte d'Ivoire">>;
alpha_2_to_name(<<"HR">>) -> <<"Croatia">>;
alpha_2_to_name(<<"CU">>) -> <<"Cuba">>;
alpha_2_to_name(<<"CY">>) -> <<"Cyprus">>;
alpha_2_to_name(<<"CZ">>) -> <<"Czech Republic">>;
alpha_2_to_name(<<"DK">>) -> <<"Denmark">>;
alpha_2_to_name(<<"DJ">>) -> <<"Djibouti">>;
alpha_2_to_name(<<"DM">>) -> <<"Dominica">>;
alpha_2_to_name(<<"DO">>) -> <<"Dominican Republic">>;
alpha_2_to_name(<<"EC">>) -> <<"Ecuador">>;
alpha_2_to_name(<<"EG">>) -> <<"Egypt">>;
alpha_2_to_name(<<"SV">>) -> <<"El Salvador">>;
alpha_2_to_name(<<"GQ">>) -> <<"Equatorial Guinea">>;
alpha_2_to_name(<<"ER">>) -> <<"Eritrea">>;
alpha_2_to_name(<<"EE">>) -> <<"Estonia">>;
alpha_2_to_name(<<"ET">>) -> <<"Ethiopia">>;
alpha_2_to_name(<<"FK">>) -> <<"Falkland Islands (Malvinas)">>;
alpha_2_to_name(<<"FO">>) -> <<"Faroe Islands">>;
alpha_2_to_name(<<"FJ">>) -> <<"Fiji">>;
alpha_2_to_name(<<"FI">>) -> <<"Finland">>;
alpha_2_to_name(<<"FR">>) -> <<"France">>;
alpha_2_to_name(<<"GF">>) -> <<"French Guiana">>;
alpha_2_to_name(<<"PF">>) -> <<"French Polynesia">>;
alpha_2_to_name(<<"TF">>) -> <<"French Southern Territories">>;
alpha_2_to_name(<<"GA">>) -> <<"Gabon">>;
alpha_2_to_name(<<"GM">>) -> <<"Gambia">>;
alpha_2_to_name(<<"GE">>) -> <<"Georgia">>;
alpha_2_to_name(<<"DE">>) -> <<"Germany">>;
alpha_2_to_name(<<"GH">>) -> <<"Ghana">>;
alpha_2_to_name(<<"GI">>) -> <<"Gibraltar">>;
alpha_2_to_name(<<"GR">>) -> <<"Greece">>;
alpha_2_to_name(<<"GL">>) -> <<"Greenland">>;
alpha_2_to_name(<<"GD">>) -> <<"Grenada">>;
alpha_2_to_name(<<"GP">>) -> <<"Guadeloupe">>;
alpha_2_to_name(<<"GU">>) -> <<"Guam">>;
alpha_2_to_name(<<"GT">>) -> <<"Guatemala">>;
alpha_2_to_name(<<"GG">>) -> <<"Guernsey">>;
alpha_2_to_name(<<"GN">>) -> <<"Guinea">>;
alpha_2_to_name(<<"GW">>) -> <<"Guinea-Bissau">>;
alpha_2_to_name(<<"GY">>) -> <<"Guyana">>;
alpha_2_to_name(<<"HT">>) -> <<"Haiti">>;
alpha_2_to_name(<<"HM">>) -> <<"Heard Island and Mcdonald Islands">>;
alpha_2_to_name(<<"VA">>) -> <<"Holy See (Vatican City State)">>;
alpha_2_to_name(<<"HN">>) -> <<"Honduras">>;
alpha_2_to_name(<<"HU">>) -> <<"Hungary">>;
alpha_2_to_name(<<"IS">>) -> <<"Iceland">>;
alpha_2_to_name(<<"IN">>) -> <<"India">>;
alpha_2_to_name(<<"ID">>) -> <<"Indonesia">>;
alpha_2_to_name(<<"IR">>) -> <<"Iran">>;
alpha_2_to_name(<<"IQ">>) -> <<"Iraq">>;
alpha_2_to_name(<<"IE">>) -> <<"Ireland">>;
alpha_2_to_name(<<"IM">>) -> <<"Isle of Man">>;
alpha_2_to_name(<<"IL">>) -> <<"Israel">>;
alpha_2_to_name(<<"IT">>) -> <<"Italy">>;
alpha_2_to_name(<<"JM">>) -> <<"Jamaica">>;
alpha_2_to_name(<<"JP">>) -> <<"Japan">>;
alpha_2_to_name(<<"JE">>) -> <<"Jersey">>;
alpha_2_to_name(<<"JO">>) -> <<"Jordan">>;
alpha_2_to_name(<<"KZ">>) -> <<"Kazakhstan">>;
alpha_2_to_name(<<"KE">>) -> <<"Kenya">>;
alpha_2_to_name(<<"KI">>) -> <<"Kiribati">>;
alpha_2_to_name(<<"KP">>) -> <<"Democratic People's Republic of Korea">>;
alpha_2_to_name(<<"KR">>) -> <<"Republic of Korea">>;
alpha_2_to_name(<<"KW">>) -> <<"Kuwait">>;
alpha_2_to_name(<<"KG">>) -> <<"Kyrgyzstan">>;
alpha_2_to_name(<<"LA">>) -> <<"Lao PDR">>;
alpha_2_to_name(<<"LV">>) -> <<"Latvia">>;
alpha_2_to_name(<<"LB">>) -> <<"Lebanon">>;
alpha_2_to_name(<<"LS">>) -> <<"Lesotho">>;
alpha_2_to_name(<<"LR">>) -> <<"Liberia">>;
alpha_2_to_name(<<"LY">>) -> <<"Libya">>;
alpha_2_to_name(<<"LI">>) -> <<"Liechtenstein">>;
alpha_2_to_name(<<"LT">>) -> <<"Lithuania">>;
alpha_2_to_name(<<"LU">>) -> <<"Luxembourg">>;
alpha_2_to_name(<<"MK">>) -> <<"Republic of Macedonia">>;
alpha_2_to_name(<<"MG">>) -> <<"Madagascar">>;
alpha_2_to_name(<<"MW">>) -> <<"Malawi">>;
alpha_2_to_name(<<"MY">>) -> <<"Malaysia">>;
alpha_2_to_name(<<"MV">>) -> <<"Maldives">>;
alpha_2_to_name(<<"ML">>) -> <<"Mali">>;
alpha_2_to_name(<<"MT">>) -> <<"Malta">>;
alpha_2_to_name(<<"MH">>) -> <<"Marshall Islands">>;
alpha_2_to_name(<<"MQ">>) -> <<"Martinique">>;
alpha_2_to_name(<<"MR">>) -> <<"Mauritania">>;
alpha_2_to_name(<<"MU">>) -> <<"Mauritius">>;
alpha_2_to_name(<<"YT">>) -> <<"Mayotte">>;
alpha_2_to_name(<<"MX">>) -> <<"Mexico">>;
alpha_2_to_name(<<"FM">>) -> <<"Federated States of Micronesia">>;
alpha_2_to_name(<<"MD">>) -> <<"Moldova">>;
alpha_2_to_name(<<"MC">>) -> <<"Monaco">>;
alpha_2_to_name(<<"MN">>) -> <<"Mongolia">>;
alpha_2_to_name(<<"ME">>) -> <<"Montenegro">>;
alpha_2_to_name(<<"MS">>) -> <<"Montserrat">>;
alpha_2_to_name(<<"MA">>) -> <<"Morocco">>;
alpha_2_to_name(<<"MZ">>) -> <<"Mozambique">>;
alpha_2_to_name(<<"MM">>) -> <<"Myanmar">>;
alpha_2_to_name(<<"NA">>) -> <<"Namibia">>;
alpha_2_to_name(<<"NR">>) -> <<"Nauru">>;
alpha_2_to_name(<<"NP">>) -> <<"Nepal">>;
alpha_2_to_name(<<"NL">>) -> <<"Netherlands">>;
alpha_2_to_name(<<"AN">>) -> <<"Netherlands Antilles">>;
alpha_2_to_name(<<"NC">>) -> <<"New Caledonia">>;
alpha_2_to_name(<<"NZ">>) -> <<"New Zealand">>;
alpha_2_to_name(<<"NI">>) -> <<"Nicaragua">>;
alpha_2_to_name(<<"NE">>) -> <<"Niger">>;
alpha_2_to_name(<<"NG">>) -> <<"Nigeria">>;
alpha_2_to_name(<<"NU">>) -> <<"Niue">>;
alpha_2_to_name(<<"NF">>) -> <<"Norfolk Island">>;
alpha_2_to_name(<<"MP">>) -> <<"Northern Mariana Islands">>;
alpha_2_to_name(<<"NO">>) -> <<"Norway">>;
alpha_2_to_name(<<"OM">>) -> <<"Oman">>;
alpha_2_to_name(<<"PK">>) -> <<"Pakistan">>;
alpha_2_to_name(<<"PW">>) -> <<"Palau">>;
alpha_2_to_name(<<"PS">>) -> <<"Palestine">>;
alpha_2_to_name(<<"PA">>) -> <<"Panama">>;
alpha_2_to_name(<<"PG">>) -> <<"Papua New Guinea">>;
alpha_2_to_name(<<"PY">>) -> <<"Paraguay">>;
alpha_2_to_name(<<"PE">>) -> <<"Peru">>;
alpha_2_to_name(<<"PH">>) -> <<"Philippines">>;
alpha_2_to_name(<<"PN">>) -> <<"Pitcairn">>;
alpha_2_to_name(<<"PL">>) -> <<"Poland">>;
alpha_2_to_name(<<"PT">>) -> <<"Portugal">>;
alpha_2_to_name(<<"PR">>) -> <<"Puerto Rico">>;
alpha_2_to_name(<<"QA">>) -> <<"Qatar">>;
alpha_2_to_name(<<"RE">>) -> <<"Réunion">>;
alpha_2_to_name(<<"RO">>) -> <<"Romania">>;
alpha_2_to_name(<<"RU">>) -> <<"Russian Federation">>;
alpha_2_to_name(<<"RW">>) -> <<"Rwanda">>;
alpha_2_to_name(<<"BL">>) -> <<"Saint-Barthélemy">>;
alpha_2_to_name(<<"SH">>) -> <<"Saint Helena">>;
alpha_2_to_name(<<"KN">>) -> <<"Saint Kitts and Nevis">>;
alpha_2_to_name(<<"LC">>) -> <<"Saint Lucia">>;
alpha_2_to_name(<<"MF">>) -> <<"Saint-Martin (French part)">>;
alpha_2_to_name(<<"PM">>) -> <<"Saint Pierre and Miquelon">>;
alpha_2_to_name(<<"VC">>) -> <<"Saint Vincent and Grenadines">>;
alpha_2_to_name(<<"WS">>) -> <<"Samoa">>;
alpha_2_to_name(<<"SM">>) -> <<"San Marino">>;
alpha_2_to_name(<<"ST">>) -> <<"Sao Tome and Principe">>;
alpha_2_to_name(<<"SA">>) -> <<"Saudi Arabia">>;
alpha_2_to_name(<<"SN">>) -> <<"Senegal">>;
alpha_2_to_name(<<"RS">>) -> <<"Serbia">>;
alpha_2_to_name(<<"SC">>) -> <<"Seychelles">>;
alpha_2_to_name(<<"SL">>) -> <<"Sierra Leone">>;
alpha_2_to_name(<<"SG">>) -> <<"Singapore">>;
alpha_2_to_name(<<"SK">>) -> <<"Slovakia">>;
alpha_2_to_name(<<"SI">>) -> <<"Slovenia">>;
alpha_2_to_name(<<"SB">>) -> <<"Solomon Islands">>;
alpha_2_to_name(<<"SO">>) -> <<"Somalia">>;
alpha_2_to_name(<<"ZA">>) -> <<"South Africa">>;
alpha_2_to_name(<<"GS">>) -> <<"South Georgia and the South Sandwich Islands">>;
alpha_2_to_name(<<"SS">>) -> <<"South Sudan">>;
alpha_2_to_name(<<"ES">>) -> <<"Spain">>;
alpha_2_to_name(<<"LK">>) -> <<"Sri Lanka">>;
alpha_2_to_name(<<"SD">>) -> <<"Sudan">>;
alpha_2_to_name(<<"SR">>) -> <<"Suriname *">>;
alpha_2_to_name(<<"SJ">>) -> <<"Svalbard and Jan Mayen Islands">>;
alpha_2_to_name(<<"SZ">>) -> <<"Swaziland">>;
alpha_2_to_name(<<"SE">>) -> <<"Sweden">>;
alpha_2_to_name(<<"CH">>) -> <<"Switzerland">>;
alpha_2_to_name(<<"SY">>) -> <<"Syrian Arab Republic (Syria)">>;
alpha_2_to_name(<<"TW">>) -> <<"Taiwan, Republic of China">>;
alpha_2_to_name(<<"TJ">>) -> <<"Tajikistan">>;
alpha_2_to_name(<<"TZ">>) -> <<"Tanzania">>;
alpha_2_to_name(<<"TH">>) -> <<"Thailand">>;
alpha_2_to_name(<<"TL">>) -> <<"Timor-Leste">>;
alpha_2_to_name(<<"TG">>) -> <<"Togo">>;
alpha_2_to_name(<<"TK">>) -> <<"Tokelau">>;
alpha_2_to_name(<<"TO">>) -> <<"Tonga">>;
alpha_2_to_name(<<"TT">>) -> <<"Trinidad and Tobago">>;
alpha_2_to_name(<<"TN">>) -> <<"Tunisia">>;
alpha_2_to_name(<<"TR">>) -> <<"Turkey">>;
alpha_2_to_name(<<"TM">>) -> <<"Turkmenistan">>;
alpha_2_to_name(<<"TC">>) -> <<"Turks and Caicos Islands">>;
alpha_2_to_name(<<"TV">>) -> <<"Tuvalu">>;
alpha_2_to_name(<<"UG">>) -> <<"Uganda">>;
alpha_2_to_name(<<"UA">>) -> <<"Ukraine">>;
alpha_2_to_name(<<"AE">>) -> <<"United Arab Emirates">>;
alpha_2_to_name(<<"GB">>) -> <<"United Kingdom">>;
alpha_2_to_name(<<"US">>) -> <<"United States of America">>;
alpha_2_to_name(<<"UM">>) -> <<"United States Minor Outlying Islands">>;
alpha_2_to_name(<<"UY">>) -> <<"Uruguay">>;
alpha_2_to_name(<<"UZ">>) -> <<"Uzbekistan">>;
alpha_2_to_name(<<"VU">>) -> <<"Vanuatu">>;
alpha_2_to_name(<<"VE">>) -> <<"Venezuela (Bolivarian Republic of)">>;
alpha_2_to_name(<<"VN">>) -> <<"Viet Nam">>;
alpha_2_to_name(<<"VI">>) -> <<"US Virgin Islands">>;
alpha_2_to_name(<<"WF">>) -> <<"Wallis and Futuna Islands">>;
alpha_2_to_name(<<"EH">>) -> <<"Western Sahara">>;
alpha_2_to_name(<<"YE">>) -> <<"Yemen">>;
alpha_2_to_name(<<"ZM">>) -> <<"Zambia">>;
alpha_2_to_name(<<"ZW">>) -> <<"Zimbabwe">>.

alpha_3_to_name(<<"AFG">>) -> <<"Afghanistan">>;
alpha_3_to_name(<<"ALA">>) -> <<"Aland Islands">>;
alpha_3_to_name(<<"ALB">>) -> <<"Albania">>;
alpha_3_to_name(<<"DZA">>) -> <<"Algeria">>;
alpha_3_to_name(<<"ASM">>) -> <<"American Samoa">>;
alpha_3_to_name(<<"AND">>) -> <<"Andorra">>;
alpha_3_to_name(<<"AGO">>) -> <<"Angola">>;
alpha_3_to_name(<<"AIA">>) -> <<"Anguilla">>;
alpha_3_to_name(<<"ATA">>) -> <<"Antarctica">>;
alpha_3_to_name(<<"ATG">>) -> <<"Antigua and Barbuda">>;
alpha_3_to_name(<<"ARG">>) -> <<"Argentina">>;
alpha_3_to_name(<<"ARM">>) -> <<"Armenia">>;
alpha_3_to_name(<<"ABW">>) -> <<"Aruba">>;
alpha_3_to_name(<<"AUS">>) -> <<"Australia">>;
alpha_3_to_name(<<"AUT">>) -> <<"Austria">>;
alpha_3_to_name(<<"AZE">>) -> <<"Azerbaijan">>;
alpha_3_to_name(<<"BHS">>) -> <<"Bahamas">>;
alpha_3_to_name(<<"BHR">>) -> <<"Bahrain">>;
alpha_3_to_name(<<"BGD">>) -> <<"Bangladesh">>;
alpha_3_to_name(<<"BRB">>) -> <<"Barbados">>;
alpha_3_to_name(<<"BLR">>) -> <<"Belarus">>;
alpha_3_to_name(<<"BEL">>) -> <<"Belgium">>;
alpha_3_to_name(<<"BLZ">>) -> <<"Belize">>;
alpha_3_to_name(<<"BEN">>) -> <<"Benin">>;
alpha_3_to_name(<<"BMU">>) -> <<"Bermuda">>;
alpha_3_to_name(<<"BTN">>) -> <<"Bhutan">>;
alpha_3_to_name(<<"BOL">>) -> <<"Bolivia">>;
alpha_3_to_name(<<"BIH">>) -> <<"Bosnia and Herzegovina">>;
alpha_3_to_name(<<"BWA">>) -> <<"Botswana">>;
alpha_3_to_name(<<"BVT">>) -> <<"Bouvet Island">>;
alpha_3_to_name(<<"BRA">>) -> <<"Brazil">>;
alpha_3_to_name(<<"VGB">>) -> <<"British Virgin Islands">>;
alpha_3_to_name(<<"IOT">>) -> <<"British Indian Ocean Territory">>;
alpha_3_to_name(<<"BRN">>) -> <<"Brunei Darussalam">>;
alpha_3_to_name(<<"BGR">>) -> <<"Bulgaria">>;
alpha_3_to_name(<<"BFA">>) -> <<"Burkina Faso">>;
alpha_3_to_name(<<"BDI">>) -> <<"Burundi">>;
alpha_3_to_name(<<"KHM">>) -> <<"Cambodia">>;
alpha_3_to_name(<<"CMR">>) -> <<"Cameroon">>;
alpha_3_to_name(<<"CAN">>) -> <<"Canada">>;
alpha_3_to_name(<<"CPV">>) -> <<"Cape Verde">>;
alpha_3_to_name(<<"CYM">>) -> <<"Cayman Islands">>;
alpha_3_to_name(<<"CAF">>) -> <<"Central African Republic">>;
alpha_3_to_name(<<"TCD">>) -> <<"Chad">>;
alpha_3_to_name(<<"CHL">>) -> <<"Chile">>;
alpha_3_to_name(<<"CHN">>) -> <<"China">>;
alpha_3_to_name(<<"HKG">>) -> <<"Hong Kong, Special Administrative Region of China">>;
alpha_3_to_name(<<"MAC">>) -> <<"Macao, Special Administrative Region of China">>;
alpha_3_to_name(<<"CXR">>) -> <<"Christmas Island">>;
alpha_3_to_name(<<"CCK">>) -> <<"Cocos (Keeling) Islands">>;
alpha_3_to_name(<<"COL">>) -> <<"Colombia">>;
alpha_3_to_name(<<"COM">>) -> <<"Comoros">>;
alpha_3_to_name(<<"COG">>) -> <<"Congo (Brazzaville)">>;
alpha_3_to_name(<<"COD">>) -> <<"Democratic Republic of the Congo">>;
alpha_3_to_name(<<"COK">>) -> <<"Cook Islands">>;
alpha_3_to_name(<<"CRI">>) -> <<"Costa Rica">>;
alpha_3_to_name(<<"CIV">>) -> <<"Côte d'Ivoire">>;
alpha_3_to_name(<<"HRV">>) -> <<"Croatia">>;
alpha_3_to_name(<<"CUB">>) -> <<"Cuba">>;
alpha_3_to_name(<<"CYP">>) -> <<"Cyprus">>;
alpha_3_to_name(<<"CZE">>) -> <<"Czech Republic">>;
alpha_3_to_name(<<"DNK">>) -> <<"Denmark">>;
alpha_3_to_name(<<"DJI">>) -> <<"Djibouti">>;
alpha_3_to_name(<<"DMA">>) -> <<"Dominica">>;
alpha_3_to_name(<<"DOM">>) -> <<"Dominican Republic">>;
alpha_3_to_name(<<"ECU">>) -> <<"Ecuador">>;
alpha_3_to_name(<<"EGY">>) -> <<"Egypt">>;
alpha_3_to_name(<<"SLV">>) -> <<"El Salvador">>;
alpha_3_to_name(<<"GNQ">>) -> <<"Equatorial Guinea">>;
alpha_3_to_name(<<"ERI">>) -> <<"Eritrea">>;
alpha_3_to_name(<<"EST">>) -> <<"Estonia">>;
alpha_3_to_name(<<"ETH">>) -> <<"Ethiopia">>;
alpha_3_to_name(<<"FLK">>) -> <<"Falkland Islands (Malvinas)">>;
alpha_3_to_name(<<"FRO">>) -> <<"Faroe Islands">>;
alpha_3_to_name(<<"FJI">>) -> <<"Fiji">>;
alpha_3_to_name(<<"FIN">>) -> <<"Finland">>;
alpha_3_to_name(<<"FRA">>) -> <<"France">>;
alpha_3_to_name(<<"GUF">>) -> <<"French Guiana">>;
alpha_3_to_name(<<"PYF">>) -> <<"French Polynesia">>;
alpha_3_to_name(<<"ATF">>) -> <<"French Southern Territories">>;
alpha_3_to_name(<<"GAB">>) -> <<"Gabon">>;
alpha_3_to_name(<<"GMB">>) -> <<"Gambia">>;
alpha_3_to_name(<<"GEO">>) -> <<"Georgia">>;
alpha_3_to_name(<<"DEU">>) -> <<"Germany">>;
alpha_3_to_name(<<"GHA">>) -> <<"Ghana">>;
alpha_3_to_name(<<"GIB">>) -> <<"Gibraltar">>;
alpha_3_to_name(<<"GRC">>) -> <<"Greece">>;
alpha_3_to_name(<<"GRL">>) -> <<"Greenland">>;
alpha_3_to_name(<<"GRD">>) -> <<"Grenada">>;
alpha_3_to_name(<<"GLP">>) -> <<"Guadeloupe">>;
alpha_3_to_name(<<"GUM">>) -> <<"Guam">>;
alpha_3_to_name(<<"GTM">>) -> <<"Guatemala">>;
alpha_3_to_name(<<"GGY">>) -> <<"Guernsey">>;
alpha_3_to_name(<<"GIN">>) -> <<"Guinea">>;
alpha_3_to_name(<<"GNB">>) -> <<"Guinea-Bissau">>;
alpha_3_to_name(<<"GUY">>) -> <<"Guyana">>;
alpha_3_to_name(<<"HTI">>) -> <<"Haiti">>;
alpha_3_to_name(<<"HMD">>) -> <<"Heard Island and Mcdonald Islands">>;
alpha_3_to_name(<<"VAT">>) -> <<"Holy See (Vatican City State)">>;
alpha_3_to_name(<<"HND">>) -> <<"Honduras">>;
alpha_3_to_name(<<"HUN">>) -> <<"Hungary">>;
alpha_3_to_name(<<"ISL">>) -> <<"Iceland">>;
alpha_3_to_name(<<"IND">>) -> <<"India">>;
alpha_3_to_name(<<"IDN">>) -> <<"Indonesia">>;
alpha_3_to_name(<<"IRN">>) -> <<"Iran">>;
alpha_3_to_name(<<"IRQ">>) -> <<"Iraq">>;
alpha_3_to_name(<<"IRL">>) -> <<"Ireland">>;
alpha_3_to_name(<<"IMN">>) -> <<"Isle of Man">>;
alpha_3_to_name(<<"ISR">>) -> <<"Israel">>;
alpha_3_to_name(<<"ITA">>) -> <<"Italy">>;
alpha_3_to_name(<<"JAM">>) -> <<"Jamaica">>;
alpha_3_to_name(<<"JPN">>) -> <<"Japan">>;
alpha_3_to_name(<<"JEY">>) -> <<"Jersey">>;
alpha_3_to_name(<<"JOR">>) -> <<"Jordan">>;
alpha_3_to_name(<<"KAZ">>) -> <<"Kazakhstan">>;
alpha_3_to_name(<<"KEN">>) -> <<"Kenya">>;
alpha_3_to_name(<<"KIR">>) -> <<"Kiribati">>;
alpha_3_to_name(<<"PRK">>) -> <<"Democratic People's Republic of Korea">>;
alpha_3_to_name(<<"KOR">>) -> <<"Republic of Korea">>;
alpha_3_to_name(<<"KWT">>) -> <<"Kuwait">>;
alpha_3_to_name(<<"KGZ">>) -> <<"Kyrgyzstan">>;
alpha_3_to_name(<<"LAO">>) -> <<"Lao PDR">>;
alpha_3_to_name(<<"LVA">>) -> <<"Latvia">>;
alpha_3_to_name(<<"LBN">>) -> <<"Lebanon">>;
alpha_3_to_name(<<"LSO">>) -> <<"Lesotho">>;
alpha_3_to_name(<<"LBR">>) -> <<"Liberia">>;
alpha_3_to_name(<<"LBY">>) -> <<"Libya">>;
alpha_3_to_name(<<"LIE">>) -> <<"Liechtenstein">>;
alpha_3_to_name(<<"LTU">>) -> <<"Lithuania">>;
alpha_3_to_name(<<"LUX">>) -> <<"Luxembourg">>;
alpha_3_to_name(<<"MKD">>) -> <<"Republic of Macedonia">>;
alpha_3_to_name(<<"MDG">>) -> <<"Madagascar">>;
alpha_3_to_name(<<"MWI">>) -> <<"Malawi">>;
alpha_3_to_name(<<"MYS">>) -> <<"Malaysia">>;
alpha_3_to_name(<<"MDV">>) -> <<"Maldives">>;
alpha_3_to_name(<<"MLI">>) -> <<"Mali">>;
alpha_3_to_name(<<"MLT">>) -> <<"Malta">>;
alpha_3_to_name(<<"MHL">>) -> <<"Marshall Islands">>;
alpha_3_to_name(<<"MTQ">>) -> <<"Martinique">>;
alpha_3_to_name(<<"MRT">>) -> <<"Mauritania">>;
alpha_3_to_name(<<"MUS">>) -> <<"Mauritius">>;
alpha_3_to_name(<<"MYT">>) -> <<"Mayotte">>;
alpha_3_to_name(<<"MEX">>) -> <<"Mexico">>;
alpha_3_to_name(<<"FSM">>) -> <<"Federated States of Micronesia">>;
alpha_3_to_name(<<"MDA">>) -> <<"Moldova">>;
alpha_3_to_name(<<"MCO">>) -> <<"Monaco">>;
alpha_3_to_name(<<"MNG">>) -> <<"Mongolia">>;
alpha_3_to_name(<<"MNE">>) -> <<"Montenegro">>;
alpha_3_to_name(<<"MSR">>) -> <<"Montserrat">>;
alpha_3_to_name(<<"MAR">>) -> <<"Morocco">>;
alpha_3_to_name(<<"MOZ">>) -> <<"Mozambique">>;
alpha_3_to_name(<<"MMR">>) -> <<"Myanmar">>;
alpha_3_to_name(<<"NAM">>) -> <<"Namibia">>;
alpha_3_to_name(<<"NRU">>) -> <<"Nauru">>;
alpha_3_to_name(<<"NPL">>) -> <<"Nepal">>;
alpha_3_to_name(<<"NLD">>) -> <<"Netherlands">>;
alpha_3_to_name(<<"ANT">>) -> <<"Netherlands Antilles">>;
alpha_3_to_name(<<"NCL">>) -> <<"New Caledonia">>;
alpha_3_to_name(<<"NZL">>) -> <<"New Zealand">>;
alpha_3_to_name(<<"NIC">>) -> <<"Nicaragua">>;
alpha_3_to_name(<<"NER">>) -> <<"Niger">>;
alpha_3_to_name(<<"NGA">>) -> <<"Nigeria">>;
alpha_3_to_name(<<"NIU">>) -> <<"Niue">>;
alpha_3_to_name(<<"NFK">>) -> <<"Norfolk Island">>;
alpha_3_to_name(<<"MNP">>) -> <<"Northern Mariana Islands">>;
alpha_3_to_name(<<"NOR">>) -> <<"Norway">>;
alpha_3_to_name(<<"OMN">>) -> <<"Oman">>;
alpha_3_to_name(<<"PAK">>) -> <<"Pakistan">>;
alpha_3_to_name(<<"PLW">>) -> <<"Palau">>;
alpha_3_to_name(<<"PSE">>) -> <<"Palestine">>;
alpha_3_to_name(<<"PAN">>) -> <<"Panama">>;
alpha_3_to_name(<<"PNG">>) -> <<"Papua New Guinea">>;
alpha_3_to_name(<<"PRY">>) -> <<"Paraguay">>;
alpha_3_to_name(<<"PER">>) -> <<"Peru">>;
alpha_3_to_name(<<"PHL">>) -> <<"Philippines">>;
alpha_3_to_name(<<"PCN">>) -> <<"Pitcairn">>;
alpha_3_to_name(<<"POL">>) -> <<"Poland">>;
alpha_3_to_name(<<"PRT">>) -> <<"Portugal">>;
alpha_3_to_name(<<"PRI">>) -> <<"Puerto Rico">>;
alpha_3_to_name(<<"QAT">>) -> <<"Qatar">>;
alpha_3_to_name(<<"REU">>) -> <<"Réunion">>;
alpha_3_to_name(<<"ROU">>) -> <<"Romania">>;
alpha_3_to_name(<<"RUS">>) -> <<"Russian Federation">>;
alpha_3_to_name(<<"RWA">>) -> <<"Rwanda">>;
alpha_3_to_name(<<"BLM">>) -> <<"Saint-Barthélemy">>;
alpha_3_to_name(<<"SHN">>) -> <<"Saint Helena">>;
alpha_3_to_name(<<"KNA">>) -> <<"Saint Kitts and Nevis">>;
alpha_3_to_name(<<"LCA">>) -> <<"Saint Lucia">>;
alpha_3_to_name(<<"MAF">>) -> <<"Saint-Martin (French part)">>;
alpha_3_to_name(<<"SPM">>) -> <<"Saint Pierre and Miquelon">>;
alpha_3_to_name(<<"VCT">>) -> <<"Saint Vincent and Grenadines">>;
alpha_3_to_name(<<"WSM">>) -> <<"Samoa">>;
alpha_3_to_name(<<"SMR">>) -> <<"San Marino">>;
alpha_3_to_name(<<"STP">>) -> <<"Sao Tome and Principe">>;
alpha_3_to_name(<<"SAU">>) -> <<"Saudi Arabia">>;
alpha_3_to_name(<<"SEN">>) -> <<"Senegal">>;
alpha_3_to_name(<<"SRB">>) -> <<"Serbia">>;
alpha_3_to_name(<<"SYC">>) -> <<"Seychelles">>;
alpha_3_to_name(<<"SLE">>) -> <<"Sierra Leone">>;
alpha_3_to_name(<<"SGP">>) -> <<"Singapore">>;
alpha_3_to_name(<<"SVK">>) -> <<"Slovakia">>;
alpha_3_to_name(<<"SVN">>) -> <<"Slovenia">>;
alpha_3_to_name(<<"SLB">>) -> <<"Solomon Islands">>;
alpha_3_to_name(<<"SOM">>) -> <<"Somalia">>;
alpha_3_to_name(<<"ZAF">>) -> <<"South Africa">>;
alpha_3_to_name(<<"SGS">>) -> <<"South Georgia and the South Sandwich Islands">>;
alpha_3_to_name(<<"SSD">>) -> <<"South Sudan">>;
alpha_3_to_name(<<"ESP">>) -> <<"Spain">>;
alpha_3_to_name(<<"LKA">>) -> <<"Sri Lanka">>;
alpha_3_to_name(<<"SDN">>) -> <<"Sudan">>;
alpha_3_to_name(<<"SUR">>) -> <<"Suriname *">>;
alpha_3_to_name(<<"SJM">>) -> <<"Svalbard and Jan Mayen Islands">>;
alpha_3_to_name(<<"SWZ">>) -> <<"Swaziland">>;
alpha_3_to_name(<<"SWE">>) -> <<"Sweden">>;
alpha_3_to_name(<<"CHE">>) -> <<"Switzerland">>;
alpha_3_to_name(<<"SYR">>) -> <<"Syrian Arab Republic (Syria)">>;
alpha_3_to_name(<<"TWN">>) -> <<"Taiwan, Republic of China">>;
alpha_3_to_name(<<"TJK">>) -> <<"Tajikistan">>;
alpha_3_to_name(<<"TZA">>) -> <<"Tanzania">>;
alpha_3_to_name(<<"THA">>) -> <<"Thailand">>;
alpha_3_to_name(<<"TLS">>) -> <<"Timor-Leste">>;
alpha_3_to_name(<<"TGO">>) -> <<"Togo">>;
alpha_3_to_name(<<"TKL">>) -> <<"Tokelau">>;
alpha_3_to_name(<<"TON">>) -> <<"Tonga">>;
alpha_3_to_name(<<"TTO">>) -> <<"Trinidad and Tobago">>;
alpha_3_to_name(<<"TUN">>) -> <<"Tunisia">>;
alpha_3_to_name(<<"TUR">>) -> <<"Turkey">>;
alpha_3_to_name(<<"TKM">>) -> <<"Turkmenistan">>;
alpha_3_to_name(<<"TCA">>) -> <<"Turks and Caicos Islands">>;
alpha_3_to_name(<<"TUV">>) -> <<"Tuvalu">>;
alpha_3_to_name(<<"UGA">>) -> <<"Uganda">>;
alpha_3_to_name(<<"UKR">>) -> <<"Ukraine">>;
alpha_3_to_name(<<"ARE">>) -> <<"United Arab Emirates">>;
alpha_3_to_name(<<"GBR">>) -> <<"United Kingdom">>;
alpha_3_to_name(<<"USA">>) -> <<"United States of America">>;
alpha_3_to_name(<<"UMI">>) -> <<"United States Minor Outlying Islands">>;
alpha_3_to_name(<<"URY">>) -> <<"Uruguay">>;
alpha_3_to_name(<<"UZB">>) -> <<"Uzbekistan">>;
alpha_3_to_name(<<"VUT">>) -> <<"Vanuatu">>;
alpha_3_to_name(<<"VEN">>) -> <<"Venezuela (Bolivarian Republic of)">>;
alpha_3_to_name(<<"VNM">>) -> <<"Viet Nam">>;
alpha_3_to_name(<<"VIR">>) -> <<"US Virgin Islands">>;
alpha_3_to_name(<<"WLF">>) -> <<"Wallis and Futuna Islands">>;
alpha_3_to_name(<<"ESH">>) -> <<"Western Sahara">>;
alpha_3_to_name(<<"YEM">>) -> <<"Yemen">>;
alpha_3_to_name(<<"ZMB">>) -> <<"Zambia">>;
alpha_3_to_name(<<"ZWE">>) -> <<"Zimbabwe">>.