-module(iso_erlang_converter).

%% API
-export([
    alpha_2_to_name_upper/1,
    country_alpha_3_to_name_upper/1,
    country_alpha_2_to_numerical_code_upper/1,
    country_alpha_3_to_numerical_code_upper/1,
    to_country_alpha_2_upper/1,
    to_alpha_3_upper/1,
    to_country_name_upper/1,
    country_to_numerical_code_upper/1
]).

%% @doc Converts two letter country codes (ISO alpha-2) and the three letter country codes (ISO alpha-3)
%%      to United Nations numerical code M49 for countries. This is case-sensitive (Expects uppercase).
%% @end
country_to_numerical_code_upper(Country) when bit_size(Country) =:= 16 -> country_alpha_2_to_numerical_code_upper(Country);
country_to_numerical_code_upper(Country) when bit_size(Country) =:= 24 -> country_alpha_3_to_numerical_code_upper(Country).

%% @doc Converts two letter country codes (ISO alpha-2) and the three letter country codes (ISO alpha-3)
%%      to Country names. This is case-sensitive (Expects uppercase).
%% @end
to_country_name_upper(Country) when bit_size(Country) =:= 16 -> alpha_2_to_name_upper(Country);
to_country_name_upper(Country) when bit_size(Country) =:= 24 -> country_alpha_3_to_name_upper(Country).

%% @doc Converts two letter country code (ISO alpha-2) to the equivalent three letter country code (ISO alpha-3)
%%      This is case-sensitive (Expects uppercase).
%% @end
to_alpha_3_upper(<<"AF">>) -> <<"AFG">>;
to_alpha_3_upper(<<"AX">>) -> <<"ALA">>;
to_alpha_3_upper(<<"AL">>) -> <<"ALB">>;
to_alpha_3_upper(<<"DZ">>) -> <<"DZA">>;
to_alpha_3_upper(<<"AS">>) -> <<"ASM">>;
to_alpha_3_upper(<<"AD">>) -> <<"AND">>;
to_alpha_3_upper(<<"AO">>) -> <<"AGO">>;
to_alpha_3_upper(<<"AI">>) -> <<"AIA">>;
to_alpha_3_upper(<<"AQ">>) -> <<"ATA">>;
to_alpha_3_upper(<<"AG">>) -> <<"ATG">>;
to_alpha_3_upper(<<"AR">>) -> <<"ARG">>;
to_alpha_3_upper(<<"AM">>) -> <<"ARM">>;
to_alpha_3_upper(<<"AW">>) -> <<"ABW">>;
to_alpha_3_upper(<<"AU">>) -> <<"AUS">>;
to_alpha_3_upper(<<"AT">>) -> <<"AUT">>;
to_alpha_3_upper(<<"AZ">>) -> <<"AZE">>;
to_alpha_3_upper(<<"BS">>) -> <<"BHS">>;
to_alpha_3_upper(<<"BH">>) -> <<"BHR">>;
to_alpha_3_upper(<<"BD">>) -> <<"BGD">>;
to_alpha_3_upper(<<"BB">>) -> <<"BRB">>;
to_alpha_3_upper(<<"BY">>) -> <<"BLR">>;
to_alpha_3_upper(<<"BE">>) -> <<"BEL">>;
to_alpha_3_upper(<<"BZ">>) -> <<"BLZ">>;
to_alpha_3_upper(<<"BJ">>) -> <<"BEN">>;
to_alpha_3_upper(<<"BM">>) -> <<"BMU">>;
to_alpha_3_upper(<<"BT">>) -> <<"BTN">>;
to_alpha_3_upper(<<"BO">>) -> <<"BOL">>;
to_alpha_3_upper(<<"BA">>) -> <<"BIH">>;
to_alpha_3_upper(<<"BW">>) -> <<"BWA">>;
to_alpha_3_upper(<<"BV">>) -> <<"BVT">>;
to_alpha_3_upper(<<"BR">>) -> <<"BRA">>;
to_alpha_3_upper(<<"VG">>) -> <<"VGB">>;
to_alpha_3_upper(<<"IO">>) -> <<"IOT">>;
to_alpha_3_upper(<<"BN">>) -> <<"BRN">>;
to_alpha_3_upper(<<"BG">>) -> <<"BGR">>;
to_alpha_3_upper(<<"BF">>) -> <<"BFA">>;
to_alpha_3_upper(<<"BI">>) -> <<"BDI">>;
to_alpha_3_upper(<<"KH">>) -> <<"KHM">>;
to_alpha_3_upper(<<"CM">>) -> <<"CMR">>;
to_alpha_3_upper(<<"CA">>) -> <<"CAN">>;
to_alpha_3_upper(<<"CV">>) -> <<"CPV">>;
to_alpha_3_upper(<<"KY">>) -> <<"CYM">>;
to_alpha_3_upper(<<"CF">>) -> <<"CAF">>;
to_alpha_3_upper(<<"TD">>) -> <<"TCD">>;
to_alpha_3_upper(<<"CL">>) -> <<"CHL">>;
to_alpha_3_upper(<<"CN">>) -> <<"CHN">>;
to_alpha_3_upper(<<"HK">>) -> <<"HKG">>;
to_alpha_3_upper(<<"MO">>) -> <<"MAC">>;
to_alpha_3_upper(<<"CX">>) -> <<"CXR">>;
to_alpha_3_upper(<<"CC">>) -> <<"CCK">>;
to_alpha_3_upper(<<"CO">>) -> <<"COL">>;
to_alpha_3_upper(<<"KM">>) -> <<"COM">>;
to_alpha_3_upper(<<"CG">>) -> <<"COG">>;
to_alpha_3_upper(<<"CD">>) -> <<"COD">>;
to_alpha_3_upper(<<"CK">>) -> <<"COK">>;
to_alpha_3_upper(<<"CR">>) -> <<"CRI">>;
to_alpha_3_upper(<<"CI">>) -> <<"CIV">>;
to_alpha_3_upper(<<"HR">>) -> <<"HRV">>;
to_alpha_3_upper(<<"CU">>) -> <<"CUB">>;
to_alpha_3_upper(<<"CY">>) -> <<"CYP">>;
to_alpha_3_upper(<<"CZ">>) -> <<"CZE">>;
to_alpha_3_upper(<<"DK">>) -> <<"DNK">>;
to_alpha_3_upper(<<"DJ">>) -> <<"DJI">>;
to_alpha_3_upper(<<"DM">>) -> <<"DMA">>;
to_alpha_3_upper(<<"DO">>) -> <<"DOM">>;
to_alpha_3_upper(<<"EC">>) -> <<"ECU">>;
to_alpha_3_upper(<<"EG">>) -> <<"EGY">>;
to_alpha_3_upper(<<"SV">>) -> <<"SLV">>;
to_alpha_3_upper(<<"GQ">>) -> <<"GNQ">>;
to_alpha_3_upper(<<"ER">>) -> <<"ERI">>;
to_alpha_3_upper(<<"EE">>) -> <<"EST">>;
to_alpha_3_upper(<<"ET">>) -> <<"ETH">>;
to_alpha_3_upper(<<"FK">>) -> <<"FLK">>;
to_alpha_3_upper(<<"FO">>) -> <<"FRO">>;
to_alpha_3_upper(<<"FJ">>) -> <<"FJI">>;
to_alpha_3_upper(<<"FI">>) -> <<"FIN">>;
to_alpha_3_upper(<<"FR">>) -> <<"FRA">>;
to_alpha_3_upper(<<"GF">>) -> <<"GUF">>;
to_alpha_3_upper(<<"PF">>) -> <<"PYF">>;
to_alpha_3_upper(<<"TF">>) -> <<"ATF">>;
to_alpha_3_upper(<<"GA">>) -> <<"GAB">>;
to_alpha_3_upper(<<"GM">>) -> <<"GMB">>;
to_alpha_3_upper(<<"GE">>) -> <<"GEO">>;
to_alpha_3_upper(<<"DE">>) -> <<"DEU">>;
to_alpha_3_upper(<<"GH">>) -> <<"GHA">>;
to_alpha_3_upper(<<"GI">>) -> <<"GIB">>;
to_alpha_3_upper(<<"GR">>) -> <<"GRC">>;
to_alpha_3_upper(<<"GL">>) -> <<"GRL">>;
to_alpha_3_upper(<<"GD">>) -> <<"GRD">>;
to_alpha_3_upper(<<"GP">>) -> <<"GLP">>;
to_alpha_3_upper(<<"GU">>) -> <<"GUM">>;
to_alpha_3_upper(<<"GT">>) -> <<"GTM">>;
to_alpha_3_upper(<<"GG">>) -> <<"GGY">>;
to_alpha_3_upper(<<"GN">>) -> <<"GIN">>;
to_alpha_3_upper(<<"GW">>) -> <<"GNB">>;
to_alpha_3_upper(<<"GY">>) -> <<"GUY">>;
to_alpha_3_upper(<<"HT">>) -> <<"HTI">>;
to_alpha_3_upper(<<"HM">>) -> <<"HMD">>;
to_alpha_3_upper(<<"VA">>) -> <<"VAT">>;
to_alpha_3_upper(<<"HN">>) -> <<"HND">>;
to_alpha_3_upper(<<"HU">>) -> <<"HUN">>;
to_alpha_3_upper(<<"IS">>) -> <<"ISL">>;
to_alpha_3_upper(<<"IN">>) -> <<"IND">>;
to_alpha_3_upper(<<"ID">>) -> <<"IDN">>;
to_alpha_3_upper(<<"IR">>) -> <<"IRN">>;
to_alpha_3_upper(<<"IQ">>) -> <<"IRQ">>;
to_alpha_3_upper(<<"IE">>) -> <<"IRL">>;
to_alpha_3_upper(<<"IM">>) -> <<"IMN">>;
to_alpha_3_upper(<<"IL">>) -> <<"ISR">>;
to_alpha_3_upper(<<"IT">>) -> <<"ITA">>;
to_alpha_3_upper(<<"JM">>) -> <<"JAM">>;
to_alpha_3_upper(<<"JP">>) -> <<"JPN">>;
to_alpha_3_upper(<<"JE">>) -> <<"JEY">>;
to_alpha_3_upper(<<"JO">>) -> <<"JOR">>;
to_alpha_3_upper(<<"KZ">>) -> <<"KAZ">>;
to_alpha_3_upper(<<"KE">>) -> <<"KEN">>;
to_alpha_3_upper(<<"KI">>) -> <<"KIR">>;
to_alpha_3_upper(<<"KP">>) -> <<"PRK">>;
to_alpha_3_upper(<<"KR">>) -> <<"KOR">>;
to_alpha_3_upper(<<"KW">>) -> <<"KWT">>;
to_alpha_3_upper(<<"KG">>) -> <<"KGZ">>;
to_alpha_3_upper(<<"LA">>) -> <<"LAO">>;
to_alpha_3_upper(<<"LV">>) -> <<"LVA">>;
to_alpha_3_upper(<<"LB">>) -> <<"LBN">>;
to_alpha_3_upper(<<"LS">>) -> <<"LSO">>;
to_alpha_3_upper(<<"LR">>) -> <<"LBR">>;
to_alpha_3_upper(<<"LY">>) -> <<"LBY">>;
to_alpha_3_upper(<<"LI">>) -> <<"LIE">>;
to_alpha_3_upper(<<"LT">>) -> <<"LTU">>;
to_alpha_3_upper(<<"LU">>) -> <<"LUX">>;
to_alpha_3_upper(<<"MK">>) -> <<"MKD">>;
to_alpha_3_upper(<<"MG">>) -> <<"MDG">>;
to_alpha_3_upper(<<"MW">>) -> <<"MWI">>;
to_alpha_3_upper(<<"MY">>) -> <<"MYS">>;
to_alpha_3_upper(<<"MV">>) -> <<"MDV">>;
to_alpha_3_upper(<<"ML">>) -> <<"MLI">>;
to_alpha_3_upper(<<"MT">>) -> <<"MLT">>;
to_alpha_3_upper(<<"MH">>) -> <<"MHL">>;
to_alpha_3_upper(<<"MQ">>) -> <<"MTQ">>;
to_alpha_3_upper(<<"MR">>) -> <<"MRT">>;
to_alpha_3_upper(<<"MU">>) -> <<"MUS">>;
to_alpha_3_upper(<<"YT">>) -> <<"MYT">>;
to_alpha_3_upper(<<"MX">>) -> <<"MEX">>;
to_alpha_3_upper(<<"FM">>) -> <<"FSM">>;
to_alpha_3_upper(<<"MD">>) -> <<"MDA">>;
to_alpha_3_upper(<<"MC">>) -> <<"MCO">>;
to_alpha_3_upper(<<"MN">>) -> <<"MNG">>;
to_alpha_3_upper(<<"ME">>) -> <<"MNE">>;
to_alpha_3_upper(<<"MS">>) -> <<"MSR">>;
to_alpha_3_upper(<<"MA">>) -> <<"MAR">>;
to_alpha_3_upper(<<"MZ">>) -> <<"MOZ">>;
to_alpha_3_upper(<<"MM">>) -> <<"MMR">>;
to_alpha_3_upper(<<"NA">>) -> <<"NAM">>;
to_alpha_3_upper(<<"NR">>) -> <<"NRU">>;
to_alpha_3_upper(<<"NP">>) -> <<"NPL">>;
to_alpha_3_upper(<<"NL">>) -> <<"NLD">>;
to_alpha_3_upper(<<"AN">>) -> <<"ANT">>;
to_alpha_3_upper(<<"NC">>) -> <<"NCL">>;
to_alpha_3_upper(<<"NZ">>) -> <<"NZL">>;
to_alpha_3_upper(<<"NI">>) -> <<"NIC">>;
to_alpha_3_upper(<<"NE">>) -> <<"NER">>;
to_alpha_3_upper(<<"NG">>) -> <<"NGA">>;
to_alpha_3_upper(<<"NU">>) -> <<"NIU">>;
to_alpha_3_upper(<<"NF">>) -> <<"NFK">>;
to_alpha_3_upper(<<"MP">>) -> <<"MNP">>;
to_alpha_3_upper(<<"NO">>) -> <<"NOR">>;
to_alpha_3_upper(<<"OM">>) -> <<"OMN">>;
to_alpha_3_upper(<<"PK">>) -> <<"PAK">>;
to_alpha_3_upper(<<"PW">>) -> <<"PLW">>;
to_alpha_3_upper(<<"PS">>) -> <<"PSE">>;
to_alpha_3_upper(<<"PA">>) -> <<"PAN">>;
to_alpha_3_upper(<<"PG">>) -> <<"PNG">>;
to_alpha_3_upper(<<"PY">>) -> <<"PRY">>;
to_alpha_3_upper(<<"PE">>) -> <<"PER">>;
to_alpha_3_upper(<<"PH">>) -> <<"PHL">>;
to_alpha_3_upper(<<"PN">>) -> <<"PCN">>;
to_alpha_3_upper(<<"PL">>) -> <<"POL">>;
to_alpha_3_upper(<<"PT">>) -> <<"PRT">>;
to_alpha_3_upper(<<"PR">>) -> <<"PRI">>;
to_alpha_3_upper(<<"QA">>) -> <<"QAT">>;
to_alpha_3_upper(<<"RE">>) -> <<"REU">>;
to_alpha_3_upper(<<"RO">>) -> <<"ROU">>;
to_alpha_3_upper(<<"RU">>) -> <<"RUS">>;
to_alpha_3_upper(<<"RW">>) -> <<"RWA">>;
to_alpha_3_upper(<<"BL">>) -> <<"BLM">>;
to_alpha_3_upper(<<"SH">>) -> <<"SHN">>;
to_alpha_3_upper(<<"KN">>) -> <<"KNA">>;
to_alpha_3_upper(<<"LC">>) -> <<"LCA">>;
to_alpha_3_upper(<<"MF">>) -> <<"MAF">>;
to_alpha_3_upper(<<"PM">>) -> <<"SPM">>;
to_alpha_3_upper(<<"VC">>) -> <<"VCT">>;
to_alpha_3_upper(<<"WS">>) -> <<"WSM">>;
to_alpha_3_upper(<<"SM">>) -> <<"SMR">>;
to_alpha_3_upper(<<"ST">>) -> <<"STP">>;
to_alpha_3_upper(<<"SA">>) -> <<"SAU">>;
to_alpha_3_upper(<<"SN">>) -> <<"SEN">>;
to_alpha_3_upper(<<"RS">>) -> <<"SRB">>;
to_alpha_3_upper(<<"SC">>) -> <<"SYC">>;
to_alpha_3_upper(<<"SL">>) -> <<"SLE">>;
to_alpha_3_upper(<<"SG">>) -> <<"SGP">>;
to_alpha_3_upper(<<"SK">>) -> <<"SVK">>;
to_alpha_3_upper(<<"SI">>) -> <<"SVN">>;
to_alpha_3_upper(<<"SB">>) -> <<"SLB">>;
to_alpha_3_upper(<<"SO">>) -> <<"SOM">>;
to_alpha_3_upper(<<"ZA">>) -> <<"ZAF">>;
to_alpha_3_upper(<<"GS">>) -> <<"SGS">>;
to_alpha_3_upper(<<"SS">>) -> <<"SSD">>;
to_alpha_3_upper(<<"ES">>) -> <<"ESP">>;
to_alpha_3_upper(<<"LK">>) -> <<"LKA">>;
to_alpha_3_upper(<<"SD">>) -> <<"SDN">>;
to_alpha_3_upper(<<"SR">>) -> <<"SUR">>;
to_alpha_3_upper(<<"SJ">>) -> <<"SJM">>;
to_alpha_3_upper(<<"SZ">>) -> <<"SWZ">>;
to_alpha_3_upper(<<"SE">>) -> <<"SWE">>;
to_alpha_3_upper(<<"CH">>) -> <<"CHE">>;
to_alpha_3_upper(<<"SY">>) -> <<"SYR">>;
to_alpha_3_upper(<<"TW">>) -> <<"TWN">>;
to_alpha_3_upper(<<"TJ">>) -> <<"TJK">>;
to_alpha_3_upper(<<"TZ">>) -> <<"TZA">>;
to_alpha_3_upper(<<"TH">>) -> <<"THA">>;
to_alpha_3_upper(<<"TL">>) -> <<"TLS">>;
to_alpha_3_upper(<<"TG">>) -> <<"TGO">>;
to_alpha_3_upper(<<"TK">>) -> <<"TKL">>;
to_alpha_3_upper(<<"TO">>) -> <<"TON">>;
to_alpha_3_upper(<<"TT">>) -> <<"TTO">>;
to_alpha_3_upper(<<"TN">>) -> <<"TUN">>;
to_alpha_3_upper(<<"TR">>) -> <<"TUR">>;
to_alpha_3_upper(<<"TM">>) -> <<"TKM">>;
to_alpha_3_upper(<<"TC">>) -> <<"TCA">>;
to_alpha_3_upper(<<"TV">>) -> <<"TUV">>;
to_alpha_3_upper(<<"UG">>) -> <<"UGA">>;
to_alpha_3_upper(<<"UA">>) -> <<"UKR">>;
to_alpha_3_upper(<<"AE">>) -> <<"ARE">>;
to_alpha_3_upper(<<"GB">>) -> <<"GBR">>;
to_alpha_3_upper(<<"US">>) -> <<"USA">>;
to_alpha_3_upper(<<"UM">>) -> <<"UMI">>;
to_alpha_3_upper(<<"UY">>) -> <<"URY">>;
to_alpha_3_upper(<<"UZ">>) -> <<"UZB">>;
to_alpha_3_upper(<<"VU">>) -> <<"VUT">>;
to_alpha_3_upper(<<"VE">>) -> <<"VEN">>;
to_alpha_3_upper(<<"VN">>) -> <<"VNM">>;
to_alpha_3_upper(<<"VI">>) -> <<"VIR">>;
to_alpha_3_upper(<<"WF">>) -> <<"WLF">>;
to_alpha_3_upper(<<"EH">>) -> <<"ESH">>;
to_alpha_3_upper(<<"YE">>) -> <<"YEM">>;
to_alpha_3_upper(<<"ZM">>) -> <<"ZMB">>;
to_alpha_3_upper(<<"ZW">>) -> <<"ZWE">>.

%% @doc Converts three letter country code (ISO alpha-3) to the equivalent two letter country code (ISO alpha-2).
%%      This is case-sensitive (Expects uppercase).
%% @end
to_country_alpha_2_upper(<<"AFG">>) -> <<"AF">>;
to_country_alpha_2_upper(<<"ALA">>) -> <<"AX">>;
to_country_alpha_2_upper(<<"ALB">>) -> <<"AL">>;
to_country_alpha_2_upper(<<"DZA">>) -> <<"DZ">>;
to_country_alpha_2_upper(<<"ASM">>) -> <<"AS">>;
to_country_alpha_2_upper(<<"AND">>) -> <<"AD">>;
to_country_alpha_2_upper(<<"AGO">>) -> <<"AO">>;
to_country_alpha_2_upper(<<"AIA">>) -> <<"AI">>;
to_country_alpha_2_upper(<<"ATA">>) -> <<"AQ">>;
to_country_alpha_2_upper(<<"ATG">>) -> <<"AG">>;
to_country_alpha_2_upper(<<"ARG">>) -> <<"AR">>;
to_country_alpha_2_upper(<<"ARM">>) -> <<"AM">>;
to_country_alpha_2_upper(<<"ABW">>) -> <<"AW">>;
to_country_alpha_2_upper(<<"AUS">>) -> <<"AU">>;
to_country_alpha_2_upper(<<"AUT">>) -> <<"AT">>;
to_country_alpha_2_upper(<<"AZE">>) -> <<"AZ">>;
to_country_alpha_2_upper(<<"BHS">>) -> <<"BS">>;
to_country_alpha_2_upper(<<"BHR">>) -> <<"BH">>;
to_country_alpha_2_upper(<<"BGD">>) -> <<"BD">>;
to_country_alpha_2_upper(<<"BRB">>) -> <<"BB">>;
to_country_alpha_2_upper(<<"BLR">>) -> <<"BY">>;
to_country_alpha_2_upper(<<"BEL">>) -> <<"BE">>;
to_country_alpha_2_upper(<<"BLZ">>) -> <<"BZ">>;
to_country_alpha_2_upper(<<"BEN">>) -> <<"BJ">>;
to_country_alpha_2_upper(<<"BMU">>) -> <<"BM">>;
to_country_alpha_2_upper(<<"BTN">>) -> <<"BT">>;
to_country_alpha_2_upper(<<"BOL">>) -> <<"BO">>;
to_country_alpha_2_upper(<<"BIH">>) -> <<"BA">>;
to_country_alpha_2_upper(<<"BWA">>) -> <<"BW">>;
to_country_alpha_2_upper(<<"BVT">>) -> <<"BV">>;
to_country_alpha_2_upper(<<"BRA">>) -> <<"BR">>;
to_country_alpha_2_upper(<<"VGB">>) -> <<"VG">>;
to_country_alpha_2_upper(<<"IOT">>) -> <<"IO">>;
to_country_alpha_2_upper(<<"BRN">>) -> <<"BN">>;
to_country_alpha_2_upper(<<"BGR">>) -> <<"BG">>;
to_country_alpha_2_upper(<<"BFA">>) -> <<"BF">>;
to_country_alpha_2_upper(<<"BDI">>) -> <<"BI">>;
to_country_alpha_2_upper(<<"KHM">>) -> <<"KH">>;
to_country_alpha_2_upper(<<"CMR">>) -> <<"CM">>;
to_country_alpha_2_upper(<<"CAN">>) -> <<"CA">>;
to_country_alpha_2_upper(<<"CPV">>) -> <<"CV">>;
to_country_alpha_2_upper(<<"CYM">>) -> <<"KY">>;
to_country_alpha_2_upper(<<"CAF">>) -> <<"CF">>;
to_country_alpha_2_upper(<<"TCD">>) -> <<"TD">>;
to_country_alpha_2_upper(<<"CHL">>) -> <<"CL">>;
to_country_alpha_2_upper(<<"CHN">>) -> <<"CN">>;
to_country_alpha_2_upper(<<"HKG">>) -> <<"HK">>;
to_country_alpha_2_upper(<<"MAC">>) -> <<"MO">>;
to_country_alpha_2_upper(<<"CXR">>) -> <<"CX">>;
to_country_alpha_2_upper(<<"CCK">>) -> <<"CC">>;
to_country_alpha_2_upper(<<"COL">>) -> <<"CO">>;
to_country_alpha_2_upper(<<"COM">>) -> <<"KM">>;
to_country_alpha_2_upper(<<"COG">>) -> <<"CG">>;
to_country_alpha_2_upper(<<"COD">>) -> <<"CD">>;
to_country_alpha_2_upper(<<"COK">>) -> <<"CK">>;
to_country_alpha_2_upper(<<"CRI">>) -> <<"CR">>;
to_country_alpha_2_upper(<<"CIV">>) -> <<"CI">>;
to_country_alpha_2_upper(<<"HRV">>) -> <<"HR">>;
to_country_alpha_2_upper(<<"CUB">>) -> <<"CU">>;
to_country_alpha_2_upper(<<"CYP">>) -> <<"CY">>;
to_country_alpha_2_upper(<<"CZE">>) -> <<"CZ">>;
to_country_alpha_2_upper(<<"DNK">>) -> <<"DK">>;
to_country_alpha_2_upper(<<"DJI">>) -> <<"DJ">>;
to_country_alpha_2_upper(<<"DMA">>) -> <<"DM">>;
to_country_alpha_2_upper(<<"DOM">>) -> <<"DO">>;
to_country_alpha_2_upper(<<"ECU">>) -> <<"EC">>;
to_country_alpha_2_upper(<<"EGY">>) -> <<"EG">>;
to_country_alpha_2_upper(<<"SLV">>) -> <<"SV">>;
to_country_alpha_2_upper(<<"GNQ">>) -> <<"GQ">>;
to_country_alpha_2_upper(<<"ERI">>) -> <<"ER">>;
to_country_alpha_2_upper(<<"EST">>) -> <<"EE">>;
to_country_alpha_2_upper(<<"ETH">>) -> <<"ET">>;
to_country_alpha_2_upper(<<"FLK">>) -> <<"FK">>;
to_country_alpha_2_upper(<<"FRO">>) -> <<"FO">>;
to_country_alpha_2_upper(<<"FJI">>) -> <<"FJ">>;
to_country_alpha_2_upper(<<"FIN">>) -> <<"FI">>;
to_country_alpha_2_upper(<<"FRA">>) -> <<"FR">>;
to_country_alpha_2_upper(<<"GUF">>) -> <<"GF">>;
to_country_alpha_2_upper(<<"PYF">>) -> <<"PF">>;
to_country_alpha_2_upper(<<"ATF">>) -> <<"TF">>;
to_country_alpha_2_upper(<<"GAB">>) -> <<"GA">>;
to_country_alpha_2_upper(<<"GMB">>) -> <<"GM">>;
to_country_alpha_2_upper(<<"GEO">>) -> <<"GE">>;
to_country_alpha_2_upper(<<"DEU">>) -> <<"DE">>;
to_country_alpha_2_upper(<<"GHA">>) -> <<"GH">>;
to_country_alpha_2_upper(<<"GIB">>) -> <<"GI">>;
to_country_alpha_2_upper(<<"GRC">>) -> <<"GR">>;
to_country_alpha_2_upper(<<"GRL">>) -> <<"GL">>;
to_country_alpha_2_upper(<<"GRD">>) -> <<"GD">>;
to_country_alpha_2_upper(<<"GLP">>) -> <<"GP">>;
to_country_alpha_2_upper(<<"GUM">>) -> <<"GU">>;
to_country_alpha_2_upper(<<"GTM">>) -> <<"GT">>;
to_country_alpha_2_upper(<<"GGY">>) -> <<"GG">>;
to_country_alpha_2_upper(<<"GIN">>) -> <<"GN">>;
to_country_alpha_2_upper(<<"GNB">>) -> <<"GW">>;
to_country_alpha_2_upper(<<"GUY">>) -> <<"GY">>;
to_country_alpha_2_upper(<<"HTI">>) -> <<"HT">>;
to_country_alpha_2_upper(<<"HMD">>) -> <<"HM">>;
to_country_alpha_2_upper(<<"VAT">>) -> <<"VA">>;
to_country_alpha_2_upper(<<"HND">>) -> <<"HN">>;
to_country_alpha_2_upper(<<"HUN">>) -> <<"HU">>;
to_country_alpha_2_upper(<<"ISL">>) -> <<"IS">>;
to_country_alpha_2_upper(<<"IND">>) -> <<"IN">>;
to_country_alpha_2_upper(<<"IDN">>) -> <<"ID">>;
to_country_alpha_2_upper(<<"IRN">>) -> <<"IR">>;
to_country_alpha_2_upper(<<"IRQ">>) -> <<"IQ">>;
to_country_alpha_2_upper(<<"IRL">>) -> <<"IE">>;
to_country_alpha_2_upper(<<"IMN">>) -> <<"IM">>;
to_country_alpha_2_upper(<<"ISR">>) -> <<"IL">>;
to_country_alpha_2_upper(<<"ITA">>) -> <<"IT">>;
to_country_alpha_2_upper(<<"JAM">>) -> <<"JM">>;
to_country_alpha_2_upper(<<"JPN">>) -> <<"JP">>;
to_country_alpha_2_upper(<<"JEY">>) -> <<"JE">>;
to_country_alpha_2_upper(<<"JOR">>) -> <<"JO">>;
to_country_alpha_2_upper(<<"KAZ">>) -> <<"KZ">>;
to_country_alpha_2_upper(<<"KEN">>) -> <<"KE">>;
to_country_alpha_2_upper(<<"KIR">>) -> <<"KI">>;
to_country_alpha_2_upper(<<"PRK">>) -> <<"KP">>;
to_country_alpha_2_upper(<<"KOR">>) -> <<"KR">>;
to_country_alpha_2_upper(<<"KWT">>) -> <<"KW">>;
to_country_alpha_2_upper(<<"KGZ">>) -> <<"KG">>;
to_country_alpha_2_upper(<<"LAO">>) -> <<"LA">>;
to_country_alpha_2_upper(<<"LVA">>) -> <<"LV">>;
to_country_alpha_2_upper(<<"LBN">>) -> <<"LB">>;
to_country_alpha_2_upper(<<"LSO">>) -> <<"LS">>;
to_country_alpha_2_upper(<<"LBR">>) -> <<"LR">>;
to_country_alpha_2_upper(<<"LBY">>) -> <<"LY">>;
to_country_alpha_2_upper(<<"LIE">>) -> <<"LI">>;
to_country_alpha_2_upper(<<"LTU">>) -> <<"LT">>;
to_country_alpha_2_upper(<<"LUX">>) -> <<"LU">>;
to_country_alpha_2_upper(<<"MKD">>) -> <<"MK">>;
to_country_alpha_2_upper(<<"MDG">>) -> <<"MG">>;
to_country_alpha_2_upper(<<"MWI">>) -> <<"MW">>;
to_country_alpha_2_upper(<<"MYS">>) -> <<"MY">>;
to_country_alpha_2_upper(<<"MDV">>) -> <<"MV">>;
to_country_alpha_2_upper(<<"MLI">>) -> <<"ML">>;
to_country_alpha_2_upper(<<"MLT">>) -> <<"MT">>;
to_country_alpha_2_upper(<<"MHL">>) -> <<"MH">>;
to_country_alpha_2_upper(<<"MTQ">>) -> <<"MQ">>;
to_country_alpha_2_upper(<<"MRT">>) -> <<"MR">>;
to_country_alpha_2_upper(<<"MUS">>) -> <<"MU">>;
to_country_alpha_2_upper(<<"MYT">>) -> <<"YT">>;
to_country_alpha_2_upper(<<"MEX">>) -> <<"MX">>;
to_country_alpha_2_upper(<<"FSM">>) -> <<"FM">>;
to_country_alpha_2_upper(<<"MDA">>) -> <<"MD">>;
to_country_alpha_2_upper(<<"MCO">>) -> <<"MC">>;
to_country_alpha_2_upper(<<"MNG">>) -> <<"MN">>;
to_country_alpha_2_upper(<<"MNE">>) -> <<"ME">>;
to_country_alpha_2_upper(<<"MSR">>) -> <<"MS">>;
to_country_alpha_2_upper(<<"MAR">>) -> <<"MA">>;
to_country_alpha_2_upper(<<"MOZ">>) -> <<"MZ">>;
to_country_alpha_2_upper(<<"MMR">>) -> <<"MM">>;
to_country_alpha_2_upper(<<"NAM">>) -> <<"NA">>;
to_country_alpha_2_upper(<<"NRU">>) -> <<"NR">>;
to_country_alpha_2_upper(<<"NPL">>) -> <<"NP">>;
to_country_alpha_2_upper(<<"NLD">>) -> <<"NL">>;
to_country_alpha_2_upper(<<"ANT">>) -> <<"AN">>;
to_country_alpha_2_upper(<<"NCL">>) -> <<"NC">>;
to_country_alpha_2_upper(<<"NZL">>) -> <<"NZ">>;
to_country_alpha_2_upper(<<"NIC">>) -> <<"NI">>;
to_country_alpha_2_upper(<<"NER">>) -> <<"NE">>;
to_country_alpha_2_upper(<<"NGA">>) -> <<"NG">>;
to_country_alpha_2_upper(<<"NIU">>) -> <<"NU">>;
to_country_alpha_2_upper(<<"NFK">>) -> <<"NF">>;
to_country_alpha_2_upper(<<"MNP">>) -> <<"MP">>;
to_country_alpha_2_upper(<<"NOR">>) -> <<"NO">>;
to_country_alpha_2_upper(<<"OMN">>) -> <<"OM">>;
to_country_alpha_2_upper(<<"PAK">>) -> <<"PK">>;
to_country_alpha_2_upper(<<"PLW">>) -> <<"PW">>;
to_country_alpha_2_upper(<<"PSE">>) -> <<"PS">>;
to_country_alpha_2_upper(<<"PAN">>) -> <<"PA">>;
to_country_alpha_2_upper(<<"PNG">>) -> <<"PG">>;
to_country_alpha_2_upper(<<"PRY">>) -> <<"PY">>;
to_country_alpha_2_upper(<<"PER">>) -> <<"PE">>;
to_country_alpha_2_upper(<<"PHL">>) -> <<"PH">>;
to_country_alpha_2_upper(<<"PCN">>) -> <<"PN">>;
to_country_alpha_2_upper(<<"POL">>) -> <<"PL">>;
to_country_alpha_2_upper(<<"PRT">>) -> <<"PT">>;
to_country_alpha_2_upper(<<"PRI">>) -> <<"PR">>;
to_country_alpha_2_upper(<<"QAT">>) -> <<"QA">>;
to_country_alpha_2_upper(<<"REU">>) -> <<"RE">>;
to_country_alpha_2_upper(<<"ROU">>) -> <<"RO">>;
to_country_alpha_2_upper(<<"RUS">>) -> <<"RU">>;
to_country_alpha_2_upper(<<"RWA">>) -> <<"RW">>;
to_country_alpha_2_upper(<<"BLM">>) -> <<"BL">>;
to_country_alpha_2_upper(<<"SHN">>) -> <<"SH">>;
to_country_alpha_2_upper(<<"KNA">>) -> <<"KN">>;
to_country_alpha_2_upper(<<"LCA">>) -> <<"LC">>;
to_country_alpha_2_upper(<<"MAF">>) -> <<"MF">>;
to_country_alpha_2_upper(<<"SPM">>) -> <<"PM">>;
to_country_alpha_2_upper(<<"VCT">>) -> <<"VC">>;
to_country_alpha_2_upper(<<"WSM">>) -> <<"WS">>;
to_country_alpha_2_upper(<<"SMR">>) -> <<"SM">>;
to_country_alpha_2_upper(<<"STP">>) -> <<"ST">>;
to_country_alpha_2_upper(<<"SAU">>) -> <<"SA">>;
to_country_alpha_2_upper(<<"SEN">>) -> <<"SN">>;
to_country_alpha_2_upper(<<"SRB">>) -> <<"RS">>;
to_country_alpha_2_upper(<<"SYC">>) -> <<"SC">>;
to_country_alpha_2_upper(<<"SLE">>) -> <<"SL">>;
to_country_alpha_2_upper(<<"SGP">>) -> <<"SG">>;
to_country_alpha_2_upper(<<"SVK">>) -> <<"SK">>;
to_country_alpha_2_upper(<<"SVN">>) -> <<"SI">>;
to_country_alpha_2_upper(<<"SLB">>) -> <<"SB">>;
to_country_alpha_2_upper(<<"SOM">>) -> <<"SO">>;
to_country_alpha_2_upper(<<"ZAF">>) -> <<"ZA">>;
to_country_alpha_2_upper(<<"SGS">>) -> <<"GS">>;
to_country_alpha_2_upper(<<"SSD">>) -> <<"SS">>;
to_country_alpha_2_upper(<<"ESP">>) -> <<"ES">>;
to_country_alpha_2_upper(<<"LKA">>) -> <<"LK">>;
to_country_alpha_2_upper(<<"SDN">>) -> <<"SD">>;
to_country_alpha_2_upper(<<"SUR">>) -> <<"SR">>;
to_country_alpha_2_upper(<<"SJM">>) -> <<"SJ">>;
to_country_alpha_2_upper(<<"SWZ">>) -> <<"SZ">>;
to_country_alpha_2_upper(<<"SWE">>) -> <<"SE">>;
to_country_alpha_2_upper(<<"CHE">>) -> <<"CH">>;
to_country_alpha_2_upper(<<"SYR">>) -> <<"SY">>;
to_country_alpha_2_upper(<<"TWN">>) -> <<"TW">>;
to_country_alpha_2_upper(<<"TJK">>) -> <<"TJ">>;
to_country_alpha_2_upper(<<"TZA">>) -> <<"TZ">>;
to_country_alpha_2_upper(<<"THA">>) -> <<"TH">>;
to_country_alpha_2_upper(<<"TLS">>) -> <<"TL">>;
to_country_alpha_2_upper(<<"TGO">>) -> <<"TG">>;
to_country_alpha_2_upper(<<"TKL">>) -> <<"TK">>;
to_country_alpha_2_upper(<<"TON">>) -> <<"TO">>;
to_country_alpha_2_upper(<<"TTO">>) -> <<"TT">>;
to_country_alpha_2_upper(<<"TUN">>) -> <<"TN">>;
to_country_alpha_2_upper(<<"TUR">>) -> <<"TR">>;
to_country_alpha_2_upper(<<"TKM">>) -> <<"TM">>;
to_country_alpha_2_upper(<<"TCA">>) -> <<"TC">>;
to_country_alpha_2_upper(<<"TUV">>) -> <<"TV">>;
to_country_alpha_2_upper(<<"UGA">>) -> <<"UG">>;
to_country_alpha_2_upper(<<"UKR">>) -> <<"UA">>;
to_country_alpha_2_upper(<<"ARE">>) -> <<"AE">>;
to_country_alpha_2_upper(<<"GBR">>) -> <<"GB">>;
to_country_alpha_2_upper(<<"USA">>) -> <<"US">>;
to_country_alpha_2_upper(<<"UMI">>) -> <<"UM">>;
to_country_alpha_2_upper(<<"URY">>) -> <<"UY">>;
to_country_alpha_2_upper(<<"UZB">>) -> <<"UZ">>;
to_country_alpha_2_upper(<<"VUT">>) -> <<"VU">>;
to_country_alpha_2_upper(<<"VEN">>) -> <<"VE">>;
to_country_alpha_2_upper(<<"VNM">>) -> <<"VN">>;
to_country_alpha_2_upper(<<"VIR">>) -> <<"VI">>;
to_country_alpha_2_upper(<<"WLF">>) -> <<"WF">>;
to_country_alpha_2_upper(<<"ESH">>) -> <<"EH">>;
to_country_alpha_2_upper(<<"YEM">>) -> <<"YE">>;
to_country_alpha_2_upper(<<"ZMB">>) -> <<"ZM">>;
to_country_alpha_2_upper(<<"ZWE">>) -> <<"ZW">>.

%% @doc Converts two letter country code (ISO alpha-2) to the equivalent country name.
%%      This is case-sensitive (Expects uppercase).
%% @end
alpha_2_to_name_upper(<<"AF">>) -> <<"Afghanistan">>;
alpha_2_to_name_upper(<<"AX">>) -> <<"Aland Islands">>;
alpha_2_to_name_upper(<<"AL">>) -> <<"Albania">>;
alpha_2_to_name_upper(<<"DZ">>) -> <<"Algeria">>;
alpha_2_to_name_upper(<<"AS">>) -> <<"American Samoa">>;
alpha_2_to_name_upper(<<"AD">>) -> <<"Andorra">>;
alpha_2_to_name_upper(<<"AO">>) -> <<"Angola">>;
alpha_2_to_name_upper(<<"AI">>) -> <<"Anguilla">>;
alpha_2_to_name_upper(<<"AQ">>) -> <<"Antarctica">>;
alpha_2_to_name_upper(<<"AG">>) -> <<"Antigua and Barbuda">>;
alpha_2_to_name_upper(<<"AR">>) -> <<"Argentina">>;
alpha_2_to_name_upper(<<"AM">>) -> <<"Armenia">>;
alpha_2_to_name_upper(<<"AW">>) -> <<"Aruba">>;
alpha_2_to_name_upper(<<"AU">>) -> <<"Australia">>;
alpha_2_to_name_upper(<<"AT">>) -> <<"Austria">>;
alpha_2_to_name_upper(<<"AZ">>) -> <<"Azerbaijan">>;
alpha_2_to_name_upper(<<"BS">>) -> <<"Bahamas">>;
alpha_2_to_name_upper(<<"BH">>) -> <<"Bahrain">>;
alpha_2_to_name_upper(<<"BD">>) -> <<"Bangladesh">>;
alpha_2_to_name_upper(<<"BB">>) -> <<"Barbados">>;
alpha_2_to_name_upper(<<"BY">>) -> <<"Belarus">>;
alpha_2_to_name_upper(<<"BE">>) -> <<"Belgium">>;
alpha_2_to_name_upper(<<"BZ">>) -> <<"Belize">>;
alpha_2_to_name_upper(<<"BJ">>) -> <<"Benin">>;
alpha_2_to_name_upper(<<"BM">>) -> <<"Bermuda">>;
alpha_2_to_name_upper(<<"BT">>) -> <<"Bhutan">>;
alpha_2_to_name_upper(<<"BO">>) -> <<"Bolivia">>;
alpha_2_to_name_upper(<<"BA">>) -> <<"Bosnia and Herzegovina">>;
alpha_2_to_name_upper(<<"BW">>) -> <<"Botswana">>;
alpha_2_to_name_upper(<<"BV">>) -> <<"Bouvet Island">>;
alpha_2_to_name_upper(<<"BR">>) -> <<"Brazil">>;
alpha_2_to_name_upper(<<"VG">>) -> <<"British Virgin Islands">>;
alpha_2_to_name_upper(<<"IO">>) -> <<"British Indian Ocean Territory">>;
alpha_2_to_name_upper(<<"BN">>) -> <<"Brunei Darussalam">>;
alpha_2_to_name_upper(<<"BG">>) -> <<"Bulgaria">>;
alpha_2_to_name_upper(<<"BF">>) -> <<"Burkina Faso">>;
alpha_2_to_name_upper(<<"BI">>) -> <<"Burundi">>;
alpha_2_to_name_upper(<<"KH">>) -> <<"Cambodia">>;
alpha_2_to_name_upper(<<"CM">>) -> <<"Cameroon">>;
alpha_2_to_name_upper(<<"CA">>) -> <<"Canada">>;
alpha_2_to_name_upper(<<"CV">>) -> <<"Cape Verde">>;
alpha_2_to_name_upper(<<"KY">>) -> <<"Cayman Islands">>;
alpha_2_to_name_upper(<<"CF">>) -> <<"Central African Republic">>;
alpha_2_to_name_upper(<<"TD">>) -> <<"Chad">>;
alpha_2_to_name_upper(<<"CL">>) -> <<"Chile">>;
alpha_2_to_name_upper(<<"CN">>) -> <<"China">>;
alpha_2_to_name_upper(<<"HK">>) -> <<"Hong Kong, Special Administrative Region of China">>;
alpha_2_to_name_upper(<<"MO">>) -> <<"Macao, Special Administrative Region of China">>;
alpha_2_to_name_upper(<<"CX">>) -> <<"Christmas Island">>;
alpha_2_to_name_upper(<<"CC">>) -> <<"Cocos (Keeling) Islands">>;
alpha_2_to_name_upper(<<"CO">>) -> <<"Colombia">>;
alpha_2_to_name_upper(<<"KM">>) -> <<"Comoros">>;
alpha_2_to_name_upper(<<"CG">>) -> <<"Congo (Brazzaville)">>;
alpha_2_to_name_upper(<<"CD">>) -> <<"Democratic Republic of the Congo">>;
alpha_2_to_name_upper(<<"CK">>) -> <<"Cook Islands">>;
alpha_2_to_name_upper(<<"CR">>) -> <<"Costa Rica">>;
alpha_2_to_name_upper(<<"CI">>) -> <<"Côte d'Ivoire">>;
alpha_2_to_name_upper(<<"HR">>) -> <<"Croatia">>;
alpha_2_to_name_upper(<<"CU">>) -> <<"Cuba">>;
alpha_2_to_name_upper(<<"CY">>) -> <<"Cyprus">>;
alpha_2_to_name_upper(<<"CZ">>) -> <<"Czech Republic">>;
alpha_2_to_name_upper(<<"DK">>) -> <<"Denmark">>;
alpha_2_to_name_upper(<<"DJ">>) -> <<"Djibouti">>;
alpha_2_to_name_upper(<<"DM">>) -> <<"Dominica">>;
alpha_2_to_name_upper(<<"DO">>) -> <<"Dominican Republic">>;
alpha_2_to_name_upper(<<"EC">>) -> <<"Ecuador">>;
alpha_2_to_name_upper(<<"EG">>) -> <<"Egypt">>;
alpha_2_to_name_upper(<<"SV">>) -> <<"El Salvador">>;
alpha_2_to_name_upper(<<"GQ">>) -> <<"Equatorial Guinea">>;
alpha_2_to_name_upper(<<"ER">>) -> <<"Eritrea">>;
alpha_2_to_name_upper(<<"EE">>) -> <<"Estonia">>;
alpha_2_to_name_upper(<<"ET">>) -> <<"Ethiopia">>;
alpha_2_to_name_upper(<<"FK">>) -> <<"Falkland Islands (Malvinas)">>;
alpha_2_to_name_upper(<<"FO">>) -> <<"Faroe Islands">>;
alpha_2_to_name_upper(<<"FJ">>) -> <<"Fiji">>;
alpha_2_to_name_upper(<<"FI">>) -> <<"Finland">>;
alpha_2_to_name_upper(<<"FR">>) -> <<"France">>;
alpha_2_to_name_upper(<<"GF">>) -> <<"French Guiana">>;
alpha_2_to_name_upper(<<"PF">>) -> <<"French Polynesia">>;
alpha_2_to_name_upper(<<"TF">>) -> <<"French Southern Territories">>;
alpha_2_to_name_upper(<<"GA">>) -> <<"Gabon">>;
alpha_2_to_name_upper(<<"GM">>) -> <<"Gambia">>;
alpha_2_to_name_upper(<<"GE">>) -> <<"Georgia">>;
alpha_2_to_name_upper(<<"DE">>) -> <<"Germany">>;
alpha_2_to_name_upper(<<"GH">>) -> <<"Ghana">>;
alpha_2_to_name_upper(<<"GI">>) -> <<"Gibraltar">>;
alpha_2_to_name_upper(<<"GR">>) -> <<"Greece">>;
alpha_2_to_name_upper(<<"GL">>) -> <<"Greenland">>;
alpha_2_to_name_upper(<<"GD">>) -> <<"Grenada">>;
alpha_2_to_name_upper(<<"GP">>) -> <<"Guadeloupe">>;
alpha_2_to_name_upper(<<"GU">>) -> <<"Guam">>;
alpha_2_to_name_upper(<<"GT">>) -> <<"Guatemala">>;
alpha_2_to_name_upper(<<"GG">>) -> <<"Guernsey">>;
alpha_2_to_name_upper(<<"GN">>) -> <<"Guinea">>;
alpha_2_to_name_upper(<<"GW">>) -> <<"Guinea-Bissau">>;
alpha_2_to_name_upper(<<"GY">>) -> <<"Guyana">>;
alpha_2_to_name_upper(<<"HT">>) -> <<"Haiti">>;
alpha_2_to_name_upper(<<"HM">>) -> <<"Heard Island and Mcdonald Islands">>;
alpha_2_to_name_upper(<<"VA">>) -> <<"Holy See (Vatican City State)">>;
alpha_2_to_name_upper(<<"HN">>) -> <<"Honduras">>;
alpha_2_to_name_upper(<<"HU">>) -> <<"Hungary">>;
alpha_2_to_name_upper(<<"IS">>) -> <<"Iceland">>;
alpha_2_to_name_upper(<<"IN">>) -> <<"India">>;
alpha_2_to_name_upper(<<"ID">>) -> <<"Indonesia">>;
alpha_2_to_name_upper(<<"IR">>) -> <<"Iran">>;
alpha_2_to_name_upper(<<"IQ">>) -> <<"Iraq">>;
alpha_2_to_name_upper(<<"IE">>) -> <<"Ireland">>;
alpha_2_to_name_upper(<<"IM">>) -> <<"Isle of Man">>;
alpha_2_to_name_upper(<<"IL">>) -> <<"Israel">>;
alpha_2_to_name_upper(<<"IT">>) -> <<"Italy">>;
alpha_2_to_name_upper(<<"JM">>) -> <<"Jamaica">>;
alpha_2_to_name_upper(<<"JP">>) -> <<"Japan">>;
alpha_2_to_name_upper(<<"JE">>) -> <<"Jersey">>;
alpha_2_to_name_upper(<<"JO">>) -> <<"Jordan">>;
alpha_2_to_name_upper(<<"KZ">>) -> <<"Kazakhstan">>;
alpha_2_to_name_upper(<<"KE">>) -> <<"Kenya">>;
alpha_2_to_name_upper(<<"KI">>) -> <<"Kiribati">>;
alpha_2_to_name_upper(<<"KP">>) -> <<"Democratic People's Republic of Korea">>;
alpha_2_to_name_upper(<<"KR">>) -> <<"Republic of Korea">>;
alpha_2_to_name_upper(<<"KW">>) -> <<"Kuwait">>;
alpha_2_to_name_upper(<<"KG">>) -> <<"Kyrgyzstan">>;
alpha_2_to_name_upper(<<"LA">>) -> <<"Lao PDR">>;
alpha_2_to_name_upper(<<"LV">>) -> <<"Latvia">>;
alpha_2_to_name_upper(<<"LB">>) -> <<"Lebanon">>;
alpha_2_to_name_upper(<<"LS">>) -> <<"Lesotho">>;
alpha_2_to_name_upper(<<"LR">>) -> <<"Liberia">>;
alpha_2_to_name_upper(<<"LY">>) -> <<"Libya">>;
alpha_2_to_name_upper(<<"LI">>) -> <<"Liechtenstein">>;
alpha_2_to_name_upper(<<"LT">>) -> <<"Lithuania">>;
alpha_2_to_name_upper(<<"LU">>) -> <<"Luxembourg">>;
alpha_2_to_name_upper(<<"MK">>) -> <<"Republic of Macedonia">>;
alpha_2_to_name_upper(<<"MG">>) -> <<"Madagascar">>;
alpha_2_to_name_upper(<<"MW">>) -> <<"Malawi">>;
alpha_2_to_name_upper(<<"MY">>) -> <<"Malaysia">>;
alpha_2_to_name_upper(<<"MV">>) -> <<"Maldives">>;
alpha_2_to_name_upper(<<"ML">>) -> <<"Mali">>;
alpha_2_to_name_upper(<<"MT">>) -> <<"Malta">>;
alpha_2_to_name_upper(<<"MH">>) -> <<"Marshall Islands">>;
alpha_2_to_name_upper(<<"MQ">>) -> <<"Martinique">>;
alpha_2_to_name_upper(<<"MR">>) -> <<"Mauritania">>;
alpha_2_to_name_upper(<<"MU">>) -> <<"Mauritius">>;
alpha_2_to_name_upper(<<"YT">>) -> <<"Mayotte">>;
alpha_2_to_name_upper(<<"MX">>) -> <<"Mexico">>;
alpha_2_to_name_upper(<<"FM">>) -> <<"Federated States of Micronesia">>;
alpha_2_to_name_upper(<<"MD">>) -> <<"Moldova">>;
alpha_2_to_name_upper(<<"MC">>) -> <<"Monaco">>;
alpha_2_to_name_upper(<<"MN">>) -> <<"Mongolia">>;
alpha_2_to_name_upper(<<"ME">>) -> <<"Montenegro">>;
alpha_2_to_name_upper(<<"MS">>) -> <<"Montserrat">>;
alpha_2_to_name_upper(<<"MA">>) -> <<"Morocco">>;
alpha_2_to_name_upper(<<"MZ">>) -> <<"Mozambique">>;
alpha_2_to_name_upper(<<"MM">>) -> <<"Myanmar">>;
alpha_2_to_name_upper(<<"NA">>) -> <<"Namibia">>;
alpha_2_to_name_upper(<<"NR">>) -> <<"Nauru">>;
alpha_2_to_name_upper(<<"NP">>) -> <<"Nepal">>;
alpha_2_to_name_upper(<<"NL">>) -> <<"Netherlands">>;
alpha_2_to_name_upper(<<"AN">>) -> <<"Netherlands Antilles">>;
alpha_2_to_name_upper(<<"NC">>) -> <<"New Caledonia">>;
alpha_2_to_name_upper(<<"NZ">>) -> <<"New Zealand">>;
alpha_2_to_name_upper(<<"NI">>) -> <<"Nicaragua">>;
alpha_2_to_name_upper(<<"NE">>) -> <<"Niger">>;
alpha_2_to_name_upper(<<"NG">>) -> <<"Nigeria">>;
alpha_2_to_name_upper(<<"NU">>) -> <<"Niue">>;
alpha_2_to_name_upper(<<"NF">>) -> <<"Norfolk Island">>;
alpha_2_to_name_upper(<<"MP">>) -> <<"Northern Mariana Islands">>;
alpha_2_to_name_upper(<<"NO">>) -> <<"Norway">>;
alpha_2_to_name_upper(<<"OM">>) -> <<"Oman">>;
alpha_2_to_name_upper(<<"PK">>) -> <<"Pakistan">>;
alpha_2_to_name_upper(<<"PW">>) -> <<"Palau">>;
alpha_2_to_name_upper(<<"PS">>) -> <<"Palestine">>;
alpha_2_to_name_upper(<<"PA">>) -> <<"Panama">>;
alpha_2_to_name_upper(<<"PG">>) -> <<"Papua New Guinea">>;
alpha_2_to_name_upper(<<"PY">>) -> <<"Paraguay">>;
alpha_2_to_name_upper(<<"PE">>) -> <<"Peru">>;
alpha_2_to_name_upper(<<"PH">>) -> <<"Philippines">>;
alpha_2_to_name_upper(<<"PN">>) -> <<"Pitcairn">>;
alpha_2_to_name_upper(<<"PL">>) -> <<"Poland">>;
alpha_2_to_name_upper(<<"PT">>) -> <<"Portugal">>;
alpha_2_to_name_upper(<<"PR">>) -> <<"Puerto Rico">>;
alpha_2_to_name_upper(<<"QA">>) -> <<"Qatar">>;
alpha_2_to_name_upper(<<"RE">>) -> <<"Réunion">>;
alpha_2_to_name_upper(<<"RO">>) -> <<"Romania">>;
alpha_2_to_name_upper(<<"RU">>) -> <<"Russian Federation">>;
alpha_2_to_name_upper(<<"RW">>) -> <<"Rwanda">>;
alpha_2_to_name_upper(<<"BL">>) -> <<"Saint-Barthélemy">>;
alpha_2_to_name_upper(<<"SH">>) -> <<"Saint Helena">>;
alpha_2_to_name_upper(<<"KN">>) -> <<"Saint Kitts and Nevis">>;
alpha_2_to_name_upper(<<"LC">>) -> <<"Saint Lucia">>;
alpha_2_to_name_upper(<<"MF">>) -> <<"Saint-Martin (French part)">>;
alpha_2_to_name_upper(<<"PM">>) -> <<"Saint Pierre and Miquelon">>;
alpha_2_to_name_upper(<<"VC">>) -> <<"Saint Vincent and Grenadines">>;
alpha_2_to_name_upper(<<"WS">>) -> <<"Samoa">>;
alpha_2_to_name_upper(<<"SM">>) -> <<"San Marino">>;
alpha_2_to_name_upper(<<"ST">>) -> <<"Sao Tome and Principe">>;
alpha_2_to_name_upper(<<"SA">>) -> <<"Saudi Arabia">>;
alpha_2_to_name_upper(<<"SN">>) -> <<"Senegal">>;
alpha_2_to_name_upper(<<"RS">>) -> <<"Serbia">>;
alpha_2_to_name_upper(<<"SC">>) -> <<"Seychelles">>;
alpha_2_to_name_upper(<<"SL">>) -> <<"Sierra Leone">>;
alpha_2_to_name_upper(<<"SG">>) -> <<"Singapore">>;
alpha_2_to_name_upper(<<"SK">>) -> <<"Slovakia">>;
alpha_2_to_name_upper(<<"SI">>) -> <<"Slovenia">>;
alpha_2_to_name_upper(<<"SB">>) -> <<"Solomon Islands">>;
alpha_2_to_name_upper(<<"SO">>) -> <<"Somalia">>;
alpha_2_to_name_upper(<<"ZA">>) -> <<"South Africa">>;
alpha_2_to_name_upper(<<"GS">>) -> <<"South Georgia and the South Sandwich Islands">>;
alpha_2_to_name_upper(<<"SS">>) -> <<"South Sudan">>;
alpha_2_to_name_upper(<<"ES">>) -> <<"Spain">>;
alpha_2_to_name_upper(<<"LK">>) -> <<"Sri Lanka">>;
alpha_2_to_name_upper(<<"SD">>) -> <<"Sudan">>;
alpha_2_to_name_upper(<<"SR">>) -> <<"Suriname *">>;
alpha_2_to_name_upper(<<"SJ">>) -> <<"Svalbard and Jan Mayen Islands">>;
alpha_2_to_name_upper(<<"SZ">>) -> <<"Swaziland">>;
alpha_2_to_name_upper(<<"SE">>) -> <<"Sweden">>;
alpha_2_to_name_upper(<<"CH">>) -> <<"Switzerland">>;
alpha_2_to_name_upper(<<"SY">>) -> <<"Syrian Arab Republic (Syria)">>;
alpha_2_to_name_upper(<<"TW">>) -> <<"Taiwan, Republic of China">>;
alpha_2_to_name_upper(<<"TJ">>) -> <<"Tajikistan">>;
alpha_2_to_name_upper(<<"TZ">>) -> <<"Tanzania">>;
alpha_2_to_name_upper(<<"TH">>) -> <<"Thailand">>;
alpha_2_to_name_upper(<<"TL">>) -> <<"Timor-Leste">>;
alpha_2_to_name_upper(<<"TG">>) -> <<"Togo">>;
alpha_2_to_name_upper(<<"TK">>) -> <<"Tokelau">>;
alpha_2_to_name_upper(<<"TO">>) -> <<"Tonga">>;
alpha_2_to_name_upper(<<"TT">>) -> <<"Trinidad and Tobago">>;
alpha_2_to_name_upper(<<"TN">>) -> <<"Tunisia">>;
alpha_2_to_name_upper(<<"TR">>) -> <<"Turkey">>;
alpha_2_to_name_upper(<<"TM">>) -> <<"Turkmenistan">>;
alpha_2_to_name_upper(<<"TC">>) -> <<"Turks and Caicos Islands">>;
alpha_2_to_name_upper(<<"TV">>) -> <<"Tuvalu">>;
alpha_2_to_name_upper(<<"UG">>) -> <<"Uganda">>;
alpha_2_to_name_upper(<<"UA">>) -> <<"Ukraine">>;
alpha_2_to_name_upper(<<"AE">>) -> <<"United Arab Emirates">>;
alpha_2_to_name_upper(<<"GB">>) -> <<"United Kingdom">>;
alpha_2_to_name_upper(<<"US">>) -> <<"United States of America">>;
alpha_2_to_name_upper(<<"UM">>) -> <<"United States Minor Outlying Islands">>;
alpha_2_to_name_upper(<<"UY">>) -> <<"Uruguay">>;
alpha_2_to_name_upper(<<"UZ">>) -> <<"Uzbekistan">>;
alpha_2_to_name_upper(<<"VU">>) -> <<"Vanuatu">>;
alpha_2_to_name_upper(<<"VE">>) -> <<"Venezuela (Bolivarian Republic of)">>;
alpha_2_to_name_upper(<<"VN">>) -> <<"Viet Nam">>;
alpha_2_to_name_upper(<<"VI">>) -> <<"US Virgin Islands">>;
alpha_2_to_name_upper(<<"WF">>) -> <<"Wallis and Futuna Islands">>;
alpha_2_to_name_upper(<<"EH">>) -> <<"Western Sahara">>;
alpha_2_to_name_upper(<<"YE">>) -> <<"Yemen">>;
alpha_2_to_name_upper(<<"ZM">>) -> <<"Zambia">>;
alpha_2_to_name_upper(<<"ZW">>) -> <<"Zimbabwe">>.

%% @doc Converts three letter country code (ISO alpha-3) to the equivalent country name.
%%      This is case-sensitive (Expects uppercase).
%% @end
country_alpha_3_to_name_upper(<<"AFG">>) -> <<"Afghanistan">>;
country_alpha_3_to_name_upper(<<"ALA">>) -> <<"Aland Islands">>;
country_alpha_3_to_name_upper(<<"ALB">>) -> <<"Albania">>;
country_alpha_3_to_name_upper(<<"DZA">>) -> <<"Algeria">>;
country_alpha_3_to_name_upper(<<"ASM">>) -> <<"American Samoa">>;
country_alpha_3_to_name_upper(<<"AND">>) -> <<"Andorra">>;
country_alpha_3_to_name_upper(<<"AGO">>) -> <<"Angola">>;
country_alpha_3_to_name_upper(<<"AIA">>) -> <<"Anguilla">>;
country_alpha_3_to_name_upper(<<"ATA">>) -> <<"Antarctica">>;
country_alpha_3_to_name_upper(<<"ATG">>) -> <<"Antigua and Barbuda">>;
country_alpha_3_to_name_upper(<<"ARG">>) -> <<"Argentina">>;
country_alpha_3_to_name_upper(<<"ARM">>) -> <<"Armenia">>;
country_alpha_3_to_name_upper(<<"ABW">>) -> <<"Aruba">>;
country_alpha_3_to_name_upper(<<"AUS">>) -> <<"Australia">>;
country_alpha_3_to_name_upper(<<"AUT">>) -> <<"Austria">>;
country_alpha_3_to_name_upper(<<"AZE">>) -> <<"Azerbaijan">>;
country_alpha_3_to_name_upper(<<"BHS">>) -> <<"Bahamas">>;
country_alpha_3_to_name_upper(<<"BHR">>) -> <<"Bahrain">>;
country_alpha_3_to_name_upper(<<"BGD">>) -> <<"Bangladesh">>;
country_alpha_3_to_name_upper(<<"BRB">>) -> <<"Barbados">>;
country_alpha_3_to_name_upper(<<"BLR">>) -> <<"Belarus">>;
country_alpha_3_to_name_upper(<<"BEL">>) -> <<"Belgium">>;
country_alpha_3_to_name_upper(<<"BLZ">>) -> <<"Belize">>;
country_alpha_3_to_name_upper(<<"BEN">>) -> <<"Benin">>;
country_alpha_3_to_name_upper(<<"BMU">>) -> <<"Bermuda">>;
country_alpha_3_to_name_upper(<<"BTN">>) -> <<"Bhutan">>;
country_alpha_3_to_name_upper(<<"BOL">>) -> <<"Bolivia">>;
country_alpha_3_to_name_upper(<<"BIH">>) -> <<"Bosnia and Herzegovina">>;
country_alpha_3_to_name_upper(<<"BWA">>) -> <<"Botswana">>;
country_alpha_3_to_name_upper(<<"BVT">>) -> <<"Bouvet Island">>;
country_alpha_3_to_name_upper(<<"BRA">>) -> <<"Brazil">>;
country_alpha_3_to_name_upper(<<"VGB">>) -> <<"British Virgin Islands">>;
country_alpha_3_to_name_upper(<<"IOT">>) -> <<"British Indian Ocean Territory">>;
country_alpha_3_to_name_upper(<<"BRN">>) -> <<"Brunei Darussalam">>;
country_alpha_3_to_name_upper(<<"BGR">>) -> <<"Bulgaria">>;
country_alpha_3_to_name_upper(<<"BFA">>) -> <<"Burkina Faso">>;
country_alpha_3_to_name_upper(<<"BDI">>) -> <<"Burundi">>;
country_alpha_3_to_name_upper(<<"KHM">>) -> <<"Cambodia">>;
country_alpha_3_to_name_upper(<<"CMR">>) -> <<"Cameroon">>;
country_alpha_3_to_name_upper(<<"CAN">>) -> <<"Canada">>;
country_alpha_3_to_name_upper(<<"CPV">>) -> <<"Cape Verde">>;
country_alpha_3_to_name_upper(<<"CYM">>) -> <<"Cayman Islands">>;
country_alpha_3_to_name_upper(<<"CAF">>) -> <<"Central African Republic">>;
country_alpha_3_to_name_upper(<<"TCD">>) -> <<"Chad">>;
country_alpha_3_to_name_upper(<<"CHL">>) -> <<"Chile">>;
country_alpha_3_to_name_upper(<<"CHN">>) -> <<"China">>;
country_alpha_3_to_name_upper(<<"HKG">>) -> <<"Hong Kong, Special Administrative Region of China">>;
country_alpha_3_to_name_upper(<<"MAC">>) -> <<"Macao, Special Administrative Region of China">>;
country_alpha_3_to_name_upper(<<"CXR">>) -> <<"Christmas Island">>;
country_alpha_3_to_name_upper(<<"CCK">>) -> <<"Cocos (Keeling) Islands">>;
country_alpha_3_to_name_upper(<<"COL">>) -> <<"Colombia">>;
country_alpha_3_to_name_upper(<<"COM">>) -> <<"Comoros">>;
country_alpha_3_to_name_upper(<<"COG">>) -> <<"Congo (Brazzaville)">>;
country_alpha_3_to_name_upper(<<"COD">>) -> <<"Democratic Republic of the Congo">>;
country_alpha_3_to_name_upper(<<"COK">>) -> <<"Cook Islands">>;
country_alpha_3_to_name_upper(<<"CRI">>) -> <<"Costa Rica">>;
country_alpha_3_to_name_upper(<<"CIV">>) -> <<"Côte d'Ivoire">>;
country_alpha_3_to_name_upper(<<"HRV">>) -> <<"Croatia">>;
country_alpha_3_to_name_upper(<<"CUB">>) -> <<"Cuba">>;
country_alpha_3_to_name_upper(<<"CYP">>) -> <<"Cyprus">>;
country_alpha_3_to_name_upper(<<"CZE">>) -> <<"Czech Republic">>;
country_alpha_3_to_name_upper(<<"DNK">>) -> <<"Denmark">>;
country_alpha_3_to_name_upper(<<"DJI">>) -> <<"Djibouti">>;
country_alpha_3_to_name_upper(<<"DMA">>) -> <<"Dominica">>;
country_alpha_3_to_name_upper(<<"DOM">>) -> <<"Dominican Republic">>;
country_alpha_3_to_name_upper(<<"ECU">>) -> <<"Ecuador">>;
country_alpha_3_to_name_upper(<<"EGY">>) -> <<"Egypt">>;
country_alpha_3_to_name_upper(<<"SLV">>) -> <<"El Salvador">>;
country_alpha_3_to_name_upper(<<"GNQ">>) -> <<"Equatorial Guinea">>;
country_alpha_3_to_name_upper(<<"ERI">>) -> <<"Eritrea">>;
country_alpha_3_to_name_upper(<<"EST">>) -> <<"Estonia">>;
country_alpha_3_to_name_upper(<<"ETH">>) -> <<"Ethiopia">>;
country_alpha_3_to_name_upper(<<"FLK">>) -> <<"Falkland Islands (Malvinas)">>;
country_alpha_3_to_name_upper(<<"FRO">>) -> <<"Faroe Islands">>;
country_alpha_3_to_name_upper(<<"FJI">>) -> <<"Fiji">>;
country_alpha_3_to_name_upper(<<"FIN">>) -> <<"Finland">>;
country_alpha_3_to_name_upper(<<"FRA">>) -> <<"France">>;
country_alpha_3_to_name_upper(<<"GUF">>) -> <<"French Guiana">>;
country_alpha_3_to_name_upper(<<"PYF">>) -> <<"French Polynesia">>;
country_alpha_3_to_name_upper(<<"ATF">>) -> <<"French Southern Territories">>;
country_alpha_3_to_name_upper(<<"GAB">>) -> <<"Gabon">>;
country_alpha_3_to_name_upper(<<"GMB">>) -> <<"Gambia">>;
country_alpha_3_to_name_upper(<<"GEO">>) -> <<"Georgia">>;
country_alpha_3_to_name_upper(<<"DEU">>) -> <<"Germany">>;
country_alpha_3_to_name_upper(<<"GHA">>) -> <<"Ghana">>;
country_alpha_3_to_name_upper(<<"GIB">>) -> <<"Gibraltar">>;
country_alpha_3_to_name_upper(<<"GRC">>) -> <<"Greece">>;
country_alpha_3_to_name_upper(<<"GRL">>) -> <<"Greenland">>;
country_alpha_3_to_name_upper(<<"GRD">>) -> <<"Grenada">>;
country_alpha_3_to_name_upper(<<"GLP">>) -> <<"Guadeloupe">>;
country_alpha_3_to_name_upper(<<"GUM">>) -> <<"Guam">>;
country_alpha_3_to_name_upper(<<"GTM">>) -> <<"Guatemala">>;
country_alpha_3_to_name_upper(<<"GGY">>) -> <<"Guernsey">>;
country_alpha_3_to_name_upper(<<"GIN">>) -> <<"Guinea">>;
country_alpha_3_to_name_upper(<<"GNB">>) -> <<"Guinea-Bissau">>;
country_alpha_3_to_name_upper(<<"GUY">>) -> <<"Guyana">>;
country_alpha_3_to_name_upper(<<"HTI">>) -> <<"Haiti">>;
country_alpha_3_to_name_upper(<<"HMD">>) -> <<"Heard Island and Mcdonald Islands">>;
country_alpha_3_to_name_upper(<<"VAT">>) -> <<"Holy See (Vatican City State)">>;
country_alpha_3_to_name_upper(<<"HND">>) -> <<"Honduras">>;
country_alpha_3_to_name_upper(<<"HUN">>) -> <<"Hungary">>;
country_alpha_3_to_name_upper(<<"ISL">>) -> <<"Iceland">>;
country_alpha_3_to_name_upper(<<"IND">>) -> <<"India">>;
country_alpha_3_to_name_upper(<<"IDN">>) -> <<"Indonesia">>;
country_alpha_3_to_name_upper(<<"IRN">>) -> <<"Iran">>;
country_alpha_3_to_name_upper(<<"IRQ">>) -> <<"Iraq">>;
country_alpha_3_to_name_upper(<<"IRL">>) -> <<"Ireland">>;
country_alpha_3_to_name_upper(<<"IMN">>) -> <<"Isle of Man">>;
country_alpha_3_to_name_upper(<<"ISR">>) -> <<"Israel">>;
country_alpha_3_to_name_upper(<<"ITA">>) -> <<"Italy">>;
country_alpha_3_to_name_upper(<<"JAM">>) -> <<"Jamaica">>;
country_alpha_3_to_name_upper(<<"JPN">>) -> <<"Japan">>;
country_alpha_3_to_name_upper(<<"JEY">>) -> <<"Jersey">>;
country_alpha_3_to_name_upper(<<"JOR">>) -> <<"Jordan">>;
country_alpha_3_to_name_upper(<<"KAZ">>) -> <<"Kazakhstan">>;
country_alpha_3_to_name_upper(<<"KEN">>) -> <<"Kenya">>;
country_alpha_3_to_name_upper(<<"KIR">>) -> <<"Kiribati">>;
country_alpha_3_to_name_upper(<<"PRK">>) -> <<"Democratic People's Republic of Korea">>;
country_alpha_3_to_name_upper(<<"KOR">>) -> <<"Republic of Korea">>;
country_alpha_3_to_name_upper(<<"KWT">>) -> <<"Kuwait">>;
country_alpha_3_to_name_upper(<<"KGZ">>) -> <<"Kyrgyzstan">>;
country_alpha_3_to_name_upper(<<"LAO">>) -> <<"Lao PDR">>;
country_alpha_3_to_name_upper(<<"LVA">>) -> <<"Latvia">>;
country_alpha_3_to_name_upper(<<"LBN">>) -> <<"Lebanon">>;
country_alpha_3_to_name_upper(<<"LSO">>) -> <<"Lesotho">>;
country_alpha_3_to_name_upper(<<"LBR">>) -> <<"Liberia">>;
country_alpha_3_to_name_upper(<<"LBY">>) -> <<"Libya">>;
country_alpha_3_to_name_upper(<<"LIE">>) -> <<"Liechtenstein">>;
country_alpha_3_to_name_upper(<<"LTU">>) -> <<"Lithuania">>;
country_alpha_3_to_name_upper(<<"LUX">>) -> <<"Luxembourg">>;
country_alpha_3_to_name_upper(<<"MKD">>) -> <<"Republic of Macedonia">>;
country_alpha_3_to_name_upper(<<"MDG">>) -> <<"Madagascar">>;
country_alpha_3_to_name_upper(<<"MWI">>) -> <<"Malawi">>;
country_alpha_3_to_name_upper(<<"MYS">>) -> <<"Malaysia">>;
country_alpha_3_to_name_upper(<<"MDV">>) -> <<"Maldives">>;
country_alpha_3_to_name_upper(<<"MLI">>) -> <<"Mali">>;
country_alpha_3_to_name_upper(<<"MLT">>) -> <<"Malta">>;
country_alpha_3_to_name_upper(<<"MHL">>) -> <<"Marshall Islands">>;
country_alpha_3_to_name_upper(<<"MTQ">>) -> <<"Martinique">>;
country_alpha_3_to_name_upper(<<"MRT">>) -> <<"Mauritania">>;
country_alpha_3_to_name_upper(<<"MUS">>) -> <<"Mauritius">>;
country_alpha_3_to_name_upper(<<"MYT">>) -> <<"Mayotte">>;
country_alpha_3_to_name_upper(<<"MEX">>) -> <<"Mexico">>;
country_alpha_3_to_name_upper(<<"FSM">>) -> <<"Federated States of Micronesia">>;
country_alpha_3_to_name_upper(<<"MDA">>) -> <<"Moldova">>;
country_alpha_3_to_name_upper(<<"MCO">>) -> <<"Monaco">>;
country_alpha_3_to_name_upper(<<"MNG">>) -> <<"Mongolia">>;
country_alpha_3_to_name_upper(<<"MNE">>) -> <<"Montenegro">>;
country_alpha_3_to_name_upper(<<"MSR">>) -> <<"Montserrat">>;
country_alpha_3_to_name_upper(<<"MAR">>) -> <<"Morocco">>;
country_alpha_3_to_name_upper(<<"MOZ">>) -> <<"Mozambique">>;
country_alpha_3_to_name_upper(<<"MMR">>) -> <<"Myanmar">>;
country_alpha_3_to_name_upper(<<"NAM">>) -> <<"Namibia">>;
country_alpha_3_to_name_upper(<<"NRU">>) -> <<"Nauru">>;
country_alpha_3_to_name_upper(<<"NPL">>) -> <<"Nepal">>;
country_alpha_3_to_name_upper(<<"NLD">>) -> <<"Netherlands">>;
country_alpha_3_to_name_upper(<<"ANT">>) -> <<"Netherlands Antilles">>;
country_alpha_3_to_name_upper(<<"NCL">>) -> <<"New Caledonia">>;
country_alpha_3_to_name_upper(<<"NZL">>) -> <<"New Zealand">>;
country_alpha_3_to_name_upper(<<"NIC">>) -> <<"Nicaragua">>;
country_alpha_3_to_name_upper(<<"NER">>) -> <<"Niger">>;
country_alpha_3_to_name_upper(<<"NGA">>) -> <<"Nigeria">>;
country_alpha_3_to_name_upper(<<"NIU">>) -> <<"Niue">>;
country_alpha_3_to_name_upper(<<"NFK">>) -> <<"Norfolk Island">>;
country_alpha_3_to_name_upper(<<"MNP">>) -> <<"Northern Mariana Islands">>;
country_alpha_3_to_name_upper(<<"NOR">>) -> <<"Norway">>;
country_alpha_3_to_name_upper(<<"OMN">>) -> <<"Oman">>;
country_alpha_3_to_name_upper(<<"PAK">>) -> <<"Pakistan">>;
country_alpha_3_to_name_upper(<<"PLW">>) -> <<"Palau">>;
country_alpha_3_to_name_upper(<<"PSE">>) -> <<"Palestine">>;
country_alpha_3_to_name_upper(<<"PAN">>) -> <<"Panama">>;
country_alpha_3_to_name_upper(<<"PNG">>) -> <<"Papua New Guinea">>;
country_alpha_3_to_name_upper(<<"PRY">>) -> <<"Paraguay">>;
country_alpha_3_to_name_upper(<<"PER">>) -> <<"Peru">>;
country_alpha_3_to_name_upper(<<"PHL">>) -> <<"Philippines">>;
country_alpha_3_to_name_upper(<<"PCN">>) -> <<"Pitcairn">>;
country_alpha_3_to_name_upper(<<"POL">>) -> <<"Poland">>;
country_alpha_3_to_name_upper(<<"PRT">>) -> <<"Portugal">>;
country_alpha_3_to_name_upper(<<"PRI">>) -> <<"Puerto Rico">>;
country_alpha_3_to_name_upper(<<"QAT">>) -> <<"Qatar">>;
country_alpha_3_to_name_upper(<<"REU">>) -> <<"Réunion">>;
country_alpha_3_to_name_upper(<<"ROU">>) -> <<"Romania">>;
country_alpha_3_to_name_upper(<<"RUS">>) -> <<"Russian Federation">>;
country_alpha_3_to_name_upper(<<"RWA">>) -> <<"Rwanda">>;
country_alpha_3_to_name_upper(<<"BLM">>) -> <<"Saint-Barthélemy">>;
country_alpha_3_to_name_upper(<<"SHN">>) -> <<"Saint Helena">>;
country_alpha_3_to_name_upper(<<"KNA">>) -> <<"Saint Kitts and Nevis">>;
country_alpha_3_to_name_upper(<<"LCA">>) -> <<"Saint Lucia">>;
country_alpha_3_to_name_upper(<<"MAF">>) -> <<"Saint-Martin (French part)">>;
country_alpha_3_to_name_upper(<<"SPM">>) -> <<"Saint Pierre and Miquelon">>;
country_alpha_3_to_name_upper(<<"VCT">>) -> <<"Saint Vincent and Grenadines">>;
country_alpha_3_to_name_upper(<<"WSM">>) -> <<"Samoa">>;
country_alpha_3_to_name_upper(<<"SMR">>) -> <<"San Marino">>;
country_alpha_3_to_name_upper(<<"STP">>) -> <<"Sao Tome and Principe">>;
country_alpha_3_to_name_upper(<<"SAU">>) -> <<"Saudi Arabia">>;
country_alpha_3_to_name_upper(<<"SEN">>) -> <<"Senegal">>;
country_alpha_3_to_name_upper(<<"SRB">>) -> <<"Serbia">>;
country_alpha_3_to_name_upper(<<"SYC">>) -> <<"Seychelles">>;
country_alpha_3_to_name_upper(<<"SLE">>) -> <<"Sierra Leone">>;
country_alpha_3_to_name_upper(<<"SGP">>) -> <<"Singapore">>;
country_alpha_3_to_name_upper(<<"SVK">>) -> <<"Slovakia">>;
country_alpha_3_to_name_upper(<<"SVN">>) -> <<"Slovenia">>;
country_alpha_3_to_name_upper(<<"SLB">>) -> <<"Solomon Islands">>;
country_alpha_3_to_name_upper(<<"SOM">>) -> <<"Somalia">>;
country_alpha_3_to_name_upper(<<"ZAF">>) -> <<"South Africa">>;
country_alpha_3_to_name_upper(<<"SGS">>) -> <<"South Georgia and the South Sandwich Islands">>;
country_alpha_3_to_name_upper(<<"SSD">>) -> <<"South Sudan">>;
country_alpha_3_to_name_upper(<<"ESP">>) -> <<"Spain">>;
country_alpha_3_to_name_upper(<<"LKA">>) -> <<"Sri Lanka">>;
country_alpha_3_to_name_upper(<<"SDN">>) -> <<"Sudan">>;
country_alpha_3_to_name_upper(<<"SUR">>) -> <<"Suriname *">>;
country_alpha_3_to_name_upper(<<"SJM">>) -> <<"Svalbard and Jan Mayen Islands">>;
country_alpha_3_to_name_upper(<<"SWZ">>) -> <<"Swaziland">>;
country_alpha_3_to_name_upper(<<"SWE">>) -> <<"Sweden">>;
country_alpha_3_to_name_upper(<<"CHE">>) -> <<"Switzerland">>;
country_alpha_3_to_name_upper(<<"SYR">>) -> <<"Syrian Arab Republic (Syria)">>;
country_alpha_3_to_name_upper(<<"TWN">>) -> <<"Taiwan, Republic of China">>;
country_alpha_3_to_name_upper(<<"TJK">>) -> <<"Tajikistan">>;
country_alpha_3_to_name_upper(<<"TZA">>) -> <<"Tanzania">>;
country_alpha_3_to_name_upper(<<"THA">>) -> <<"Thailand">>;
country_alpha_3_to_name_upper(<<"TLS">>) -> <<"Timor-Leste">>;
country_alpha_3_to_name_upper(<<"TGO">>) -> <<"Togo">>;
country_alpha_3_to_name_upper(<<"TKL">>) -> <<"Tokelau">>;
country_alpha_3_to_name_upper(<<"TON">>) -> <<"Tonga">>;
country_alpha_3_to_name_upper(<<"TTO">>) -> <<"Trinidad and Tobago">>;
country_alpha_3_to_name_upper(<<"TUN">>) -> <<"Tunisia">>;
country_alpha_3_to_name_upper(<<"TUR">>) -> <<"Turkey">>;
country_alpha_3_to_name_upper(<<"TKM">>) -> <<"Turkmenistan">>;
country_alpha_3_to_name_upper(<<"TCA">>) -> <<"Turks and Caicos Islands">>;
country_alpha_3_to_name_upper(<<"TUV">>) -> <<"Tuvalu">>;
country_alpha_3_to_name_upper(<<"UGA">>) -> <<"Uganda">>;
country_alpha_3_to_name_upper(<<"UKR">>) -> <<"Ukraine">>;
country_alpha_3_to_name_upper(<<"ARE">>) -> <<"United Arab Emirates">>;
country_alpha_3_to_name_upper(<<"GBR">>) -> <<"United Kingdom">>;
country_alpha_3_to_name_upper(<<"USA">>) -> <<"United States of America">>;
country_alpha_3_to_name_upper(<<"UMI">>) -> <<"United States Minor Outlying Islands">>;
country_alpha_3_to_name_upper(<<"URY">>) -> <<"Uruguay">>;
country_alpha_3_to_name_upper(<<"UZB">>) -> <<"Uzbekistan">>;
country_alpha_3_to_name_upper(<<"VUT">>) -> <<"Vanuatu">>;
country_alpha_3_to_name_upper(<<"VEN">>) -> <<"Venezuela (Bolivarian Republic of)">>;
country_alpha_3_to_name_upper(<<"VNM">>) -> <<"Viet Nam">>;
country_alpha_3_to_name_upper(<<"VIR">>) -> <<"US Virgin Islands">>;
country_alpha_3_to_name_upper(<<"WLF">>) -> <<"Wallis and Futuna Islands">>;
country_alpha_3_to_name_upper(<<"ESH">>) -> <<"Western Sahara">>;
country_alpha_3_to_name_upper(<<"YEM">>) -> <<"Yemen">>;
country_alpha_3_to_name_upper(<<"ZMB">>) -> <<"Zambia">>;
country_alpha_3_to_name_upper(<<"ZWE">>) -> <<"Zimbabwe">>.

%% @doc Converts three letter country code (ISO alpha-3) to the equivalent United Nations numerical code M49 for countries.
%%      This is case-sensitive (Expects uppercase).
%% @end
country_alpha_3_to_numerical_code_upper(<<"AFG">>) -> 4;
country_alpha_3_to_numerical_code_upper(<<"ALA">>) -> 248;
country_alpha_3_to_numerical_code_upper(<<"ALB">>) -> 8;
country_alpha_3_to_numerical_code_upper(<<"DZA">>) -> 12;
country_alpha_3_to_numerical_code_upper(<<"ASM">>) -> 16;
country_alpha_3_to_numerical_code_upper(<<"AND">>) -> 20;
country_alpha_3_to_numerical_code_upper(<<"AGO">>) -> 24;
country_alpha_3_to_numerical_code_upper(<<"AIA">>) -> 660;
country_alpha_3_to_numerical_code_upper(<<"ATA">>) -> 10;
country_alpha_3_to_numerical_code_upper(<<"ATG">>) -> 28;
country_alpha_3_to_numerical_code_upper(<<"ARG">>) -> 32;
country_alpha_3_to_numerical_code_upper(<<"ARM">>) -> 51;
country_alpha_3_to_numerical_code_upper(<<"ABW">>) -> 533;
country_alpha_3_to_numerical_code_upper(<<"AUS">>) -> 36;
country_alpha_3_to_numerical_code_upper(<<"AUT">>) -> 40;
country_alpha_3_to_numerical_code_upper(<<"AZE">>) -> 31;
country_alpha_3_to_numerical_code_upper(<<"BHS">>) -> 44;
country_alpha_3_to_numerical_code_upper(<<"BHR">>) -> 48;
country_alpha_3_to_numerical_code_upper(<<"BGD">>) -> 50;
country_alpha_3_to_numerical_code_upper(<<"BRB">>) -> 52;
country_alpha_3_to_numerical_code_upper(<<"BLR">>) -> 112;
country_alpha_3_to_numerical_code_upper(<<"BEL">>) -> 56;
country_alpha_3_to_numerical_code_upper(<<"BLZ">>) -> 84;
country_alpha_3_to_numerical_code_upper(<<"BEN">>) -> 204;
country_alpha_3_to_numerical_code_upper(<<"BMU">>) -> 60;
country_alpha_3_to_numerical_code_upper(<<"BTN">>) -> 64;
country_alpha_3_to_numerical_code_upper(<<"BOL">>) -> 68;
country_alpha_3_to_numerical_code_upper(<<"BIH">>) -> 70;
country_alpha_3_to_numerical_code_upper(<<"BWA">>) -> 72;
country_alpha_3_to_numerical_code_upper(<<"BVT">>) -> 74;
country_alpha_3_to_numerical_code_upper(<<"BRA">>) -> 76;
country_alpha_3_to_numerical_code_upper(<<"VGB">>) -> 92;
country_alpha_3_to_numerical_code_upper(<<"IOT">>) -> 86;
country_alpha_3_to_numerical_code_upper(<<"BRN">>) -> 96;
country_alpha_3_to_numerical_code_upper(<<"BGR">>) -> 100;
country_alpha_3_to_numerical_code_upper(<<"BFA">>) -> 854;
country_alpha_3_to_numerical_code_upper(<<"BDI">>) -> 108;
country_alpha_3_to_numerical_code_upper(<<"KHM">>) -> 116;
country_alpha_3_to_numerical_code_upper(<<"CMR">>) -> 120;
country_alpha_3_to_numerical_code_upper(<<"CAN">>) -> 124;
country_alpha_3_to_numerical_code_upper(<<"CPV">>) -> 132;
country_alpha_3_to_numerical_code_upper(<<"CYM">>) -> 136;
country_alpha_3_to_numerical_code_upper(<<"CAF">>) -> 140;
country_alpha_3_to_numerical_code_upper(<<"TCD">>) -> 148;
country_alpha_3_to_numerical_code_upper(<<"CHL">>) -> 152;
country_alpha_3_to_numerical_code_upper(<<"CHN">>) -> 156;
country_alpha_3_to_numerical_code_upper(<<"HKG">>) -> 344;
country_alpha_3_to_numerical_code_upper(<<"MAC">>) -> 446;
country_alpha_3_to_numerical_code_upper(<<"CXR">>) -> 162;
country_alpha_3_to_numerical_code_upper(<<"CCK">>) -> 166;
country_alpha_3_to_numerical_code_upper(<<"COL">>) -> 170;
country_alpha_3_to_numerical_code_upper(<<"COM">>) -> 174;
country_alpha_3_to_numerical_code_upper(<<"COG">>) -> 178;
country_alpha_3_to_numerical_code_upper(<<"COD">>) -> 180;
country_alpha_3_to_numerical_code_upper(<<"COK">>) -> 184;
country_alpha_3_to_numerical_code_upper(<<"CRI">>) -> 188;
country_alpha_3_to_numerical_code_upper(<<"CIV">>) -> 384;
country_alpha_3_to_numerical_code_upper(<<"HRV">>) -> 191;
country_alpha_3_to_numerical_code_upper(<<"CUB">>) -> 192;
country_alpha_3_to_numerical_code_upper(<<"CYP">>) -> 196;
country_alpha_3_to_numerical_code_upper(<<"CZE">>) -> 203;
country_alpha_3_to_numerical_code_upper(<<"DNK">>) -> 208;
country_alpha_3_to_numerical_code_upper(<<"DJI">>) -> 262;
country_alpha_3_to_numerical_code_upper(<<"DMA">>) -> 212;
country_alpha_3_to_numerical_code_upper(<<"DOM">>) -> 214;
country_alpha_3_to_numerical_code_upper(<<"ECU">>) -> 218;
country_alpha_3_to_numerical_code_upper(<<"EGY">>) -> 818;
country_alpha_3_to_numerical_code_upper(<<"SLV">>) -> 222;
country_alpha_3_to_numerical_code_upper(<<"GNQ">>) -> 226;
country_alpha_3_to_numerical_code_upper(<<"ERI">>) -> 232;
country_alpha_3_to_numerical_code_upper(<<"EST">>) -> 233;
country_alpha_3_to_numerical_code_upper(<<"ETH">>) -> 231;
country_alpha_3_to_numerical_code_upper(<<"FLK">>) -> 238;
country_alpha_3_to_numerical_code_upper(<<"FRO">>) -> 234;
country_alpha_3_to_numerical_code_upper(<<"FJI">>) -> 242;
country_alpha_3_to_numerical_code_upper(<<"FIN">>) -> 246;
country_alpha_3_to_numerical_code_upper(<<"FRA">>) -> 250;
country_alpha_3_to_numerical_code_upper(<<"GUF">>) -> 254;
country_alpha_3_to_numerical_code_upper(<<"PYF">>) -> 258;
country_alpha_3_to_numerical_code_upper(<<"ATF">>) -> 260;
country_alpha_3_to_numerical_code_upper(<<"GAB">>) -> 266;
country_alpha_3_to_numerical_code_upper(<<"GMB">>) -> 270;
country_alpha_3_to_numerical_code_upper(<<"GEO">>) -> 268;
country_alpha_3_to_numerical_code_upper(<<"DEU">>) -> 276;
country_alpha_3_to_numerical_code_upper(<<"GHA">>) -> 288;
country_alpha_3_to_numerical_code_upper(<<"GIB">>) -> 292;
country_alpha_3_to_numerical_code_upper(<<"GRC">>) -> 300;
country_alpha_3_to_numerical_code_upper(<<"GRL">>) -> 304;
country_alpha_3_to_numerical_code_upper(<<"GRD">>) -> 308;
country_alpha_3_to_numerical_code_upper(<<"GLP">>) -> 312;
country_alpha_3_to_numerical_code_upper(<<"GUM">>) -> 316;
country_alpha_3_to_numerical_code_upper(<<"GTM">>) -> 320;
country_alpha_3_to_numerical_code_upper(<<"GGY">>) -> 831;
country_alpha_3_to_numerical_code_upper(<<"GIN">>) -> 324;
country_alpha_3_to_numerical_code_upper(<<"GNB">>) -> 624;
country_alpha_3_to_numerical_code_upper(<<"GUY">>) -> 328;
country_alpha_3_to_numerical_code_upper(<<"HTI">>) -> 332;
country_alpha_3_to_numerical_code_upper(<<"HMD">>) -> 334;
country_alpha_3_to_numerical_code_upper(<<"VAT">>) -> 336;
country_alpha_3_to_numerical_code_upper(<<"HND">>) -> 340;
country_alpha_3_to_numerical_code_upper(<<"HUN">>) -> 348;
country_alpha_3_to_numerical_code_upper(<<"ISL">>) -> 352;
country_alpha_3_to_numerical_code_upper(<<"IND">>) -> 356;
country_alpha_3_to_numerical_code_upper(<<"IDN">>) -> 360;
country_alpha_3_to_numerical_code_upper(<<"IRN">>) -> 364;
country_alpha_3_to_numerical_code_upper(<<"IRQ">>) -> 368;
country_alpha_3_to_numerical_code_upper(<<"IRL">>) -> 372;
country_alpha_3_to_numerical_code_upper(<<"IMN">>) -> 833;
country_alpha_3_to_numerical_code_upper(<<"ISR">>) -> 376;
country_alpha_3_to_numerical_code_upper(<<"ITA">>) -> 380;
country_alpha_3_to_numerical_code_upper(<<"JAM">>) -> 388;
country_alpha_3_to_numerical_code_upper(<<"JPN">>) -> 392;
country_alpha_3_to_numerical_code_upper(<<"JEY">>) -> 832;
country_alpha_3_to_numerical_code_upper(<<"JOR">>) -> 400;
country_alpha_3_to_numerical_code_upper(<<"KAZ">>) -> 398;
country_alpha_3_to_numerical_code_upper(<<"KEN">>) -> 404;
country_alpha_3_to_numerical_code_upper(<<"KIR">>) -> 296;
country_alpha_3_to_numerical_code_upper(<<"PRK">>) -> 408;
country_alpha_3_to_numerical_code_upper(<<"KOR">>) -> 410;
country_alpha_3_to_numerical_code_upper(<<"KWT">>) -> 414;
country_alpha_3_to_numerical_code_upper(<<"KGZ">>) -> 417;
country_alpha_3_to_numerical_code_upper(<<"LAO">>) -> 418;
country_alpha_3_to_numerical_code_upper(<<"LVA">>) -> 428;
country_alpha_3_to_numerical_code_upper(<<"LBN">>) -> 422;
country_alpha_3_to_numerical_code_upper(<<"LSO">>) -> 426;
country_alpha_3_to_numerical_code_upper(<<"LBR">>) -> 430;
country_alpha_3_to_numerical_code_upper(<<"LBY">>) -> 434;
country_alpha_3_to_numerical_code_upper(<<"LIE">>) -> 438;
country_alpha_3_to_numerical_code_upper(<<"LTU">>) -> 440;
country_alpha_3_to_numerical_code_upper(<<"LUX">>) -> 442;
country_alpha_3_to_numerical_code_upper(<<"MKD">>) -> 807;
country_alpha_3_to_numerical_code_upper(<<"MDG">>) -> 450;
country_alpha_3_to_numerical_code_upper(<<"MWI">>) -> 454;
country_alpha_3_to_numerical_code_upper(<<"MYS">>) -> 458;
country_alpha_3_to_numerical_code_upper(<<"MDV">>) -> 462;
country_alpha_3_to_numerical_code_upper(<<"MLI">>) -> 466;
country_alpha_3_to_numerical_code_upper(<<"MLT">>) -> 470;
country_alpha_3_to_numerical_code_upper(<<"MHL">>) -> 584;
country_alpha_3_to_numerical_code_upper(<<"MTQ">>) -> 474;
country_alpha_3_to_numerical_code_upper(<<"MRT">>) -> 478;
country_alpha_3_to_numerical_code_upper(<<"MUS">>) -> 480;
country_alpha_3_to_numerical_code_upper(<<"MYT">>) -> 175;
country_alpha_3_to_numerical_code_upper(<<"MEX">>) -> 484;
country_alpha_3_to_numerical_code_upper(<<"FSM">>) -> 583;
country_alpha_3_to_numerical_code_upper(<<"MDA">>) -> 498;
country_alpha_3_to_numerical_code_upper(<<"MCO">>) -> 492;
country_alpha_3_to_numerical_code_upper(<<"MNG">>) -> 496;
country_alpha_3_to_numerical_code_upper(<<"MNE">>) -> 499;
country_alpha_3_to_numerical_code_upper(<<"MSR">>) -> 500;
country_alpha_3_to_numerical_code_upper(<<"MAR">>) -> 504;
country_alpha_3_to_numerical_code_upper(<<"MOZ">>) -> 508;
country_alpha_3_to_numerical_code_upper(<<"MMR">>) -> 104;
country_alpha_3_to_numerical_code_upper(<<"NAM">>) -> 516;
country_alpha_3_to_numerical_code_upper(<<"NRU">>) -> 520;
country_alpha_3_to_numerical_code_upper(<<"NPL">>) -> 524;
country_alpha_3_to_numerical_code_upper(<<"NLD">>) -> 528;
country_alpha_3_to_numerical_code_upper(<<"ANT">>) -> 530;
country_alpha_3_to_numerical_code_upper(<<"NCL">>) -> 540;
country_alpha_3_to_numerical_code_upper(<<"NZL">>) -> 554;
country_alpha_3_to_numerical_code_upper(<<"NIC">>) -> 558;
country_alpha_3_to_numerical_code_upper(<<"NER">>) -> 562;
country_alpha_3_to_numerical_code_upper(<<"NGA">>) -> 566;
country_alpha_3_to_numerical_code_upper(<<"NIU">>) -> 570;
country_alpha_3_to_numerical_code_upper(<<"NFK">>) -> 574;
country_alpha_3_to_numerical_code_upper(<<"MNP">>) -> 580;
country_alpha_3_to_numerical_code_upper(<<"NOR">>) -> 578;
country_alpha_3_to_numerical_code_upper(<<"OMN">>) -> 512;
country_alpha_3_to_numerical_code_upper(<<"PAK">>) -> 586;
country_alpha_3_to_numerical_code_upper(<<"PLW">>) -> 585;
country_alpha_3_to_numerical_code_upper(<<"PSE">>) -> 275;
country_alpha_3_to_numerical_code_upper(<<"PAN">>) -> 591;
country_alpha_3_to_numerical_code_upper(<<"PNG">>) -> 598;
country_alpha_3_to_numerical_code_upper(<<"PRY">>) -> 600;
country_alpha_3_to_numerical_code_upper(<<"PER">>) -> 604;
country_alpha_3_to_numerical_code_upper(<<"PHL">>) -> 608;
country_alpha_3_to_numerical_code_upper(<<"PCN">>) -> 612;
country_alpha_3_to_numerical_code_upper(<<"POL">>) -> 616;
country_alpha_3_to_numerical_code_upper(<<"PRT">>) -> 620;
country_alpha_3_to_numerical_code_upper(<<"PRI">>) -> 630;
country_alpha_3_to_numerical_code_upper(<<"QAT">>) -> 634;
country_alpha_3_to_numerical_code_upper(<<"REU">>) -> 638;
country_alpha_3_to_numerical_code_upper(<<"ROU">>) -> 642;
country_alpha_3_to_numerical_code_upper(<<"RUS">>) -> 643;
country_alpha_3_to_numerical_code_upper(<<"RWA">>) -> 646;
country_alpha_3_to_numerical_code_upper(<<"BLM">>) -> 652;
country_alpha_3_to_numerical_code_upper(<<"SHN">>) -> 654;
country_alpha_3_to_numerical_code_upper(<<"KNA">>) -> 659;
country_alpha_3_to_numerical_code_upper(<<"LCA">>) -> 662;
country_alpha_3_to_numerical_code_upper(<<"MAF">>) -> 663;
country_alpha_3_to_numerical_code_upper(<<"SPM">>) -> 666;
country_alpha_3_to_numerical_code_upper(<<"VCT">>) -> 670;
country_alpha_3_to_numerical_code_upper(<<"WSM">>) -> 882;
country_alpha_3_to_numerical_code_upper(<<"SMR">>) -> 674;
country_alpha_3_to_numerical_code_upper(<<"STP">>) -> 678;
country_alpha_3_to_numerical_code_upper(<<"SAU">>) -> 682;
country_alpha_3_to_numerical_code_upper(<<"SEN">>) -> 686;
country_alpha_3_to_numerical_code_upper(<<"SRB">>) -> 688;
country_alpha_3_to_numerical_code_upper(<<"SYC">>) -> 690;
country_alpha_3_to_numerical_code_upper(<<"SLE">>) -> 694;
country_alpha_3_to_numerical_code_upper(<<"SGP">>) -> 702;
country_alpha_3_to_numerical_code_upper(<<"SVK">>) -> 703;
country_alpha_3_to_numerical_code_upper(<<"SVN">>) -> 705;
country_alpha_3_to_numerical_code_upper(<<"SLB">>) -> 90;
country_alpha_3_to_numerical_code_upper(<<"SOM">>) -> 706;
country_alpha_3_to_numerical_code_upper(<<"ZAF">>) -> 710;
country_alpha_3_to_numerical_code_upper(<<"SGS">>) -> 239;
country_alpha_3_to_numerical_code_upper(<<"SSD">>) -> 728;
country_alpha_3_to_numerical_code_upper(<<"ESP">>) -> 724;
country_alpha_3_to_numerical_code_upper(<<"LKA">>) -> 144;
country_alpha_3_to_numerical_code_upper(<<"SDN">>) -> 736;
country_alpha_3_to_numerical_code_upper(<<"SUR">>) -> 740;
country_alpha_3_to_numerical_code_upper(<<"SJM">>) -> 744;
country_alpha_3_to_numerical_code_upper(<<"SWZ">>) -> 748;
country_alpha_3_to_numerical_code_upper(<<"SWE">>) -> 752;
country_alpha_3_to_numerical_code_upper(<<"CHE">>) -> 756;
country_alpha_3_to_numerical_code_upper(<<"SYR">>) -> 760;
country_alpha_3_to_numerical_code_upper(<<"TWN">>) -> 158;
country_alpha_3_to_numerical_code_upper(<<"TJK">>) -> 762;
country_alpha_3_to_numerical_code_upper(<<"TZA">>) -> 834;
country_alpha_3_to_numerical_code_upper(<<"THA">>) -> 764;
country_alpha_3_to_numerical_code_upper(<<"TLS">>) -> 626;
country_alpha_3_to_numerical_code_upper(<<"TGO">>) -> 768;
country_alpha_3_to_numerical_code_upper(<<"TKL">>) -> 772;
country_alpha_3_to_numerical_code_upper(<<"TON">>) -> 776;
country_alpha_3_to_numerical_code_upper(<<"TTO">>) -> 780;
country_alpha_3_to_numerical_code_upper(<<"TUN">>) -> 788;
country_alpha_3_to_numerical_code_upper(<<"TUR">>) -> 792;
country_alpha_3_to_numerical_code_upper(<<"TKM">>) -> 795;
country_alpha_3_to_numerical_code_upper(<<"TCA">>) -> 796;
country_alpha_3_to_numerical_code_upper(<<"TUV">>) -> 798;
country_alpha_3_to_numerical_code_upper(<<"UGA">>) -> 800;
country_alpha_3_to_numerical_code_upper(<<"UKR">>) -> 804;
country_alpha_3_to_numerical_code_upper(<<"ARE">>) -> 784;
country_alpha_3_to_numerical_code_upper(<<"GBR">>) -> 826;
country_alpha_3_to_numerical_code_upper(<<"USA">>) -> 840;
country_alpha_3_to_numerical_code_upper(<<"UMI">>) -> 581;
country_alpha_3_to_numerical_code_upper(<<"URY">>) -> 858;
country_alpha_3_to_numerical_code_upper(<<"UZB">>) -> 860;
country_alpha_3_to_numerical_code_upper(<<"VUT">>) -> 548;
country_alpha_3_to_numerical_code_upper(<<"VEN">>) -> 862;
country_alpha_3_to_numerical_code_upper(<<"VNM">>) -> 704;
country_alpha_3_to_numerical_code_upper(<<"VIR">>) -> 850;
country_alpha_3_to_numerical_code_upper(<<"WLF">>) -> 876;
country_alpha_3_to_numerical_code_upper(<<"ESH">>) -> 732;
country_alpha_3_to_numerical_code_upper(<<"YEM">>) -> 887;
country_alpha_3_to_numerical_code_upper(<<"ZMB">>) -> 894;
country_alpha_3_to_numerical_code_upper(<<"ZWE">>) -> 716.

%% @doc Converts two letter country code (ISO alpha-2) to the equivalent United Nations numerical code M49 for countries.
%%      This is case-sensitive (Expects uppercase).
%% @end
country_alpha_2_to_numerical_code_upper(<<"AF">>) -> 4;
country_alpha_2_to_numerical_code_upper(<<"AX">>) -> 248;
country_alpha_2_to_numerical_code_upper(<<"AL">>) -> 8;
country_alpha_2_to_numerical_code_upper(<<"DZ">>) -> 12;
country_alpha_2_to_numerical_code_upper(<<"AS">>) -> 16;
country_alpha_2_to_numerical_code_upper(<<"AD">>) -> 20;
country_alpha_2_to_numerical_code_upper(<<"AO">>) -> 24;
country_alpha_2_to_numerical_code_upper(<<"AI">>) -> 660;
country_alpha_2_to_numerical_code_upper(<<"AQ">>) -> 10;
country_alpha_2_to_numerical_code_upper(<<"AG">>) -> 28;
country_alpha_2_to_numerical_code_upper(<<"AR">>) -> 32;
country_alpha_2_to_numerical_code_upper(<<"AM">>) -> 51;
country_alpha_2_to_numerical_code_upper(<<"AW">>) -> 533;
country_alpha_2_to_numerical_code_upper(<<"AU">>) -> 36;
country_alpha_2_to_numerical_code_upper(<<"AT">>) -> 40;
country_alpha_2_to_numerical_code_upper(<<"AZ">>) -> 31;
country_alpha_2_to_numerical_code_upper(<<"BS">>) -> 44;
country_alpha_2_to_numerical_code_upper(<<"BH">>) -> 48;
country_alpha_2_to_numerical_code_upper(<<"BD">>) -> 50;
country_alpha_2_to_numerical_code_upper(<<"BB">>) -> 52;
country_alpha_2_to_numerical_code_upper(<<"BY">>) -> 112;
country_alpha_2_to_numerical_code_upper(<<"BE">>) -> 56;
country_alpha_2_to_numerical_code_upper(<<"BZ">>) -> 84;
country_alpha_2_to_numerical_code_upper(<<"BJ">>) -> 204;
country_alpha_2_to_numerical_code_upper(<<"BM">>) -> 60;
country_alpha_2_to_numerical_code_upper(<<"BT">>) -> 64;
country_alpha_2_to_numerical_code_upper(<<"BO">>) -> 68;
country_alpha_2_to_numerical_code_upper(<<"BA">>) -> 70;
country_alpha_2_to_numerical_code_upper(<<"BW">>) -> 72;
country_alpha_2_to_numerical_code_upper(<<"BV">>) -> 74;
country_alpha_2_to_numerical_code_upper(<<"BR">>) -> 76;
country_alpha_2_to_numerical_code_upper(<<"VG">>) -> 92;
country_alpha_2_to_numerical_code_upper(<<"IO">>) -> 86;
country_alpha_2_to_numerical_code_upper(<<"BN">>) -> 96;
country_alpha_2_to_numerical_code_upper(<<"BG">>) -> 100;
country_alpha_2_to_numerical_code_upper(<<"BF">>) -> 854;
country_alpha_2_to_numerical_code_upper(<<"BI">>) -> 108;
country_alpha_2_to_numerical_code_upper(<<"KH">>) -> 116;
country_alpha_2_to_numerical_code_upper(<<"CM">>) -> 120;
country_alpha_2_to_numerical_code_upper(<<"CA">>) -> 124;
country_alpha_2_to_numerical_code_upper(<<"CV">>) -> 132;
country_alpha_2_to_numerical_code_upper(<<"KY">>) -> 136;
country_alpha_2_to_numerical_code_upper(<<"CF">>) -> 140;
country_alpha_2_to_numerical_code_upper(<<"TD">>) -> 148;
country_alpha_2_to_numerical_code_upper(<<"CL">>) -> 152;
country_alpha_2_to_numerical_code_upper(<<"CN">>) -> 156;
country_alpha_2_to_numerical_code_upper(<<"HK">>) -> 344;
country_alpha_2_to_numerical_code_upper(<<"MO">>) -> 446;
country_alpha_2_to_numerical_code_upper(<<"CX">>) -> 162;
country_alpha_2_to_numerical_code_upper(<<"CC">>) -> 166;
country_alpha_2_to_numerical_code_upper(<<"CO">>) -> 170;
country_alpha_2_to_numerical_code_upper(<<"KM">>) -> 174;
country_alpha_2_to_numerical_code_upper(<<"CG">>) -> 178;
country_alpha_2_to_numerical_code_upper(<<"CD">>) -> 180;
country_alpha_2_to_numerical_code_upper(<<"CK">>) -> 184;
country_alpha_2_to_numerical_code_upper(<<"CR">>) -> 188;
country_alpha_2_to_numerical_code_upper(<<"CI">>) -> 384;
country_alpha_2_to_numerical_code_upper(<<"HR">>) -> 191;
country_alpha_2_to_numerical_code_upper(<<"CU">>) -> 192;
country_alpha_2_to_numerical_code_upper(<<"CY">>) -> 196;
country_alpha_2_to_numerical_code_upper(<<"CZ">>) -> 203;
country_alpha_2_to_numerical_code_upper(<<"DK">>) -> 208;
country_alpha_2_to_numerical_code_upper(<<"DJ">>) -> 262;
country_alpha_2_to_numerical_code_upper(<<"DM">>) -> 212;
country_alpha_2_to_numerical_code_upper(<<"DO">>) -> 214;
country_alpha_2_to_numerical_code_upper(<<"EC">>) -> 218;
country_alpha_2_to_numerical_code_upper(<<"EG">>) -> 818;
country_alpha_2_to_numerical_code_upper(<<"SV">>) -> 222;
country_alpha_2_to_numerical_code_upper(<<"GQ">>) -> 226;
country_alpha_2_to_numerical_code_upper(<<"ER">>) -> 232;
country_alpha_2_to_numerical_code_upper(<<"EE">>) -> 233;
country_alpha_2_to_numerical_code_upper(<<"ET">>) -> 231;
country_alpha_2_to_numerical_code_upper(<<"FK">>) -> 238;
country_alpha_2_to_numerical_code_upper(<<"FO">>) -> 234;
country_alpha_2_to_numerical_code_upper(<<"FJ">>) -> 242;
country_alpha_2_to_numerical_code_upper(<<"FI">>) -> 246;
country_alpha_2_to_numerical_code_upper(<<"FR">>) -> 250;
country_alpha_2_to_numerical_code_upper(<<"GF">>) -> 254;
country_alpha_2_to_numerical_code_upper(<<"PF">>) -> 258;
country_alpha_2_to_numerical_code_upper(<<"TF">>) -> 260;
country_alpha_2_to_numerical_code_upper(<<"GA">>) -> 266;
country_alpha_2_to_numerical_code_upper(<<"GM">>) -> 270;
country_alpha_2_to_numerical_code_upper(<<"GE">>) -> 268;
country_alpha_2_to_numerical_code_upper(<<"DE">>) -> 276;
country_alpha_2_to_numerical_code_upper(<<"GH">>) -> 288;
country_alpha_2_to_numerical_code_upper(<<"GI">>) -> 292;
country_alpha_2_to_numerical_code_upper(<<"GR">>) -> 300;
country_alpha_2_to_numerical_code_upper(<<"GL">>) -> 304;
country_alpha_2_to_numerical_code_upper(<<"GD">>) -> 308;
country_alpha_2_to_numerical_code_upper(<<"GP">>) -> 312;
country_alpha_2_to_numerical_code_upper(<<"GU">>) -> 316;
country_alpha_2_to_numerical_code_upper(<<"GT">>) -> 320;
country_alpha_2_to_numerical_code_upper(<<"GG">>) -> 831;
country_alpha_2_to_numerical_code_upper(<<"GN">>) -> 324;
country_alpha_2_to_numerical_code_upper(<<"GW">>) -> 624;
country_alpha_2_to_numerical_code_upper(<<"GY">>) -> 328;
country_alpha_2_to_numerical_code_upper(<<"HT">>) -> 332;
country_alpha_2_to_numerical_code_upper(<<"HM">>) -> 334;
country_alpha_2_to_numerical_code_upper(<<"VA">>) -> 336;
country_alpha_2_to_numerical_code_upper(<<"HN">>) -> 340;
country_alpha_2_to_numerical_code_upper(<<"HU">>) -> 348;
country_alpha_2_to_numerical_code_upper(<<"IS">>) -> 352;
country_alpha_2_to_numerical_code_upper(<<"IN">>) -> 356;
country_alpha_2_to_numerical_code_upper(<<"ID">>) -> 360;
country_alpha_2_to_numerical_code_upper(<<"IR">>) -> 364;
country_alpha_2_to_numerical_code_upper(<<"IQ">>) -> 368;
country_alpha_2_to_numerical_code_upper(<<"IE">>) -> 372;
country_alpha_2_to_numerical_code_upper(<<"IM">>) -> 833;
country_alpha_2_to_numerical_code_upper(<<"IL">>) -> 376;
country_alpha_2_to_numerical_code_upper(<<"IT">>) -> 380;
country_alpha_2_to_numerical_code_upper(<<"JM">>) -> 388;
country_alpha_2_to_numerical_code_upper(<<"JP">>) -> 392;
country_alpha_2_to_numerical_code_upper(<<"JE">>) -> 832;
country_alpha_2_to_numerical_code_upper(<<"JO">>) -> 400;
country_alpha_2_to_numerical_code_upper(<<"KZ">>) -> 398;
country_alpha_2_to_numerical_code_upper(<<"KE">>) -> 404;
country_alpha_2_to_numerical_code_upper(<<"KI">>) -> 296;
country_alpha_2_to_numerical_code_upper(<<"KP">>) -> 408;
country_alpha_2_to_numerical_code_upper(<<"KR">>) -> 410;
country_alpha_2_to_numerical_code_upper(<<"KW">>) -> 414;
country_alpha_2_to_numerical_code_upper(<<"KG">>) -> 417;
country_alpha_2_to_numerical_code_upper(<<"LA">>) -> 418;
country_alpha_2_to_numerical_code_upper(<<"LV">>) -> 428;
country_alpha_2_to_numerical_code_upper(<<"LB">>) -> 422;
country_alpha_2_to_numerical_code_upper(<<"LS">>) -> 426;
country_alpha_2_to_numerical_code_upper(<<"LR">>) -> 430;
country_alpha_2_to_numerical_code_upper(<<"LY">>) -> 434;
country_alpha_2_to_numerical_code_upper(<<"LI">>) -> 438;
country_alpha_2_to_numerical_code_upper(<<"LT">>) -> 440;
country_alpha_2_to_numerical_code_upper(<<"LU">>) -> 442;
country_alpha_2_to_numerical_code_upper(<<"MK">>) -> 807;
country_alpha_2_to_numerical_code_upper(<<"MG">>) -> 450;
country_alpha_2_to_numerical_code_upper(<<"MW">>) -> 454;
country_alpha_2_to_numerical_code_upper(<<"MY">>) -> 458;
country_alpha_2_to_numerical_code_upper(<<"MV">>) -> 462;
country_alpha_2_to_numerical_code_upper(<<"ML">>) -> 466;
country_alpha_2_to_numerical_code_upper(<<"MT">>) -> 470;
country_alpha_2_to_numerical_code_upper(<<"MH">>) -> 584;
country_alpha_2_to_numerical_code_upper(<<"MQ">>) -> 474;
country_alpha_2_to_numerical_code_upper(<<"MR">>) -> 478;
country_alpha_2_to_numerical_code_upper(<<"MU">>) -> 480;
country_alpha_2_to_numerical_code_upper(<<"YT">>) -> 175;
country_alpha_2_to_numerical_code_upper(<<"MX">>) -> 484;
country_alpha_2_to_numerical_code_upper(<<"FM">>) -> 583;
country_alpha_2_to_numerical_code_upper(<<"MD">>) -> 498;
country_alpha_2_to_numerical_code_upper(<<"MC">>) -> 492;
country_alpha_2_to_numerical_code_upper(<<"MN">>) -> 496;
country_alpha_2_to_numerical_code_upper(<<"ME">>) -> 499;
country_alpha_2_to_numerical_code_upper(<<"MS">>) -> 500;
country_alpha_2_to_numerical_code_upper(<<"MA">>) -> 504;
country_alpha_2_to_numerical_code_upper(<<"MZ">>) -> 508;
country_alpha_2_to_numerical_code_upper(<<"MM">>) -> 104;
country_alpha_2_to_numerical_code_upper(<<"NA">>) -> 516;
country_alpha_2_to_numerical_code_upper(<<"NR">>) -> 520;
country_alpha_2_to_numerical_code_upper(<<"NP">>) -> 524;
country_alpha_2_to_numerical_code_upper(<<"NL">>) -> 528;
country_alpha_2_to_numerical_code_upper(<<"AN">>) -> 530;
country_alpha_2_to_numerical_code_upper(<<"NC">>) -> 540;
country_alpha_2_to_numerical_code_upper(<<"NZ">>) -> 554;
country_alpha_2_to_numerical_code_upper(<<"NI">>) -> 558;
country_alpha_2_to_numerical_code_upper(<<"NE">>) -> 562;
country_alpha_2_to_numerical_code_upper(<<"NG">>) -> 566;
country_alpha_2_to_numerical_code_upper(<<"NU">>) -> 570;
country_alpha_2_to_numerical_code_upper(<<"NF">>) -> 574;
country_alpha_2_to_numerical_code_upper(<<"MP">>) -> 580;
country_alpha_2_to_numerical_code_upper(<<"NO">>) -> 578;
country_alpha_2_to_numerical_code_upper(<<"OM">>) -> 512;
country_alpha_2_to_numerical_code_upper(<<"PK">>) -> 586;
country_alpha_2_to_numerical_code_upper(<<"PW">>) -> 585;
country_alpha_2_to_numerical_code_upper(<<"PS">>) -> 275;
country_alpha_2_to_numerical_code_upper(<<"PA">>) -> 591;
country_alpha_2_to_numerical_code_upper(<<"PG">>) -> 598;
country_alpha_2_to_numerical_code_upper(<<"PY">>) -> 600;
country_alpha_2_to_numerical_code_upper(<<"PE">>) -> 604;
country_alpha_2_to_numerical_code_upper(<<"PH">>) -> 608;
country_alpha_2_to_numerical_code_upper(<<"PN">>) -> 612;
country_alpha_2_to_numerical_code_upper(<<"PL">>) -> 616;
country_alpha_2_to_numerical_code_upper(<<"PT">>) -> 620;
country_alpha_2_to_numerical_code_upper(<<"PR">>) -> 630;
country_alpha_2_to_numerical_code_upper(<<"QA">>) -> 634;
country_alpha_2_to_numerical_code_upper(<<"RE">>) -> 638;
country_alpha_2_to_numerical_code_upper(<<"RO">>) -> 642;
country_alpha_2_to_numerical_code_upper(<<"RU">>) -> 643;
country_alpha_2_to_numerical_code_upper(<<"RW">>) -> 646;
country_alpha_2_to_numerical_code_upper(<<"BL">>) -> 652;
country_alpha_2_to_numerical_code_upper(<<"SH">>) -> 654;
country_alpha_2_to_numerical_code_upper(<<"KN">>) -> 659;
country_alpha_2_to_numerical_code_upper(<<"LC">>) -> 662;
country_alpha_2_to_numerical_code_upper(<<"MF">>) -> 663;
country_alpha_2_to_numerical_code_upper(<<"PM">>) -> 666;
country_alpha_2_to_numerical_code_upper(<<"VC">>) -> 670;
country_alpha_2_to_numerical_code_upper(<<"WS">>) -> 882;
country_alpha_2_to_numerical_code_upper(<<"SM">>) -> 674;
country_alpha_2_to_numerical_code_upper(<<"ST">>) -> 678;
country_alpha_2_to_numerical_code_upper(<<"SA">>) -> 682;
country_alpha_2_to_numerical_code_upper(<<"SN">>) -> 686;
country_alpha_2_to_numerical_code_upper(<<"RS">>) -> 688;
country_alpha_2_to_numerical_code_upper(<<"SC">>) -> 690;
country_alpha_2_to_numerical_code_upper(<<"SL">>) -> 694;
country_alpha_2_to_numerical_code_upper(<<"SG">>) -> 702;
country_alpha_2_to_numerical_code_upper(<<"SK">>) -> 703;
country_alpha_2_to_numerical_code_upper(<<"SI">>) -> 705;
country_alpha_2_to_numerical_code_upper(<<"SB">>) -> 90;
country_alpha_2_to_numerical_code_upper(<<"SO">>) -> 706;
country_alpha_2_to_numerical_code_upper(<<"ZA">>) -> 710;
country_alpha_2_to_numerical_code_upper(<<"GS">>) -> 239;
country_alpha_2_to_numerical_code_upper(<<"SS">>) -> 728;
country_alpha_2_to_numerical_code_upper(<<"ES">>) -> 724;
country_alpha_2_to_numerical_code_upper(<<"LK">>) -> 144;
country_alpha_2_to_numerical_code_upper(<<"SD">>) -> 736;
country_alpha_2_to_numerical_code_upper(<<"SR">>) -> 740;
country_alpha_2_to_numerical_code_upper(<<"SJ">>) -> 744;
country_alpha_2_to_numerical_code_upper(<<"SZ">>) -> 748;
country_alpha_2_to_numerical_code_upper(<<"SE">>) -> 752;
country_alpha_2_to_numerical_code_upper(<<"CH">>) -> 756;
country_alpha_2_to_numerical_code_upper(<<"SY">>) -> 760;
country_alpha_2_to_numerical_code_upper(<<"TW">>) -> 158;
country_alpha_2_to_numerical_code_upper(<<"TJ">>) -> 762;
country_alpha_2_to_numerical_code_upper(<<"TZ">>) -> 834;
country_alpha_2_to_numerical_code_upper(<<"TH">>) -> 764;
country_alpha_2_to_numerical_code_upper(<<"TL">>) -> 626;
country_alpha_2_to_numerical_code_upper(<<"TG">>) -> 768;
country_alpha_2_to_numerical_code_upper(<<"TK">>) -> 772;
country_alpha_2_to_numerical_code_upper(<<"TO">>) -> 776;
country_alpha_2_to_numerical_code_upper(<<"TT">>) -> 780;
country_alpha_2_to_numerical_code_upper(<<"TN">>) -> 788;
country_alpha_2_to_numerical_code_upper(<<"TR">>) -> 792;
country_alpha_2_to_numerical_code_upper(<<"TM">>) -> 795;
country_alpha_2_to_numerical_code_upper(<<"TC">>) -> 796;
country_alpha_2_to_numerical_code_upper(<<"TV">>) -> 798;
country_alpha_2_to_numerical_code_upper(<<"UG">>) -> 800;
country_alpha_2_to_numerical_code_upper(<<"UA">>) -> 804;
country_alpha_2_to_numerical_code_upper(<<"AE">>) -> 784;
country_alpha_2_to_numerical_code_upper(<<"GB">>) -> 826;
country_alpha_2_to_numerical_code_upper(<<"US">>) -> 840;
country_alpha_2_to_numerical_code_upper(<<"UM">>) -> 581;
country_alpha_2_to_numerical_code_upper(<<"UY">>) -> 858;
country_alpha_2_to_numerical_code_upper(<<"UZ">>) -> 860;
country_alpha_2_to_numerical_code_upper(<<"VU">>) -> 548;
country_alpha_2_to_numerical_code_upper(<<"VE">>) -> 862;
country_alpha_2_to_numerical_code_upper(<<"VN">>) -> 704;
country_alpha_2_to_numerical_code_upper(<<"VI">>) -> 850;
country_alpha_2_to_numerical_code_upper(<<"WF">>) -> 876;
country_alpha_2_to_numerical_code_upper(<<"EH">>) -> 732;
country_alpha_2_to_numerical_code_upper(<<"YE">>) -> 887;
country_alpha_2_to_numerical_code_upper(<<"ZM">>) -> 894;
country_alpha_2_to_numerical_code_upper(<<"ZW">>) -> 716.
