%%%-------------------------------------------------------------------
%%% @copyright (C) 2016, Vungle
%%% @doc Returns list of all countries
%%% @end
%%%-------------------------------------------------------------------
-module(iso_erlang_lists).

%% API
-export([
 get_alpha_2_country_list/0,
 get_alpha_3_country_list/0,
 get_country_name_list/0
]).

get_alpha_2_country_list() ->
    [<<"AF">>,
     <<"AX">>,
     <<"AL">>,
     <<"DZ">>,
     <<"AS">>,
     <<"AD">>,
     <<"AO">>,
     <<"AI">>,
     <<"AQ">>,
     <<"AG">>,
     <<"AR">>,
     <<"AM">>,
     <<"AW">>,
     <<"AU">>,
     <<"AT">>,
     <<"AZ">>,
     <<"BS">>,
     <<"BH">>,
     <<"BD">>,
     <<"BB">>,
     <<"BY">>,
     <<"BE">>,
     <<"BZ">>,
     <<"BJ">>,
     <<"BM">>,
     <<"BT">>,
     <<"BO">>,
     <<"BA">>,
     <<"BW">>,
     <<"BV">>,
     <<"BR">>,
     <<"VG">>,
     <<"IO">>,
     <<"BN">>,
     <<"BG">>,
     <<"BF">>,
     <<"BI">>,
     <<"KH">>,
     <<"CM">>,
     <<"CA">>,
     <<"CV">>,
     <<"KY">>,
     <<"CF">>,
     <<"TD">>,
     <<"CL">>,
     <<"CN">>,
     <<"HK">>,
     <<"MO">>,
     <<"CX">>,
     <<"CC">>,
     <<"CO">>,
     <<"KM">>,
     <<"CG">>,
     <<"CD">>,
     <<"CK">>,
     <<"CR">>,
     <<"CI">>,
     <<"HR">>,
     <<"CU">>,
     <<"CY">>,
     <<"CZ">>,
     <<"DK">>,
     <<"DJ">>,
     <<"DM">>,
     <<"DO">>,
     <<"EC">>,
     <<"EG">>,
     <<"SV">>,
     <<"GQ">>,
     <<"ER">>,
     <<"EE">>,
     <<"ET">>,
     <<"FK">>,
     <<"FO">>,
     <<"FJ">>,
     <<"FI">>,
     <<"FR">>,
     <<"GF">>,
     <<"PF">>,
     <<"TF">>,
     <<"GA">>,
     <<"GM">>,
     <<"GE">>,
     <<"DE">>,
     <<"GH">>,
     <<"GI">>,
     <<"GR">>,
     <<"GL">>,
     <<"GD">>,
     <<"GP">>,
     <<"GU">>,
     <<"GT">>,
     <<"GG">>,
     <<"GN">>,
     <<"GW">>,
     <<"GY">>,
     <<"HT">>,
     <<"HM">>,
     <<"VA">>,
     <<"HN">>,
     <<"HU">>,
     <<"IS">>,
     <<"IN">>,
     <<"ID">>,
     <<"IR">>,
     <<"IQ">>,
     <<"IE">>,
     <<"IM">>,
     <<"IL">>,
     <<"IT">>,
     <<"JM">>,
     <<"JP">>,
     <<"JE">>,
     <<"JO">>,
     <<"KZ">>,
     <<"KE">>,
     <<"KI">>,
     <<"KP">>,
     <<"KR">>,
     <<"KW">>,
     <<"KG">>,
     <<"LA">>,
     <<"LV">>,
     <<"LB">>,
     <<"LS">>,
     <<"LR">>,
     <<"LY">>,
     <<"LI">>,
     <<"LT">>,
     <<"LU">>,
     <<"MK">>,
     <<"MG">>,
     <<"MW">>,
     <<"MY">>,
     <<"MV">>,
     <<"ML">>,
     <<"MT">>,
     <<"MH">>,
     <<"MQ">>,
     <<"MR">>,
     <<"MU">>,
     <<"YT">>,
     <<"MX">>,
     <<"FM">>,
     <<"MD">>,
     <<"MC">>,
     <<"MN">>,
     <<"ME">>,
     <<"MS">>,
     <<"MA">>,
     <<"MZ">>,
     <<"MM">>,
     <<"NA">>,
     <<"NR">>,
     <<"NP">>,
     <<"NL">>,
     <<"AN">>,
     <<"NC">>,
     <<"NZ">>,
     <<"NI">>,
     <<"NE">>,
     <<"NG">>,
     <<"NU">>,
     <<"NF">>,
     <<"MP">>,
     <<"NO">>,
     <<"OM">>,
     <<"PK">>,
     <<"PW">>,
     <<"PS">>,
     <<"PA">>,
     <<"PG">>,
     <<"PY">>,
     <<"PE">>,
     <<"PH">>,
     <<"PN">>,
     <<"PL">>,
     <<"PT">>,
     <<"PR">>,
     <<"QA">>,
     <<"RE">>,
     <<"RO">>,
     <<"RU">>,
     <<"RW">>,
     <<"BL">>,
     <<"SH">>,
     <<"KN">>,
     <<"LC">>,
     <<"MF">>,
     <<"PM">>,
     <<"VC">>,
     <<"WS">>,
     <<"SM">>,
     <<"ST">>,
     <<"SA">>,
     <<"SN">>,
     <<"RS">>,
     <<"SC">>,
     <<"SL">>,
     <<"SG">>,
     <<"SK">>,
     <<"SI">>,
     <<"SB">>,
     <<"SO">>,
     <<"ZA">>,
     <<"GS">>,
     <<"SS">>,
     <<"ES">>,
     <<"LK">>,
     <<"SD">>,
     <<"SR">>,
     <<"SJ">>,
     <<"SZ">>,
     <<"SE">>,
     <<"CH">>,
     <<"SY">>,
     <<"TW">>,
     <<"TJ">>,
     <<"TZ">>,
     <<"TH">>,
     <<"TL">>,
     <<"TG">>,
     <<"TK">>,
     <<"TO">>,
     <<"TT">>,
     <<"TN">>,
     <<"TR">>,
     <<"TM">>,
     <<"TC">>,
     <<"TV">>,
     <<"UG">>,
     <<"UA">>,
     <<"AE">>,
     <<"GB">>,
     <<"US">>,
     <<"UM">>,
     <<"UY">>,
     <<"UZ">>,
     <<"VU">>,
     <<"VE">>,
     <<"VN">>,
     <<"VI">>,
     <<"WF">>,
     <<"EH">>,
     <<"YE">>,
     <<"ZM">>,
     <<"ZW">>].

get_alpha_3_country_list() ->
    [<<"AFG">>,
     <<"ALA">>,
     <<"ALB">>,
     <<"DZA">>,
     <<"ASM">>,
     <<"AND">>,
     <<"AGO">>,
     <<"AIA">>,
     <<"ATA">>,
     <<"ATG">>,
     <<"ARG">>,
     <<"ARM">>,
     <<"ABW">>,
     <<"AUS">>,
     <<"AUT">>,
     <<"AZE">>,
     <<"BHS">>,
     <<"BHR">>,
     <<"BGD">>,
     <<"BRB">>,
     <<"BLR">>,
     <<"BEL">>,
     <<"BLZ">>,
     <<"BEN">>,
     <<"BMU">>,
     <<"BTN">>,
     <<"BOL">>,
     <<"BIH">>,
     <<"BWA">>,
     <<"BVT">>,
     <<"BRA">>,
     <<"VGB">>,
     <<"IOT">>,
     <<"BRN">>,
     <<"BGR">>,
     <<"BFA">>,
     <<"BDI">>,
     <<"KHM">>,
     <<"CMR">>,
     <<"CAN">>,
     <<"CPV">>,
     <<"CYM">>,
     <<"CAF">>,
     <<"TCD">>,
     <<"CHL">>,
     <<"CHN">>,
     <<"HKG">>,
     <<"MAC">>,
     <<"CXR">>,
     <<"CCK">>,
     <<"COL">>,
     <<"COM">>,
     <<"COG">>,
     <<"COD">>,
     <<"COK">>,
     <<"CRI">>,
     <<"CIV">>,
     <<"HRV">>,
     <<"CUB">>,
     <<"CYP">>,
     <<"CZE">>,
     <<"DNK">>,
     <<"DJI">>,
     <<"DMA">>,
     <<"DOM">>,
     <<"ECU">>,
     <<"EGY">>,
     <<"SLV">>,
     <<"GNQ">>,
     <<"ERI">>,
     <<"EST">>,
     <<"ETH">>,
     <<"FLK">>,
     <<"FRO">>,
     <<"FJI">>,
     <<"FIN">>,
     <<"FRA">>,
     <<"GUF">>,
     <<"PYF">>,
     <<"ATF">>,
     <<"GAB">>,
     <<"GMB">>,
     <<"GEO">>,
     <<"DEU">>,
     <<"GHA">>,
     <<"GIB">>,
     <<"GRC">>,
     <<"GRL">>,
     <<"GRD">>,
     <<"GLP">>,
     <<"GUM">>,
     <<"GTM">>,
     <<"GGY">>,
     <<"GIN">>,
     <<"GNB">>,
     <<"GUY">>,
     <<"HTI">>,
     <<"HMD">>,
     <<"VAT">>,
     <<"HND">>,
     <<"HUN">>,
     <<"ISL">>,
     <<"IND">>,
     <<"IDN">>,
     <<"IRN">>,
     <<"IRQ">>,
     <<"IRL">>,
     <<"IMN">>,
     <<"ISR">>,
     <<"ITA">>,
     <<"JAM">>,
     <<"JPN">>,
     <<"JEY">>,
     <<"JOR">>,
     <<"KAZ">>,
     <<"KEN">>,
     <<"KIR">>,
     <<"PRK">>,
     <<"KOR">>,
     <<"KWT">>,
     <<"KGZ">>,
     <<"LAO">>,
     <<"LVA">>,
     <<"LBN">>,
     <<"LSO">>,
     <<"LBR">>,
     <<"LBY">>,
     <<"LIE">>,
     <<"LTU">>,
     <<"LUX">>,
     <<"MKD">>,
     <<"MDG">>,
     <<"MWI">>,
     <<"MYS">>,
     <<"MDV">>,
     <<"MLI">>,
     <<"MLT">>,
     <<"MHL">>,
     <<"MTQ">>,
     <<"MRT">>,
     <<"MUS">>,
     <<"MYT">>,
     <<"MEX">>,
     <<"FSM">>,
     <<"MDA">>,
     <<"MCO">>,
     <<"MNG">>,
     <<"MNE">>,
     <<"MSR">>,
     <<"MAR">>,
     <<"MOZ">>,
     <<"MMR">>,
     <<"NAM">>,
     <<"NRU">>,
     <<"NPL">>,
     <<"NLD">>,
     <<"ANT">>,
     <<"NCL">>,
     <<"NZL">>,
     <<"NIC">>,
     <<"NER">>,
     <<"NGA">>,
     <<"NIU">>,
     <<"NFK">>,
     <<"MNP">>,
     <<"NOR">>,
     <<"OMN">>,
     <<"PAK">>,
     <<"PLW">>,
     <<"PSE">>,
     <<"PAN">>,
     <<"PNG">>,
     <<"PRY">>,
     <<"PER">>,
     <<"PHL">>,
     <<"PCN">>,
     <<"POL">>,
     <<"PRT">>,
     <<"PRI">>,
     <<"QAT">>,
     <<"REU">>,
     <<"ROU">>,
     <<"RUS">>,
     <<"RWA">>,
     <<"BLM">>,
     <<"SHN">>,
     <<"KNA">>,
     <<"LCA">>,
     <<"MAF">>,
     <<"SPM">>,
     <<"VCT">>,
     <<"WSM">>,
     <<"SMR">>,
     <<"STP">>,
     <<"SAU">>,
     <<"SEN">>,
     <<"SRB">>,
     <<"SYC">>,
     <<"SLE">>,
     <<"SGP">>,
     <<"SVK">>,
     <<"SVN">>,
     <<"SLB">>,
     <<"SOM">>,
     <<"ZAF">>,
     <<"SGS">>,
     <<"SSD">>,
     <<"ESP">>,
     <<"LKA">>,
     <<"SDN">>,
     <<"SUR">>,
     <<"SJM">>,
     <<"SWZ">>,
     <<"SWE">>,
     <<"CHE">>,
     <<"SYR">>,
     <<"TWN">>,
     <<"TJK">>,
     <<"TZA">>,
     <<"THA">>,
     <<"TLS">>,
     <<"TGO">>,
     <<"TKL">>,
     <<"TON">>,
     <<"TTO">>,
     <<"TUN">>,
     <<"TUR">>,
     <<"TKM">>,
     <<"TCA">>,
     <<"TUV">>,
     <<"UGA">>,
     <<"UKR">>,
     <<"ARE">>,
     <<"GBR">>,
     <<"USA">>,
     <<"UMI">>,
     <<"URY">>,
     <<"UZB">>,
     <<"VUT">>,
     <<"VEN">>,
     <<"VNM">>,
     <<"VIR">>,
     <<"WLF">>,
     <<"ESH">>,
     <<"YEM">>,
     <<"ZMB">>,
     <<"ZWE">>].

get_country_name_list() ->
    [<<"Afghanistan">>,
     <<"Aland Islands">>,
     <<"Albania">>,
     <<"Algeria">>,
     <<"American Samoa">>,
     <<"Andorra">>,
     <<"Angola">>,
     <<"Anguilla">>,
     <<"Antarctica">>,
     <<"Antigua and Barbuda">>,
     <<"Argentina">>,
     <<"Armenia">>,
     <<"Aruba">>,
     <<"Australia">>,
     <<"Austria">>,
     <<"Azerbaijan">>,
     <<"Bahamas">>,
     <<"Bahrain">>,
     <<"Bangladesh">>,
     <<"Barbados">>,
     <<"Belarus">>,
     <<"Belgium">>,
     <<"Belize">>,
     <<"Benin">>,
     <<"Bermuda">>,
     <<"Bhutan">>,
     <<"Bolivia">>,
     <<"Bosnia and Herzegovina">>,
     <<"Botswana">>,
     <<"Bouvet Island">>,
     <<"Brazil">>,
     <<"British Virgin Islands">>,
     <<"British Indian Ocean Territory">>,
     <<"Brunei Darussalam">>,
     <<"Bulgaria">>,
     <<"Burkina Faso">>,
     <<"Burundi">>,
     <<"Cambodia">>,
     <<"Cameroon">>,
     <<"Canada">>,
     <<"Cape Verde">>,
     <<"Cayman Islands">>,
     <<"Central African Republic">>,
     <<"Chad">>,
     <<"Chile">>,
     <<"China">>,
     <<"Hong Kong, Special Administrative Region of China">>,
     <<"Macao, Special Administrative Region of China">>,
     <<"Christmas Island">>,
     <<"Cocos (Keeling) Islands">>,
     <<"Colombia">>,
     <<"Comoros">>,
     <<"Congo (Brazzaville)">>,
     <<"Democratic Republic of the Congo">>,
     <<"Cook Islands">>,
     <<"Costa Rica">>,
     <<"Côte d'Ivoire">>,
     <<"Croatia">>,
     <<"Cuba">>,
     <<"Cyprus">>,
     <<"Czech Republic">>,
     <<"Denmark">>,
     <<"Djibouti">>,
     <<"Dominica">>,
     <<"Dominican Republic">>,
     <<"Ecuador">>,
     <<"Egypt">>,
     <<"El Salvador">>,
     <<"Equatorial Guinea">>,
     <<"Eritrea">>,
     <<"Estonia">>,
     <<"Ethiopia">>,
     <<"Falkland Islands (Malvinas)">>,
     <<"Faroe Islands">>,
     <<"Fiji">>,
     <<"Finland">>,
     <<"France">>,
     <<"French Guiana">>,
     <<"French Polynesia">>,
     <<"French Southern Territories">>,
     <<"Gabon">>,
     <<"Gambia">>,
     <<"Georgia">>,
     <<"Germany">>,
     <<"Ghana">>,
     <<"Gibraltar">>,
     <<"Greece">>,
     <<"Greenland">>,
     <<"Grenada">>,
     <<"Guadeloupe">>,
     <<"Guam">>,
     <<"Guatemala">>,
     <<"Guernsey">>,
     <<"Guinea">>,
     <<"Guinea-Bissau">>,
     <<"Guyana">>,
     <<"Haiti">>,
     <<"Heard Island and Mcdonald Islands">>,
     <<"Holy See (Vatican City State)">>,
     <<"Honduras">>,
     <<"Hungary">>,
     <<"Iceland">>,
     <<"India">>,
     <<"Indonesia">>,
     <<"Iran">>,
     <<"Iraq">>,
     <<"Ireland">>,
     <<"Isle of Man">>,
     <<"Israel">>,
     <<"Italy">>,
     <<"Jamaica">>,
     <<"Japan">>,
     <<"Jersey">>,
     <<"Jordan">>,
     <<"Kazakhstan">>,
     <<"Kenya">>,
     <<"Kiribati">>,
     <<"Democratic People's Republic of Korea">>,
     <<"Republic of Korea">>,
     <<"Kuwait">>,
     <<"Kyrgyzstan">>,
     <<"Lao PDR">>,
     <<"Latvia">>,
     <<"Lebanon">>,
     <<"Lesotho">>,
     <<"Liberia">>,
     <<"Libya">>,
     <<"Liechtenstein">>,
     <<"Lithuania">>,
     <<"Luxembourg">>,
     <<"Republic of Macedonia">>,
     <<"Madagascar">>,
     <<"Malawi">>,
     <<"Malaysia">>,
     <<"Maldives">>,
     <<"Mali">>,
     <<"Malta">>,
     <<"Marshall Islands">>,
     <<"Martinique">>,
     <<"Mauritania">>,
     <<"Mauritius">>,
     <<"Mayotte">>,
     <<"Mexico">>,
     <<"Federated States of Micronesia">>,
     <<"Moldova">>,
     <<"Monaco">>,
     <<"Mongolia">>,
     <<"Montenegro">>,
     <<"Montserrat">>,
     <<"Morocco">>,
     <<"Mozambique">>,
     <<"Myanmar">>,
     <<"Namibia">>,
     <<"Nauru">>,
     <<"Nepal">>,
     <<"Netherlands">>,
     <<"Netherlands Antilles">>,
     <<"New Caledonia">>,
     <<"New Zealand">>,
     <<"Nicaragua">>,
     <<"Niger">>,
     <<"Nigeria">>,
     <<"Niue">>,
     <<"Norfolk Island">>,
     <<"Northern Mariana Islands">>,
     <<"Norway">>,
     <<"Oman">>,
     <<"Pakistan">>,
     <<"Palau">>,
     <<"Palestine">>,
     <<"Panama">>,
     <<"Papua New Guinea">>,
     <<"Paraguay">>,
     <<"Peru">>,
     <<"Philippines">>,
     <<"Pitcairn">>,
     <<"Poland">>,
     <<"Portugal">>,
     <<"Puerto Rico">>,
     <<"Qatar">>,
     <<"Réunion">>,
     <<"Romania">>,
     <<"Russian Federation">>,
     <<"Rwanda">>,
     <<"Saint-Barthélemy">>,
     <<"Saint Helena">>,
     <<"Saint Kitts and Nevis">>,
     <<"Saint Lucia">>,
     <<"Saint-Martin (French part)">>,
     <<"Saint Pierre and Miquelon">>,
     <<"Saint Vincent and Grenadines">>,
     <<"Samoa">>,
     <<"San Marino">>,
     <<"Sao Tome and Principe">>,
     <<"Saudi Arabia">>,
     <<"Senegal">>,
     <<"Serbia">>,
     <<"Seychelles">>,
     <<"Sierra Leone">>,
     <<"Singapore">>,
     <<"Slovakia">>,
     <<"Slovenia">>,
     <<"Solomon Islands">>,
     <<"Somalia">>,
     <<"South Africa">>,
     <<"South Georgia and the South Sandwich Islands">>,
     <<"South Sudan">>,
     <<"Spain">>,
     <<"Sri Lanka">>,
     <<"Sudan">>,
     <<"Suriname *">>,
     <<"Svalbard and Jan Mayen Islands">>,
     <<"Swaziland">>,
     <<"Sweden">>,
     <<"Switzerland">>,
     <<"Syrian Arab Republic (Syria)">>,
     <<"Taiwan, Republic of China">>,
     <<"Tajikistan">>,
     <<"Tanzania">>,
     <<"Thailand">>,
     <<"Timor-Leste">>,
     <<"Togo">>,
     <<"Tokelau">>,
     <<"Tonga">>,
     <<"Trinidad and Tobago">>,
     <<"Tunisia">>,
     <<"Turkey">>,
     <<"Turkmenistan">>,
     <<"Turks and Caicos Islands">>,
     <<"Tuvalu">>,
     <<"Uganda">>,
     <<"Ukraine">>,
     <<"United Arab Emirates">>,
     <<"United Kingdom">>,
     <<"United States of America">>,
     <<"United States Minor Outlying Islands">>,
     <<"Uruguay">>,
     <<"Uzbekistan">>,
     <<"Vanuatu">>,
     <<"Venezuela (Bolivarian Republic of)">>,
     <<"Viet Nam">>,
     <<"US Virgin Islands">>,
     <<"Wallis and Futuna Islands">>,
     <<"Western Sahara">>,
     <<"Yemen">>,
     <<"Zambia">>,
     <<"Zimbabwe">>].